### ISSUE TITLE
Kalendarium Layout

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#100]
1. Die Monatslabels überschneiden sich bei kleinen Bildschirmen wieder. Können wir es wieder so machen wie im letzten Jahr, dass die labels auf vertikale Ausrichtung springen, sobald sie nicht mehr überschneidungsfrei dargestellt werden können?

2. Bitte einen horizontalen Trennstrich zwischen die Jahre.

3. Bei Fortbildung, Elternzeit und Sonstiges sind die Zeilenumbrüche ungünstig. Bitte so abändern dass die Labels direkt neben den farbigen Icons beginnen.

4. In der Horizontalen haben die Monatslabels auf meinem Smartphone eine viel zu kleine Schriftgröße (Android 8.1.0, Browser: Firefox Klar 8.0.23).

_Originally posted by @jocarstensen in https://github.com/dzhw/SLC-IntEr/issues/26#issuecomment-553389580_

**Comment by jocarstensen** [comment]
Screenshots s. #26

**Comment by woisch** [comment]
5. Bitte die Monatslabels folgendermaßen abkürzen: Jan./Feb./März/Apr./Mai/Juni/Juli/Aug./Sep./Okt./Nov./Dez.

**Comment by woisch** [comment]
6. Die Funktionalität "Start und Ende antippen bei Mobile devices" ist noch nicht implementiert oder fuktioniert noch nicht @dzhwmeisner


_Originally posted by @woisch in https://github.com/dzhw/SLC-IntEr/issues/28#issuecomment-558214448_

**Comment by dzhwmeisner** [comment]
>1.  Die Monatslabels überschneiden sich bei kleinen Bildschirmen wieder. Können wir es wieder so machen wie im letzten Jahr, dass die labels auf vertikale Ausrichtung springen, sobald sie nicht mehr überschneidungsfrei dargestellt werden können?

Sind geändert zu Jan./Feb./März/Apr./Mai/Juni/Juli/Aug./Sep./Okt./Nov./Dez.
Bitte nochmal überprüfen, ob Ausrichtungswechsel notwendig

>2. Bitte einen horizontalen Trennstrich zwischen die Jahre.

erledigt. Im nächsten Rollout verfügbar
    
>3. Bei Fortbildung, Elternzeit und Sonstiges sind die Zeilenumbrüche ungünstig. Bitte so abändern dass die Labels direkt neben den farbigen Icons beginnen.

erledigt. Im nächsten Rollout verfügbar

>4. In der Horizontalen haben die Monatslabels auf meinem Smartphone eine viel zu kleine Schriftgröße (Android 8.1.0, Browser: Firefox Klar 8.0.23).

Schriftgröße ist nicht mehr abhängig von der Seitenbreite. Siehe 1

>5. Bitte die Monatslabels folgendermaßen abkürzen: Jan./Feb./März/Apr./Mai/Juni/Juli/Aug./Sep./Okt./Nov./Dez.

erledigt. Im nächsten Rollout verfügbar

**Comment by woisch** [comment]
Danke fürs Umsetzen, wir prüfen das nach Rollout!

**Comment by woisch** [comment]
> 
> 
> > 1. Die Monatslabels überschneiden sich bei kleinen Bildschirmen wieder. Können wir es wieder so machen wie im letzten Jahr, dass die labels auf vertikale Ausrichtung springen, sobald sie nicht mehr überschneidungsfrei dargestellt werden können?
> 
> Sind geändert zu Jan./Feb./März/Apr./Mai/Juni/Juli/Aug./Sep./Okt./Nov./Dez.
> Bitte nochmal überprüfen, ob Ausrichtungswechsel notwendig
> 
@dzhwmeisner 
Auf mobilen Endgeräten überschneiden sich die (gekürzten) Monatslabels immer noch stark. Da wäre ein vertikales Kippen auf jeden Fall notwendig!

**Comment by woisch** [comment]
Das Kalendarium sieht auf meinem iPad folgendermaßen aus. Ein Ausfüllen ist nicht möglich.

![grafik](https://user-images.githubusercontent.com/53002476/69858800-103ac180-1293-11ea-96a9-5977a70d4c91.png)

**Comment by woisch** [comment]
@vdick @dzhwmeisner @andreaschu 
Beim Kalendarium sind noch wichtige Punkte offen. 
Für die Ipad-Ansicht brauchen wir eine Lösung. Habt ihr eine Idee? Wäre es eine Lösung bei der Zwischengröße (Tablet) die mobile-Ansicht zu "erzwingen"?

**Comment by dzhwmeisner** [comment]
Ich arbeite an einer Lösung fürs IPad. Das Erzwingen der Mobil-Ansicht ist schwieriger, als ein CSS-Patch.

Die Monatslable werden im nächsten Rollout gedreht.

**Comment by woisch** [comment]
Alles klar, danke dir!

Ein wichtiger Punkt noch:
Die Funktion Start/Ende antippen ist momentan für alle Befragten implementiert. Wir wollen diese aber nur für mobile devices.

**Comment by dzhwmeisner** [comment]
Die IPad-Version ist repariert.

**Comment by dzhwmeisner** [comment]
> Die Funktion Start/Ende antippen ist momentan für alle Befragten implementiert. Wir wollen diese aber nur für mobile devices.

Abhängig von der Variablen isMobile wird eine der beiden Auswahlmethoden gewählt.
Im nächsten Rollout vorhanden

**Comment by jocarstensen** [comment]
Seit dem iPad-Fix sieht das Kalendarium auf einem iPhone 7 so aus:

![img_7428](https://user-images.githubusercontent.com/35771616/70051778-0fc36300-15d2-11ea-896a-4b0da1eca43a.png)

Es sind nur noch 3 Monate zu sehen

**Comment by se-lang** [comment]
Auf Android Smartphone (Galaxy S7, Firefox 68) sind die Labels der Monate verschoben und sitzen auf den Linien:
![Screenshot_20191203-134509_Firefox](https://user-images.githubusercontent.com/35341060/70052600-eefc0d00-15d3-11ea-91a2-22b4bd4abf8e.jpg)

**Comment by jocarstensen** [comment]
weiteres Problem: auf iPhone SE und in Chrome lassen sich einmal markierte Monate nicht mehr deaktivieren/löschen

**Comment by woisch** [comment]
- [ ] Bei der Desktop Ansicht die Jahreszahl fett machen und vertikal zentrieren

**Comment by andreaschu** [comment]
> weiteres Problem: auf iPhone SE und in Chrome lassen sich einmal markierte Monate nicht mehr deaktivieren/löschen

sollte gefixed sein

**Comment by andreaschu** [comment]
> Auf Android Smartphone (Galaxy S7, Firefox 68) sind die Labels der Monate verschoben und sitzen auf den Linien (Landscape ist nicht ganz so schlimm aber ähnlich):

sollte gefixed sein

**Comment by woisch** [comment]
> 
> 
> > Auf Android Smartphone (Galaxy S7, Firefox 68) sind die Labels der Monate verschoben und sitzen auf den Linien (Landscape ist nicht ganz so schlimm aber ähnlich):
> 
> sollte gefixed sein

@se-lang: Kannst du mal testen?

**Comment by woisch** [comment]
> 
> 
> > weiteres Problem: auf iPhone SE und in Chrome lassen sich einmal markierte Monate nicht mehr deaktivieren/löschen
> 
> sollte gefixed sein

das scheint zu gehen, zumindest auf  dem iPhone 7 und Safari kann ich die Monate jetzt wieder löschen

**Comment by woisch** [comment]
Es bleibt aber nach wie vor das Problem, dass auf iPhone 7 und SE nur die ersten 3-4 Monate sichtbar sind.

**Comment by se-lang** [comment]
@andreaschu Ist die Befragung nach dem fix denn überhaupt schon wieder ausgerollt?
Falls ja, bei mir hat sich "nichts" geänder, außer, dass ich jetzt auf allen Seiten noch Einblendungen ganz oben habe:
![Screenshot_20191203-165710_Firefox](https://user-images.githubusercontent.com/35341060/70067983-74d98180-15ef-11ea-8e2c-e593f465033e.jpg)

**Comment by woisch** [comment]
@andreaschu: Arbeitet ihr gerade noch dran? das Hauptproblem (Darstellung auf mobilen Endgeräten) besteht ja immer noch!

**Comment by andreaschu** [comment]
Nein, ist noch nicht neu ausgerollt. Es gab einige Fehler. Wir hoffen es klappt jetzt.

**Comment by dzhwmeisner** [comment]
Iphone und IPad Bug ist gefixed

**Comment by woisch** [comment]
Auf dem iPhone sehe ich jetzt das ganze kalendarium. Start und Ende antippen klappt.
Die Ausrichtung der Monate ist noch nicht optimal, im Landscape Mode werden sie knapp abgeschnitten.
Normale Ansicht:
![grafik](https://user-images.githubusercontent.com/53002476/70140559-4dd58b00-1695-11ea-90c2-d0992c8c1d7b.png)

Landscape:
![grafik](https://user-images.githubusercontent.com/53002476/70140541-3f876f00-1695-11ea-9e14-0c5b73cb6132.png)

**Comment by woisch** [comment]
Ipad sieht jetzt so aus, sehe nur die Monate bis September oder Oktober:

![grafik](https://user-images.githubusercontent.com/53002476/70140725-ab69d780-1695-11ea-9720-f9fa70570f28.png)

**Comment by woisch** [comment]
Das Kalendarium braucht dringend noch Unterstützung:

- [ ] Monatslabels in der mobilen Ansicht korrigieren, werden zum Teil noch abgeschnitten (siehe mein Post oben)

- [ ] Bei der Desktop Ansicht die Jahreszahl fett machen und vertikal zentrieren

**Comment by bafranke** [comment]
au meinem Handy sieht es noch schlechter aus:
![grafik](https://user-images.githubusercontent.com/56022369/70146305-33ee7500-16a2-11ea-8555-5b2f7c3bb5ba.png)
![grafik](https://user-images.githubusercontent.com/56022369/70146348-436dbe00-16a2-11ea-9da3-53b7f5e74e85.png)

**Comment by dzhwmeisner** [comment]
Magst du mir sagen, welches Handy, Betriebssystem und Browser du benutzt hast?

**Comment by dzhwmeisner** [comment]
> Ipad sieht jetzt so aus, sehe nur die Monate bis September oder Oktober. Monate können nur durch antippen einzeln ausgewählt werden

ist erledigt.

**Comment by dzhwmeisner** [comment]
>Monatslabels in der mobilen Ansicht korrigieren, werden zum Teil noch abgeschnitten (siehe mein Post oben) 

bitte Browser-Cache leeren. Ist ausgerollt.

>Bei der Desktop Ansicht die Jahreszahl fett machen und vertikal zentrieren

bitte Browser-Cache leeren. Ist ausgerollt.

**Comment by woisch** [comment]
> 
> 
> Magst du mir sagen, welches Handy, Betriebssystem und Browser du benutzt hast?

Also bei mir iPhone 7, iOs 13.2.3, Safari

**Comment by woisch** [comment]
Barbara nutzt das iPhone SE mit Ecosia Browser

**Comment by jocarstensen** [comment]
Android 8.1, Chrome, 6,2": 

![grafik](https://user-images.githubusercontent.com/35771616/70149729-078a2700-16a9-11ea-8323-f9986bd6f1b4.png)
![grafik](https://user-images.githubusercontent.com/35771616/70149741-0c4edb00-16a9-11ea-9c33-61846aaddb49.png)

**Comment by jocarstensen** [comment]
Auf Firefox Klar sieht es bei mir besser aus:
![grafik](https://user-images.githubusercontent.com/35771616/70150184-e0802500-16a9-11ea-8ce2-2e596fcf1002.png)
![grafik](https://user-images.githubusercontent.com/35771616/70150200-e413ac00-16a9-11ea-89de-559e6d80a43d.png)

**Comment by dzhwmeisner** [comment]
@bafranke  bitte nochmal probieren. Ich habe die IPhone Erkennung angepasst.

**Comment by woisch** [comment]
Kurzzeitig sah es gut aus, jetzt ist auf allen Geräten wieder nur eine fehlerhafte Anzeige zu sehen. 

![grafik](https://user-images.githubusercontent.com/53002476/70152630-dd873380-16ad-11ea-9310-2a2de17655e2.png)

**Comment by woisch** [comment]
Auf dem iPad ist die Darstellung jetzt gut!
Ausfüllen läuft aber bei mir weiterhin durch Antippen einzelner Monate (wird also scheinbar nicht als mobile erkannt).

![img_7437](https://user-images.githubusercontent.com/53002476/70155858-4b822980-16b3-11ea-9ad0-79cc3cec64a3.jpg)

**Comment by woisch** [comment]
Aufm iPhone7 ist jetzt alles so wie es sein soll.
![grafik](https://user-images.githubusercontent.com/53002476/70156352-132f1b00-16b4-11ea-8fc7-343f928e2ee2.png)
![grafik](https://user-images.githubusercontent.com/53002476/70156360-17f3cf00-16b4-11ea-9498-26fc7ecc6771.png)

**Comment by dzhwmeisner** [comment]
> Android 8.1, Chrome, 6,2":
erledigt

**Comment by dzhwmeisner** [comment]
Bitte nicht wundern. Auf jeder Seite wird momentan der UserAgentString eingeblendet.
Bei Screenshots bitte berücksichtigen. Beschleunigt die Fehlersuche

**Comment by bafranke** [comment]
Iphone SE OS 13.1.2 Ecosia 
sieht ebenfalls gut aus! Auswählen funktioniert hier aber ebenfalls über Einzelklicks
etwas irritierend: die Beschriftung in den Monatszellen spring ein bisschen beim scrollen. Scheint an Kopf- und Fußleiste des Browsers zu liegen - sobald diese eingeblendet ist, springen die Beschriftungen nach rechts. Mich persönlich stört das aber nicht. Fällt auch nur im Portrait-Modus auf.
![grafik](https://user-images.githubusercontent.com/56022369/70211990-ca6c7600-1736-11ea-9653-0c5bcf41718a.png)
![grafik](https://user-images.githubusercontent.com/56022369/70212017-d22c1a80-1736-11ea-863e-ab42d9f4b5c6.png)

**Comment by andreaschu** [comment]
Kann das dann zu?

**Comment by jocarstensen** [comment]
Nein, die Auswahl der Monate funktioniert scheinbar mobil noch nicht (immer) wie sie soll (s. Posts von Barbara und Andreas).

**Comment by dzhwmeisner** [comment]
Die Auswahl des Bedienverfahrens hängt von der Variable isMobile() ab, welche true ist, wenn der UserAgentString erkennen lässt, daß es ein mobiles Gerät ist. Dummerweise gibt es Geräte, vornehmlich Tablets, die bewußt verschleiern, daß sie mobil sind.

**Comment by woisch** [comment]
@andreaschu @dzhwmeisner 
Sind mit dem vorhin angestoßenen Rollout noch Änderungen am Kalendarium zu erwarten? Hattet ihr noch irgendwas geändert heute früh/vormittag?

**Comment by dzhwmeisner** [comment]
nein

**Comment by bafranke** [comment]
> 
> 
> Die Auswahl des Bedienverfahrens hängt von der Variable isMobile() ab, welche true ist, wenn der UserAgentString erkennen lässt, daß es ein mobiles Gerät ist. Dummerweise gibt es Geräte, vornehmlich Tablets, die bewußt verschleiern, daß sie mobil sind.

wenn ich mit meinem Handy (iphone SE) Safari nutze, funktioniert das Kalendarium wie für mobil geplant. Bei Ecosia funktioniert die Auswahl so wie am Laptop mit Klick.

Ich scheine mit diesem Browser also meine Mobilität zu verschleiern... kann das sein?

**Comment by dzhwmeisner** [comment]
Da der Browser selber den UserAgentString verschickt... durchaus möglich

**Comment by woisch** [comment]
Die Layout-Wünsche sind umgesetzt. Ich schließe hier.
Einen Punkt packe ich für uns noch in ein extra Issue, falls noch Zeit sein sollte.
