### ISSUE TITLE
Episoden - Datumsseiten Häkchen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#101]
Wir haben uns die testweise programmierten Seiten angeguckt und finden es gut so. Das müsste jetzt für alle Seiten, auf denen die Häkchen vorkommen, umgesetzt werden. Zusätzlich bräuchten wir jede dieser Seiten zweimal (einmal pro Kohorte) und die Filter zu und auf diesen Seiten müssten entsprechend angepasst werden.

Zusätzlich hätten wir auf jeder dieser Seite noch folgende Instruction:
""Wir interessieren uns auch für Tätigkeiten, die vor <h_enterdatum> begonnen haben und zu dem Zeitpunkt noch andauerten. Unsere Nachfragen beziehen sich in diesem Fall aber nur auf den Zeitraum seit <h_enterdatum>."

@SilinaKowalewski Bitte setze Dich mit @se-lang in Verbindung, um das Vorgehen beim Duplizieren der Seiten abzusprechen. Dabei dürfen uns absolut keine Fehler unterlaufen.

**Comment by jocarstensen** [comment]
@se-lang Kannst Du eine Liste aller Seiten erstellen, die geändert (dupliziert und mit Java-Magic versehen) werden müssen?

**Comment by se-lang** [comment]
Hier die Liste mit den betroffenen Seiten:
- [ ] taa01, tba01, tca01, tda01, tea01
- [ ] seaa01, ..., sezz01 (soweit ich weiß aber noch in Bearbeitung durch @jocarstensen )
- [ ] vaa01, vba01, vca01, vda01, vea01, vza01
- [ ] oaa01, oab01, oca01, oda01, odb01, oea01, oeb01
- [ ] scaa02, scab02, scac02, scad02, scae02, scaz02
- [ ] uaa01, uba01, uca01, uda01
- [ ] staa01, stba01, stca01, stda01, stea01, st0005
- [ ] emaa01, emba01, emca01, emda01, emea01, emfa01, em0004
- [ ] iaa01, iba01, ica01, ida01, iea01, iza01

Könnt ihr mir bitte jeweils Bescheid geben, wenn ein Modul angepasst ist? Dann kann ich nochmal gegenchecken, einfach weil wir uns insb. bei dem Punkt nicht nur auf das Testen verlassen können/wollen.

**Comment by SilinaKowalewski** [comment]
Vermutlich haben wir (probs to Christian und Viktor) eine Lösung gefunden die uns das komplette Duplizieren der Seiten ersparen würde! Dadurch müssten auch keine Transitions oder ähnliches angepasst werden. 

Viktor testet das Verfahren gerade für die taa01. 

Melde mich sobald wir weiter sind!

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Werde jetzt damit beginnen die entsprechenden Trigger auf den Seiten zu löschen.

**Comment by SilinaKowalewski** [comment]
Für diese Fragen sollte nun alles richtig funktionieren 💯

**Comment by woisch** [comment]
@se-lang @heikQ 
Könnt ihr mal testen, ob die Häkchenlösung auf euren Mobiles funktioniert?

**Comment by se-lang** [comment]
Hat auf allen Seiten, die ich getestet habe, funktioniert.

**Comment by woisch** [comment]
@vdick @SilinaKowalewski 
Technik-Frage: Gibt es irgendwelche Einstellungen auf Mobilen Endgeräten, die die Funktion der Häkchen-Automatismus beeinträchtigen/unterbinden können?

**Comment by andreaschu** [comment]
Mit mobilen Geräten dürfte es nicht korrelieren, aber es hat mit der Funktionalität von java script zu tun. Wenn JavaScript nicht aktiviert ist oder nicht funktioniert, dann funktioniert die Häkchenlösung nicht. 
Aus Erfahrung aus anderen Projekten trifft das für Personen von unter einem Prozent zu.

**Comment by jocarstensen** [comment]
s Eingangspost: Wir wollten auf den Seiten auch noch eine Ausfüllanweisung. Bei ausgeschaltetem Java sollte die dann wenigstens noch was bewirken.

**Comment by jocarstensen** [comment]
Auf den Datumsseiten der Schulen funktioniert die JavaScript-Lösung aktuell nicht. Ist die dort noch nicht umgesetzt?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Du meinst damit diese Seiten, oder? 
scaa02, scab02, scac02, scad02, scae02, scaz02

Bei mir funktioniert hier alles.

**Comment by jocarstensen** [comment]
Genau auf den Seiten. Ich teste auf dem externen Server. Macht das einen Unterschied?

**Comment by SilinaKowalewski** [comment]
Manchmal scheint das einen Unterschied zu machen. Aber eher andersherum. Der externe ist auf jeden Fall auf aktuellem Stand. Mit dem teste ich auch. Hast du noch mal deinen Cache geleert?

**Comment by jocarstensen** [comment]
Jetzt ja und jetzt geht's auch.

**Comment by jocarstensen** [comment]
Häkchen für das neue sET-Modul auf folgenden Seiten:
- seaa01
- seba01
- seca01
- seda01
- seea01
- sezz01

**Comment by SilinaKowalewski** [comment]
Die Funktionalität auf diesen Seiten ist eingebaut. 

Bevor ich euch erschreckt: Aktuell wird die vorletzte Dropdown nicht auf den richtigen Zeitpunkt gesetzt. Das liegt aber "nur" daran, dass Januar in diesem Fall als ao2 definiert ist und sich somit die IDs der Monate verschoben haben. Passe nun die IDs an und dann sollte alles funktionieren.

**Comment by jocarstensen** [comment]
Ist der Zustand im aktuellen Rollout relevant? Dort sind die Häkchen nur auf seaa01 implementiert. Dort springt es aber auch auf den falschen Zeitpunkt (Juni statt Juli und November statt Dezember) und scheinbar bleibt die Datenbank leer; in der Folge funktionieren die Einblendungen nicht.

**Comment by SilinaKowalewski** [comment]
Hast du auch hier vorher deinen Cache geleert? Bei mir klappt es nach dem leeren auch auf den anderen Seiten. 

Das mit dem falschen Zeitpunkt kann gut sein. Musste alle Monatsdropdowns ändern.

**Comment by jocarstensen** [comment]
Stimmt, mit geleertem Cache geht es auch auf den anderen Seiten. Auch dort mit den falschen Daten (Monate um einen verschoben). Und auch dort funktionieren die Einblendungen auf den folgenden Seiten nicht. Wenn ich ein Datum per Hand eingebe, funktionieren die Einblendungen.

**Comment by jocarstensen** [comment]
Habe vielleicht den Fehler gefunden, der zu den kaputten Einblendungen führt. Habe die Trigger scheinbar nicht überall rausgenommen. Kann ich das jetzt gleich in questionnaire5 korrigieren oder seid Ihr gerade unterwegs?

**Comment by jocarstensen** [comment]
Und was meinst Du, wo Januar als ao2 definiert ist? Kann ich nicht finden.

**Comment by SilinaKowalewski** [comment]
So sah die Liste der Monate aus: 
```
                            <zofar:answerOption uid="ao0" value="999999" label="Monat"/>
                            <zofar:answerOption uid="ao2" value="1" label="Januar"/>
                            <zofar:answerOption uid="ao3" value="2" label="Februar"/>
                            <zofar:answerOption uid="ao4" value="3" label="März"/>
                            <zofar:answerOption uid="ao5" value="4" label="April"/>
                            <zofar:answerOption uid="ao6" value="5" label="Mai"/>
                            <zofar:answerOption uid="ao7" value="6" label="Juni"/>
                            <zofar:answerOption uid="ao8" value="7" label="Juli"/>
                            <zofar:answerOption uid="ao9" value="8" label="August"/>
                            <zofar:answerOption uid="ao10" value="9" label="September"/>
                            <zofar:answerOption uid="ao11" value="10" label="Oktober"/>
                            <zofar:answerOption uid="ao12" value="11" label="November"/>
                            <zofar:answerOption uid="ao13" value="12" label="Dezember"/>
```

**Comment by SilinaKowalewski** [comment]
Habe nun aber alles angepasst und die ausgerollte Version funktioniert.

**Comment by jocarstensen** [comment]
Auf welcher Seite war das? Muss es in den Templates auch ändern.

**Comment by jocarstensen** [comment]
Und nochmal s. oben: Wann kann ich die anderen Korrekturen in questionnaire5 machen?

**Comment by SilinaKowalewski** [comment]
Wenn ich das richtig gesehen habe waren alle Monats-Dropdowns betroffen. Habe aber nicht nach den Seiten gesucht sondern nach falschen ao's

**Comment by SilinaKowalewski** [comment]
Aktuell arbeite ich in dem qml5 aber wenn du dringend daran musst. Kannst du das gerne jetzt machen.

**Comment by jocarstensen** [comment]
Ok, habe es in den Templates angepasst. Kannst Du mir grundsätzlich bitte sagen, was Du an der questionnaire5 noch veränderst? Wenn ich das nicht in den Templates auch noch anpasse, werden alle Deine Überarbeitungen wieder überschrieben, falls ich nochmal neu generieren muss.

Ich kann die Überarbeitungen in qml5 auch später machen. Sag einfach Bescheid, wenn es frei ist.

**Comment by SilinaKowalewski** [comment]
Habe jetzt erstmal wo anders weiter gemacht. Kannst also gerne in qml5.

**Comment by jocarstensen** [comment]
Trigger sind gelöscht und committed

**Comment by SilinaKowalewski** [comment]
Muss hier noch etwas gemacht werden?

**Comment by jocarstensen** [comment]
Die letzten Punkte scheinen gefixed. Falls irgendwo Einblendungen nicht funktionieren, machen wir ein neues Issue auf.
