### ISSUE TITLE
Eingabe Hilfsvariablen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#102]
Momentan wird die Seite zur Eingabe der Hilfsvariablen nicht korrekt dargestellt, es ist nicht mehr erkennbar, welches Textfeld zu welcher HV gehört:

![grafik](https://user-images.githubusercontent.com/53002476/69648850-61b53780-106c-11ea-8304-92194f113847.png)

**Comment by SilinaKowalewski** [comment]
Funktioniert wieder :)

**Comment by jocarstensen** [comment]
Cool, danke!

**Comment by woisch** [comment]
habs gesehen, merci.
