### ISSUE TITLE
PRELOAD-Präfix Variablennamen

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#103]
Ich habe gerade gesehen, dass cohort auf einmal in einigen anderen Modulen PRELOADcohort heißt. Ich ändere das jetzt für nsET und Studium (questionnaire16 und 17).
EDIT: nsET also questionnaire17 hat das anscheinend schon jemand geändert nur in Studium nicht.

Wir haben aber ja noch 3 andere Preloads: h_enterdatum, h_exitdatum und h_exitlabel. Muss da zwingend das Präfix PRELOAD davor?

Das müsste dann in allen Modulen nochmal geprüft und angepasst werden.

**Comment by jocarstensen** [comment]
cohort müsste auch in den noch nicht bearbeiteten Modulen geprüft werden.

**Comment by SilinaKowalewski** [comment]
h_enterdatum, h_exitdatum und h_exitlabel sind keine Preload-Variablen. Diese werden nicht vorab in die Datenbank geladen sonder auf der Index-Seite gefüllt. Hier muss also nichts geändert werden. 

Die anderen Module kann ich gerne prüfen.

**Comment by SilinaKowalewski** [comment]
Habe nun alle Fragebogen durchsucht und den Fehler nirgendwo anders gefunden. 

Andrea hatte auch im Zuge von Issue #66 schon Änderungen an der Variable vorgenommen.

**Comment by jocarstensen** [comment]
Ach richtig. Hatte nur für Ausbildung im Kopf, dass sie das gemacht hatte. Dann passt alles, danke!
