### ISSUE TITLE
Kalendarium: Funktionalität ohne JavaScript

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#105]
Auch wenn es nur eine sehr kleine Zahl an Befragten betrifft, bei denen JavaScript nicht aktiviert ist: Funktioniert das Kalendarium ohne Java Script dann überhaupt in irgendeiner Weise? Und wenn nicht, was würden die Befragten dann sehen? 
Wie sehen die Auswirkungen auf die restliche Befragung aus? Bekommen wir da irgendwo Probleme ohne JavaScript?

**Comment by andreaschu** [comment]
Wir haben es getestet. Wenn JavaScript nicht aktiviert ist (!jsCheck.value) dann kann das Kalendarium nicht ausgefüllt werden.
Das betrifft aber auch die Funktionalität auf den Seiten mit der CheckBox-Deselektion und dem Setzen der Hilfsvariablen, z.B. auf Seite taa01.

Insofern sollte das auf jeden Fall am Anfang kommuniziert oder gar abgefangen werden.

**Comment by se-lang** [comment]
@jocarstensen @woisch @heikQ @bafranke Wollen wir das irgendwie proaktiv adressieren? Sind idR sehr wenige Befragte, aber für die funktioniert dann halt doch einiges nicht...

**Comment by woisch** [comment]
Aus meiner Sicht macht dann ein Hinweis in Sachen Java Sinn. Habe sowas, meine ich, auch schon irgendwo gesehen, wahrscheinlich auf der Startseite. Könnten wir aber auch (zusätzlich?) bei der Anleitung fürs Kalendarium machen?

Von: se-lang [mailto:notifications@github.com]
Gesendet: Montag, 2. Dezember 2019 12:55
An: dzhw/SLC-IntEr
Cc: Woisch, Andreas; Mention
Betreff: Re: [dzhw/SLC-IntEr] Kalendarium: Funktionalität ohne JavaScript (#105)


@jocarstensen<https://github.com/jocarstensen> @woisch<https://github.com/woisch> @heikQ<https://github.com/heikQ> @bafranke<https://github.com/bafranke> Wollen wir das irgendwie proaktiv adressieren? Sind idR sehr wenige Befragte, aber für die funktioniert dann halt doch einiges nicht...

**Comment by jocarstensen** [comment]
Für das Kalendarium ist das zu verschmerzen, da dann ja wie Missing weitergeleitet wird. Allerdings kann ein nicht ausfüllbares Kalendarium sehr verwirrend sein. In diesem Fall fände ich es gut, wenn das Kalendarium bei ausgeschaltetem Java übersprungen und sonst wie Missing gefiltert würde.

Häkchen: Wir wollten auf den Häkchenseiten sowieso noch eine Ausfüllanweisung hinzufügen. Für die ohne Java gibt es dann nur noch die.

**Comment by SilinaKowalewski** [comment]
Habe noch mal mit Vitkor Rücksprache gehalten. Wir können **_!jsCheck.value_** nutzen um Probanden ohne JavaScript zu filtern. 

Wollt ihr diese Bedingung einbauen oder sollen wir das machen? Und wenn wir das machen sollen, weißt du spontan auf welche Seiten die am sinnvollsten einzubauen ist?

**Comment by se-lang** [comment]
Ok, das muss auf zwischen_epi geändert werden. Ich mach das aber schnell selber an questionnaire9, das macht mehr Sinn, als wenn ich hier schreib schriebe was da genau rein muss.

**Comment by se-lang** [comment]
Done, müssten wir nur nach dem nächsten Rollout irgendwie mal testen, ob das auch wirklich funktioniert.

**Comment by se-lang** [comment]
Getestet und funktioniert, ich mach hier also zu.
