### ISSUE TITLE
Name der Befragung

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#107]
Ich hatte Andrea versprochen, noch den Namen der Befragung nachzuliefern, da dieser ja relevant für den Zugangslink ist. 
Wir würden es gerne knapp halten und die Befragung "spanel" nennen. So sollte es dann auch im Zugangslink auftauchen, wenn ich das richtig verstanden habe.

Könnt ihr uns bitte dann den finalen Zugangslink zur Befragung mitteilen? Wir benötigen diesen möglichst bis nächste Woche, da wir noch Umleitungen auf diese Webseite einrichten müssen für einen Teil der Befragten...

**Comment by SilinaKowalewski** [comment]
Alle Befragungen - also auch die AddOns - heißen nun spanel. Das heißt, dieser Name wird in den Brower-Reitern dargestellt und wird zukünftig Teil der URL sein. 

Den Link hatte Andrea ja schon per Mail geschickt. 

@woisch: Wenn damit alle deine Fragen beantwortet sind, können wir aus meiner Sicht das Issue schließen.
