### ISSUE TITLE
Auswahl Abschlussarten: staa07

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#109]
@se-lang: Kannst du mal checken, ob die Einblendbedingungen für cohort1 bei den Abschlussarten im Epimodul richtig funktionieren?
Die folgenden 3 Abschlüsse werden eigentlich nur fpr cohort 2 gebraucht, da wir für cohort 1 ja die Differenzierung nach Schulart eingebaut haben in die Liste:
![grafik](https://user-images.githubusercontent.com/53002476/69727844-93d5a080-1123-11ea-83ae-54b35d9748bf.png)

**Comment by se-lang** [comment]
Ok, hab das Problem gefunden, die VC ist im falschen Tag, dafür hab ich damit gleich die Lösung für ein anderes Problem gefunden ;-)
Ich telefoniere gleich mit @SilinaKowalewski und klär mit ihr ab, wo die VC eigentlich hin muss.

**Comment by woisch** [comment]
Super, dann mach ich hier mal wieder zu!

**Comment by se-lang** [comment]
Alle VC korrigiert, sollte nach dem nächsten Rollout korrekt angezeigt werden.
