### ISSUE TITLE
Update Modul SozDem

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#11]
msg_02 gelöscht, bitte updaten.
Nachfolgende Transitions angepasst
0c815905ee12f479388e71493a6040bf42bcdf04 

Zuvor wurde msg_06 gelöscht (siehe 773fe8003ccaf35f97a38956b25ec3cc137f3e35)

**Comment by heikQ** [comment]
msg_02 hinter dem Feld für Monatseingabe fehlt (Monat) hinter dem für Jahreseingabe (Jahr). Siehe PV

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Bitte prüfen.

**Comment by woisch** [comment]
OK. Issue kann geschlossen werden
