### ISSUE TITLE
Seite zur Tokeneingabe bearbeiten

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#110]
Wir würden gerne die Seite, auf der die Befragten ihr Token eingeben etwas modifizieren. Ihr findet angehängt auch eine PDF, wie es in etwa aussehen sollte...

- das "Willkommen zur BEfragung" im header löschen. Stattdessen folgenden Text verwenden "Willkommen zur Studienberechtigtenbefragung" und diesen unterhalb des Headers platzieren
- Wir hätten gerne ein Bild auf der Seite. Ich habe euch das gewünschte Bild in verschiedenen Größen hier hochgeladen da es vorhin offenbar Probleme mit zu großen Bilddateien gab.
- Bitte vorm Textfeld das Wort "Token" durch "Zugangscode" ersetzen
- Ist es üblich, dass auf der Eingabeseite für die Tokens kein "Weiter-Button" ist? Gerade auf Mobilen Endgeräten ist das etwas verwirrend. Könnt ihr da noch einen Button einbauen unter dem Eingabefenster? Im besten Falle bleibt es so, dass man auch durch die Entertaste weiterkommt, der Weiterbutton nur als zusätzliche Option angeboten wird.
-Falls der Login fehlschlägt bitte folgende Fehlermeldung: Bitte geben Sie Ihren 7-stelligen Zugangscode ein. Beachten Sie dabei Groß- und Kleinschreibung.

[Landingpage_tokens.pdf](https://github.com/dzhw/SLC-IntEr/files/3897618/Landingpage_tokens.pdf)

![directionKreideTafel-2314636_1920_klein](https://user-images.githubusercontent.com/53002476/69735348-d6ea4080-1130-11ea-9b95-fe830951ba5f.jpg)
![directionKreideTafel-2314636_1920_kleiner](https://user-images.githubusercontent.com/53002476/69735349-d782d700-1130-11ea-8d7a-af98e21f0c47.jpg)
![directionKreideTafel-2314636_1920_mittelklein](https://user-images.githubusercontent.com/53002476/69735351-d782d700-1130-11ea-903e-7808cd3712b0.jpg)
![directionKreideTafel-2314636_1920](https://user-images.githubusercontent.com/53002476/69735352-d782d700-1130-11ea-9eed-d03613523600.jpg)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
Danke fürs Umsetzen!

Eine Sache fehlt noch (falls das umsetzbar ist):
Falls der Login fehlschlägt bitte folgende Fehlermeldung: Bitte geben Sie Ihren 7-stelligen Zugangscode ein. Beachten Sie dabei Groß- und Kleinschreibung.

**Comment by woisch** [comment]
Sorry, die Fehlermeldung ist doch da! Nehme alles zurück!
Nach Rücksprache mit Viktor ist das Platzieren des Login Buttons zwischen Textfeld und Bild nicht möglich.

@jocarstensen @heikQ @bafranke @se-lang 
Schaut bei Gelegenheit mal drauf, ob ihr noch Änderungswünsche habt. Sonst mache ich hier zu

**Comment by se-lang** [comment]
Ich find das gut so. 

Auf dem Desktop werden die meisten sowieso mit Enter bestätigen und auf dem Smartphone ist der Button zumindest im Portaitmode gut zu sehen, im Landscape würde ich zumindest ohnehin immer erwarten vertikal scrollen zu müssen (und ich kenne niemanden der sein Smarphone in erster Linie im Landscape benutzt).

**Comment by jocarstensen** [comment]
Ich finde es gut so.

**Comment by woisch** [comment]
dann mache ich hier erstmal zu
