### ISSUE TITLE
Kalendarium: Hilfvariablen müssen spätestens bei Betreten von zwischen_k gebildet werden

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#111]
Wir haben vorhin festgestellt, dass die HVs, die aus dem Kalendarium gebildet werden, scheinbar nicht bei Betreten von zwischen_k gebildet werden. Ich brauch die HVs aber für die Einblendbedingungen auf dieser Seite.
@SilinaKowalewski: Sorry, dass mir das vorhin nicht direkt aufgefallen ist!

**Comment by SilinaKowalewski** [comment]
Christian hat dieses Problem bereits behoben. Die HV werden zwar erst beim Verlassen der Seite in die Datenbank geschrieben, werden aber vorher schon berechnet und sind somit schon beim Betreten der Seite "nutzbar"

**Comment by se-lang** [comment]
Top, dann ist alles gut und ich mach hier zu 👍 . Danke euch!
