### ISSUE TITLE
Nach Unterbrechung auf zuletzt bearbeiteter Seite weiter machen - funktioniert derzeit nicht

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#112]
Im Moment werde ich, wenn ich die Befragung unterbreche, nach dem nochmaligen Eingeben des Tokens wieder an den Anfang der Befragung geführt. Soweit ich informiert bin, war geplant, dass die Befragung nach Unterbrechung auf der zuletzt bearbeiteten Seite (oder der danach folgenden) weiter bearbeitet gehen sollte. Liegt das am Testmodus oder warum funktioniert das nicht?

**Comment by se-lang** [comment]
Info bei unserem Pretest des Episodenmoduls war, dass das erst aktiviert werden kann, wenn die Navigation über die url deaktiviert wurde, gleichzeitig funktioniert nicht. Sollten wir dann aber auf jeden Fall nochmal checken.

**Comment by SilinaKowalewski** [comment]
@bafranke: 
Sebastian hat Recht. Wir können diese Funktionen an- bzw. ausschalten. Wenn wir jetzt ermöglichen würden, dass es nach Unterbrechung auf der zuletzt bearbeiteten Seite weiter geht, könntet ihr im Fragebogen nicht mehr über die URL springen sondern müsstet euch für jeden Test durchklicken. 

Würde daher vorschlagen diese Funktion erst kurz vor Feldstart anzupassen.

**Comment by bafranke** [comment]
Super, danke für die Info! Dann schließe ich das issue und wir prüfen es kurz vor Feldstart!
