### ISSUE TITLE
Layout: Probleme bei mobilen Endgeräten (nicht Episodenmodule)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#113]
folgende Punkte sind unseren Testerinnen auf ihren mobilen Endgeräten aufgefallen:

- [x] Beg_06: Skalenbeschriftung überlappt

- [x] Beg_08: Antwortmöglichkeiten rutschen so nah zusammen (horizontal), dass sie sich gegenseitig fast überlappen

- [x] Beg_10: Antwortkästchen sind oben ausgerichtet – bitte mittig ausrichten

- [x] Beg_10: Ao’s mittig ausrichten – sind links orientiert

- [x] Aus_03: Beschriftung der Freitextfelder fehlt

- [ ] Stu_20: Überschrift nicht als Überschrift formatiert, Frage insgesamt noch sehr fehlerhaft

- [x] stu_42: Darstellung letztes Item auf mobilem Gerät
- [x] gleiche Seite, gleiches Item: Umbruchpunkt auf PC: bitte nach „/“ umbrechen

- [x] Stu_44: Skalenbeschriftung auf mobilem Endgerät überlappt 
- [x] Stu_44:  Auf Handy ist Freitextfeld sehr klein
 
- [x] Stu_45: Insgesamt Layout nicht ansprechend, "Monate" steht unter den Textfeldern

- [x] Stu_51/Stu_54/Mas_02/mas_03/mas_12: Freitextfeld auf mobilem Endgerät sehr klein, kann man das vergrößern?

- [x] Stu_92/stu_94: Textfelder auf Handy viel zu lang

- [x] msg_01: hier werden noch die aktuellen Hilfsvariablen eingeblendet – bitte rausnehmen!

- [x] Msg_02a: dropdown-Felder größer machen, damit Inhalt besser zu lesen ist

- [x] Msg_03: auf Handy fehlt Beschriftung der Freitextfelder

- [x] Mas_05: Verbindungslinie zwischen ja, nein und weiß ich noch nicht streichen

- [x] Msg_07: Antwortoptionen auf Handy überlappen sich fast 

Könnt ihr schauen, ob ihr da was machen könnt? Ich habe zu allen Punkten Screenshots, falls ihr die benötigt, sagt einfach Bescheid, bei welchen Punkten es für euch relevant ist (sonst wird das hier zu unübersichtlich).
Bitte entschuldigt, falls hier noch Punkte auftauchen, die schon in einem anderen Issue gemeldet wurden.

**Comment by vdick** [comment]
@bafranke  könntest du mir bitte die Screenshots senden? Es würde mir die Suche um einiges erleichetern.

**Comment by bafranke** [comment]
@vdick von allen oder nur von den noch offenen?

**Comment by vdick** [comment]
@bafranke nur von den offenen,  wenn möglich bitte das gleiche auch für Issue #114 
Besten Dank

**Comment by bafranke** [comment]
Beg_10: Ao’s mittig ausrichten – sind links orientiert
 
![grafik](https://user-images.githubusercontent.com/56022369/69812554-a4078180-11f0-11ea-915d-672d6a9264db.png)

stu_42: 
![grafik](https://user-images.githubusercontent.com/56022369/69812634-d1542f80-11f0-11ea-9b52-a1c9ddccc306.png)

stu_44
![grafik](https://user-images.githubusercontent.com/56022369/69812708-ff397400-11f0-11ea-8d97-97de4c452fb4.png)
 Auf Handy sehr kleines Freitextfeld:
![grafik](https://user-images.githubusercontent.com/56022369/69812743-0ceef980-11f1-11ea-8923-fa88fda285af.png)

stu_51
![grafik](https://user-images.githubusercontent.com/56022369/69812773-1e380600-11f1-11ea-98a3-d18e01eff00d.png)

stu_92
![grafik](https://user-images.githubusercontent.com/56022369/69812796-285a0480-11f1-11ea-8af2-1b1bc8032381.png)

msg_2a
![grafik](https://user-images.githubusercontent.com/56022369/69812809-3445c680-11f1-11ea-9e10-fa2fb11904ed.png)

msg_03
![grafik](https://user-images.githubusercontent.com/56022369/69812833-4162b580-11f1-11ea-898b-a3b5bb000b4b.png)

 
der Rest folgt gleich

**Comment by bafranke** [comment]
aus_03
![grafik](https://user-images.githubusercontent.com/56022369/69813252-19278680-11f2-11ea-8c6e-682032e46936.png)

stu_42b
![grafik](https://user-images.githubusercontent.com/56022369/69813420-791e2d00-11f2-11ea-838e-7933fec84430.png)

stu_45
![grafik](https://user-images.githubusercontent.com/56022369/69813142-e3829d80-11f1-11ea-9494-d08acb4a2e03.png)

msg_01 ist nicht mehr problematisch - seit dem rollout behoben!

ich sehe gerade oben das die screenshots zum Teil kaum lesbar sind - reichen dir die? sonst schicke ich dir die Datei per Mail...

**Comment by vdick** [comment]
aus_03: gerade geprüft, die Freitextfelder sind da und werden angezeigt;
stu_20: @SilinaKowalewski  die Formatierung der Texte am besten im QML vornehmen;
stu_42: leider haben wir  keine Möglichkeit den Text manuell umzubrechen;
stu_44: wegen der größe des Freitextfeldes können wir zunächst kaum was ändern, der verfügbare Platz ist extrem begrenzt..
msg_03: gerade geprüft, die Freitextfelder sind da und werden angezeigt;

**Comment by bafranke** [comment]
super, danke!

**Comment by vdick** [comment]
gerne! sobald die restlichen Punkte abgearbeitet sind, werde ich das css commiten

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by bafranke** [comment]
Danke für die Umsetzung! Für mich noch nicht zufriedenstellend gelöst:  

- [ ] stu_42, letztes Item: Umbruchpunkt auf PC: bitte nach „Kurse/“ umbrechen - im Moment beginnt die neue Zeite mit /
![grafik](https://user-images.githubusercontent.com/56022369/69957667-644bdd00-1503-11ea-8b7b-20827dbee0e5.png)

- [ ]  Stu_45: kann das "Monate" hinter dem Textfeld oder zu Beginn einer neuen Zeile stehen? sieht im Moment unter dem Textfeld merkwürdig aus
![grafik](https://user-images.githubusercontent.com/56022369/69957591-3cf51000-1503-11ea-83ce-34ee3baf80ef.png)

noch offen: @heikQ oder @jocarstensen oder @se-lang 
- [ ] stu_20/stu_21: Habt ihr entschieden, wie ihr die Frage stellen wollt (split half, Kurzversion)?

**Comment by se-lang** [comment]
[ ] Auf beg_03 und beg_04 scheint das Freitextfeld nicht auf die Bildschirmbreite zu reagieren (Galaxy S7, Android 8.0, Firefox 68.x)
![Screenshot_20191204-175534_Firefox](https://user-images.githubusercontent.com/35341060/70163515-e97bf100-16bf-11ea-9392-ebcef381d334.jpg)

**Comment by andreaschu** [comment]
> stu_42, letztes Item: Umbruchpunkt auf PC: bitte nach „Kurse/“ umbrechen - im Moment beginnt die neue Zeite mit /

wir können nicht die Umbrüche an bestimmten Punkten setzen.

**Comment by bafranke** [comment]
@woisch was meinst du: so lassen oder hinter jeden / ein Leerzeichen, damit nach dem / umgebrochen wird? Sähe im Fließtext dann so aus:
Die einzelnen Lehrveranstaltungen/ Kurse/ Studienmaterialien sind inhaltlich gut aufeinander abgestimmt.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
@bafranke könntest Du bitte die noch offenen Punkte aus diesem Issue in ein neues schreiben und hier zumachen? Hier wird es etwas unübersichtlich.

**Comment by bafranke** [comment]
offene Punkte in #156 übertragen
