### ISSUE TITLE
Layout: Probleme bei mobilen Endgeräten (Episodenmodule)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#114]
unseren Testerinnen ist auf ihren mobilen Endgeräten (iphone, ipad) folgendes aufgefallen:

- [x] Emaa12: Antwortoptionen überlappen stark

- [x] Emaa16: Textfelder zu klein und ungeordnet, Felder nicht beschriftet

- [x] Emaa28: Textfeld bei Sonstiges zu klein – geht es für mobil unter das Item zu setzen und länger zu ziehen?

- [x] Emab06: Beschriftung der Eingabefelder fehlt mobil – Absicht?

- [x] Ebenso: em0065

- [x] Ebenso: vaa06

- [x] vaa10: Textfelder zu klein und ungeordnet

- [x] Vaa29: Skalenpunkte klammern

- [x] Iaa06: Felder für PLZ und Ort nicht beschriftet

Könnt ihr mal schauen, was ihr da machen könnt? Ich befürchte, da sind einige Punkte dabei, die ich euch bereits weitergeleitet hatte. Bitte entschuldigt die Dopplung, bis heute morgen traten diese Probleme noch auf. Ich habe für (fast) alle Punkte Screenshots, sagt Bescheid, falls ihr die benötigt! Ich habe sie erst einmal weggelassen, damit es übersichtlich bleibt.

**Comment by bafranke** [comment]
> 
> 
> unseren Testerinnen ist auf ihren mobilen Endgeräten (iphone, ipad) folgendes aufgefallen:
> 
>     * [ ]  Emaa12: Antwortoptionen überlappen stark
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813794-3c9f0100-11f3-11ea-9712-45450ede1420.png)

>     * [ ]  Emaa16: Textfelder zu klein und ungeordnet, Felder nicht beschriftet
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813816-47599600-11f3-11ea-8564-86be6b933862.png)

>     * [ ]  Emaa28: Textfeld bei Sonstiges zu klein – geht es für mobil unter das Item zu setzen und länger zu ziehen?
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813835-517b9480-11f3-11ea-8778-174a8de18c8b.png)

>     * [ ]  Emab06: Beschriftung der Eingabefelder fehlt mobil – Absicht?
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813849-580a0c00-11f3-11ea-8123-0fc8405ecc59.png)

>     * [ ]  Ebenso: em0065
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813864-60624700-11f3-11ea-93a6-23bc7d894f8f.png)

>     * [ ]  Ebenso: vaa06
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813879-66582800-11f3-11ea-96b5-a01479aa1d8c.png)

>     * [ ]  vaa10: Textfelder zu klein und ungeordnet
> 
![grafik](https://user-images.githubusercontent.com/56022369/69813889-6c4e0900-11f3-11ea-90a7-42d2f827eb3e.png)

> 
>     * [ ]  Iaa06: Felder für PLZ und Ort nicht beschriftet
> 
![grafik](https://user-images.githubusercontent.com/56022369/69814154-e7172400-11f3-11ea-826a-44badd9c800c.png)

> 
> Könnt ihr mal schauen, was ihr da machen könnt? Ich befürchte, da sind einige Punkte dabei, die ich euch bereits weitergeleitet hatte. Bitte entschuldigt die Dopplung, bis heute morgen traten diese Probleme noch auf. Ich habe für (fast) alle Punkte Screenshots, sagt Bescheid, falls ihr die benötigt! Ich habe sie erst einmal weggelassen, damit es übersichtlich bleibt.

**Comment by vdick** [comment]
ab nächsten Rollout werden die Text in emaa16, vaa10 und iaa06 angezeigt;
layout wird erst morgen umgesetzt werden

**Comment by vdick** [comment]
layout angepasst, ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
@bafranke kann gestestet werden.

**Comment by woisch** [comment]
- [ ] vaa25, vba25, vca25, vda25, vea25


obere beiden Kästchen für die Noten sind zu klein
![grafik](https://user-images.githubusercontent.com/53002476/70141964-71e69b80-1698-11ea-9394-f3c536ae80e4.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
@woisch @bafranke bitte testen

**Comment by woisch** [comment]
sieht jetzt gut aus von der Breite
getestet auf iphone7 , Seizten vaa25 bis vea25

**Comment by bafranke** [comment]
meine Punkte sind alle geklärt, dann mach ich hier mal zu.
