### ISSUE TITLE
Probleme auf mobilen Endgeräten (nicht Episodenmodule)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#115]
Beim Testen auf mobilen Endgeräten (iphone, ipad) sind folgende Probleme aufgetreten:

- [x] zwischen_epi -> hängenbleiben

- [x] aus_05: online Eingabe in Freitextfeld „sonstige Zusatzquali…“ nicht möglich

- [x] Stu_45: Handy: Größe der Textfelder für Zahlen an sich in Ordnung, Eingabe funktioniert aber nicht optimal, erst nach mehrmaligem Eintippen bleibt Zahl sichtbar. Manchmal bei Korrektur der Eingabe bei fachnah wird die Eingabe bei fachfremd gelöscht. Wenn man zuerst ein Häckchen macht und dann die Zahl eintippt wird das Häckchen wieder gelöscht.

Bitte entschuldigt, wenn sich Punkte mit anderen Issues doppeln sollten.

**Comment by se-lang** [comment]
zwischen_epi habe ich gestern erst die korrekten Transitions geschrieben, da dürfte man jetzt nicht mehr hängen bleiben

**Comment by andreaschu** [comment]
![grafik](https://user-images.githubusercontent.com/30111489/69967264-53f22d00-1518-11ea-94a0-1c9d4e8ebf46.png)

**Comment by jocarstensen** [comment]
@andreaschu Hier sind noch zwei Punkte offen.

**Comment by dzhwmeisner** [comment]
aus_05 ist gefixed

**Comment by woisch** [comment]
aus_05 ist jetzt im Landscape ausfüllbar.
![grafik](https://user-images.githubusercontent.com/53002476/70254787-f105cd80-1785-11ea-8782-124c5a3195a6.png)


Bei der anderen Ansicht geht es aber immer noch nicht:
![grafik](https://user-images.githubusercontent.com/53002476/70254761-e77c6580-1785-11ea-8bbb-cb00fcc16522.png)

**Comment by dzhwmeisner** [comment]
erledigt. Im nächsten Rollout verfügbar.

**Comment by woisch** [comment]
Ist jetzt besser.
