### ISSUE TITLE
Probleme in Episodenmodulen (u.a. auf mobilen Endgeräten)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#116]
Unseren Testerinnen sind beim Testen auf mobilen Endgeräten (ipad, iphone) einige Punkte aufgefallen, die noch behoben werden sollten. Bei vielen Punkten tritt das Problem aber sowohl in der mobilen als auch in der Desktop-Version auf. Da es recht viele Punkte sind (u.a. vermutlich auch schon welche, die ich euch in der letzten Runde weitergeleitet habe, bitte entschuldigt, sie sind aber noch nicht gefixed!), könnte es sinnvoll sein, dass ihr die Punkte auf separate Issues verteilt, je nachdem, wer für die einzelnen Punkte zuständig ist.

- [ ] Seaa15: Zeichenlänge für Freitextfelder erhöhen (beide derzeit nur 20 Zeichen, bitte Berufsbezeichnung auf 60 und Erläuterungen auf 200 hochsetzen)

- [ ] Se0003: o. ä. -> o. Ä.? 

- [ ] se0003:	Weiterleitung auf Endseite der gesamten Befragung

- [ ] Taa05: Fehler in der Überschrift: „Fort- und Weiterbildung Test:“

- [ ] taa05: Meister(in)/Techniker(in) in getrennte Kategorien (war so besprochen zum Weiterbildungsmodul)

- [ ] Taa06: Fehler in der Überschrift: „Fort- und Weiterbildung Test: Test2:“

- [ ] Zwischen_t und zwischen_aus laufen beide nacheinander mit dem gleichen Inhalt

- [ ] Em0001: Rechtschreibfehler bei „selbsständig“ (Hinweistext) außerdem nicht einheitliche Schreibweise mit restlicher Befragung -> da verwenden wir immer selbständig

- [ ] Generell: Beschriftung der Freitextfelder (Orte und PLZ bzw. Ausland) noch nicht umgesetzt

- [ ] Emaa28: gendern: Berufssoldat(in); (nicht Referendar(in)

- [ ] Emaa35: hängenbleiben auf der Seite

- [ ] Emaa39: Weiterleitung auf Unterkategorien funktioniert nicht – es wird derzeit in jedem Fall „Sonstiges, und zwar“ angezeigt

- [ ] Ema64: Rechtschreibfehler: nichtselstständige

- [ ] Em0065: Textfeld erlaubt nur 2 Zeichen und schein als Zahl definiert zu sein – Texteingabe führt zu Fehler: Bitte geben Sie eine Zahl größer 0 ein.

- [ ] Em0050: Rechtschreibfehler: bie (richtig: bei)

- [ ] Em0042: Skalenpunkte beschriften (1-5)

- [ ] Em0051: Skalenpunkte beschriften

- [ ]  Em0051: autoforward einstellen (Zofar?) funktioniert derzeit nicht als autoforward

- [ ] O0001: Freitextfeld bei Sonstiges fehlt

- [ ] oaa(b)01: hängenbleiben, wenn nur Beginn vor und dauert an angekreuzt, ohne Fehlermeldung, gleiches gilt für oca01, oda, odb,

- [ ] Oaa07: Fehler im Hinweistext (Layout.break)

- [ ] Oca05: Fehler im Hinweistext (Layout.break)

- [ ] vaa30: Haben Sie zwischen Juli 2018 und November 2019 noch eine weitere Ausbildung, Umschulung oder ein Volontariat gemacht? -> Müsste es Dezember 2019 heißen?

- [ ] hängenbleiben auf iaa05

- [ ] iba21: Enddatum November 2019 richtig?

- [ ] Scaa13: Hier stimmt etwas nicht, es gibt die ao „bitte auswählen“ -> dropdown geplant?

- [ ] Uaa05: Hier wird der Verweis auf den Monat, der im Dropdown auf der Vorseite ausgewählt wird, als Zahl und nicht als Wort angezeigt

- [ ] Uaa06: Im Fragetext ist das Wort „Zeit“ hinter der Zeitraumangabe überflüssig

- [ ] Uaa06: Ich habe auf der Vorseite ausgewählt, dass ich mich nicht arbeitssuchend gemeldet habe, dann dürfte ich die Frage doch nicht kriegen, oder?

- [ ] AddOn Cohort2: Hier wird noch von einer Befragung in etwa 2 Jahren gesprochen – die nächste ist doch aber bereits im Dez?! oder wird der Teil der Cohorte tatsächlich erst in 2 Jahren wieder befragt?

**Comment by se-lang** [comment]
Ich mach hier mal kurz ein Issue pro Punkt draus, sonst verlieren wird glaube ich ganz schnell den Überblick.

**Comment by se-lang** [comment]
Die einzigen verbleibenden Punkte hier sind die folgenden:

>  Zwischen_t und zwischen_aus laufen beide nacheinander mit dem gleichen Inhalt

Das ist tatsächlich ein bisschen doof. Das betrifft eigentlich jede Zwischenseite aus dem Episodenmodul, wenn dieses von dort aus verlassen wird und die jeweils nachfolgende Zwischenseite des folgenden Moduls. Ich befürchte das lässt sich aber nicht ganz einfach lösen. Einziger positiver Punkt: Sobald die Grafiken auf den (nicht Episodenmodul)-Zwischenseiten eingebledet werden sind die Seiten zumindest nicht mehr identisch...

> AddOn Cohort2: Hier wird noch von einer Befragung in etwa 2 Jahren gesprochen – die nächste ist doch aber bereits im Dez?! oder wird der Teil der Cohorte tatsächlich erst in 2 Jahren wieder befragt?
Das muss vielleicht @heikQ nochmal bestätigen, aber ich mein Stand wäre auch in 1 Jahr

**Comment by jocarstensen** [comment]
@heikQ Kannst Du hier nochmal bestätigen?

**Comment by jocarstensen** [comment]
@SilinaKowalewski Kannst Du für Cohort2 zwei Jahre in ein Jahr ändern?

**Comment by SilinaKowalewski** [comment]
Also: 
_Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung 
        			(in einem Jahren) erreichen und im Falle eines Gewinns informieren können._

**Comment by jocarstensen** [comment]
> Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung
(in einem Jahr**~en~**) erreichen und im Falle eines Gewinns informieren können.

**Comment by SilinaKowalewski** [comment]
Wäre auch zu schön gewesen. Ist angepasst, comitted und ausgerollt.

**Comment by SilinaKowalewski** [comment]
Ist hier noch etwas offen oder kann das Issue geschlossen werden?

**Comment by woisch** [comment]
> 
> 
> Fast:
> Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung
> (in einem Jahr**~en~**) erreichen und im Falle eines Gewinns informieren können.

War nur ein Test für euch :P

**Comment by jocarstensen** [comment]
Dürfte alles behoben sein.
