### ISSUE TITLE
Probleme Episoden: Selbstständige

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#117]
Übertragen aus #116:
- [x]  Seaa15: Zeichenlänge für Freitextfelder erhöhen (beide derzeit nur 20 Zeichen, bitte Berufsbezeichnung auf 60 und Erläuterungen auf 200 hochsetzen)

- [x] Se0003: o. ä. -> o. Ä.?

- [x] se0003: Weiterleitung auf Endseite der gesamten Befragung

**Comment by jocarstensen** [comment]
Das erldige ich in den Templates

**Comment by jocarstensen** [comment]
@SilinaKowalewski Zu 3.: Im Code steht eindeutig nur die Transition zu zwischen_em. Kann es sein, dass das Problem nicht im Code der questionnaire liegt?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Also ich komme auch zur zwischen_em. Tritt bei dir der gleiche Fehler auf wie bei Sebastian?

**Comment by jocarstensen** [comment]
Das stammt aus einem alten Issue. Kann auch sein, dass es mitlerweile behoben ist.
@bafranke Kannst Du sagen, von wann dieser Punkt stammt und ob er noch repliziert werden kann?

**Comment by bafranke** [comment]
Das Problem bestand gestern abend noch. Jetzt funktioniert es, kann also als erledigt markiert werden!

**Comment by jocarstensen** [comment]
@SilinaKowalewski Kann es sein, dass das zweite Problem mit dem Fix der Debugging-Seiten erledigt wurde? Was anderes habe ich da in der Zwischenzeit nicht geändert.

Die anderen zwei Punkte sind erledigt und stehen im vollständig generierten Modul zur Verfügung.

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Kann schon sein, dass es mit der Debug-Seite zusammenhing. Wenn es nun klappt ist ja aber alles super!

**Comment by jocarstensen** [comment]
Ok, dann mache ich hier erstmal zu.
