### ISSUE TITLE
Problem Episoden: Weiterbildung

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#118]
Übertragen aus #116:
- [x] Taa05: Fehler in der Überschrift: „Fort- und Weiterbildung Test:“

- [x] taa05: Meister(in)/Techniker(in) in getrennte Kategorien (war so besprochen zum Weiterbildungsmodul)

- [x] Taa06: Fehler in der Überschrift: „Fort- und Weiterbildung Test: Test2:“

**Comment by jocarstensen** [comment]
Die "Tests" in den Überschriften sind bekannt und kommen später weg. Ich lasse das mal offen, damit wir uns dran erinnern.

@SilinaKowalewski Könntest Du aus Meister(in) und Techniker(in) zwei ao machen? Die haben keine Auswirkung auf die Filterführung

**Comment by woisch** [comment]
Meister(in) und Techniker(in) sind auf taa05 inzwischen getrennt.

Das kommt aber noch weitere Male vor, bitte ändern: 
- [ ] tba05, 
- [ ] tca05
- [ ] tda05
- [ ] tea05

@jocarstensen: Das sind dann doch alle Schleifen richtig? ansonsten bitte ergänzen...

**Comment by jocarstensen** [comment]
Stimmt, sorry. Das hätte ich dazu sagen können. Das muss auf den anderen Seiten auch korrigiert werden.

**Comment by SilinaKowalewski** [comment]
> Taa06: Fehler in der Überschrift: „Fort- und Weiterbildung Test: Test2:“

Habe zwar die Seite taa06 nicht gefunden, aber alle Test-Einblendungen sind nun entfernt.

**Comment by bafranke** [comment]
geprüft, Fehler tritt nicht mehr auf! Geschlossen
