### ISSUE TITLE
Probleme Episoden: nsET

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#119]
Übertragen aus #116:
- [x] Em0001: Rechtschreibfehler bei „selbsständig“ (Hinweistext) außerdem nicht einheitliche Schreibweise mit restlicher Befragung -> da verwenden wir immer selbständig

- [x] Generell: Beschriftung der Freitextfelder (Orte und PLZ bzw. Ausland) noch nicht umgesetzt

- [x] Emaa28: gendern: Berufssoldat(in); (nicht Referendar(in)

- [x] Emaa35: hängenbleiben auf der Seite

- [x] Emaa39: Weiterleitung auf Unterkategorien funktioniert nicht – es wird derzeit in jedem Fall „Sonstiges, und zwar“ angezeigt

- [x] Ema64: Rechtschreibfehler: nichtselstständige

- [x] Em0065: Textfeld erlaubt nur 2 Zeichen und schein als Zahl definiert zu sein – Texteingabe führt zu Fehler: Bitte geben Sie eine Zahl größer 0 ein.

- [x] Em0050: Rechtschreibfehler: bie (richtig: bei)

- [x] Em0042: Skalenpunkte beschriften (1-5)

- [x] Em0051: Skalenpunkte beschriften

- [x] Em0051: autoforward einstellen (Zofar?) funktioniert derzeit nicht als autoforward

**Comment by se-lang** [comment]
>  Em0001: Rechtschreibfehler bei „selbsständig“ (Hinweistext) außerdem nicht einheitliche Schreibweise mit restlicher Befragung -> da verwenden wir immer selbständig

Wir hatten uns im Rahmen des Pretest bewusst für "selbstständig" entschieden weil wir eine einheitliche schriebweise mit "nichtselbstständig erwerbstätig" haben wollten. Laut Duden geht sowohl "selbstständig" als auch "selbständig", aber es gibt nur "nichtselbstständig" oder "nicht selbständig" jedoch nicht "nichtselbständig". Wenn wir Befragten aber fragen ob sie "nicht selbständig erwerbstätig" waren ist nicht eindeutig was wir meinen.

> Generell: Beschriftung der Freitextfelder (Orte und PLZ bzw. Ausland) noch nicht umgesetzt

Dann funktioniert die Anzeige aus irgendeinem Grund wieder nicht, im QML ist eigentlich eine Beschriftung drin (@SilinaKowalewski das Problem gibt es ja anscheinend immer wieder an unterschiedlichen Stellen)

>Emaa39: Weiterleitung auf Unterkategorien funktioniert nicht – es wird derzeit in jedem Fall „Sonstiges, und zwar“ angezeigt

Das ist soweit ich mich erinnere Absicht, weil wir verhindern wollten, dass jemand abbricht nur, weil er/sie die Zuordnung der Branche nicht hinbekommt (@woisch hatten wir darüber geredet?)

>  Em0042: Skalenpunkte beschriften (1-5)
> Em0051: Skalenpunkte beschriften

Wie meinst du das? Vor allen Punkten (1) (2) etc., auch vor dem Text? Oder Nur bei den Punkten ohne Skalenbeschriftung? Ich bin daovn ausgegangen, dass wir hier bewusst endpunktgelabelte Skalen verwenden und habe deswegen keine zusätzliche Beschriftung eingefügt. Kann ich aber machen.

> Em0051: autoforward einstellen (Zofar?) funktioniert derzeit nicht als autoforward

Das wäre ein Punkt für Zofar (@SilinaKowalewski )

**Comment by se-lang** [comment]
@bafranke:
>Emaa28: gendern: Berufssoldat(in); (nicht Referendar(in)

Was meinst du hier? Bei mir ist das bereits so gegendert wie du geschrieben hast. (Könnte es sein, dass der Punkt aus einer älteren Version kommt?)

**Comment by woisch** [comment]
zu emaa39: Wir haben über das sonstiges bei beruflicher Stellung gesprochen. Bei der Branche bin ich mir nicht mehr sicher. Müsste das "sonstiges und zwar" nicht auf der ersten Ebene stehen müsste (also emaa39), für diejenigen, die sich nicht zuordnen können? Wir können hierzu nochmal telefonieren @se-lang 

zu em0042& em0051 Wir sollten im Sinne der Einheitlichkeit, die Skalenpunkte belabeln mit den Zahlen, auch bei den Textlabels. Haben wir im restlichen Fragebogen so gehandhabt:
![grafik](https://user-images.githubusercontent.com/53002476/69800105-dc996200-11d4-11ea-880b-ac62bbea88ab.png)

**Comment by bafranke** [comment]
![grafik](https://user-images.githubusercontent.com/56022369/69802462-f0939280-11d9-11ea-935e-22340019ccdc.png)
ich arbeite mit dem externen Link

**Comment by bafranke** [comment]
emaa39: es ist nichts außer sonstiges und zwar zu lesen - soweit ich es verstehe, müssten da aber jeweils die Unterkategorien abgebildet sein!
![grafik](https://user-images.githubusercontent.com/56022369/69802595-2fc1e380-11da-11ea-82f4-abccefbadecd.png)
![grafik](https://user-images.githubusercontent.com/56022369/69802614-35b7c480-11da-11ea-82a0-5e9fd383eae5.png)

**Comment by se-lang** [comment]
> ich arbeite mit dem externen Link, und habe nur das zurück gemeldet, was ich noch gefunden habe kann aber gut sein, dass du das angepasst hast, und es nur nicht ausgerollt ist?!

Das war wohl der Grund, jetzt sollte es passen.

> maa39: es ist nichts außer sonstiges und zwar zu lesen - soweit ich es verstehe, müssten da aber jeweils die Unterkategorien abgebildet sein!

@bafranke: Ach so, da hab ich dich falsch verstanden. Hab den Fehler gefunden, sollte nach dem nächsten Rollout funktionieren.

**Comment by se-lang** [comment]
@SilinaKowalewski damit ist hier nur noch folgender Punkt offen:
> Generell: Beschriftung der Freitextfelder (Orte und PLZ bzw. Ausland) noch nicht umgesetzt

Bei solchen Fehler, bitte immer dran denken, dass die meisten Fragen in dem Episodenmodulen mehrfach vorkommen (teilweise mit leichten Anpassungen im Fragetext):
> Em0042: Skalenpunkte beschriften (1-5)
> Em0051: Skalenpunkte beschriften

Hab ich in den beiden Fällen aber schon auf die anderen Seiten übertragen.

**Comment by jocarstensen** [comment]
Soweit ich weiß ist die Einblendung von Labels in offenen Feldern für die gesamte Befragung zentral geregelt. Dazu haben wir schon ewig ein Issue offen.

**Comment by SilinaKowalewski** [comment]
> Soweit ich weiß ist die Einblendung von Labels in offenen Feldern für die gesamte Befragung zentral geregelt. 

Das wäre mir neu ;)

Welches Issue meinst du denn?

**Comment by jocarstensen** [comment]
Issue #71 
Das war mal eine Aussage bei Pretest. Entweder Präfix oder Einblendung, das würde zentral gesteuert. In dem Fall gibt es aber nichts davon

**Comment by SilinaKowalewski** [comment]
Es ist richtig, dass nur Präfix oder Einblendung funktionieren aber nicht beides. Standardmäßig sind Präfixes eingestellt, die bei diesem Fragetyp nicht so einfach funktionieren, da sie ja schon ein "Präfix" bzw. den Itemtext haben. 

Wenn ein Infield-Text eingeblendet werden soll, müssen wir dies aber für jede Seite einzeln angeben. 

Aktuell ist die Option der Infield-Texte noch nicht eingebaut. @dzhwmeisner: Wird sich aber sicherlich drum kümmern sobald er Zeit dafür findet.

**Comment by woisch** [comment]
@se-lang 
- [ ] em0042: Hier steht als Überschrift "Abschlussfragen" (sonst immer Erwerbstätigkeit). Wollen wir das wirklich so? Könnte auch verwirrend sein, falls Befragte denken, danach ist die Befragung zuende.. 
Alternative wäre, auch hier einheitlich die Überschrift "Erwerbstätigkeit" zu nutzen.

![grafik](https://user-images.githubusercontent.com/53002476/69824487-29e4f600-120c-11ea-82c6-ebd5aaa03fc8.png)

**Comment by se-lang** [comment]
Ist korrigiert, war ein Relikt

**Comment by se-lang** [comment]
@bafranke hat mir noch neue Fehler geschickt:

> em0051: Umbruch nach: In Bezug auf … einfügen – möglich?

Ist korrigiert, das war insgesamt irgendwie falsch...

> Marie hat Seite mit Ausfüllhinweis „ismobile“ gesehen (cal0003), hat aber mit lnovo thinkpad getestet?!

@bafranke Weißt du zufällig mit welchem Tester Marie drin war? Dann könnten wir mal nachsehen was in jsCheck2 und width2 für Werte drin standen.

> Marie ist irgendwann auf eine Seite geführt worden, die fehlt (em0000)

Den Fehler hatte ich Freitag auch schon, ist inzwischen behoben und sollte nicht mehr vorkommen.

**Comment by bafranke** [comment]
Token: Tester220

**Comment by se-lang** [comment]
> Token: Tester220

Ok, wir haben nochmal in der Datenbank anchgesehen, die Werte passen alle zu einem Laptop und im QML passen alle Transitions. Kann mir das ehrlich gesagt nicht erklären... Müssten wir mal schauen, ob wir den Fall nochmal reproduzieren können. Vielleicht hat sie auch Seiten übersprungen und das hat zu dem Fehler geführt...

**Comment by woisch** [comment]
Wir brauchen noch Autoforward in:
emaa51
emba51
emca51
emda51
emea51
emfa51

(bisher haben wir den nur in em0051 implementiert)
@se-lang: Das sind alle nsET-Schleifen für berufl. Zufriedenheit, richtig?

**Comment by bafranke** [comment]
kleiner Nachtrag: 
-	em0046: z.B. Schichtzulagen (Leerzeichen zwischen z. B.)

**Comment by SilinaKowalewski** [comment]
> Wir brauchen noch Autoforward in:
> 
> * [ ]  emaa51
> * [ ]  emba51
> * [ ]  emca51
> * [ ]  emda51
> * [ ]  emea51
> * [ ]  emfa51
> 

Sind das dann alle verbleibenden Seiten auf denen der Autoforward eingebaut werden muss? Es würde Sinn machen die Seiten erstmal zu sammeln falls noch mehr kommen.

**Comment by SilinaKowalewski** [comment]
> kleiner Nachtrag:
> 
> * em0046: z.B. Schichtzulagen (Leerzeichen zwischen z. B.)

@bafranke: Habe diesen "Fehler" durch Suchen&Ersetzen gelöst und dabei 6 weitere Stellen gefunden. Denke das passt so, oder?

**Comment by bafranke** [comment]
perfekt, danke!

**Comment by woisch** [comment]
> 
> 
> > Wir brauchen noch Autoforward in:
> > 
> > * [ ]   emaa51
> > * [ ]   emba51
> > * [ ]   emca51
> > * [ ]   emda51
> > * [ ]   emea51
> > * [ ]   emfa51
> 
> Sind das dann alle verbleibenden Seiten auf denen der Autoforward eingebaut werden muss? Es würde Sinn machen die Seiten erstmal zu sammeln falls noch mehr kommen.

Für nsET und SET sollten das alle sein, ja.

**Comment by se-lang** [comment]
>@se-lang: Das sind alle nsET-Schleifen für berufl. Zufriedenheit, richtig?
Ja, das sind alle.

**Comment by SilinaKowalewski** [comment]
Alles klar, sind eingebaut und ab nächstem Roll-Out verfügbar.

**Comment by woisch** [comment]
Die o.g. Autoforwards sind eingebaut.

**Comment by woisch** [comment]
Rechtschreibfehler auf embb11 entdeckt. Der scheint auf allen entsprechenden Seiten mit Wechsel der beruflichen Stellung zu sein: emcc11, emdd11 usw. aber auch emab11, emac11, emad11 usw...

Sie haben angegeben, dass sich Ihre berufliche _Stellug_ bei HIS geändert hat.

**Comment by se-lang** [comment]
> 
> 
> Rechtschreibfehler auf embb11 entdeckt. Der scheint auf allen entsprechenden Seiten mit Wechsel der beruflichen Stellung zu sein: emcc11, emdd11 usw. aber auch emab11, emac11, emad11 usw...
> 
> Sie haben angegeben, dass sich Ihre berufliche _Stellug_ bei HIS geändert hat.

Korrigiert.

**Comment by se-lang** [comment]
Nachdem hier jetzt alles bearbeitet und überpürft ist mach ich hier mal zu. Das wird mir zu unübersichtlich 😉
