### ISSUE TITLE
Modul Gesundheit, bug report 1

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#12]
- Alle Seiten des Moduls, auch Karussell: für Iphone 5/SE & Galaxy S5 werden auf keiner Seite die vor uns zurück Buttons mit auf der Seite angezeigt, sondern sind nur durch scrollen nach unten sichtbar, obwohl noch Platz auf der Seite wäre. Wäre es möglich dasso darzustellen, dass die vor und zurück buttons ohne scrollen sichtbar sind?

- gsh01 in der responsivem mobile Darstellung (responsive allgemein, Galaxy, iphone etc.) wird die Skala nicht ganz im Bild dargestellt, sondern istabgeschnitten. Vermutlich müsste hier die Karussell-Darstellung greifen, auch wenn Einzelitem.

- bei gsh03 und gsh04 wird der Plausi-Hinweis für die gültige Eingabe der Tage (in der pv die punkte av, kh) nicht richtig dargestellt, dass keine mögliche Zahl zwischen 0 und 28 eingetragen wurde, stattdessen steht da:
 h_beispiel: Das heißt: heißt bei Ihnen: 42
Alternative: Das heißt: heißt bei Ihnen: 42

**Comment by se-lang** [comment]
>- bei gsh03 und gsh04 wird der Plausi-Hinweis für die gültige Eingabe der Tage (in der pv die punkte av, kh) nicht richtig dargestellt, dass keine mögliche Zahl zwischen 0 und 28 eingetragen wurde, stattdessen steht da:
> h_beispiel: Das heißt: heißt bei Ihnen: 42
> Alternative: Das heißt: heißt bei Ihnen: 42

@SilinaKowalewski Das ist wohl noch unser Beispiel für die Einblendungen, muss natürlich wieder raus ;-) Sorry!

**Comment by heikQ** [comment]
jup, kann zu
