### ISSUE TITLE
Probleme Episoden: andere Tätigkeiten

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#120]
Übertragen aus #116:
- [x] O0001: Freitextfeld bei Sonstiges fehlt

- [x] oaa(b)01: hängenbleiben, wenn nur Beginn vor und dauert an angekreuzt, ohne Fehlermeldung, gleiches gilt für oca01, oda, odb,

- [x] Oaa07: Fehler im Hinweistext (Layout.break)

- [x] Oca05: Fehler im Hinweistext (Layout.break)

**Comment by jocarstensen** [comment]
Nummer zwei gucke ich mir an. 

@SilinaKowalewski Könnt Ihr Nummer eins, drei und vier übernehmen?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Nummer eins schaue ich mir am Montag an.

**Comment by se-lang** [comment]
> Nummer zwei gucke ich mir an.

Falls du das noch nicht getan hast, ich kann den Fehler nicht reproduzieren.

**Comment by jocarstensen** [comment]
Ich gehe mal stark davon aus, dass das ein altes Issue von vor der Häkchenlösung war. Ich markiere es als gelöst.

**Comment by SilinaKowalewski** [comment]
Nummer 1 ist auch gelöst und bereits ausgerollt.

**Comment by jocarstensen** [comment]
Der Fehler aus Punkt 3 findet sich auch auf oab07

**Comment by SilinaKowalewski** [comment]
Fehler ist auch auf oab07 behoben.

**Comment by woisch** [comment]
o0001: Wenn ich "Sonstiges" und/oder "keiner weiteren Tätigkeit " auswähle crasht die Seite beim Verlassen

**Comment by jocarstensen** [comment]
da fehlte ein "or". Hab ich comitted. Nächsten Rollout abwarten...

**Comment by woisch** [comment]
Problem auf o0001 scheint behoben. Komme jetzt weiter wenn ich eine der beiden unteren Kategorien auswähle.

**Comment by jocarstensen** [comment]
Japp, sieht gut aus.
