### ISSUE TITLE
Problem Episoden: Ausbildung

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#121]
Übertragen aus #116:
- [x] vaa30: Haben Sie zwischen Juli 2018 und November 2019 noch eine weitere Ausbildung, Umschulung oder ein Volontariat gemacht? -> Müsste es Dezember 2019 heißen?

**Comment by jocarstensen** [comment]
Gucke ich mir an

**Comment by se-lang** [comment]
Gleicher Fehler wie in #122, hab analog die Einblendung des aktuellen Monats durch die Enblendung von h_exitlabel ersetzt

**Comment by woisch** [comment]
ist das dann jetzt behoben und kann zu?

**Comment by bafranke** [comment]
bei mir funktioniert es!

**Comment by woisch** [comment]
bei mir auch

**Comment by se-lang** [comment]
dann mach ich hier zu
