### ISSUE TITLE
Probleme Episoden: Praktikum

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#122]
Übertragen aus #116:
- [x] hängenbleiben auf iaa05

- [x] iba21: Enddatum November 2019 richtig?

**Comment by se-lang** [comment]
>  hängenbleiben auf iaa05

Liegt an folgender Transition, es gibt keine condition für den Fall, dass man geantwortet hat. Ich nehm die condition einfach raus, dann sollte es funktionieren.
`<zofar:transition target="iaa06" condition="zofar.isMissing(iaa05) and sf_iaa05.value"/>`

>iba21: Enddatum November 2019 richtig?

Als Enddatum wurde noch der aktuelle Monat durch `#{zofar.getMonthLabel(startPoint)}` eingeblendet. Hab die gesamte Einblendung des Enddatums durch `#{h_exitlabel.value}` ersetzt.

@bafranke: sollte nach dem nächsten Rollout beides funktionieren.

**Comment by bafranke** [comment]
läuft! Danke!
