### ISSUE TITLE
Problem Episoden: Schule

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#123]
Übertragen aus #116:
- [x] Scaa13: Hier stimmt etwas nicht, es gibt die ao „bitte auswählen“ -> dropdown geplant?

**Comment by se-lang** [comment]
@jocarstensen: Ich hab die Antwortoption einfach auskommentiert. Falls du doch eigentlich Dropdown haben wolltest, lässt sich das schnell wieder ändern. Wenn das passt, kannst du hier zumachen.

**Comment by jocarstensen** [comment]
passt, danke!
