### ISSUE TITLE
Probleme Episoden: Arbeitslosigkeit

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#124]
Übertragen aus #116:
- [x] Uaa05: Hier wird der Verweis auf den Monat, der im Dropdown auf der Vorseite ausgewählt wird, als Zahl und nicht als Wort angezeigt

- [x] Uaa06: Im Fragetext ist das Wort „Zeit“ hinter der Zeitraumangabe überflüssig

- [x] Uaa06: Ich habe auf der Vorseite ausgewählt, dass ich mich nicht arbeitssuchend gemeldet habe, dann dürfte ich die Frage doch nicht kriegen, oder?

**Comment by SilinaKowalewski** [comment]
> * Uaa05: Hier wird der Verweis auf den Monat, der im Dropdown auf der Vorseite ausgewählt wird, als Zahl und nicht als Wort angezeigt

Der Fehler liegt daran, dass #{zofar.valueOf(xxx)} genutzt wird anstelle von #{zofar.labelOf(xxx)}.

**Comment by se-lang** [comment]
> 
> 
> > * Uaa05: Hier wird der Verweis auf den Monat, der im Dropdown auf der Vorseite ausgewählt wird, als Zahl und nicht als Wort angezeigt
> 
> Der Fehler liegt daran, dass #{zofar.valueOf(xxx)} genutzt wird anstelle von #{zofar.labelOf(xxx)}.

Hab ich korrigiert.

**Comment by SilinaKowalewski** [comment]
>  Uaa06: Ich habe auf der Vorseite ausgewählt, dass ich mich nicht arbeitssuchend gemeldet habe, dann dürfte ich die Frage doch nicht kriegen, oder?

@se-lang: Müssen wir hier noch etwas anpassen?

**Comment by jocarstensen** [comment]
>  Uaa06: Ich habe auf der Vorseite ausgewählt, dass ich mich nicht arbeitssuchend gemeldet habe, dann dürfte ich die Frage doch nicht kriegen, oder?
Da habe ich keinen Filter programmiert. Würde aber Sinn machen. 

@SilinaKowalewski Könntest Du auf uaa05 folgende Transition einbauen:
`GOTO uaa06 IF uaa05==1`
`GOTO uaa20 IF uaa<>1`

Und das Ganze analog auch für uba05, uca05 und uda05?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Habe ich umgesetzt. Allerdings in dieser Form: 
```
GOTO uaa06 IF uaa05==1
GOTO uaa20 IF ELSE
```
Sonst käme man im Falle eines Missings nicht von der Seite. Oder soll für diesen Fall eine extra Transition eingefügt werden?

**Comment by jocarstensen** [comment]
Das passt, das meinte ich auch mit <>1.

Danke!

**Comment by SilinaKowalewski** [comment]
Änderungen sind ausgerollt und können getestet werden.

**Comment by jocarstensen** [comment]
passt
