### ISSUE TITLE
Befragungseinstieg Mobile Endgeräte

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#125]
Auf mobilen Endgeräten wird man zur Zeit nach Eingabe des Tokens direkt auf die Seite st0001.html geleitet. Der komplette erste Befragungsteil (Einstieg/beg) sowie das Kalendarium werden übersprungen.

**Comment by woisch** [comment]
Triit bisher bei 3 Geräten auf. 2 mal iPhone (safari) und einmal Samsung (mozilla)

**Comment by woisch** [comment]
@se-lang, @heikQ : Könnt ihr bei Gelegenheit mal auf deinem Smartphone testen, wo ihrnach dem Login rauskommt? 
Bei Silina und Viktor scheint es normal zu funktionieren...

**Comment by se-lang** [comment]
Ich lande nicht direkt auf st0001, aber fast. Nach Eingabe des Tokens kommt erst ganz normal index, dann offer und *dann* lande ich auf st0001.

**Comment by andreaschu** [comment]
@se-lang und @heikQ ihr braucht das nicht noch mal zu testen. Das ist bei uns auch so. Es war nur missverständlich formuliert.
Wir suchen nachher nach dem Grund.

**Comment by se-lang** [comment]
Hab das Problem gefunden

**Comment by se-lang** [comment]
In questionnaire16 gibt es nochmal index und offer, die hätten vermutlich raus gemusst bevor ich das Modul gestern oder vorgestern in Abstimmung mit @SilinaKowalewski ausgetauscht habe

**Comment by SilinaKowalewski** [comment]
@se-lang: Jap, dass wird der Fehler gewesen sein. Dadurch wurden die Seiten mit den richtigen Transitions überschrieben. 

Habe beide Seiten auf dem qml16 gelöscht.

**Comment by se-lang** [comment]
Super, danke!

**Comment by SilinaKowalewski** [comment]
Das Problem scheint leider noch in anderen qmls zu existieren. Komme nun leider auf die taa01 weil diese auch in einer anderen Index-Seite als Transition angelegt ist. 

Werde nun alle qmls durchsuchen und doppelte Seiten raus löschen.

**Comment by SilinaKowalewski** [comment]
Nun klappt alles. Komme nach dem Einstieg auf beg_00.

**Comment by jocarstensen** [comment]
@woisch @bafranke @se-lang @heikQ Kann das jemand bestätigen?

**Comment by woisch** [comment]
Ich lande nach der Tokeneingabe (und einer Zwischenseite mit dem Hinweis zum Landscaüe-Modus) auch auf beg_00 auf meinem Mobile

**Comment by bafranke** [comment]
bei mir funktioniert es auch

**Comment by jocarstensen** [comment]
Super, dann machen wir hier zu.
