### ISSUE TITLE
Modul Studium: Exklusive Kategorie vs. offene Angaben (mas_09)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#126]
Ist es (ohne großen Aufwand!) möglich, die offenen Felder automatisch zu leeren, wenn das Häkchen unten gesetzt ist?
Wenn nein: Könnt ihr hier einen softforce/Fehlermeldung einbauen, wenn Häkchen gesetzt und irgendwo Zahlen eingetragen sind?
![grafik](https://user-images.githubusercontent.com/53002476/69802416-d0fc6a00-11d9-11ea-92af-5048154bc5e4.png)

**Comment by SilinaKowalewski** [comment]
@woisch: 

Das ist leider gar nicht möglich. Erst recht nicht ohne großen Aufwand ;)

Einen SF kann ich aber natürlich gerne einbauen. Gibst du mir einen entsprechenden Text dafür?

**Comment by woisch** [comment]
Ok, dann nehme ich den folgenden sf-Text: 
"Bitte prüfen Sie Ihre Angaben."

**Comment by SilinaKowalewski** [comment]
Das wäre dann ein Hardforce. Oder soll zusätzlich eine Checkbox angezeigt werden?

**Comment by SilinaKowalewski** [comment]
Habe das Forcing zunächst wieder komplett ausgebaut. Sollten wir wider erwarten in den nächsten Wochen noch Zeit dafür übrig haben würde ich mir dieses Issue wieder vornehmen und eine Art "RangeCheck" einbauen.

**Comment by woisch** [comment]
Was Silina sagt.
Ich schließe dann hier erstmal-
