### ISSUE TITLE
Kalendarium: make the button schö´ again

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#127]
Auf den Seiten der jeweiligen Kalendarien für cohorte 1 und 2 hätten wir gern vor dem Button zur Auswahl der Aktivitäten in gut lesbaren wunderschönen Lettern stehen: 
Aktitvität: (Anmerkung des Verfassers: hier folgt dann der bisherige Button)
Wenn noch keine Aktivität gewählt wurde, soll in dem Auswahlbutton dann stehen "... bitte auswählen"

Sollte sich nichts vor dem Button platzieren lassen, ginge es notfalls auch oben drüber.

**Comment by woisch** [comment]
@heikQ 
Ist das hier noch aktuell?

**Comment by SilinaKowalewski** [comment]
Ja, isses. Wir setzten uns heute daran.

**Comment by dzhwmeisner** [comment]
erledigt. wirdd im nächsten Rollout vorhanden sein

**Comment by woisch** [comment]
könnt ihr den Text "Aktivität" noch größer machen, sodass er die selbe Schriftgröße hat wie der Inhalt der Box?

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
Ich mache hier erstmal zu. Ist umgesetzt.
