### ISSUE TITLE
Probleme Episoden: Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#128]
- [x] staa10 (und weitere) kein Rangecheck bei der PLZ, kann Zahlen mit mehr als 5 stellen sowie buchstaben angeben:
![grafik](https://user-images.githubusercontent.com/53002476/69816486-c8675c00-11f8-11ea-8187-c002b5bbe486.png)

- [x] falsche Weiterleitung, bitte mal prüfen: Ich habe auf staa24 angegeben, dass sich mehrere Punkte meines Studiums geändert haben. Auf staa33 habe ich angegeben, dass sich Abschlussart und Umfang/Art geändert haben. Auf staa34 gebe ich dann 2 Wechseldaten ein. Anschließend kommt stab07, auf der ich meinen neuen Abschluss angebe, dann wird mir stab17 vorgelegt (die macht keinen Sinn hier) und danach erst stab21 (da wird der Wechsel von Umfang/Art abgefragt, was ja korrekt ist).

**Comment by se-lang** [comment]
>staa10 (und weitere) kein Rangecheck bei der PLZ, kann Zahlen mit mehr als 5 stellen sowie buchstaben angeben:

Rangecheck ist hier nicht drin, weil wir auf der gleichen Seite die Angabe ob Deutschland oder Ausland forcieren (filterrelevant). Beides zusammen funktioniert leider nicht, dann kommt das soft-forcing auch wenn der Rangecheck anschlägt.

Zweiten Punkt schau ich mir an.

**Comment by jocarstensen** [comment]
aber man könnte das Feld doch auf fünf Felder begrenzen, oder? @SilinaKowalewski

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Du meinst 5 Zeichen? Klar, das ginge. Ich kann ja auch bspw. 100-99999 als Min- und Max-Value einstellen.

**Comment by se-lang** [comment]
Der Wertbereich funktioniert meines Wissens eben nicht, wenn wir ein soft-force auf der gleichen Seite haben, bzw. er funktioniert schon, aber dann wird immer auch der soft-force angezeigt. Wenn wir mit der Zeichenbegrenzung noch keine ValidationMessage brauchen, sondern einfach nicht mehr engetragen werden kann, könnten wir das zumindest gerne umsetzen. Ist das so @SilinaKowalewski?

Den zweiten Fehler habe ich gefunden und gerade korrigiert. @woisch bitte nach dem nächsten Rollout nochmal testen.

**Comment by SilinaKowalewski** [comment]
@se-lang: Du könntest Recht haben, mit dem SF. Wir eine reine Zeichenbegrenzung brauchen wir aber keine ValidationMessage. Kann den ersten Fall aber morgen gerne noch mal prüfen.

**Comment by jocarstensen** [comment]
@SilinaKowalewski Bitte Zeichenbegrenzung für alle offenen Eingabefelder mit Label "PLZ:" im Studium umsetzen (5 Zeichen).

**Comment by SilinaKowalewski** [comment]
Habe auf staa10 (und weitere) die maximale Zeichenlänge auf 5 gesetzt.

**Comment by jocarstensen** [comment]
@woisch Kannst Du testen?

**Comment by woisch** [comment]
Kann die Seite staa10 nicht sehen...

**Comment by woisch** [comment]
Sorry, es geht doch.
Die PLZs sind jetzt auf 5 Stellen (Zeichen und Zahlen) begrenzt.
auch auf stba10, stca10,stda10 und stea10

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue dann geschlossen werden?

**Comment by woisch** [comment]
@se-lang 
Das Problem mit der falschen Weiterleitung tritt jetzt nicht mehr auf!

**Comment by woisch** [comment]
Allerdings bleibt man unter bestimmten Umständen auf der staa34 hängen. Habe den selben Fall wie oben beim Weiterleitungsproblem ausgefüllt. Ich bleibe ghängen, wenn ich beim 2. Wechsel ein Datum angebe, was vor dem ersten Wechsel liegt. (Januar 2018 ist in meinem Beispiel auch das Startdatum der Studienepisode). Sobald ich Februar 2018 oder später wähle, geht es normal weiter..

![grafik](https://user-images.githubusercontent.com/53002476/69953534-b982f100-14f9-11ea-8700-058661dadda9.png)

**Comment by woisch** [comment]
> 
> 
> Kann dieses Issue dann geschlossen werden?

noch nicht also :)

**Comment by woisch** [comment]
> 
> 
> @se-lang
> Das Problem mit der falschen Weiterleitung tritt jetzt nicht mehr auf!

Allerdings kriege ich meinem obigen Szenario auch die Nachfragen zum Wechsel von Umfang/Art (stab21) nicht mehr vorgelegt! Wird man da jetzt versehentlich drübergefiltert?

**Comment by se-lang** [comment]
Das Hängenbleiben kann ich reproduzieren, schau ich mir gleich an...
 
> > @se-lang
> > Das Problem mit der falschen Weiterleitung tritt jetzt nicht mehr auf!
> 
> Allerdings kriege ich meinem obigen Szenario auch die Nachfragen zum Wechsel von Umfang/Art (stab21) nicht mehr vorgelegt! Wird man da jetzt versehentlich drübergefiltert?

Diesen Fehler kann ich aber nicht reproduzieren, ich werde erst nach dem Abschlusswechsel gefragt und dann nach Umfang/Art...

**Comment by woisch** [comment]
> 
> > > @se-lang
> > > Das Problem mit der falschen Weiterleitung tritt jetzt nicht mehr auf!
> > 
> > 
> > Allerdings kriege ich meinem obigen Szenario auch die Nachfragen zum Wechsel von Umfang/Art (stab21) nicht mehr vorgelegt! Wird man da jetzt versehentlich drübergefiltert?
> 
> Diesen Fehler kann ich aber nicht reproduzieren, ich werde erst nach dem Abschlusswechsel gefragt und dann nach Umfang/Art...

Okay, jetzt geht es bei mir auch, wie es sein sollte, kriege alle Fragen vorgelegt! Sorry für die Verwirrung!

**Comment by jocarstensen** [comment]
@SilinaKowalewski Kann man die Zeichen in den Feldern auch noch auf Ziffern beschränken oder erfordert das einen Force?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Das würde wieder eine ValidationMessage erfordern.

**Comment by jocarstensen** [comment]
Gut, dann belassen wir es dabei. @woisch Kann dann hier zu?

**Comment by woisch** [comment]
@jocarstensen: 
@se-lang prüft noch das Hängenbleiben auf staa34

**Comment by se-lang** [comment]
@woisch Hab den Fehler gefunden und korrigiert, sollte nach dem nächsten Rollout funktionieren.

**Comment by woisch** [comment]
dann warte ich den rollout ab, danach könnte hier zu

**Comment by woisch** [comment]
jetzt geht es, bleibe im obigen Szenario nicht mehr hängen.
