### ISSUE TITLE
HV aus Kalendarium anpassen

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#129]
Ist es mögliche h_alofam folgendermaßen anzupassen? Hatte ich ursprünglich nicht ganz korrekt formuliert.
h_alofam=1 wenn (cohort==1 and (22 Monate Arbeitslosigkeit oder Familientätigeit)) or (cohort==2 and (16 Monate Arbeitslosigkeit oder Familientätigkeit))

Bisher wird sie nur dann 1 wenn in ~einem~ (oder beiden) der Episodentypen 22 bzw. 16 Monate ausgewählt wurden. Eigentlich sollte die HV aber anzeigen wenn 22 bzw. 16 Monate entweder Arbeitslosigkeit oder Familientätigkeit eingetragen würde, eine Kombination aus den beiden Episodentypen wäre also auch "zulässig".

**Comment by SilinaKowalewski** [comment]
@se-lang: Ich weiß zwar nicht genau wie, aber ich glaube, ich habe das Problem gelöst bzw. die HV angepasst. Ruf mich doch einfach mal an wenn du Zeit hast, dass wir das nochmal gemeinsam prüfen.

**Comment by SilinaKowalewski** [comment]
@se-lang: Unsere Änderungen von gestern crashen nun nicht mehr und sind ausgerollt. Komm doch am besten heute mal vorbei damit wir sie noch mal testen können.

**Comment by se-lang** [comment]
Top, ich komm nach der Mittagspause mal vorbei 👍

**Comment by SilinaKowalewski** [comment]
Habe es nun auf die alte Version zurück geändert. Solltest du/wir aber nach dem nächsten Roll-Out noch mal testen.

**Comment by SilinaKowalewski** [comment]
@se-lang: Hattest du schon Gelegenheit hier zu testen? Oder soll ich das noch mal machen?

**Comment by jocarstensen** [comment]
Sebastian ist leider erst heute Nachmittag/Abend wieder da. Wenn Du schon mal mit Testen anfangen könntest, wäre das super!

**Comment by SilinaKowalewski** [comment]
Habe gerade mal mit Hilfe der Datenbank getestet. 

Das hier passiert: 
**Cohort1** - wenn Arbeitslosigkeit ODER Familientätigkeit mind. 22 Monate angegeben werden => h_alofam=1

**Cohort2** - wenn Arbeitslosigkeit ODER Familientätigkeit mind. 16 Monate angegeben werden => h_alofam=1

Wenn ich es richtig verstanden habe, ich es genau das, was passieren soll.

**Comment by jocarstensen** [comment]
Klingt für mich auch so. Ich würde es aber gern offen lassen, bis @se-lang nochmal drübergeguckt hat.

**Comment by se-lang** [comment]
Genau das soll sie tun. Dann mach ich hier jetzt zu,
