### ISSUE TITLE
Modul_Einstieg updated

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#13]
Modul Einstieg bitte updaten.
eb36d903f1752f4ffa284ca7bece8840e2bf9409

beg_10 und beg_11 gelöscht
neu eingefügt ehemalige msg_02 (ist jetzt beg09)
Änderungen der Reihenfolge und Transitions

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Bitte prüfen.

**Comment by woisch** [comment]
Ich hänge auf Seite beg_01 direkt fest (tester1 als Token genommen).

**Comment by SilinaKowalewski** [comment]
Das liegt daran, dass sich die Transitions auf die Hilfsvariable bzw. Preload-Variable beziehen, die noch nicht angelegt sind. 

Du kannst aber einfach über die URL navigieren.

**Comment by SilinaKowalewski** [comment]
Funktionieren die Transitions nun? Falls ja, kann aus meiner Sicht das Issue geschlossen werden.

**Comment by woisch** [comment]
jetzt geht es, kann zu
