### ISSUE TITLE
Update Modul Studium: mas_07

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#130]
mas_07 auf 2 Seiten aufgeteilt, weil in responsiver Ansicht nicht darstellbar:

- [x] mas_07 nur noch mit offenen Abfragen plus Checkbox
- [x] mas_07a neu eingefügt: dort nur die Items einblenden und bewerten lassen, die auf mas_07 Angaben enthalten

https://github.com/dzhw/SLC-IntEr/commit/ac44fe4a7aae1df5c9a913abbf29e896bf9664de

@SilinaKowalewski: Kannst du mal einen Blick auf die transition aus mas_07 raus werfen? Hoffe das passt so/ist erschöpfend. War unsicher wegen der Checkbox (wenn diese angehakt ist, soll auf jeden Fall mas_07a übersprungen werden nach meiner Definition)

**Comment by SilinaKowalewski** [comment]
@woisch: 

Die Transition bzgl. der Checkbox sieht gut aus. Die obere Transition würde aber bedeuten, dass man nur auf mas_07a kommt, falls eines der offenen Felder leer ist. Meinst du das? 

Ich hätte vermutet, dass man zur mas_07a kommen soll solange nicht alle Felder leer sind.

**Comment by SilinaKowalewski** [comment]
@woisch: 

Und sollen die offenen Felder beschriftet werden? Laut PV würde kein Text davor stehen.

**Comment by woisch** [comment]
> 
> 
> @woisch:
> 
> Die Transition bzgl. der Checkbox sieht gut aus. Die obere Transition würde aber bedeuten, dass man nur auf mas_07a kommt, falls eines der offenen Felder leer ist. Meinst du das?
> 
> Ich hätte vermutet, dass man zur mas_07a kommen soll solange nicht alle Felder leer sind.

Ok, ich wollte eigentlich sagen, dass mindestens ein Feld gefüllt ist (also keines der Felder Missing). Müsste es dann eine Und-Bedingung sein einfach?

**Comment by woisch** [comment]
> 
> 
> @woisch:
> 
> Und sollen die offenen Felder beschriftet werden? Laut PV würde kein Text davor stehen.

Ich hätte gerne als Präfix vorm Feld:
1.
2.
3.
...
8.

**Comment by SilinaKowalewski** [comment]
Ja, genau. Wäre dann eine Und-Verknüpfung.

**Comment by woisch** [comment]
Habe beides (hoffentlich korrekt) in der PV geändert
https://github.com/dzhw/SLC-IntEr/commit/aab2622a7de7d1b842d2dcc5f3cc8405fbcdb1ca

**Comment by SilinaKowalewski** [comment]
> Ja, genau. Wäre dann eine Und-Verknüpfung.

Ach ne, quatscht! Das passt auch nicht. Du hattest total Recht! Sorry für die Verwirrung. Ist alles richtig in der PV.

**Comment by woisch** [comment]
OK, dann mache ich wieder eine oder-Bedingung draus? Welche Variante ist besser?

**Comment by SilinaKowalewski** [comment]
Habe es jetzt mit einer Oder-Bedingung programmiert. Das sollte eigentlich hinhauen.

**Comment by woisch** [comment]
OK, dann ändere ich es wieder zurück, wegen der Doku.

**Comment by SilinaKowalewski** [comment]
@vdick: Kannst du dir hier bitte noch mal das Layout anschauen. Die Textfelder sollten definitiv größer sein. 

@woisch: Die neue Seite ist zwar schon ausgerollt aber mir sind selber noch zwei Fehler aufgefallen. Gebe Bescheid wenn ich die behoben habe.

**Comment by woisch** [comment]
Ok!
Momentan werden auch bei einer Angabe in msg_07 noch alle 8 Items eingeblendet auf msg_07a (Wahrscheinlich hast du das auf dem Schirm)

**Comment by SilinaKowalewski** [comment]
Ja, genau. Habe die Sichtbarkeitsbedingung versehentlich an die Item-Texte und nicht an die Items an sich gehängt. Ist beim nächsten Roll-Out aber behoben.

**Comment by woisch** [comment]
Das Einblenden aus mas_07a funktioniert jetzt wie gewünscht!

Aber die eine Transition geht noch nicht, sofern in mindestens einem Kästchen etwas steht:
GOTO mas_08 if mainfnn_154==1

Ich vermute das geht nicht, weil die Transition in Konflikt mit der anderen Transition steht? Zur Not könnte es so bleiben, falls es zu aufwendig wird.

**Comment by woisch** [comment]
@vdick: Wie Silina schon schrieb, die Textfelder bitte breiter (etwa so breit wie der Hinweistext) und dann auch linksbündig!

**Comment by SilinaKowalewski** [comment]
> @SilinaKowalewski: Das Einblenden aus mas_07a funktioniert jetzt wie gewünscht!
> 
> Aber die eine Transition geht noch nicht, sofern in mindestens einem Kästchen etwas steht:
> GOTO mas_08 if mainfnn_154==1
> 
> Ich vermute das geht nicht, weil die Transition in Konflikt mit der anderen Transition steht? Zur Not könnte es so bleiben, falls es zu aufwendig wird.

Ja, da scheint es eine Überschneidung zu geben. Die sollte aber nun gefixed sein.

**Comment by woisch** [comment]
@SilinaKowalewski: Klappt jetzt so wie in der PV geschrieben! 

@bafranke: Macht die Transition auch aus deiner Sicht so Sinn?

**Comment by SilinaKowalewski** [comment]
@woisch: 
Habe die Transition angepasst. Kann jetzt also getestet werden. 
Allerdings ist noch unklar was passieren soll, wenn ein Text angegeben wurde und die CheckBox ausgewählt. Soll dann auch auf Seite mas_08 weitergeleitet werden?

**Comment by woisch** [comment]
Wenn text eingegen wird und die Checkbox ausgewählt wird, dann sollen die Befragten auch auf mas_07a gehen. So wie es jetzt aktuell auch umgesetzt ist.
Auf mas_08 also nur, wenn nur die Checkbox angehakt oder alles leer ist.

**Comment by SilinaKowalewski** [comment]
Super, dann sollte jetzt alles passen.

**Comment by woisch** [comment]
Transition stimmt jetzt.
Allerdings ist das Layout der Textfelder noch nicht korrigiert.

**Comment by woisch** [comment]
Hier brauchen wir noch Layout Unterstützung von @vdick

**Comment by SilinaKowalewski** [comment]
@woisch @vdick: 
Habe mich gerade mal selber am css versucht. Können nach dem nächsten Roll-Out mal checken ob das geklappt hat.

**Comment by woisch** [comment]
@bafranke:
Kannst du das Layout heute bitte auch noch mal testen? 
Auch auf dem mobile. Ist mas_07 aus deiner Sicht auf dem mobile verständlich und ausfüllbar?

**Comment by woisch** [comment]
- [ ] mas_07: Kannst du die Textfelder links ausrichten (wenns zu aufwendig ist so lassen)?
- [ ] Bitte vor den Textfeldern den Text ändern und Doppelpunkt davor:
1. Angebot/Quelle:
2. Angebot/Quelle:
3. Angebot/Quelle:
4. Angebot/Quelle:
5. Angebot/Quelle:
6. Angebot/Quelle:
7. Angebot/Quelle:
8. Angebot/Quelle:

**Comment by SilinaKowalewski** [comment]
> * mas_07: Kannst du die Textfelder links ausrichten (wenns zu aufwendig ist so lassen)?

@vdick: Kannst du mal schauen wie aufwendig das wäre und es eventuell umsetzen?

**Comment by woisch** [comment]
Der eine Punkt ist schon umgesetzt.
Das links ausrichten hat geringe Prio wie gesagt. Lasse aber hier nochmal offen

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
Im neuesten Rollout noch keine Veränderung bei der Ausrichtung der Items

**Comment by woisch** [comment]
jetzt sieht es besser aus, mache mal zu
