### ISSUE TITLE
Problem und Layout - mobil und desktop (Modulübergreifend, keine Episoden)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#132]
bitte noch folgende Punkte anpassen:

- [x] Aus_02: bug: kein Weiterkommen ohne Angabe, aber auch kein sf-Fehlermeldung angezeigt!

- [x] msg_08: online: Kind(er) hinter Freifeld positionierbar?
![grafik](https://user-images.githubusercontent.com/56022369/69868677-b0501500-12aa-11ea-9835-c2c5186d378f.png)

- [x] Mas_11: Leerzeile vor „Mehrfachnennung…“ entfernen
![grafik](https://user-images.githubusercontent.com/56022369/69868818-35d3c500-12ab-11ea-9dd8-b56a7f9ec33a.png)

**Comment by SilinaKowalewski** [comment]
>  Aus_02: bug: kein Weiterkommen ohne Angabe, aber auch kein sf-Fehlermeldung angezeigt!

@woisch: Aktuell ist die Seite so programmiert wie in der PV vorgegeben. Wohin sollen Missings geleitet werden?

**Comment by SilinaKowalewski** [comment]
> msg_08: online: Kind(er) hinter Freifeld positionierbar?

@vdick: Kannst du das Layout hier bitte anpassen?

**Comment by woisch** [comment]
> 
> 
> > Aus_02: bug: kein Weiterkommen ohne Angabe, aber auch kein sf-Fehlermeldung angezeigt!
> 
> @woisch: Aktuell ist die Seite so programmiert wie in der PV vorgegeben. Wohin sollen Missings geleitet werden?

Habs in der PV korrigiert: GOTO aus_03a if ausabs_154=MISSING
https://github.com/dzhw/SLC-IntEr/commit/5460206e7b7e43defa972aa909bbabe3f2d58dd7

**Comment by vdick** [comment]
> > msg_08: online: Kind(er) hinter Freifeld positionierbar?
> 
> @vdick: Kannst du das Layout hier bitte anpassen?
Ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
alles umgesetzt, kann zu
