### ISSUE TITLE
Karussell auf beg_10: sf ergänzen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#133]
In einem bereits geschlossenen Issue wurde festgestellt, dass auf Seite beg_10 wegen der Mehrfachnennung kein Karussell möglich ist.
Das ist auf mobilen Endgeräten sehr unglücklich, da die Gefahr besteht, dass alle Befragten nach dem ersten Item auf Weiter klicken und die übrigen 14 Items übersehen werden.
Habt ihr eine Idee, wie sich das lösen ließe? Oder müssten wir für alle 15 Items eine eigene Seite programmieren für Mobile Endgeräte (die dann jeweils über den "Weiter-Button" angesteuert werden)?

![grafik](https://user-images.githubusercontent.com/53002476/69941963-7bc79d80-14e4-11ea-943c-928e8c394374.png)

**Comment by SilinaKowalewski** [comment]
Das Karussell funktioniert hier schon. Nur eben kein autoforwarding. 

Wir könnten ein SF programmieren, der einen Hinweistext zeigt, sobald nur das erste Item beantwortet wurde aber alle anderen Missing sind...oder generell ein SF falls eines der Items nicht beantwortet wurde.

**Comment by woisch** [comment]
Dann bitte einen sf einbauen und folgenden Text einblenden, wenn Befragte mobiles Endgerät nutzen **und** nur das erste Item beantwortet wurde. (Durch erneutes Klicken des Weiter-Buttons soll man aber weiterkommen.)

Hinweis: Sie haben bisher nur eine von 15 Fragen zu Ihrem Umfeld beantwortet. Über die Pfeiltasten können Sie die weiteren Fragen ansteuern und gelangen anschließend durch den Weiter-Button zur nächsten Frage.

**Comment by woisch** [comment]
Seit dem letzten rollout crasht es nun bei verlassen der Seite beg_10, wenn ich das erste item leer lasse bzw. Nicht mindestens die ersten beiden Items bearbeite und dann auf weiter klicke
(Teste mobil)
________________________________
Von: SilinaKowalewski <notifications@github.com>
Gesendet: Montag, 2. Dezember 2019 09:26:10
An: dzhw/SLC-IntEr
Cc: Woisch, Andreas; Author
Betreff: Re: [dzhw/SLC-IntEr] Karussell auf beg_10 (#133)


Das Karussell funktioniert hier schon. Nur eben kein autoforwarding.

Wir k?nnten ein SF programmieren, der einen Hinweistext zeigt, sobald nur das erste Item beantwortet wurde aber alle anderen Missing sind...oder generell ein SF falls eines der Items nicht beantwortet wurde.

-

**Comment by SilinaKowalewski** [comment]
Ja, ist mir auch schon aufgefallen. Habe den Fehler evtl. schon gefunden und rolle gleich neu aus. 

Ansonsten schaue ich mir das Problem morgen noch mal an.

**Comment by woisch** [comment]
es crasht nicht mehr und ich kriege den sf-Text eingeblendet.

Allerdings auch, wenn ich auf dem nicht responsiven Format antworte! Das soll aber nur erscheinen, wenn auf dem kleinen Bildschirm (mit Karussell) ausgefüllt wird. Sonst macht der Hinweis mit den Pfeiltasten auch keinen Sinn..

**Comment by SilinaKowalewski** [comment]
Na klar..sorry. Habe vergessen die mobile-Bedingung mit einzubauen.

**Comment by SilinaKowalewski** [comment]
Habe die Bedingung hinzugefügt und jetzt passt es.

**Comment by woisch** [comment]
sieht gut aus.
