### ISSUE TITLE
Erwerbstätigkeit: Klammerfehler

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#134]
Es gibt in dem Modul noch nicht geschlossene Klammern:
( - 75359
) - 75329
Der Zahl nach zu urteilen hat es was mit Schleifen oder Splits zu tun (da glatte Zahl 30). 
Wir können danach suchen. Das würde ich aber lieber im Template machen.

**Comment by andreaschu** [comment]
ich habe mal jemanden drangesetzt. Wenn Du eine schnellere Lösung hast, immer her damit.

**Comment by christian-fr** [comment]
Für Notepad++ gibt es das Plugin [BracketsCheck](https://github.com/niccord/BracketsCheck/tree/master/BracketsCheck/bin/Release).

In folgenden Zeilen gibt es jeweils zwei fehlende Klammern (offenbar ein copy&paste-Fehler):

5400
6697
7963
9197
12299
13627
14924
16189
19322
20650
21946
25110
26437
29631

**Comment by se-lang** [comment]
@andreaschu Schau ich mir kurz an und korrigier die per Hand. Danke euch!

**Comment by se-lang** [comment]
Korrigiert.

**Comment by se-lang** [comment]
Verdammt, zwei fehlen ja noch...

**Comment by christian-fr** [comment]
Stimmt. Ich habe den Kommentar oben korrigiert, die Zeile 4072 fehlte noch.

**Comment by se-lang** [comment]
Top, danke dir! Ist korrigiert, jetzt stimmt die Zahl auch wieder überein.
