### ISSUE TITLE
scaX12

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#135]
Auf den 12er-Seiten im Schulmodul wird in der zweiten Einblendung offenbar noch "valueOf" statt "labelOf" genutzt. Könnt Ihr das bitte anpassen?

**Comment by SilinaKowalewski** [comment]
Ich bin mir unsicher ob ich genau verstehe was du meinst. Sehe aber auch das Problem. Allerdings wird im kompletten Modul lediglich "labelOf" für Einblendungen genutzt. 

Hast du spontan eine Idee woran der Fehler sonst liegen könnte? Wird das Label irgendwo anders überschrieben oder geändert?

**Comment by se-lang** [comment]
Das hab ich heute früh schon korrigiert, weil mir der Fehler selbst beim testen aufgefallen ist. Deswegen stimmt die QML aber der Rollout.

**Comment by SilinaKowalewski** [comment]
Ah! Dann sollte ja ab dem nächsten Roll-Out alles passen!

**Comment by SilinaKowalewski** [comment]
Kann nun getestet werden. Sieht aber auf den ersten Blick richtig aus.

**Comment by SilinaKowalewski** [comment]
Ist hier noch was zu tun oder kann das Issue zu?

**Comment by jocarstensen** [comment]
Der Fehler bestand noch. Habe die Ursache aber gefunden, gerade korrigiert und committed. Sollte ab dem nächsten Rollout funktionieren.

**Comment by jocarstensen** [comment]
scheint behoben zu sein
