### ISSUE TITLE
nsET & sET: Orte und AutoForward

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#137]
Ortsseiten gibt es viele in sET:
- seXX17/seXX25/seXX33/seXX41/seXX49
- sezz17
--> wobei XX steht für
- aa/ab/ac/ad/ae
- ba/bb/bc/bd
- ca/cb/cc
- da/db
- ea

AutoForward brauchen wir in den Batterien auf:

- [x] seaa61/seaa66
- [x] seba61/seba66
- [x] seca61/seca66
- [x] seda61/seda66
- [x] seea61/seea66
- [x] sezz61/sezz66

**Comment by andreaschu** [comment]
Wir benötigen für die Infield-Texte am besten eine comma-separierte Liste. Hier für die oben genannten Seiten im Selbständigen-Modul. Ich hoffe ich habe es richtig gemacht.

seaa17, seab17, seac17, sead17, seae17, 
seaa25, seab25, seac25, sead25, seae25, 
seaa33, seab33, seac33, sead33, seae33, 
seaa41, seab41, seac41, sead41, seae41, 
seaa49, seab49, seac49, sead49, seae49, 
seba17, sebb17, sebc17, sebd17, 
seba25, sebb25, sebc25, sebd25, 
seba33, sebb33, sebc33, sebd33, 
seba41, sebb41, sebc41, sebd41, 
seba49, sebb49, sebc49, sebd49, 
seca17, secb17, secc17, 
seca25, secb25, secc25, 
seca33, secb33, secc33, 
seca41, secb41, secc41, 
seca49, secb49, secc49, 
seda17, sedb17, 
seda25, sedb25, 
seda33, sedb33, 
seda41, sedb41, 
seda49, sedb49,
seea17, seea25, seea41, seea49, 
sezz17

**Comment by se-lang** [comment]
Ich häng mich bzgl. autoforward mal hier mit dran. In questionnaire17 bräuchten wir auch auf folgenden Seiten noch Autoforward:
- [ ] emaa43
- [ ] emba43
- [ ] emca43
- [ ] emda43
- [ ] emea43
- [ ] emfa43
- [ ] em0043

**Comment by jocarstensen** [comment]
@andreaschu Genau, die Liste ist für sET richtig so.

**Comment by se-lang** [comment]
@andreaschu braucht ihr das für alle Module?

**Comment by andreaschu** [comment]
@se-lang ja, aber wir haben gestern besprochen, dass wir (von zofar) das machen und alle Tester darauf achten sollen noch weitere Seiten zu finden.

**Comment by christian-fr** [comment]
@vdick Ich habe 151 pages mit _Ort_ oder _PLZ_ oder _Land_ gefunden:

em0016, emaa16, emab16, emac16, emad16, emae16, emaf16, emba16, embb16, embc16, embd16, embe16, emca16, emcb16, emcc16, emcd16, emda16, emdb16, emdc16, emea16, emeb16, emfa16, iaa06, iba06, ica06, ida06, iea06, msg_03, oaa07, oab07, oca05, scaa07, scab07, scac07, scad07, scae07, scaz07, seaa17, seaa25, seaa33, seaa41, seaa49, seab17, seab25, seab33, seab41, seab49, seac17, seac25, seac33, seac41, seac49, sead17, sead25, sead33, sead41, sead49, seae17, seae25, seae33, seae41, seae49, seba17, seba25, seba33, seba41, seba49, sebb17, sebb25, sebb33, sebb41, sebb49, sebc17, sebc25, sebc33, sebc41, sebc49, sebd17, sebd25, sebd33, sebd41, sebd49, seca17, seca25, seca33, seca41, seca49, secb17, secb25, secb33, secb41, secb49, secc17, secc25, secc33, secc41, secc49, seda17, seda25, seda33, seda41, seda49, sedb17, sedb25, sedb33, sedb41, sedb49, seea17, seea25, seea33, seea41, seea49, sezz17, st0011, staa10, stab10, stac10, stad10, stae10, stba10, stbb10, stbc10, stbd10, stca10, stcb10, stcc10, stda10, stdb10, stea10, vaa10, vab10, vac10, vad10, vae10, vaz10, vba10, vbb10, vbb21, vbc10, vbd10, vbz10, vca10, vcb10, vcc10, vcz10, vda10, vdb10, vdz10, vea10, vez10, vza10

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Wir haben zusätzlich noch Seiten gefunden für die Infield-Texte benötigt werden und dort die Funktion eingebaut: 


stab10
stac10
stad10
stba10
stbb10
stbc10
stbd10
stca10
stcb10
stcc10
stda10
stdb10
stea10

**Comment by SilinaKowalewski** [comment]
Einblendung von Infield-Texten macht auf der Seite msg_03 nicht so viel Sinn. Habe das hier bereits rausgenommen. Ist dann ab nächstem Roll-Out angepasst.

**Comment by christian-fr** [comment]
Auf der Seite vbb21 macht es auch keinen Sinn, es gibt gar kein Textfeld.

**Comment by SilinaKowalewski** [comment]
Ist hier noch was wichtiges zu tun? Issue trägt immer noch das Label "Hohe Priorität" sieht aber eigentlich soweit abgearbeitet aus.

**Comment by jocarstensen** [comment]
@se-lang gerade noch auf em0042 eine Batterie gefunden. Brauchen wir dort nicht auch Auto-Forward?

**Comment by se-lang** [comment]
@jocarstensen em0042 ist nur ein Item, deswegen braucht es da kein Autoforward. (Oder?)

**Comment by jocarstensen** [comment]
Stimmt. Aber dann sollte es auch nicht im Karussell angezeigt werden, oder? Die Pfeilbuttons verwirren dann ja nur...

**Comment by se-lang** [comment]
Stimmt, das war ursprünglich so gemacht, damit der Look der Seite einheitlich ist. Jetzt könnte man auf em0042 (und der anderen Seiten mit dieser Frage) eine normale SingeChoice draus machen.

**Comment by se-lang** [comment]
@jocarstensen nachdem wir für die Baterie auf em0042 etc einen eigenen Issue haben kann der hier eigentlich zu, oder?

**Comment by jocarstensen** [comment]
Meinetwegen schon.
