### ISSUE TITLE
bug: Übergang aus dem Calendarium stürzt ab

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#138]
Ich komme derzeit nicht aus dem Kalendarium raus, egal was ich angebe - HTTP Status 500 - Internal Server Error

**Comment by jocarstensen** [comment]
Japp, auf zwischen_k ist scheinbar ein Kommafehler.

**Comment by SilinaKowalewski** [comment]
Der Übergang funktioniert nun wieder.

**Comment by bafranke** [comment]
Danke!
