### ISSUE TITLE
Startseiten

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#139]
Die Startseiten können bei nächster Gelegenheit implementiert werden. Für jede Kohorte eine eigene mit jeweils auch anderem Datenschutzblatt als PDF verlinkt.
Auf beiden Startseiten folgendes Bild eingefügt werden über dem Text aber unter dem Header.
![present futurepast-459846 -neu](https://user-images.githubusercontent.com/53002476/70054778-76e41600-15d8-11ea-8e41-03ef68319ffa.jpg)

Hier die Dokumente für cohort 1:
[startseite_cohort1.zip](https://github.com/dzhw/SLC-IntEr/files/3917196/startseite_cohort1.zip)

Hier für cohort2:
[startseite_cohort2.zip](https://github.com/dzhw/SLC-IntEr/files/3917192/startseite_cohort2.zip)

**Comment by SilinaKowalewski** [comment]
@woisch: Können hier eigentlich die Eingabefelder für die HV raus?

**Comment by woisch** [comment]
@jocarstensen: was meinst du? Bei funktionierendem Kalendarium sollten wir die HVs nicht mehr brauchen..

**Comment by jocarstensen** [comment]
Ich würde sie morgen für den pretest rausnehmen. Bis dahin kann man da zum Testen gut noch manipulieren, sofern man sich nicht durchklicken will.

**Comment by woisch** [comment]
Jetzt hast du alle Dokumente.
habe eben nochmal die Dateien für cohort 1 neu eingestellt. Falls du die PDF schon verlinkt hast, bitte nochmal austauschen.

**Comment by SilinaKowalewski** [comment]
Habe die Startseiten nun für beide Versionen angelegt. Cohort 1 schon vor dem letzten Roll-Out. Diese kannst du dir also schon anschauen. 

Generell fehlt allerdings noch das Bild und die Kontaktdaten werden aktuell nicht eingeblendet. Sollte aber nach dem nächsten Roll-Out beides mit drin sein.

**Comment by woisch** [comment]
Bitte noch anpassen für cohort1:
Ansprechpartner(innen) fehlen

**Comment by jocarstensen** [comment]
Soweit ich sehe, sind die Ansprechpartner*innen jetzt da. @woisch  Kann zu?

**Comment by SilinaKowalewski** [comment]
Ansprechpartner*innen war nur für eine der beiden Cohorten sichtbar weil ich noch getestet habe ob es klappt. Im neuen Roll-Out sollten aber beide Cohorten ihre Ansprechpartner*innen sehen.

**Comment by woisch** [comment]
Ich prüfe das nach dem Rollout und mache dann zu

**Comment by woisch** [comment]
vor meiner Mailadresse ist noch eine geschweifte Klammer und alles ist etwas nach rechts eingerückt. Besser auf Höhe mit dem "Ihr Panel 2015-Team am DZHW " ausrichten.

![grafik](https://user-images.githubusercontent.com/53002476/70226595-673c0d00-1751-11ea-93c3-8e100d2d5f09.png)

**Comment by SilinaKowalewski** [comment]
Die Klammer habe ich raus genommen. Ob die Tabelle weiter nach rechts gesetzt werden kann, muss sich @vdick mal anschauen.

**Comment by woisch** [comment]
Nur zur Sicherheit: ich meinte nach links. Also die Namen auf Höhe des restlichen Textes ausrichten.

**Comment by woisch** [comment]
In der Mobilen Ansicht werden die drei Ansprechpartner als Karussell angezeigt. Grundsätzlich OK. allerdungs sind die beiden Pfeiltasten des Karussells nicht erkennbar als Pfeile sondern irgendwie transparent.

**Comment by woisch** [comment]
![grafik](https://user-images.githubusercontent.com/53002476/70228116-1974d400-1754-11ea-96ac-7d7bf30188aa.png)

getestet auf iPhone7 mit Safari

**Comment by SilinaKowalewski** [comment]
> Nur zur Sicherheit: ich meinte nach links. Also die Namen auf Höhe des restlichen Textes ausrichten.

Ups, ja! Meinte ich.

**Comment by woisch** [comment]
Bei cohort 2 ist das Datenschutzblatt nicht verlinkt!

**Comment by SilinaKowalewski** [comment]
@woisch: Danke für den Hinweis. Passe ich an! 

Habt ihr euch schon über die Darstellung der Kontaktdaten verständigt? In Form einer Tabelle ist die Darstellung recht Fehleranfällig. Aktuell sieht es sowohl auf Smartphones als auch in Chrome unschön aus. 

Würde vorschlagen die Kontaktdaten als Blöcke untereinander darzustellen oder einfach jeden Kontakt in einer Zeile.

**Comment by jocarstensen** [comment]
@SilinaKowalewski Ja, so hatte ich es jetzt auch mit Viktor besprochen. Wenn niemand widerspricht, machen wir es so.

**Comment by woisch** [comment]
Ja, gerne anpassen, finde es auf dem Smartphone auch noch nicht optimal.

**Comment by woisch** [comment]
@SilinaKowalewski Kriegst du die Breite des Bildes so hin, dass sie mit der Textbreite übereinstimmt?

**Comment by woisch** [comment]
Ansprechpartner-Liste sieht jetzt besser aus. Datenschutzblatt ist auch verlinkt.

Hast du noch ne Idee, wie man das Bild schöner hinkriegt?

**Comment by SilinaKowalewski** [comment]
@woisch: Was hättest du daran denn schöner? Es exakt an die Textlänge anzupassen ist nicht so einfach machbar. Dazu müssten wir Einstellungen ändern und schauen ob es in etwas passt.

**Comment by woisch** [comment]
@heikQ was meinste? so lassen? Du hattest das am Freitag angeregt mit dem Bild auf der Startseite..

**Comment by heikQ** [comment]
@woisch @SilinaKowalewski dann lassen wir es unschön so. Aber warum ist über dem bild so viel white space, kann das nicht näher an den Header?

**Comment by SilinaKowalewski** [comment]
@heikQ: Wir können es gerne in den Header einbauen. Dort würde es dann aber natürlich auf jeder Seite eingeblendet werden. 

Aktuell ist so viel WhiteSpace über dem Bild, da dort der Platz für die Navigationsleiste reserviert ist.

**Comment by heikQ** [comment]
kÖnnte man die Navigationsleiste auch in den header setzen?  da stört sie nicht 🥇

**Comment by woisch** [comment]
> 
> 
> kÖnnte man die Navigationsleiste auch in den header setzen? da stört sie nicht 🥇

Die Frage verschiebe ich ins entsprechende Issue #89

**Comment by SilinaKowalewski** [comment]
Das Bild ist nun in etwa so breit wie der Text, aber natürlich ziemlich groß. 

Kann dieses Issue dann geschlossen werden oder muss auf der Startseite noch mehr angepasst werden?

**Comment by woisch** [comment]
Folgende Änderungen noch, bitte alles für beide cohorten umsetzen:

- [ ] im ersten Satz das Wort "beruflicher" vor Werdegang streichen. (also: im Fokus unserer Befragung, die Teil einer wissenschaftlichen Längsschnittstudie ist, steht Ihr Werdegang in den vergangenen zwei Jahren sowie Ihre weiteren Pläne für die Zukunft.) 

- [ ] im Absatz Datenschutz: Ein komme hinter die Klammer nach "Herr Martin Fuchs". (Also: Für Fragen rund um den Datenschutz steht Ihnen außerdem auch der Datenschutzbeauftragte des DZHW, Herr Martin Fuchs (datenschutz@dzhw.eu, Tel.: 0511 450670-491), zur Verfügung.)
 

- [ ] den letzten Absatz (Sollten Sie noch Fragen haben, können Sie sich auch gerne per E-Mail (panel2015@dzhw.eu) oder telefonisch an uns wenden. Auf der Webseite finden Sie unter www.bildungswege.dzhw.eu/jahrgang-2015 weitere Informationen zum Projekt sowie Ergebnisse aus vorangegangenen Befragungen. ) vor die Überschrift "Hinweise zum Datenschutz" ziehen.

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und ausgerollt.

**Comment by woisch** [comment]
Danke!
Ist es möglich zwischen dem Datenschutzhäkchen und dem "Herzlichen Dank" noch den whitespace zu reduzieren?

**Comment by woisch** [comment]
Telefonnummer von Martin Fuchs noch anpassen, das Format soll so sein wie bei den Ansprechpartner(inne)n unten. Bitte im Text für cohort1 und 2 ändern. 

"Für Fragen rund um den Datenschutz steht Ihnen außerdem auch der Datenschutzbeauftragte des DZHW, Herr Martin Fuchs (datenschutz@dzhw.eu, Tel.: +49 (0)511 450670-491), zur Verfügung."

**Comment by woisch** [comment]
Danke, passt so!

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue dann geschlossen werden?

**Comment by woisch** [comment]
Ich finde bestimmt noch was ,-)
Mache aber mal zu hier.

**Comment by jocarstensen** [comment]
Bitte für beide Kohorten "Willkommen" in der ersten Zeile klein schreiben und eine Leerzeile nach der ersten Zeile einfügen.

Für 18.3a bitte noch die Gewinne kursiv formatieren.

**Comment by woisch** [comment]
Meinetwegen kann das Bild gerne raus. Viel zu groß, gerade aufm Mobile.

**Comment by woisch** [comment]
- [ ] Bitte das Bild auf der indexseite wieder ganz rausnehmen

- [ ] Den Fortschrittsbalken ebenfalls auf der indexseite rausnehmen, wenn möglich

**Comment by woisch** [comment]
@SilinaKowalewski 

- [ ] Bild auf der indexseite raus

- [ ] Fortschrittsbalken auf Indexseite ebenfalls deaktivieren

**Comment by andreaschu** [comment]
> - [x]  Bild auf der indexseite raus
> - [x]  Fortschrittsbalken auf Indexseite ebenfalls deaktivieren

nach nächstem Rollout (vorausstl. 17.00-17:45) testbar

**Comment by woisch** [comment]
Bild und Fortschrittsbalken sind raus. Dafür jetzt viel Whitespace an der Stelle zwischen text und Header. Falls es da noch ne Möglichkeit gibt das zu reduzieren, wäre das super.

**Comment by andreaschu** [comment]
ich fürchte, dass da nicht viel reduziert werden kann, weil das der Platz für den Fortschrittsbalken ist, oder @dzhwmeisner?

**Comment by jocarstensen** [comment]
>  Bitte für beide Kohorten "Willkommen" in der ersten Zeile klein schreiben und eine Leerzeile nach der ersten Zeile einfügen.
> 
> Für 18.3a bitte noch die Gewinne kursiv formatieren.

Passt, danke

**Comment by jocarstensen** [comment]
@andreaschu @dzhwmeisner Gibt es was zum Whitespace?

**Comment by dzhwmeisner** [comment]
Es gibt nichts Neues zum Whitespace

**Comment by woisch** [comment]
@jocarstensen: so lassen?

**Comment by woisch** [comment]
Der SF Text ist jetzt sehr nach an dem nächsten Satz dran. So lassen?

![grafik](https://user-images.githubusercontent.com/53002476/70909658-3cce3780-200e-11ea-9c08-112dbd39b0e1.png)

**Comment by andreaschu** [comment]
Wird für die produktive Befragung angepasst.

**Comment by woisch** [comment]
> 
> 
> Wird für die produktive Befragung angepasst.

Passt jetzt so, danke!

**Comment by woisch** [comment]
Leider fubktionieren in der Live-Version die Links zu den Datenschutzanschreiben nicht mehr!
