### ISSUE TITLE
Modul Ausbildung: udpate 2

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#14]
PV in Modul ausbildung überarbeitet (2 neue Seiten, tc und tr überarbeitet, Antwortoptionen in aus_01 und aus_04).

https://github.com/dzhw/SLC-IntEr/commit/739f39363bbc95d6fe2eec58ef485fd579a8629e

**Comment by andreaschu** [comment]
Änderungen wurden umgesetzt und können getestet werden.

**Comment by SilinaKowalewski** [comment]
@heikQ:
Kann dieses Issue geschlossen werden oder müssen noch Änderungen vorgenommen werden?

**Comment by SilinaKowalewski** [comment]
@heikQ:
Kann dieses Issue geschlossen werden oder müssen noch Änderungen vorgenommen werden? ;)
