### ISSUE TITLE
kleine Fehler in Episoden

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#140]
hier eine Sammlung kleinerer bugs, die noch behoben werden müssen:

- [x] emaa01: Leerzeichen zwischen 2. und 3. Satz in Anweisung fehlt

- [x] staa31: Rechtschreibfehler: deises = dieses (bitte auch in allen entsprechenden Seiten in den anderen Schleifen korrigieren!)

- [x] o0001: keiner weiteren Tätigkeit – führt zu Fehler, geht nicht weiter 
![grafik](https://user-images.githubusercontent.com/56022369/70054509-fe7d5500-15d7-11ea-8d8a-a516eff612a7.png)

- [x] seab06: Fehlerhinweis erscheint im Feld der ersten Frage, müsste aber im Feld der dritten Frage erscheinen (bei seaa06 richtig) 
![grafik](https://user-images.githubusercontent.com/56022369/70054563-1a80f680-15d8-11ea-92ea-820ed58939b8.png)

**Comment by SilinaKowalewski** [comment]
> * o0001: keiner weiteren Tätigkeit – führt zu Fehler, geht nicht weiter

Da wir für dieses Modul leider keine PV haben, kann ich nicht prüfen was hier eigentlich gewünscht ist. 

Die Programmierung sieht aktuell so aus: 
```
            <zofar:transition target="o0001" condition="    (     !o0001a.value     and      !o0001c.value     and      !o0001d.value     and      !o0001e.value     and     !o0001g.value   and  !o0001f.value   )    and     !sf_o0001.value    "/>
            <zofar:transition target="oaa01" condition="o0001a.value"/>
            <zofar:transition target="oca01" condition="!o0001a.value and o0001c.value"/>
            <zofar:transition target="oda01" condition="!o0001a.value and !o0001c.value and o0001d.value"/>
            <zofar:transition target="oea01" condition="!o0001a.value and !o0001c.value and !o0001d.value and o0001e.value"/>
            <zofar:transition target="zwischen_o" condition="!o0001a.value and !o0001c.value and !o0001d.value and !o0001e.value and o0001g.value"/>
            <zofar:transition target="zwischen_o" condition="!o0001a.value and !o0001c.value and !o0001d.value and !o0001e.value and !o0001g.value and sf_o0001.value"/>
```

Es gibt also bisher lediglich eine Bedingung (target="o0001") die sich darauf bezieht, dass o0001f nicht ausgewählt wurde. Kann aber nicht entscheiden was hier richtig wäre. Das muss sich vermutlich @jocarstensen mal ansehen.

**Comment by jocarstensen** [comment]
Habe es hoffentlich gefixed. Müsste nach dem nächsten Rollout funktionieren.

**Comment by jocarstensen** [comment]
> seab06: Fehlerhinweis erscheint im Feld der ersten Frage, müsste aber im Feld der dritten Frage erscheinen (bei seaa06 richtig)

@SilinaKowalewski Kannst Du das im qml5 ändern? Dann passe ich es in den Templates an.
(Das betrifft vermutlich die Seiten seab06/seac06/sead06/seae06/sebb06/sebc06/sebd06/secb06/secc06/sedb06)

**Comment by SilinaKowalewski** [comment]
Für die Seiten seab06/seac06/sead06/seae06/sebb06/sebc06/sebd06/secb06/secc06/sedb06 umgesetzt und comitted.

**Comment by bafranke** [comment]
seab06 getestet: ohne Angabe erscheint gar kein Fehlertext, ich komme aber auch nicht mehr weiter.

**Comment by jocarstensen** [comment]
Auf seac, sead und seae getestet, dort buggt der SF auch. Manchmal bekomme ich den Text eingeblendet, wenn gar nichts ausgewählt wird, aber nicht wenn alles außer seXX08 ausgefüllt wird. Manchmal aber auch gar nicht.

**Comment by jocarstensen** [comment]
@SilinaKowalewski Im neuen Rollout bleibe ich auf sead06 hängen, wenn ich sead06 nicht ausfülle, bekomme aber keine Fehlermeldung.

**Comment by jocarstensen** [comment]
das gilt vermutlich auch für die entsprechenden Seiten in anderen Splits

**Comment by jocarstensen** [comment]
Ach so, das dürfte im aktuellen Rollout noch gar nicht gefixed sein, richtig?

**Comment by SilinaKowalewski** [comment]
Ganz genau ;-) Das wollte ich dir gerade schreiben. Ist dann im nächsten mit drin.

**Comment by jocarstensen** [comment]
Ok, ich gedulde mich. Gibt auch so noch genug zu tun. :-)

**Comment by jocarstensen** [comment]
@SilinaKowalewski Kann es sein, dass der Fehler auf scaa06 (und damit vermutlich auch auf seba, seca, seda und seea) nicht behoben ist, aber auf den anderen Seiten?

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Ja, habe mich einfach an diese Liste gehalten: seab06/seac06/sead06/seae06/sebb06/sebc06/sebd06/secb06/secc06/sedb06 

Passe das aber gerne noch bei den anderen an

**Comment by SilinaKowalewski** [comment]
Habe alle weiteren Fragen angepasst. Hoffe, dass es jetzt funktioniert.

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Muss hier noch etwas gemacht werden oder passt alles?

**Comment by jocarstensen** [comment]
Passt
