### ISSUE TITLE
Infield-Einblendungen Doppelpunkte

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#141]
Nur, wenn es gar nichts anderes zu tun gibt:

In allen Infield-Einblendungen stehen jetzt noch die ursprünglichen Präfixe mit Doppelpunkt ("Ort:", "PLZ:"). Bei der Einblendung kann man die Doppelpunkte aber auch besser weglassen.

**Comment by SilinaKowalewski** [comment]
Für sET umgesetzt und comitted.

**Comment by jocarstensen** [comment]
Sieht gut aus. Wenn mal Leerlauf sein sollte, kann das auch für die anderen Module umgesetzt werden. Ist aber die am wenigsten wichtige Aufgabe von allen.

**Comment by SilinaKowalewski** [comment]
Für nSET und Ausbildung umgesetzt und comitted

**Comment by SilinaKowalewski** [comment]
Sollte nun überall umgesetzt sein. Ist nach dem nächsten Roll-Out verfügbar.

**Comment by jocarstensen** [comment]
Ich mach das mal zu. Das testen wir nebenbei.
