### ISSUE TITLE
Update Modul Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#143]
- [x] stu_08: Hier soll der Wertebereich auf 0,0 bis 4,0 begrenzt sein (so steht es auch in der kh). Umgesetzt ist aber scheinbar 1,0 bis 4,0.
- [x] mas_09: av2 und av3 geändert (0 als gültigen Wert zulassen, bei av1 und av4 aber weiterhin nicht)

https://github.com/dzhw/SLC-IntEr/commit/1df78ec3a601d5bc933c1dc64d8d184447127181

**Comment by SilinaKowalewski** [comment]
> * stu_08: Hier soll der Wertebereich auf 0,0 bis 4,0 begrenzt sein (so steht es auch in der kh). Umgesetzt ist aber scheinbar 1,0 bis 4,0.

Hier geben wir aktiv keinen Wertebereich vor, sondern lediglich den Datentyp "grade" damit die Eingabe von Kommata möglich ist. 
@vdick: Lässt sich hier dran was ändern?

**Comment by woisch** [comment]
Falls es hilft: 
im Episodenmodul Studium wird es genauso wie von mir beschrieben eingesetzt. zum Beispiel auf staa25

**Comment by woisch** [comment]
stu_80:
Ist es (ohne großen Programmieraufwand) möglich, dass sobald ein Wert ins Textfeld eingetragen wird, automatisch das "ja" angekreuzt wird.
Wenn nicht, müsste ich nochmal die Transition anpassen und diesen Fall ausformulieren..

**Comment by SilinaKowalewski** [comment]
> Falls es hilft:
> im Episodenmodul Studium wird es genauso wie von mir beschrieben eingesetzt. zum Beispiel auf staa25

Eigentlich waren beide Fragen gleich programmiert. Habe aber die Anweisungen mal exakt kopiert. Dann können wir schauen ob es danach funktioniert.

**Comment by SilinaKowalewski** [comment]
> stu_80:
> Ist es (ohne großen Programmieraufwand) möglich, dass sobald ein Wert ins Textfeld eingetragen wird, automatisch das "ja" angekreuzt wird.
> Wenn nicht, müsste ich nochmal die Transition anpassen und diesen Fall ausformulieren..

Also bei mir passiert das schon automatisch.

**Comment by woisch** [comment]
Beweis:
![grafik](https://user-images.githubusercontent.com/53002476/70072167-c0dbf480-15f6-11ea-988c-875785d61bc0.png)

**Comment by SilinaKowalewski** [comment]
das ist komisch. bei mir geht diese Kombination nicht. 

Kannst du das mal an einer ähnlichen Frage testen?

**Comment by woisch** [comment]
![grafik](https://user-images.githubusercontent.com/53002476/70072922-38f6ea00-15f8-11ea-9678-ca4a25c02543.png)

**Comment by woisch** [comment]
ok, nach einmal cache leeren, geht es wieder.

**Comment by jocarstensen** [comment]
Der erste Punkt ist noch offen. Scheinbar hat @SilinaKowalewski da was umgesetzt.
@woisch Kannst Du mal testen, ob es funktioniert?

**Comment by woisch** [comment]
der erste Punkt ich nach wie vor nicht umgesetzt:
![grafik](https://user-images.githubusercontent.com/53002476/70213762-75326380-173a-11ea-88e2-cc36f1d5a73a.png)

**Comment by jocarstensen** [comment]
@SilinaKowalewski Kannst Du nochmal gucken, ob Dir dazu eine Lösung einfällt?

**Comment by SilinaKowalewski** [comment]
@vdick: Lass und bei Gelegenheit noch mal über dieses Problem sprechen. Mir fällt keine Lösung ein.

**Comment by SilinaKowalewski** [comment]
Die Eingabe auf stu_08 klappt nun auch :)

**Comment by woisch** [comment]
Okay. Danke!
