### ISSUE TITLE
Infield-Einblendungen in Episoden

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#144]
Wir hatten gestern besprochen, dass die Infield-Einblendungen systematisch für alle Fragen nach Ort, PLZ und Land umgesetzt werden sollen.
Inzwischen wurden diese aber auch für andere Fragen umgesetzt, zum Beispiel auf staa04:
![grafik](https://user-images.githubusercontent.com/53002476/70071437-afdeb380-15f5-11ea-9ff5-0a8d159312f9.png)

Bei allen Fragen mit Prefix macht die Infield Bedingung nicht wirklich Sinn (sehe Bild) und sollte wieder rückgängig gemacht werden!

**Comment by woisch** [comment]
auch rausnehmen in :
stu_92
mas_09
msg_09

**Comment by SilinaKowalewski** [comment]
@woisch: Du brauchst die Seiten nicht weiter raus zu suchen. Das scheint eine Fehler in der globalen Einstellung zu sein. Explizit eingebunden ist es nur für folgende Seiten:  

em0016, emaa16, emab16, emac16, emad16, emae16, emaf16, emba16, embb16, embc16, embd16, embe16, emca16, emcb16, emcc16, emcd16, emda16, emdb16, emdc16, emea16, emeb16, emfa16, iaa06, iba06, ica06, ida06, iea06, msg_03, oaa07, oab07, oca05, scaa07, scab07, scac07, scad07, scae07, scaz07, seaa17, seaa25, seaa33, seaa41, seaa49, seab17, seab25, seab33, seab41, seab49, seac17, seac25, seac33, seac41, seac49, sead17, sead25, sead33, sead41, sead49, seae17, seae25, seae33, seae41, seae49, seba17, seba25, seba33, seba41, seba49, sebb17, sebb25, sebb33, sebb41, sebb49, sebc17, sebc25, sebc33, sebc41, sebc49, sebd17, sebd25, sebd33, sebd41, sebd49, seca17, seca25, seca33, seca41, seca49, secb17, secb25, secb33, secb41, secb49, secc17, secc25, secc33, secc41, secc49, seda17, seda25, seda33, seda41, seda49, sedb17, sedb25, sedb33, sedb41, sedb49, seea17, seea25, seea33, seea41, seea49, sezz17, st0011, staa10, stab10, stac10, stad10, stae10, stba10, stbb10, stbc10, stbd10, stca10, stcb10, stcc10, stda10, stdb10, stea10, vaa10, vab10, vac10, vad10, vae10, vaz10, vba10, vbb10, vbb21, vbc10, vbd10, vbz10, vca10, vcb10, vcc10, vcz10, vda10, vdb10, vdz10, vea10, vez10, vza10

**Comment by SilinaKowalewski** [comment]
@woisch: Kannst du das hier auch mal mit geleertem Cache checken? Ich sehe da auch keine Infield-Texte

**Comment by woisch** [comment]
> 
> 
> @woisch: Kannst du das hier auch mal mit geleertem Cache checken? Ich sehe da auch keine Infield-Texte

ist jetzt wieder weg nach dem cache leeren Leeren bei:
stu_92
mas_09
msg_09

**Comment by woisch** [comment]
ebenso auf dem Beispiel oben (staa04).

**Comment by woisch** [comment]
dann kann das hier eigentlich wieder zu.

**Comment by SilinaKowalewski** [comment]
Super! Wie gesagt, wir haben das nur für die oben genannten Seiten eingebaut. Sollten die Infield-Texte an anderen Stellen auftauchen wäre es ein globaleres Problem.

**Comment by woisch** [comment]
wobei es jetzt auf den o.g. Seiten auch weg ist, zB em0016
Ich lasse mal bis morgen offen

**Comment by SilinaKowalewski** [comment]
auf den o.g. Seiten ist es zwar eingebaut aber noch nicht ausgerollt. Habe dazu #137. Sollten das hier also tatsächlich schließen.

**Comment by woisch** [comment]
auf emaa16 ist es da.
muss nochmal systematisch geprüft werden.

**Comment by woisch** [comment]
okay
