### ISSUE TITLE
Probleme Episoden: Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#145]
- [x] staa24: Einblendbedingungen Abschlussart bei Lehramtsabschlüssen für cohort1 fehlerhaft. Es wird eine Zahl statt der Schulart angezeigt (zB "Bachelor für ein Lehramt an 6" statt "beruflichen Schulen")

**Comment by se-lang** [comment]
Bei mir wird ganz normal das Label angezeigt. Bitte morgen nochmal checken, ob der Fehler noch reproduzierbar ist.

**Comment by woisch** [comment]
@bafranke:
Kannst du das auch mal checken, ob die Einblendbedingung bei dir normal funktioniert?

**Comment by bafranke** [comment]
Anna hatte das Problem vorgestern auch, bei mir tritt es heute noch auf:
![grafik](https://user-images.githubusercontent.com/56022369/70119033-af800000-1669-11ea-849e-f7922de2f708.png)

**Comment by woisch** [comment]
@se-lang: Das Problem besteht scheinbar auch bei anderen. Habs auch hier nochmal am Desktop getestet (sowie am Iphone). Ich kriege immer nur die Zahlen angezeigt bei den Lehramtsoptionen.

**Comment by se-lang** [comment]
Wie heute Nachmittag schon kurz besprochen, hatte @woisch flasch verstanden, der Screenshot von @bafranke hat dann die Erleuchtung gebracht. Hab den Fehler gefunden und behoben, sollte nach dem nächsten Rollout dann passen.

**Comment by woisch** [comment]
@se-lang: Kriege jetzt die korrekten Einblendungen beim Lehramt.

**Comment by woisch** [comment]
Ich lass hier noch mal offen. Muss noch eine andere Sache testen im epimodul Studium und würde das dann hier ggf dranhängen ans Issue

**Comment by se-lang** [comment]
@woisch Bei mir funkktioniert dein anderes Szenario inzwischen fehlerfrei (Issue ist glaube ich schon zu). Aber gerne nochmal testen

**Comment by jocarstensen** [comment]
@woisch Hast Du die ominöse andere Sache getestet?

**Comment by woisch** [comment]
achso. das ist das gleiche wie im anderen Issue!  ;-) iich mach zu
