### ISSUE TITLE
Crashende Module/Seiten

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#146]
Bisher: gsh, beg, stu, aus, msg

**Comment by bafranke** [comment]
gilt auch für gsh_*, stu_*, aus_*, msg_*

**Comment by jocarstensen** [comment]
Nach bisheriger Erkenntnis crashen also gsh, beg, stu, aus, msg. Ich mache die anderen Issues mal zu.

**Comment by jocarstensen** [comment]
Vielleicht als Hinweis: Die Episodenmodule scheinen nicht zu crashen. Die Zwischenseiten aber schon.

**Comment by jocarstensen** [comment]
Auf dem externen Server scheint es aktuell wieder zu laufen!

**Comment by dzhwmeisner** [comment]
Wir haben das Problem im Blick. Auf dem Server haben wir es provisorisch gelöst, rollen aber gerade auch nochmal neu aus.

**Comment by jocarstensen** [comment]
Das Problem scheint ja aktuell behoben zu sein, also mache ich hier zu.
