### ISSUE TITLE
Scrolling auf mobilen Endgeräten

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#147]
Sehr viel Whitespace auf einigen Seiten (ab emaa33 bis Schluss). Ist das noch ein Effekt der Header und wird noch behoben?

![Screenshot_20191203-163055_Samsung Internet](https://user-images.githubusercontent.com/35771616/70122351-c544f380-1670-11ea-932f-a9b8eb58416c.jpg)
![Screenshot_20191203-163245_Samsung Internet](https://user-images.githubusercontent.com/35771616/70122358-caa23e00-1670-11ea-9734-f20c950f0e38.jpg)

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Bitte prüfe doch noch mal, ob die Seiten immer noch so aussehen. Es ist starkt davon auszugehen, dass dieses Problem am Header lag. Bei mir sieht jetzt auch alles gut aus.

**Comment by jocarstensen** [comment]
Das Problem scheint aktuell nicht mehr zu bestehen.
