### ISSUE TITLE
Carousel: 'weiter'/'zurück'-Button werden nicht angezeigt

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#15]
#12
> Alle Seiten des Moduls, auch Karussell: für Iphone 5/SE & Galaxy S5 werden auf keiner Seite die vor uns zurück Buttons mit auf der Seite angezeigt, sondern sind nur durch scrollen nach unten sichtbar, obwohl noch Platz auf der Seite wäre. Wäre es möglich dasso darzustellen, dass die vor und zurück buttons ohne scrollen sichtbar sind?

**Comment by SilinaKowalewski** [comment]
Ich kann diese Problem lediglich auf der Seite gsh_02 finden. Wenn die Frage in ein Karusell umbricht sind tatsächlich die Button nicht erkennbar, ohne dass man scrollen muss. 

Das liegt hier unter anderem an dem recht langen Introduction-Text. 

@vdick wird aber versuchen die Button etwas weiter nach oben zu rücken. 
Da allerdings im oberen Bereich der Seite vorläufig die Navigationsleiste geplant ist, wird sich dieses Problem vermutlich eher nicht lösen lassen. 

![image](https://user-images.githubusercontent.com/48087320/68377962-94de6800-014b-11ea-9f28-32700a47c528.png)

**Comment by vdick** [comment]
fixed

**Comment by vdick** [comment]
@SilinaKowalewski  ich habe die Seite noch einmal etwas optimiert.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
@heikQ Kannst Du testen, ob das Problem behoben ist? Stammte von Dir aus Issue #12

**Comment by heikQ** [comment]
Problem besteht weiterhin, ist vor allem ungüsntig, wenn die letzte Seite des Karrussels erreicht ist und der einzig (sichtbare) Weiterbutton (der vom Karussell) ist und der wieder auf das erste Item vom Karrussel führt
![grafik](https://user-images.githubusercontent.com/52539440/69622366-18032780-1041-11ea-97bd-bfb0ca0754a2.png)

**Comment by SilinaKowalewski** [comment]
@heikQ: Dadurch das oben auf der Seite nun die Navigation bzw. das "Menü-Ding" eingeblendet wird, wird sich daran allerdings nicht mehr ändern lassen. Die Seite bietet einfach kein Potential um Platz einzusparen.

**Comment by heikQ** [comment]
okay, dann machen wir hier die Tür zu, wenn sich das nicht ändern lässt?

**Comment by SilinaKowalewski** [comment]
Ja, halte ich für sinnvoll. Sollten wir irgendwann noch Langeweile haben können wir uns dieses Issue nochmal vornehmen.
