### ISSUE TITLE
Zeilenumbrüche beg_07

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#150]
Hier stimmt was mit den Zeilenumbrüchen in den Items nicht:

![grafik](https://user-images.githubusercontent.com/35771616/70123456-03431700-1673-11ea-9168-e855ccaefda5.png)

**Comment by woisch** [comment]
Das selbe Problem besteht auf beg_06 (Stand gestern). Ist die selbe Frage mit mehr/anderen Items für cohort1

**Comment by bafranke** [comment]
biete noch eine weitere Variante bei beg_10 (items 5 und 12)
![grafik](https://user-images.githubusercontent.com/56022369/70139268-62645400-1692-11ea-9538-8419e25ed2f1.png)

**Comment by vdick** [comment]
**layout** fixed, ab nächsten Rollout verfügbar

**Comment by bafranke** [comment]
beg_06 passt jetzt. 
beg_07 und beg_10 sind immernoch fehlerhaft. Beide sollten rechtsbündig ausgerichtet sein, auch in den folgenden Zeilen. 

![grafik](https://user-images.githubusercontent.com/56022369/70233227-6bbaf280-175e-11ea-9565-1d096912f364.png)
![grafik](https://user-images.githubusercontent.com/56022369/70233242-72e20080-175e-11ea-9e37-fa2f0735773c.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
beg_10 ist jetzt rechtsbündig
beg_07 sieht auch ok aus!

**Comment by woisch** [comment]
Kann zu
