### ISSUE TITLE
Episoden: nsET und sET Matrix mit einem Item zu normaler SingleChoice

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#153]
Auf folgenden Seiten müsste die matrixQuestionSingleChoice in eine questionSingleChoice überführt werden, da sie ohnehin nur 1 Item enthält:
- nsET
    - [x] emaa42
    - [x] emba42
    - [x] emca42
    - [x] emda42
    - [x] emea42
    - [x] emfa42
    - [x] em0042
- sET
    - [x] seaa65
    - [x] seba65
    - [x] seca65
    - [x] seda65
    - [x] seea65
    - [x] sezz65

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Könnten geprüft werden.

**Comment by jocarstensen** [comment]
Für sET ist es gut so.

**Comment by se-lang** [comment]
nsET ebenfalls
