### ISSUE TITLE
Epimodul Studium: Frageformulierungen bei Beginn vor Enterdatum

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#154]
Ich habe auch noch eine Anmerkung aus den Pretests, die wir diskutieren könnten (ebenfalls auf niedriger Prio).

Bei Studienbeginn vor Januar 2018 (cohort1) passen die meisten Frageformulierungen gut bzw. sind zumindest mit unserem Hinweistext auf staa01 verständlich (Wir interessieren uns auch für Tätigkeiten, die vor Januar 2018 begonnen haben und zu dem Zeitpunkt noch andauerten. Unsere Nachfragen beziehen sich in diesem Fall aber nur auf den Zeitraum seit Januar 2018.).

auf staa10 dann aber: An welcher Hochschule haben Sie sich im Januar 2018 immatrikuliert?

Für die Befragten mit früherem Beginn macht das so natürlich nicht wirklich Sinn. Könnt ihr euch ja auch nochmal anschauen. Es ist tasächlich nur diese eine Frage die etwas rausfällt, alle anderen Fragen scheinen mir verständlich für "Beginn-vor-Leute".

**Comment by se-lang** [comment]
Stimmt, klingt für die Leute ein bisschen komisch. Man könnte stattdessen fragen:
"An welcher Hochschule waren Sie ab Januar 2018 immatrikuliert?"

**Comment by woisch** [comment]
Das wäre aus meiner Sicht die passendere Formulierung, auch im Zusammenhang mit den übrigen Fragen. Wir variieren in den anderen Fragen davor und danach auch immer ein wenig. Mal heißt es "im Januar 2018" mal "ab Januar 2018".
Demnach wäre neben deinem Vorschlag auch denkbar: "An welcher Hochschule waren Sie _im_ Januar 2018 immatrikuliert?"
Könnte aber mit beidem Leben.

**Comment by se-lang** [comment]
Geändert.

**Comment by woisch** [comment]
Cool, Danke!
