### ISSUE TITLE
Modul Studium_ Instrument Lehr-Lernumwelt gekürzt

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#155]
- [x] stu_25: Variablen, Items und bedingte Itemanzeige geändert

- [x] stu_26: Variablen, Items und bedingte Itemanzeige geändert

- [x] stu_27: Variablen, Items und bedingte Itemanzeige geändert

- [x] stu_28: Variablen und Items gelöscht

- [x] stu_29: Variablen und Items gelöscht

Siehe:
https://github.com/dzhw/SLC-IntEr/commit/2d5d0d14f1b76e16402cd4d1184b970fc8393251

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und bereits ausgerollt. Können also getestet werden.

**Comment by jocarstensen** [comment]
@heikQ  bitte testen
