### ISSUE TITLE
Layout: Probleme bei mobilen Endgeräten (nicht Episodenmodule) Vol. II

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#156]
Offene Layout-Probleme aus #113 
- [x] Stu_45: kann das "Monate" hinter dem Textfeld oder zu Beginn einer neuen Zeile stehen? sieht im Moment unter dem Textfeld merkwürdig aus
  
![grafik](https://user-images.githubusercontent.com/56022369/70215482-dc9de280-173d-11ea-826e-3ad7ac9ee1dd.png)

- [x] Auf beg_03 und beg_04 scheint das Freitextfeld nicht auf die Bildschirmbreite zu reagieren (Galaxy S7, Android 8.0, Firefox 68.x)
![grafik](https://user-images.githubusercontent.com/56022369/70215514-eaebfe80-173d-11ea-9c0b-41a76d6a423d.png)

- [x] msg_08: Textfeld zum Eintragen der Kinderzahl ist zu klein, die eingetragene Zahl ist kaum sichtbar

![grafik](https://user-images.githubusercontent.com/53002476/70215843-a745c480-173e-11ea-925e-025fb688d334.png)

**Comment by bafranke** [comment]
> Auf beg_03 und beg_04 scheint das Freitextfeld nicht auf die Bildschirmbreite zu reagieren (Galaxy S7, Android 8.0, Firefox 68.x)
funktioniert bei mir inzwischen (iphone), @se-lang kannst du bei Gelegenheit noch mal testen?

die übrigen Punkte sind auch nach dem aktuellen Rollout noch nicht behoben

**Comment by vdick** [comment]
msg_08 habe ich noch einmal optimiert; bei allen anderen Punkten habe ich keine "Probleme" feststellen können (gerade alles auf dem Server getestet). Bitte leert den Cache des Browsers vor jedem Testen.
msg_08 ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
msg_08: Textfeld ist jetzt breiter, dafür ist das Kind(er) wieder nach unten gerutscht bei mir (iPhone7). sowohl im Hochformat als auch im LAndscape-Mode:
![grafik](https://user-images.githubusercontent.com/53002476/70233205-61005d80-175e-11ea-9c2c-4e2c998f0d39.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
@bafranke @woisch @heikQ bitte testen

**Comment by bafranke** [comment]
Stu_45 und msg_08 passt jetzt auch im landscape! Danke für die Umsetzung, kann aus meiner Sicht geschlossen werden!

Mithilfe von OWA für iPhone gesendet
________________________________
Von: jocarstensen <notifications@github.com>
Gesendet: Donnerstag, 5. Dezember 2019 14:19:17
An: dzhw/SLC-IntEr
Cc: Franke, Barbara; Mention
Betreff: Re: [dzhw/SLC-IntEr] Layout: Probleme bei mobilen Endgeräten (nicht Episodenmodule) Vol. II (#156)


@bafranke<https://github.com/bafranke> @woisch<https://github.com/woisch> @heikQ<https://github.com/heikQ> bitte testen

-

**Comment by woisch** [comment]
Stu_45 und msg_08 passen jetzt auch bei mir
