### ISSUE TITLE
Probleme Episoden Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#157]
Im Studienmodul gibt es in folgendem Szenario ein Problem (habe nochmal chaceh geleert und frischen Tester verwendet):

Studienbeginn: vor Januar 2018, Angaben staa33:
![grafik](https://user-images.githubusercontent.com/53002476/70216412-c42ec780-173f-11ea-99a8-d73c0d485852.png)

Angaben staa34:
![grafik](https://user-images.githubusercontent.com/53002476/70216503-efb1b200-173f-11ea-99a7-2d8bd523cf94.png)

jetzt komme ich auf stab21:
![grafik](https://user-images.githubusercontent.com/53002476/70216567-0eb04400-1740-11ea-9aa9-3629d433bab4.png)

danach folgt stab23 und beim Verlassen der stab23 crasht es.

Wenn ich das selbe Szenario durchspiele und lediglich bei staa33 das zweite Datum ändere, komme ich auf stab07 (wie es sein sollte) und danach auf stab21 und stab23 und komme dann auch weiter:
![grafik](https://user-images.githubusercontent.com/53002476/70216841-a4e46a00-1740-11ea-89d0-e508a583bea5.png)

**Comment by se-lang** [comment]
@woisch Fehler gefunden und hoffentlich behoben.

**Comment by jocarstensen** [comment]
@woisch Kannst Du schnell testen bzw. bestätigen, ob es behoben ist?

**Comment by woisch** [comment]
Sorry, hatte ich vorhin nur mündlich gemacht. Das Szenario lässt sich jetzt wieder durchklicken!
