### ISSUE TITLE
Episoden: Arbeitslosigkeit - weitere Episode in Dez 2019

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#158]
Man wird auch bei Enddatum Dez 2019 bzw. dauert noch an nach einer weiteren Arbeitslosigkeitsperiode ab Dezember 2019 gefragt. Theoretisch sind solche Konstrukte zwar möglich wo eine Beschäftigung im Dezember aufgenommen und direkt wieder beendet wurde, das könnte aber irritieren.

**Comment by jocarstensen** [comment]
Habe ich geändert. Sollte ab dem nächsten Rollout nur noch gefragt werden, wenn Enddatum<h_exitdatum

**Comment by woisch** [comment]
Funktioniert. Werde nur noch gefragt wenn Enddatum vor Dezember 2019
