### ISSUE TITLE
gsh01: Layout

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#16]
#12 

> gsh01 in der responsivem mobile Darstellung (responsive allgemein, Galaxy, iphone etc.) wird die Skala nicht ganz im Bild dargestellt, sondern istabgeschnitten. Vermutlich müsste hier die Karussell-Darstellung greifen, auch wenn Einzelitem.

**Comment by SilinaKowalewski** [comment]
Die Antwortoptionen könnten im responsiven Format auch einfach vertikal eingeblendet werden, oder @heikQ?

**Comment by heikQ** [comment]
@SilinaKowalewski ja, das ginge

**Comment by woisch** [comment]
Ist inzwischen schon mit vertikalen ao umgesetzt. 
@heikQ Kann zu hier oder?
