### ISSUE TITLE
Autoforwards Sammelthread

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#161]
Noch nicht implementiert auf:
(Bitte ergänzen)

- [x] iaa18/iba18/ica18/ida18/iea18

- [x] mas_7a

**Comment by SilinaKowalewski** [comment]
> * i**18

brauche hier eine richtige Liste der Seiten. So kann ich das leider nicht einbauen.

**Comment by jocarstensen** [comment]
oben ergänzt

**Comment by SilinaKowalewski** [comment]
Seiten zur Autoforward-Liste hinzugefügt.

**Comment by woisch** [comment]
mas_7a passt

**Comment by woisch** [comment]
iaa18/iba18/ica18/ida18/iea18 auch

Lasse hier erstmal noch offen, falls noch was nachkommt

**Comment by woisch** [comment]
Auf stu_11 noch Autoforward aktivieren

**Comment by SilinaKowalewski** [comment]
Eingebaut. Ab nächstem Roll-Out verfügbar.

**Comment by woisch** [comment]
klappt jetzt auf stu_11

**Comment by woisch** [comment]
mache hier jetzt zu
