### ISSUE TITLE
Endseite

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#162]
Wir müssen auf der Endseite noch den Link zur AddOn einbauen. in 18.2 haben wir folgenden Text verwendet:

**Hat sich Ihre Anschrift seit der letzten Befragung geändert?**

Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung (in ca. 2 Jahren) erreichen und im Falle eines Gewinns informieren können.
Ihre Kontaktadresse wird streng vertraulich behandelt und nicht mit den Befragungsdaten verknüpft.

**Klicken Sie hier, um Ihre aktuelle Adresse anzugeben.**

Was wir noch klären müssten, bevor ich das Issue erstelle:
1) Das ist der selbe Text, der auch im AddOn umgesetzt ist. Findet ihr die Redundanz schlimm?  Die Infos sind aus meiner Sicht schon auf der Endseite wichtig, um die Leute zur Adressangabe zu motivieren und den Zweck der Erhebung der Adressdaten zu erläutern. Oder wir nehmen den Text in der AddOn raus, finde ich aber auch nicht so schön, die Adressen zu erfragen, ohne nochmal auf den Zweck hinzuweisen. (Meine Präferenz wäre: es einfach zweimal zu schreiben)
2) Wie gehen wir mit der Ankündigung der nächsten Befragung hier um? in der AddOn haben wir ja unterscheidliche Zeitpunkte genannt (15.4=2 jahre, 18.3a=1 Jahr). Hier per Einblendung je Kohorte lösen? oder die Info weglassen? (Wenn das per Einblendung machbar ist, würde ich das präferieren)

**Comment by SilinaKowalewski** [comment]
> (Wenn das per Einblendung machbar ist, würde ich das präferieren)

Ist es :)

**Comment by heikQ** [comment]
?Hi,

ich finde die Redundanz nicht schlimm. Was soll man auch sonst schreiben?

Können das von mir aus gern so nehmen.

LG

Heiko

________________________________
Von: woisch <notifications@github.com>
Gesendet: Donnerstag, 5. Dezember 2019 14:55
An: dzhw/SLC-IntEr
Cc: Subscribed
Betreff: [dzhw/SLC-IntEr] Endseite (#162)


Wir müssen auf der Endseite noch den Link zur AddOn einbauen. in 18.2 haben wir folgenden Text verwendet:

Hat sich Ihre Anschrift seit der letzten Befragung geändert?

Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung (in ca. 2 Jahren) erreichen und im Falle eines Gewinns informieren können.
Ihre Kontaktadresse wird streng vertraulich behandelt und nicht mit den Befragungsdaten verknüpft.

Klicken Sie hier, um Ihre aktuelle Adresse anzugeben.

Was wir noch klären müssten, bevor ich das Issue erstelle:

  1.  Das ist der selbe Text, der auch im AddOn umgesetzt ist. Findet ihr die Redundanz schlimm? Die Infos sind aus meiner Sicht schon auf der Endseite wichtig, um die Leute zur Adressangabe zu motivieren und den Zweck der Erhebung der Adressdaten zu erläutern. Oder wir nehmen den Text in der AddOn raus, finde ich aber auch nicht so schön, die Adressen zu erfragen, ohne nochmal auf den Zweck hinzuweisen. (Meine Präferenz wäre: es einfach zweimal zu schreiben)
  2.  Wie gehen wir mit der Ankündigung der nächsten Befragung hier um? in der AddOn haben wir ja unterscheidliche Zeitpunkte genannt (15.4=2 jahre, 18.3a=1 Jahr). Hier per Einblendung je Kohorte lösen? oder die Info weglassen? (Wenn das per Einblendung machbar ist, würde ich das präferieren)

-

**Comment by woisch** [comment]
Ich würde es dann, wenn kein Widerspruch kommt, per Einblendung lösen kohortenspezifisch (Silina sagt, es geht) und ein entsprechendes Issue erstellen.

**Comment by jocarstensen** [comment]
Bin mit allem so einverstanden.

**Comment by bafranke** [comment]
kein Widerspruch

**Comment by woisch** [comment]
Dann schließe ich hier mal
