### ISSUE TITLE
Issues Epi-Studium

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#163]
- [x] staa42 (und evtl. weitere): Fragezeichen statt Punkt am Satzende
- [x] staa42 (und evtl. weitere): Warum lande ich hier, wenn ich direkt vorher angegeben habe, dass ich aktuell unterbrochen habe?
- [x] staa47 (und evtl. andere) Ich würde noch "seit <h_enterdatum>" hinzufügen
- [x] Doppelpunkte bei Orts-Infields sind noch da

**Comment by se-lang** [comment]
> staa42 (und evtl. weitere): Warum lande ich hier, wenn ich direkt vorher angegeben habe, dass ich aktuell unterbrochen habe?

Müsste man eine bedingte Formulierung für diejenigen mit einer aktuellen Unterbrechung einfügen.

**Comment by bafranke** [comment]
- [ ] Stab04 (und alle folgenden Seiten): Datum wird nicht eingeblendet, obwohl ich etwas angegeben habe
![grafik](https://user-images.githubusercontent.com/56022369/70315008-f6f8be80-1818-11ea-843d-af4cd874cdc3.png)

Andere Splits/Schleifen hab ich bislang nicht getestet.

**Comment by se-lang** [comment]
>Stab04 (und alle folgenden Seiten): Datum wird nicht eingeblendet, obwohl ich etwas angegeben habe

@bafranke Kommt mir leider jetzt erst: Von wann ist der Kommentar? Hab da gestern noch was überarbeitet.

**Comment by woisch** [comment]
das Problem scheint noch zu bestehen, vorhin von einer Pretesterin wieder bekommen und versehentlich ein neues Issue dazu aufgemacht (#177) 
Integriere das mal hier

**Comment by se-lang** [comment]
Ok, dann geh ich nochmal auf die Suche

**Comment by se-lang** [comment]
> 
> 
> > staa42 (und evtl. weitere): Warum lande ich hier, wenn ich direkt vorher angegeben habe, dass ich aktuell unterbrochen habe?
> 
> Müsste man eine bedingte Formulierung für diejenigen mit einer aktuellen Unterbrechung einfügen.

Ist eingebaut und kann nach nächstem Rollout getestet werden

**Comment by se-lang** [comment]
> 
> 
> Ok, dann geh ich nochmal auf die Suche

Komm ich aktuell so nicht weiter, muss ich mit Silina am Montag in die Datenbank schauen.

**Comment by se-lang** [comment]
Ich glaube ich hab den Fehler gefunden. @woisch @bafranke bitte nach dem nächsten Rollout einmal testen, bin aber zuversichtlich, dass es dann funktioniert.

**Comment by woisch** [comment]
Nach letztem Rollout (09.12.2019 13:35) getestet, sehe immer noch keine Datumseinblendungen.

**Comment by woisch** [comment]
@se-lang : Jetzt (seit Rollout von eben) kriege ich die Einblendungen der Monate bei Wechseln von Studienfach/Abschluss etc auf stab04 ff. angezeigt.

![grafik](https://user-images.githubusercontent.com/53002476/70514001-ff136f80-1b32-11ea-90f2-98aaa292efcd.png)


Der Rest war ja geklärt hier, dann kann zu oder?
