### ISSUE TITLE
staa34: Rechtschreibung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#166]
Itemtext fehlerhaft:
Wann hat sich Ihr**en**  angestrebter Abschluss geändert?

**Comment by SilinaKowalewski** [comment]
Habe ich mal bei allen betreffenden Seiten geändert. Sollte im nächsten Roll-Out angepasst sein.

**Comment by woisch** [comment]
habe durchgetestet von staa34 bis stad34, da war es überall umgesetzt. Danach kam der Schleifenzähler ins Spiel. 
@se-lang Gehe davon aus, dass es passt. Willst du das nochmal systematisch in der QML prüfen, oder sollen wir hier zu machen?

**Comment by se-lang** [comment]
passt
