### ISSUE TITLE
Probleme Episoden: SET

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#167]
Ich sehe für meine aktuelle SET (dauert im Dezember 2019 noch an) nach der frage zur Stundenzahl weder die Adäquanzfragen noch die berufliche Zufriedenheit.
nach seaa60 kommt se0003, dann zwischen_em

getestet als cohort 1 mit tester192

**Comment by jocarstensen** [comment]
Japp. Ich verstehe den Fehler. Bin mir nur nicht 100% sicher, dass der Fix, den ich im Kopf habe, nichts Schlimmes nach sich zieht.

**Comment by jocarstensen** [comment]
Ok, sollte ab dem nächsten Rollout funktionieren. Hoffe ich...

**Comment by jocarstensen** [comment]
Ich komme jetzt drauf. @woisch Bitte nochmal testen.

**Comment by jocarstensen** [comment]
Dafür bleibt man jetzt auf seaa68 hängen. Gucke ich mir an.

**Comment by jocarstensen** [comment]
Fehler gefunden und korrigiert. Im nächsten Rollout sollte es behoben sein.
@SilinaKowalewski wie gerade auch per Mail geschrieben wäre ein baldiger Rollout entsprechend sehr wünschenswert.

**Comment by woisch** [comment]
Ich sehe jetzt als cohort1 bei laufender SET im Dezember auch die Abfragen Stundenzahl, Zufiriedenheit und Adäquanz. Und hänge dann auf seaa68

**Comment by jocarstensen** [comment]
Ja, wie oben beschrieben. War leider im aktuellen Rollout noch nicht mit drin.

**Comment by jocarstensen** [comment]
Jetzt komme ich weiter. Meiner Meinung nach ist an der Stelle jetzt alles fein. Was sagst Du, @woisch? Kannst Du von mir aus auch schließen, wenn Du zufrieden bist.

**Comment by woisch** [comment]
Komme jetzt auch weiter, sieht alles gut aus.
