### ISSUE TITLE
Update Modul_Studium, Lehr-Lernumwelt 2

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#168]
- [x] stu_25: Transition auf stu_27 gesetzt

- [x] stu_26: Seite gelöscht

- [x] stu_27: Variablen, Items und bedingte Itemanzeige geändert

https://github.com/dzhw/SLC-IntEr/commit/b71c530f776754fdbe60b0c0683eaa66f0a093a5

**Comment by SilinaKowalewski** [comment]
Änderungen sind angepasst und ausgerollt.

**Comment by woisch** [comment]
@heikQ Kannste das mal testen?

**Comment by SilinaKowalewski** [comment]
@heikQ: Muss hier noch was gemacht werden?

**Comment by heikQ** [comment]
@SilinaKowalewski erledigt, mache zu
