### ISSUE TITLE
seT: Seite wird nach "Lösung" des sf ein weiteres Mal angezeigt

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#169]
•	Seaa09: ich gebe nichts an – bekomme den sf, gebe ein gültiges Datum an und bekomme dann diese Seite noch einmal vorgelegt ohne sf mit den Angaben, die ich gerade gemacht 
tritt auf jeden Fall auch bei seab09 auf
Hier die Screenshots dazu:
![grafik](https://user-images.githubusercontent.com/56022369/70307994-ab3f1880-180a-11ea-9d3b-9602dc280200.png)
![grafik](https://user-images.githubusercontent.com/56022369/70308003-b09c6300-180a-11ea-983b-0ca31828fb91.png)
->dann habe ich Januar 2018 ausgewählt, auf weiter geklickt und bekam diese Seite:
![grafik](https://user-images.githubusercontent.com/56022369/70308058-c578f680-180a-11ea-840c-2e2c587f1f0b.png)

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Hast du dir dieses Problem schon angeschaut und eine Idee dazu? Ich finde im qml irgendwie nichts, was dass erklären würde.

**Comment by jocarstensen** [comment]
Nein, verstehe ich auch nicht. Die Conditions sind geschrieben wie immer und auch die vc für den SF. Wirkt irgendwie so, als würden die Values nicht direkt in die Datenbank geschrieben, solange der SF visible ist. Das müsste dann aber überall sonst auch so sein.

Kannst Du das mal mit @vdick oder @dzhwmeisner besprechen?

**Comment by jocarstensen** [comment]
Liste:
- seaa09/seab09/seac09/sead09/seae09
- seba09/sebb09/sebc09/sebd09
- seca09/secb09/secc09
- seda09/sedb09
- seea09

**Comment by SilinaKowalewski** [comment]
Sollte nun passen. Bitte noch mal checken.

**Comment by jocarstensen** [comment]
Stichprobenartig getestet, sieht gut aus.
