### ISSUE TITLE
Probleme Modul Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#170]
betrifft cohort2:
habe im Epimodul Studium vollständige Angaben gemacht und ein Studium was im Dezember 2019 noch andauert angegeben (tester199). 

auf Seite stu_20/21 funktioniert irgendwas gar nicht. Ich sehe einzelbe Angaben aus dem Epimodul studium eingeblendet (Fach und Hochschule) ansonsten eine leere Skala.

stu_20
![grafik](https://user-images.githubusercontent.com/53002476/70308802-5a302400-180c-11ea-8141-9c7c3e5a62e2.png)

stu_21
![grafik](https://user-images.githubusercontent.com/53002476/70308825-6ae09a00-180c-11ea-9294-5b01d41b1d37.png)

**Comment by jocarstensen** [comment]
Problem ist bekannt, noch keine Lösung gefunden.
@se-lang Bist du da noch dran?

**Comment by jocarstensen** [comment]
Nachfrage zur Klärung @woisch: Du hast nur eine Studienepisode mit einem Studiengang und zwei Fächern angegeben, richtig? Sprich es fehlen keine Angaben, sondern nur die Einblendung der leeren Felder ist das Problem?
(Hintergrund: Die Variablen für alle anderen Loops sind natürlich angelegt. Sie sollten aber ausgeblendet werden, wenn sie leer sind.)

**Comment by woisch** [comment]
Genau, ich hatte nur eine Episode mit 2 Fächern, die noch andauert.
Dann seid ihr ja dran am Problem!

**Comment by se-lang** [comment]
@jocarstensen ich mach mich jetzt wieder hier auf die Suche

**Comment by se-lang** [comment]
Sollte gelöst sein, nach dem nächsten Rollout nochmal testen

**Comment by se-lang** [comment]
Funktioniert bei mir. Close
