### ISSUE TITLE
Endseite und Überleitung in AddOn

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#171]
- [x] Wir benötigen auf der Endseite noch einen Text und die Verlinkung in die AddOn-Befragung. Der Text soll unter dem Bild platziert werden. Wir brauchen kohortenspezifisch eine Einblendung für den Klammerzusatz, wann die nächste Befragung kommt.

**Hat sich Ihre Anschrift seit der letzten Befragung geändert?**

[visible IF cohort==1] Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung  (in ca. 2 Jahren) erreichen und im Falle eines Gewinns informieren können.
[visible IF cohort==2] Dann teilen Sie uns bitte Ihre aktuellen Kontaktdaten mit, damit wir Sie für die nächste Befragung  (in ca. einem Jahr) erreichen und im Falle eines Gewinns informieren können.
Ihre Kontaktadresse wird streng vertraulich behandelt und nicht mit den Befragungsdaten verknüpft.

Klicken Sie hier, um Ihre aktuelle Adresse anzugeben (hier die Verlinkung zu den beiden AddOns, cohort 1 und 2 haben ja unterschiedliche).

- [x]  Ist Bild auf der Endseite zentriert? Wenn ja, sollte es aus meiner Sicht eher linksbündig ausgerichtet sein. Auf dem Mobile sieht es gerade etwas unschön aus:
![grafik](https://user-images.githubusercontent.com/53002476/70313661-586b5e00-1816-11ea-8062-664527b2f495.png)

**Comment by woisch** [comment]
Nur zur Sicherheit (und weil es gerade falsch umgesetzt ist):
der Satz "Ihre Kontaktadresse wird streng vertraulich behandelt und nicht mit den Befragungsdaten verknüpft." soll für beide kohorten eingeblendet werden. Gehört nicht mehr zur visible-consition der cohort2!!
Als cohort1 sehe ich ihn gerade nicht.

Außerdem den Link auf den kompletten Satz (Klicken Sie hier, um Ihre aktuelle Adresse anzugeben) legen und nicht nur das "hier".

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können getestet werden. 

Der Link zur AddOn funktioniert natürlich noch nicht, weil diese, genau wie die Hauptbefragung, noch nicht online ist.

**Comment by woisch** [comment]
Danke!
Das Bild passt sich jetzt scheinbar der Bildschirmgröße an (was ich gut finde)! Allerdings wird es nun auf dem Mobile sehr klein. Kann man da irgendwie ne minimalgröße setzen fürs mobile, sodass es etwas größer und noch lesbar ist aufm mobile?

![grafik](https://user-images.githubusercontent.com/53002476/70435856-3711a880-1a88-11ea-9dd1-f5c7660cc394.png)

**Comment by SilinaKowalewski** [comment]
Das Bild nimmt maximal 80% der Bildschirmbreite ein. Da das von euch gelieferte Bild schon sehr breit ist bzw. sehr viel Whitespace enthält, sieht es nun leider recht klein aus.

**Comment by woisch** [comment]
Kannst du es nochmal mit dem Bild probieren`? Hab alles an whitespace gelöscht was ging
![Kohorte_1_ZS_6](https://user-images.githubusercontent.com/53002476/70436891-9bce0280-1a8a-11ea-927c-416763bda6aa.png)

**Comment by woisch** [comment]
Ist jetzt viel besser! Auch aufm mobile.

Der Fortschrittsbalken ragt jetzt aber aus irgendeinem Grund etwas in den Header rein..Nur am Desktop (getestet am Macbook)

![46E3E8C2-8530-4E79-B9BB-259BBDC1DB09_1_105_c](https://user-images.githubusercontent.com/53002476/70565998-82fd4400-1b93-11ea-952c-04b727e2c109.jpeg)

**Comment by woisch** [comment]
auch hier am Desktop hab ich das Problem mit dem Überlappen.

![grafik](https://user-images.githubusercontent.com/53002476/70616524-eaa4a500-1c0e-11ea-845f-7ebec5becc82.png)

**Comment by SilinaKowalewski** [comment]
@woisch: Kommentiere das doch am besten im Issue #89

**Comment by woisch** [comment]
ok, stimmt. betrifft eher den Fortschrittsbalken.
Dann mach ich hier zu.
