### ISSUE TITLE
Episoden Praktikum

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#172]
- [x] i0001

![grafik](https://user-images.githubusercontent.com/56022369/70316278-a59dfe80-181b-11ea-8186-329ca44b7aeb.png)

**Comment by jocarstensen** [comment]
@bafranke Was genau stört Dich da?

**Comment by woisch** [comment]
iaa18 (und weitere Schleifen): Bei diesen Fragen ist die Skalierung andersrum als im sonstigen Fragebogen (sonst immer trifft zu bis trifft nicht zu.) 

![grafik](https://user-images.githubusercontent.com/53002476/70316757-a1261580-181c-11ea-9299-f60b7fe69760.png)

**Comment by bafranke** [comment]
Ok, ich habs. Der Halbsatz bezieht sich auf das Anerkennungspraktikum. Habs 20 mal gelesen und nicht verstanden. Ich hatte nach dem "auch" weitere nicht gemeinte Dinge erwartet, und dann passte das "genannt" nicht. 
"auch Anerkennungsjahr oder Berufspraktikum genannt" wäre für mich eher ein Klammertext, oder mit Komma so: 
"Damit meinen wir keine Anerkennungspraktika zur staatlichen Anerkennung nach dem Studium, die auch Anerkennungsjahr oder Berufspraktikum genannt werden."
Aber es ist formal richtig, lass es ruhig so!

**Comment by jocarstensen** [comment]
@bafranke Können wir meinetwegen gern umformulieren wie von Dir vorgeschlagen.

**Comment by bafranke** [comment]
scheint ja aber keinen anderen gestört zu haben, also brauchst du den Aufwand nicht machen...

**Comment by jocarstensen** [comment]
Na gut.
@woisch Ist gedreht. Nach Rollout testbar.

**Comment by woisch** [comment]
iaa13 (und weitere): in der mobilen Ansicht passt es nicht auf den Bildschirm. Das alte Problem bei einzelitems in der responsiven Ansicht. Wir müssten das Item hier also in die vertikale drehen.

![grafik](https://user-images.githubusercontent.com/53002476/70327583-67163d00-1837-11ea-9462-62e9186b8d38.png)

**Comment by woisch** [comment]
> 
> 
> Na gut.
> @woisch Ist gedreht. Nach Rollout testbar.

das passt jetzt so!

**Comment by jocarstensen** [comment]
@woisch: Kannst du für iaa13 ein neues Issue aufmachen? Das ist jetzt so etwas verwirrend.

**Comment by jocarstensen** [comment]
Dann kann das hier zu

**Comment by woisch** [comment]
okay, das andere hab ich ins neue issue gepackt
