### ISSUE TITLE
Modul Studium (cohort2): Skalenrichtung Lehr-/Lernumwelt

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#173]
Im Pretest aufgefallen:
Bei den Fragen stu 22,23,24,25,28 und 29 ist die Skalenrichtung entgegen der sonstigen Logik im Fragebogen (eigentlich immer: Zustimmung bis Ablehnung)

**Comment by jocarstensen** [comment]
Die Items laufen jetzt so, wie sie entwickelt und getestet sind. Drehen könnte Einfluss auf die Faktorstruktur haben. Was meinst Du, @heikQ ?

**Comment by heikQ** [comment]
@jocarstensen Pflichte dir bei, lassen wir so, wie im Kontruktpapier vorgeschlagen. Entspricht dann zwar nicht den restlichen, ich würde es aber dennoch so lassen und mache daher mal zu hier
