### ISSUE TITLE
sET: Füllung von HV

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#174]
@SilinaKowalewski Ich schreibe das jetzt doch in ein Issue, damit es nicht verlorengeht.

In sET versuche ich, in den HV h_seaa06m_la und h_seaa06j_la (und weiteren in anderen Loops) die Labels aus seaa03/seaa04 zu speichern, um sie später in h_sezz06m_la/h_sezz06j_la zu kopieren und dann für Einblendungen zu benutzen.

`            <zofar:variable variable="h_seaa06m_la" onExit="true" direction="forward" value="zofar.labelOf(seaa03dropDown)"/>			
            <zofar:variable variable="h_seaa06j_la" onExit="true" direction="forward" value="zofar.labelOf(seaa04dropDown)"/>						
`

Zuerst hatte ich sie noch auf derselben Seite (seaa01), jetzt habe ich die Trigger auf die nächste Seite verschoben (sehen alle), falls das ein Prolem gewesen sein sollte. Leider sind die Variablen aber immer noch leer.

Was mache ich falsch?

@vdick @dzhwmeisner Silina und ich haben schon zusammen beratschlagt, kommen aber auf keine Lösung. Habt Ihr eine Idee?

**Comment by jocarstensen** [comment]
Sofern mein commit von 13:36 im letzten Rollout (Stand 13:40) berücksichtigt war, hat es nichts gebracht, "dropDown" wegzulassen. Noch weitere Ideen?

**Comment by jocarstensen** [comment]
`direction="forward"` rausnehmen und
`onExit=false`
haben auch nichts gebracht. Keine Änderung.

**Comment by jocarstensen** [comment]
@SilinaKowalewski @vdick @dzhwmeisner Habt Ihr Euch das nochmal angeguckt?

**Comment by jocarstensen** [comment]
Sebastian hat's gelöst. Sollte jetzt behoben sein. Es funktioniert mit
`value="zofar.labelOfDropDown(xxxxxx)`

**Comment by SilinaKowalewski** [comment]
[Ergebnis_Datenbank.xlsx](https://github.com/dzhw/SLC-IntEr/files/3949243/Ergebnis_Datenbank.xlsx)

**Comment by jocarstensen** [comment]
Jetzt funktioniert es. Endlich. Ich mach die Tür zu.
