### ISSUE TITLE
Modul Ausbildung (cohort2): aus_06

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#175]
Ich bekomme die Ausbildungsintention vorgelegt, obwohl ich eine Ausbildungsepisode angegeben habe in Kalendarium und Epimodul Ausbildung.
Eigentlich müsste ich demnach h_ausbever=1 sein und daher die Frage nicht sehen bzw. den ganzen Block "Ausbildung überspringen, oder?
@heikQ Kannst du das auch reproduzieren?
(ich war tester203)

**Comment by woisch** [comment]
Es scheint zumindest kein allgemeiner bug mit der HV ausbever zu sein. habe für cohort1 nochmal einen Test gemacht, da nutzen  wir ausbever und studever ja auch zum Filtern innerhalb der Module Ausbildung und Studium. Das funktioniert auch wie es sollte.

**Comment by woisch** [comment]
Ich korrigiere:
Ich habe das Gefühl, dass mit der h_ausbever etwas nicht stimmt, die scheint gerade immer 0 zu sein. Auch bei cohort1 werde ich nun von zwischen_aus soweitergeleitet, als hätte ich ausbever=0, obwohl ich eine Ausbildungsepisode im Epimodul angegeben habe. Ich sollte demnach aus_01 nicht sehen sonder direkt zu aus_04 gelangen.

Hinsichtlich h_studever scheinen die Weiterleitungen im Modul Studium komischerweise im gleichen Testfall korrekt zu funktionieren (Tester201)

**Comment by se-lang** [comment]
Hab den Fehler gefunden. @jocarstensen h_ausbever ist eine string und du befüllst sie mit true und flase, gefiltert wird aber mit zofar.asNumber(h_ausbever)==0 und ==1

**Comment by jocarstensen** [comment]
Ok, blöd. Machst Du das, soll ich das machen oder lassen wir das machen?

**Comment by se-lang** [comment]
Mach ich gleich, kein Problem

**Comment by se-lang** [comment]
done

**Comment by jocarstensen** [comment]
Riesendank!

**Comment by jocarstensen** [comment]
@woisch Kannst Du das mal testen?

**Comment by heikQ** [comment]
Also ich habe gerade mal in der Projektinternen Version geschaut für cohort2, hier wird die Ausbildungsintentionsfrage (aus_06) weiterangegeben, obwohl im Calendarium und bei den Episoden eine ausbildung gegeben wurde.

**Comment by woisch** [comment]
Habe es mit cohort1 getestet. Problem besteht weiterhin, trotz angabe von Ausbildung in kalendarium und Episoden werde ich gefiltert als wäre h_ausbever=0.

**Comment by woisch** [comment]
Das Problem besteht immer noch.

**Comment by se-lang** [comment]
@woisch @jocarstensen Hab das Problem glaube ich gefunden. Nach dem nächsten Rollout bitte nochmal testen.

**Comment by woisch** [comment]
eben für cohort1 unn 2 getestet, ging jetzt mit dem Filtern über ausbever!
