### ISSUE TITLE
Layout auf mobilen Geräten anpassen

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#176]
ich habe mal wieder mobil getestet (vornehmlich in landscape-Ansicht) und habe noch ein paar unschöne Ansichten gefunden - wenn noch Zeit ist und es nicht kompliziert ist, das umzubauen, wären folgende Änderungen noch toll:

- [x] Emaa12: mobil (landscape) zu eng
![grafik](https://user-images.githubusercontent.com/56022369/70322717-20bae100-182b-11ea-830d-534db24ec273.png)
 

- [x] Emaa16: landscape: zu kleine Freitextfelder
![grafik](https://user-images.githubusercontent.com/56022369/70322709-1b5d9680-182b-11ea-94f9-4882ade1c1cc.png)

 
- [x] Emaa16 Portrait: Freitextfelder sind unterschiedlich eingerückt, ist es möglich, sie auf gleicher Höhe beginnen zu lassen? (ich dachte, die wären schon mal auf gleicher Höhe gewesen...)
 
![grafik](https://user-images.githubusercontent.com/56022369/70322681-084ac680-182b-11ea-810d-52dda30c4d1f.png)

- [x] Emaa40: sonstige-Freitextfeld zu klein (landscape)
 ![grafik](https://user-images.githubusercontent.com/56022369/70322662-fcf79b00-182a-11ea-8d51-1e1b76096815.png)

Bitte beachtet jeweils auch die entsprechenden Seiten in den Splits/Schleifen!

**Comment by woisch** [comment]
Weiteres:

- [ ] stu_44: offenes Textfeld bei sonstiges und zwar ist zu klein:

![grafik](https://user-images.githubusercontent.com/53002476/70328988-9bd7c380-183a-11ea-8d38-b548b49bffda.png)

Im landscape geht es:
![grafik](https://user-images.githubusercontent.com/53002476/70329006-a4c89500-183a-11ea-8fb9-3a9e87ff8219.png)


- [ ] stu62,70,78,86: offenes Textfeld zu klein. 
![grafik](https://user-images.githubusercontent.com/53002476/70329227-2ddfcc00-183b-11ea-930e-3c465cc5306d.png)
Diese Frage taucht insgesamt 5 mal auf. Auf stu_54 habt ihr es schonmal gefixt, da sieht es in der mobilen Ansicht gut aus. Allerdings ist der Kasten da in der Desktop Ansicht extrem breit. Vielleicht gibt es eine Möglichkeit, dass es in beiden Varianten gut aussieht.

**Comment by vdick** [comment]
bei stu_44 finde ich keine optimale Lösung, da der Platz einfach zu begrenzt ist. Das offene Feld ist etwas breiter geworden.
Ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
stu_44 können wir so lassen.

stu62,70,78,86 sehen immer noch so aus wie vorher

**Comment by woisch** [comment]
Okay, mein Fehler. Sorry @vdick 
Alles ok so!
