### ISSUE TITLE
Episdoden Praktikum: iaa13 und weitere (Skala drehen)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#178]
iaa13 (und weitere): in der mobilen Ansicht passt es nicht auf den Bildschirm. Das alte Problem bei Einzelitems in der responsiven Ansicht. Wir müssten das Item hier also in die vertikale drehen.

![grafik](https://user-images.githubusercontent.com/53002476/70327583-67163d00-1837-11ea-9462-62e9186b8d38.png)

**Comment by jocarstensen** [comment]
Trifft zu auf iaa13/iba13/ica13/ida13/iea13

**Comment by woisch** [comment]
Wir haben das Problem jetzt auch in nsET und SET, dadurch dass wir die subj. Einschätzungsfragen zur Adäquanz auf 2 Seiten aufgeteilt haben, hier müssten wir das Einzelitem in die vertikale drehen, damit es responsiv ohne horizontales Scrollen ausfüllbar ist:
![grafik](https://user-images.githubusercontent.com/53002476/70335126-fd9e2a80-1846-11ea-8945-187b89493881.png)

betrifft:
emaa42
emaa42
emaa42
emaa42

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Kann geprüft werden.

**Comment by woisch** [comment]
Passt so!
