### ISSUE TITLE
Skalenbeschriftung bei subj. Leistungseinschätzung

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#179]
Ich habe 2 Rückmeldungen zu der Frage der subj. Leistungseinschätzung (stu_19), dass es sinnvoll wäre die positiven Leistungswerte mit einem "+" zu versehen. (In unseren Papierbefragungen machen wir das übrigens auch). Müsste dann auch im Epimodul Ausbildung für jede Schleife geändert werden.
Fände ich gut, falls nächste Woche noch Zeit ist, hat natürlich geringe Prio!

![grafik](https://user-images.githubusercontent.com/53002476/70332368-b82b2e80-1841-11ea-8039-ba83d1e3f750.png)

**Comment by jocarstensen** [comment]
Ja, ich bin auch dafür.

Gilt dann auch für vaa29/vba29/vca/29/vda29/vea29/vza29

**Comment by woisch** [comment]
- [ ] stu_19: label anpassen ("+") ergänzen
https://github.com/dzhw/SLC-IntEr/commit/4efea547f5f039de0482e78098e1e2da4590de2e#diff-1a8bc56571cbab4553ac5520ebd314fb

- [ ]  vaa29 label anpassen ("+") ergänzen (wie stu_19)

- [ ] vba29/vca/29/vda29/vea29/vza29: Labels anpassen wie die beiden oben. Also:

ao1:-5: unterdurchschnittlich (-5)

ao2:-4: (-4)

ao3:-3: (-3)

ao4:-2: (-2)

ao5:-1: (-1)

ao6:0: durchschnittlich (0)

ao7:1: (+1)

ao8:2: (+2)

ao9:3: (+3)

ao10:4: (+4)

ao11:5: überdurchschnittlich (+5)

**Comment by jocarstensen** [comment]
:-1

**Comment by woisch** [comment]
hat für mich eher mittlere Prio, vor allem weil innerhalb des Ausbi-Moduls die Skalenrichtungen scheinbar unterschiedlich umgesetzt sind!

**Comment by woisch** [comment]
ist jetzt gefixt, hab ich gesehen. Für alle o.g. Seiten getestet.
