### ISSUE TITLE
Modul_Einstieg: Item falsch programmiert

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#18]
In beg_10 wurde Item 7 falsch programmiert, richtig ist: 
it7: der Ihnen Rat geben kann, wenn es Probleme gibt? 

hier noch einmal separat als issue notiert, weil meine Angabe dazu in Update2 irritiert

**Comment by andreaschu** [comment]
Item korrigiert, kann beim nächsten roll out (morgen) getestet werden

**Comment by SilinaKowalewski** [comment]
@bafranke: 

Scheint nun richtig zu sein. Kann das Issue damit geschlossen werden?

**Comment by bafranke** [comment]
jap
