### ISSUE TITLE
Episoden nsET und SET: Adäquanz (Skala vertikal drehen)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#180]
In nsET und SET haben wir, dadurch dass wir die subj. Einschätzungsfragen zur Adäquanz auf 2 Seiten aufgeteilt haben, auf der ersten der beiden Seiten ebenfalls wieder das Problem, dass das Einzelitem responsiv ohne horizontales Scrollen nicht ausfüllbar ist:
![grafik](https://user-images.githubusercontent.com/53002476/70335126-fd9e2a80-1846-11ea-8945-187b89493881.png)

betrifft in nsET:
- [x] emaa42
- [x] emba42
- [x] emca42
- [x] emda42
- [x] emea42
- [x] emfa42
- [x] em0042

in SET:

- [x] seaa65
- [x] seba65
- [x] seca65
- [x] seda65
- [x] seea65
- [x] sezz65

- [x] bei der gelegenheit auf all diesen Seiten: zwischen Fragetext und Ausfüllanweisung ("hinsichtlich der fachlichen Inhalte") eine Leerzeile einzufügen.

 @se-lang: habe die Listen mit Issue #157 abgeglichen, gehe also davon aus, dass ich alle Fragen erwischt habe in beiden Modulen.

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können getestet werden.

**Comment by woisch** [comment]
- [ ] das Absetzen der Zeile  ("hinsichtlich der fachlichen Inhalte")  bitte auch noch bei den Items aus nsET vornehmen: 

emaa42
emba42
emca42
emda42
emea42
emfa42
em0042

**Comment by se-lang** [comment]
> 
> 
>     * [x]  das Absetzen der Zeile  ("hinsichtlich der fachlichen Inhalte")  bitte auch noch bei den Items aus nsET vornehmen:
> 
> 
> emaa42
> emba42
> emca42
> emda42
> emea42
> emfa42
> em0042

Sollte nach nächsten Rollout passen

**Comment by SilinaKowalewski** [comment]
Ist hier noch was zu tun?

**Comment by woisch** [comment]
im Rollout von gestern war das Absetzen der Zeile, meine ich, noch nicht umgesetzt. Wir prüfen das nochmal nach dem nächsten Ausrollen...

**Comment by woisch** [comment]
@SilinaKowalewski : Es ist immer noch keine Leerzeile drin. , @se-lang sagt, du könntest gerade an die QML, um das zu prüfen, weil er nicht drin ist.

![grafik](https://user-images.githubusercontent.com/53002476/70602844-98a35580-1bf5-11ea-8473-71b54344c83c.png)

**Comment by woisch** [comment]
@se-lang Kann das dann hier zu? betrifft die eben besprochene Leerzeilen-Sache...

**Comment by woisch** [comment]
Ich mache hier zu.

@SilinaKowalewski : hat sich erledigt.
