### ISSUE TITLE
Episoden SET: Datum als Zahl eingeblendet (se0002)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#181]
Beim exzessiven Durchtesten des SET Moduls kam folgendes Problem auf, das Enddatum wird als Zahl angezeigt. Tester 204.

![grafik](https://user-images.githubusercontent.com/53002476/70344512-3267ad00-185a-11ea-969d-d0c21b8bd977.png)

**Comment by jocarstensen** [comment]
Ja, so weit muss man erstmal kommen.

Aber witzig, ich hab die Seite oft gecheckt und mir ist es nie aufgefallen. Betriebsblind...

Ist auf jeden Fall korrigiert. Im nächsten Rollout gefixed.

**Comment by jocarstensen** [comment]
Ist behoben.
