### ISSUE TITLE
stu_10 zu voll?

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#182]
Ein Pretestkommentar lautete, dass die stu_10 zu voll sei. Man könnte die Batterie auf zwei Seiten verteilen. Was meint Ihr, @woisch @heikQ ?

**Comment by woisch** [comment]
Finde die auch sehr voll. In 15.4 ist die Batterie aufgeteilt (stu_17/18). Die letzten 6 Items sind auf einer extra Seite.

**Comment by woisch** [comment]
PS: Hast du schon die Pretestkommentare von ZOFAR? oder war das per Mail?

**Comment by jocarstensen** [comment]
Das war per Mail. Bin noch nicht dazu gekommen, den Export anzuschieben. Mache gleich ein Issue auf.

**Comment by woisch** [comment]
Bin schon dabei das Issue aufzumachen..

**Comment by heikQ** [comment]
ich mache jetzt zwei Seiten draus, ist wirklich etwas lang mit über 20 items. auf der zweiten Seite nehme ich dann aber einfach den gleichen Fragetext, jedoch ohne den ausführlichen einleitenden brabbelbrams

**Comment by heikQ** [comment]
ich mach hier mal zu dann, update ist raus nmit der umsetzung
