### ISSUE TITLE
Export Kommentare Pretest

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#183]
Wir benötigen einen Export der Pretestkommentare aus den offenen Feldern.

**Comment by SilinaKowalewski** [comment]
[Pretest_Kommentare.xlsx](https://github.com/dzhw/SLC-IntEr/files/3940296/Pretest_Kommentare.xlsx)

Schaut mal ob euch das reicht.

**Comment by jocarstensen** [comment]
Ich denke schon.

**Comment by se-lang** [comment]
@jocarstensen Hab mal das comment vor jedem Seitennamen entfernt und es im Projektordner abgelegt

**Comment by woisch** [comment]
Ja, damit können wir arbeiten.
