### ISSUE TITLE
Kalendarium: Zeilenumbrüche im Overlay

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#184]
Ab einer gewissen Breite springen die Zeilenimmer so um, dass sie nicht mehr in einer Zeile mit den farbigen Symbolen sind. Lässt sich das vermeiden?

![grafik](https://user-images.githubusercontent.com/35771616/70442838-5cf27980-1a97-11ea-8451-e506e5f2e4a6.png)

**Comment by dzhwmeisner** [comment]
erledigt. Im nächsten Rollout verfügbar

**Comment by woisch** [comment]
Bei mir siehts gut aus.
@jocarstensen: Lassen wir so? (Dann kann ich morgen die Screenshots machen)

**Comment by jocarstensen** [comment]
Bei mir besteht das Problem weiterhin.

![grafik](https://user-images.githubusercontent.com/35771616/70601206-d9996b00-1bf1-11ea-93b5-bff8e9efd71d.png)

**Comment by woisch** [comment]
komisch.. Bei dir ist auch die Ergänzung bei Berufsausbildung noch nicht drin. Scheinst ja aber auf dem internen Server zu testen. Cache geleert?

![grafik](https://user-images.githubusercontent.com/53002476/70601424-490f5a80-1bf2-11ea-854b-9974dc17e0c5.png)

**Comment by jocarstensen** [comment]
Quatsch, sorry. Mit gelöschtem Cache ist alles gut. Danke!

**Comment by woisch** [comment]
Jetzt hat sich bei Berufsausbildung ein Tippfehler eingeschlichen! (es fehlt ein "s")

Bitte schnell beheben, wir müssen Screenshots von der Seite machen...

**Comment by dzhwmeisner** [comment]
Korrektur wird im nächsten Build verfügbar sein

**Comment by SilinaKowalewski** [comment]
@woisch: Sieht nun gut aus. Könntest also mit den Screenshots loslegen.
