### ISSUE TITLE
Simulation / Lasttest

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#185]
Wie sind unsere Optionen bezüglich eines Lasttests vor dem Feldstart und inwiefern können wir mit Datensimulation z. B. nicht erreichbare Seiten identifizieren?

**Comment by woisch** [comment]
Wir brauchen hier dringend eine Antwort für die weitere Planung!

**Comment by jocarstensen** [comment]
@andreaschu Gibst Du uns hierfür noch Rückmeldung zu den noch offenen Punkten von gestern? (zumindest das Thema Schleifen war noch offen)

**Comment by jocarstensen** [comment]
@andreaschu Gibst Du uns hierfür noch Rückmeldung zu den noch offenen Punkten von gestern? (zumindest das Thema Schleifen war noch offen)

**Comment by andreaschu** [comment]
Den Schleifen-Check haben wir gemacht. Die Ergebnisse kommen Morgen.

**Comment by andreaschu** [comment]
Der Screenshot wird über Nacht laufen müssen, kommt auch Morgen.

**Comment by jocarstensen** [comment]
Ok, cool

**Comment by andreaschu** [comment]
Hier sind die Ergebnisse aus dem Test nach den 'echten' Schleifen. 
[Test_Transitions.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960185/Test_Transitions.xlsx)

Wir haben die Transitions danach untersucht auf welche Seite sie verweisen und an welcher Stelle diese Seite im QML steht.
Zur Lesehilfe: Die Spalte 'distance' gibt an, ob die transition auf dieselbe Seite führt (0) auf eine folgende Seite (>=1) oder auf eine vorherige Seite (<=1).

Wir haben das Gesamtdokument durchsucht. Das hat eine gewisse Unschärfe, da die Reihenfolge der einzelnen QMLs nicht der Reihenfolge im Fragebogen entspricht. Deswegen ist es nicht so schlimm, wie es im Bericht aussieht. 
Wir machen den Bericht gerade noch für die einzelnen QMLs.

**Comment by jocarstensen** [comment]
Super, das ist sehr hilfreich!

@se-lang Von meiner Seite aus sind da nur die Zeilen 136 bis 189 auffällig. Vermutlich ist das so beabsichtigt, ich würde Dich aber bitten, das sehr genau durchzugehen und zu prüfen, ob die Transitions so alle richtig sind.

Ansonsten gibt es noch Transitions von einer Zwischenseite auf eine andere. Das ist vielleicht nicht so schön aber zu verschmerzen.

**Comment by andreaschu** [comment]
Und hier noch die Transition-Auswertungen für die einzelnen QMLs.
Bei questionnaire1 hat sehr überschauliche Bedingungen. Questionnaire9 hat nur Zwischenseiten. Deswegen gibt es für die beiden keine Auswertungen.

[distance_questionnaire2.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960624/distance_questionnaire2.xlsx)
[distance_questionnaire3.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960625/distance_questionnaire3.xlsx)
[distance_questionnaire4.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960626/distance_questionnaire4.xlsx)
[distance_questionnaire5.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960627/distance_questionnaire5.xlsx)
[distance_questionnaire6.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960628/distance_questionnaire6.xlsx)
[distance_questionnaire7.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960629/distance_questionnaire7.xlsx)
[distance_questionnaire12.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960630/distance_questionnaire12.xlsx)
[distance_questionnaire13.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960631/distance_questionnaire13.xlsx)
[distance_questionnaire14.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960632/distance_questionnaire14.xlsx)
[distance_questionnaire15.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960633/distance_questionnaire15.xlsx)
[distance_questionnaire16.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960634/distance_questionnaire16.xlsx)
[distance_questionnaire17.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960635/distance_questionnaire17.xlsx)
[distance_questionnaire18.xlsx](https://github.com/dzhw/SLC-IntEr/files/3960636/distance_questionnaire18.xlsx)

**Comment by andreaschu** [comment]
Hier könnt Ihr euch den [Screenshot](http://10.4.110.53/andrea/SCL_IntEr_screenshots.zip) runterladen.

**Comment by andreaschu** [comment]
Es gibt jetzt nur noch die eine Fehlermeldung. @dzhwmeisner und ich gehen von einer 'Hypersensibilität' des Tests aus. Ich werde die Funktionalität der Transition noch mal händisch testen.

[Fehlerbericht_syntaktischeFehler2.xlsx](https://github.com/dzhw/SLC-IntEr/files/3961579/Fehlerbericht_syntaktischeFehler2.xlsx)

**Comment by woisch** [comment]
Schaue gerade noch über die Screenshots.
Sowas braucht mich zu beunruhigen, oder? Das ist ne Seite mit Einblendbedingungen für Items:
[cid:image001.png@01D5B1DB.D5C06E50]

Von: andreaschu [mailto:notifications@github.com]
Gesendet: Freitag, 13. Dezember 2019 16:17
An: dzhw/SLC-IntEr
Cc: Woisch, Andreas; Comment
Betreff: Re: [dzhw/SLC-IntEr] Simulation / Lasttest (#185)


Hier könnt Ihr euch den Screenshot<http://10.4.110.53/andrea/SCL_IntEr_screenshots.zip> runterladen.

**Comment by jocarstensen** [comment]
Kannst du das irgendwie richtig einfügen? So kann ich nicht drauf zugreifen.

**Comment by woisch** [comment]
sorry, da ging was schief:

![grafik](https://user-images.githubusercontent.com/53002476/70818441-02795600-1dd4-11ea-9e37-c5d9aa2a329c.png)

**Comment by andreaschu** [comment]
Das sind einblendbedingungen, die im Screenshot eingefügt werden. Nein, braucht Dich nicht zu beunruhigen.

**Comment by woisch** [comment]
okay, alles klar!

**Comment by andreaschu** [comment]
multiple time used variables (die nicht h_-Variablen oder flags sind)

- [ ] sezz05
- [ ] se*a05
- [x] i*a18
- [x] i*a19
- [ ] em*a05
- [ ] em0008

**Comment by jocarstensen** [comment]
Danke, haben wir uns auch gerade schon gebaut. Die passen alle. Allerdings haben wir uns gerade gefragt, ob nicht width2 auch zweimal vorhanden sein sollte. @se-lang

**Comment by jocarstensen** [comment]
Alles erledigt
