### ISSUE TITLE
beg_05/beg_06/beg_07 Antwortlabels Zeilenumbruch

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#186]
Könnt Ihr in das erste Label noch einen Umbruch einbauen, so dass es umbricht wie das fünfte? (Also Text obere Zeile, Zahl untere)
![grafik](https://user-images.githubusercontent.com/35771616/70461340-c1720080-1ab8-11ea-8c3b-4cff4ce672f9.png)

**Comment by dzhwmeisner** [comment]
erledigt. Im nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner: Leider fehlten nach deinen Anpassungen die Leerzeichen zwischen Label und Zahl. Habe gestern die Leerzeichen eingefügt und nun klappt der Umbruch nicht mehr :( 
Kannst du hier noch mal drauf schauen?

**Comment by woisch** [comment]
Der Umbruch passt jetzt auf allen 3 Seiten
