### ISSUE TITLE
Modul Studium: akad. Integration gesplittet

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#187]
Seite stu_10 in stu_10 und stu_11 gesplittet (stu_11 gab es vorher nicht)

- [x] stu_10 Variablenliste, Items und Transition entsprechend angepasst

- [x] stu_11: gänzlich neu (bzw. eben der zweite Teil aus stu_10)

https://github.com/dzhw/SLC-IntEr/commit/070e141b1fff88506cfa7ca6c4880a688a662f28

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.
