### ISSUE TITLE
Header und footer

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#188]
Ahoi,

1. da wir den Fortschrittsbalken aus Zeitgründen wohl nicht mehr im Header unterbringen (Programmierung ist aufwendig), könnten wir dort als eine Art durchgehenden identifier das Bild future present past unterbringen. Ist dann nicht so trist der header, wäre aber dann auf allen Seiten sichtbar. Ich würde es zumindest gern mal sehen. Meinungen?
2. Im footer steht noch gmbh. Ich würde das gerne weg lassen, ist überflüssig und verwirrend, ihr wisst was ich meine....

**Comment by woisch** [comment]
1. Wenn zeit ist können wir uns das ansehen. 
2. GmbH könnte meinetwegen weg.

**Comment by jocarstensen** [comment]
1. Absolute Zustimmung
2. Bin nicht ganz sicher, ob wir das weglassen dürfen. Wen könnte man da fragen?

**Comment by woisch** [comment]
zu 2) Hat für mich aber wirklich niedrige Prio. Wenn wir das noch im Haus diskutieren müssen (wie bei den Anschreiben), würde ich es lieber so lassen.

**Comment by jocarstensen** [comment]
zu 2) Können wir glaube ich einfach machen. Caro Trapp hat da nicht widersprochen, als ich sie gestern drauf angesprochen habe.

**Comment by woisch** [comment]
1) hat sich jetzt glaube ich erledigt, nach dem was wir eben besprochen haben.

2) können wir meinetwegen umsetzen lassen, wenn es Konsens ist.

**Comment by jocarstensen** [comment]
1) genau, lassen wir
2) ist umgesetzt

**Comment by SilinaKowalewski** [comment]
> 2\. ist umgesetzt

Ist nun auch auf beiden Addon-Befragungen umgesetzt und ausgerollt.

**Comment by woisch** [comment]
Der footer ist jetzt überall umgesetzt (auch in der AddOn).

Ist es OK, dass man in die AddOn-Befragung nicht reinkommt gerade mit den tester-tokens?
Wenn ja, dann kann hier zu.

**Comment by SilinaKowalewski** [comment]
@woisch: Also bei mir klappt alles. Habe beide AddOns mit verschiedenen Tester-Token getestet

**Comment by woisch** [comment]
okay, die tester<100 gehen bei mir auch. tester222 zB nicht. Sind da vielleicht nicht alle tokens zugeordnet?

**Comment by SilinaKowalewski** [comment]
Ja, das kann gut sein. 500 Tester wären hier ja auch nicht nötig. Dann ist aber alles richtig so wie es ist :)

**Comment by woisch** [comment]
okay, dann zu
