### ISSUE TITLE
Testbefragung nicht erreichbar

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#189]
Die Testbefragung ist nicht mehr verfügbar (https://presentation.dzhw.eu/SCL_IntEr_Test). Fehler 404.

**Comment by SilinaKowalewski** [comment]
Der nächtliche Roll-Out war wieder gecrasht. Sollte nun aber wieder funktionieren.

**Comment by woisch** [comment]
läuft wieder
