### ISSUE TITLE
Modul Studium: Layout

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#190]
- [x] stu_16: Text fett und das Wort "Hinweis:" davorsetzen (wie in PV vorgegeben)

- [x] mas_09: Hier sollen nur 2 Zahlen eingetragen werden. Die Textfelder bitte entsprechend etwas schmaler. 
- [x] mas_09: Könnte man die Kästchen vom 2. und 3. Item auf eine Höhe bekommen, auf Höhe des 2. Items? Dafür könnte auch das Item 3 umbrechen im Text (nach "Musikhochschule")

**Comment by dzhwmeisner** [comment]
> mas_09: Hier sollen nur 2 Zahlen eingetragen werden. Die Textfelder bitte entsprechend etwas schmaler.


erledigt. Im nächsten Rollout verfügbar

>  mas_09: Könnte man die Kästchen vom 2. und 3. Item auf eine Höhe bekommen, auf Höhe des 2. Items? Dafür könnte auch das Item 3 umbrechen im Text (nach "Musikhochschule")

erledigt. Im nächsten Rollout verfügbar

**Comment by christian-fr** [comment]
Erledigt. Im nächsten Rollout verfügbar.

**Comment by woisch** [comment]
Passt so!
