### ISSUE TITLE
Allgemein: Kann man in Karussell die Navigation über die Zahlen oben ausschalten?

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#191]
Also die Zahlen noch einblenden, aber bei Klick/Berührung nicht zum entspr. Item springen?

**Comment by SilinaKowalewski** [comment]
Das wäre leider sehr zeitaufwendig und daher vermutlich bis zum Feldstart nicht mehr lösbar.

**Comment by woisch** [comment]
@jocarstensen wollen wir das dann schließen hier?

**Comment by jocarstensen** [comment]
ja
