### ISSUE TITLE
last issues: Logoutbutton rausnehmen / Add-On-Link anpassen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#192]
Bitte kurz vor Feldstart den Logoutbutton rausnehmen.

**Comment by andreaschu** [comment]
der Link zur Add-On muss noch auf den richtigen Link angepasst werden (auf den Endseiten)

**Comment by andreaschu** [comment]
pretest-Kommentarfelder rausnehmen

**Comment by woisch** [comment]
Im Browser wird der Name der Befragung aus dem Zugangslink (spanel) angezeigt, was ein etwas unschönes Wort ist. 
Wenn möglich, hätten wir hier gerne "Studienberechtigtenbefragung" stehen. 

![grafik](https://user-images.githubusercontent.com/53002476/70804616-35f9b780-1db7-11ea-94f3-79dcb35001e9.png)

**Comment by andreaschu** [comment]
override navigation deaktivieren

**Comment by SilinaKowalewski** [comment]
Cohort1 = spanel-addon-154

Cohort2 = spanel-addon-183

**Comment by SilinaKowalewski** [comment]
> Im Browser wird der Name der Befragung aus dem Zugangslink (spanel) angezeigt, was ein etwas unschönes Wort ist. Kann man diese Anzeige ändern, ohne den Befragungsnamen zu ändern? (das geht natürlich nicht mehr zum jetzigen Zeitpunkt).
> Wenn möglich, hätten wir hier gerne "Studienberechtigtenbefragung" stehen.
> 


Es erscheint nun "Studienberechtigtenbefragung" als Name im Reiter der Befragung. 
@vdick. Du kannst die Addons also nun ausrollen.

**Comment by woisch** [comment]
Logout Button ist noch drin. Wann kommt der raus?

**Comment by jocarstensen** [comment]
Bisher ist noch Navigation über URL möglich. Das sollte auch noch ausgeschaltet werden.

**Comment by andreaschu** [comment]
@jocarstensen in die live-Befragung ist es raus.

**Comment by dzhwmeisner** [comment]
Logout-Button ist raus.
PDFs sind drin.

**Comment by woisch** [comment]
> 
> 
> Logout-Button ist raus.
> PDFs sind drin.

Passt beides! Danke!
