### ISSUE TITLE
Bitte offer-Seite rausnehmen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#193]
Hintergrund: Die Befragung ist fast ausschließlich im Portraitmodus besser zu beantworten. Für das Kalendarium nehmen wir den Hinweis in die Erklärseite auf.

**Comment by SilinaKowalewski** [comment]
Habe die offer-Seite raus genommen und die Transitions angepasst. Sobald die Befragung wieder auf dem Server läuft, können die Änderungen getestet werden.

**Comment by woisch** [comment]
hab mit jeweils einem tester für cohort1 und cohort2 am mobile getestet, bekomme keine offer Seite mehr und lande wie gewünscht auf beg_00
