### ISSUE TITLE
Änderungen an Datumsseiten - Sammelthread

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#194]
Auf den folgenden Seiten müssen noch einige Anpassungen gemacht werden.
- [x] Die Instruction geändert werden. "#{layout.BREAK}Wir nteressieren uns auch für Tätigkeiten, die vor #{h_enterdatum.value} begonnen haben und zu dem Zeitpunkt noch andauerten. Unsere Nachfragen beziehen sich in diesem Fall aber nur auf den Zeitraum seit {h_enterdatum.value}." bitte ersetzen durch "#{layout.BREAK}Wir nteressieren uns auch für Tätigkeiten, die vor #{h_enterdatum.value} begonnen haben und zu dem Zeitpunkt noch andauerten. Machen Sie für diese Tätigkeiten bitte Angaben ab #{h_enterdatum.value}."

- [ ] Bitte "von", "bis", "beginn vor..." und "dauert noch an" (sofern auf den jeweiligen Seiten vorhanden) größer formatieren

- [x] Bitte "von", "bis", "beginn vor..." und "dauert noch an" (sofern auf den jeweiligen Seiten vorhanden) fett formatieren

Liste der zu bearbeitenden Seiten:
- [x] emaa01, emba01, emca01, emda01, emea01, emfa01, em0004
- [x] taa01, tba01, tca01, tda01, tea01
- [x] seaa01, seba01, seca01, seda01, seea01, sezz01
- [x] vaa01, vba01, vca01, vda01, vea01, vza01
- [x] oaa01, oab01, oca01, oda01, odb01, oea01, oeb01
- [x] scaa02, scab02, scac02, scad02, scae02, scaz02
- [x] uaa01, uba01, uca01, uda01
- [x] staa01, stba01, stca01, stda01, stea01, st0005
- [x] iaa01, iba01, ica01, ida01, iea01, iza01

@jocarstensen bitte ergänzen, falls ich Seiten übersehen habe. Außerdem wollten wir ja noch mehr direkt zusammen ändern lassen.

**Comment by jocarstensen** [comment]
Auch auf all diesen Seiten: 
Bitte die Präfixe "von" und "bis" fett und zwei Schriftgrößen größer formatieren.

**Comment by jocarstensen** [comment]
Auf den Seiten seaa01, seba01, seca01, seda01, seea01, sezz01 steht bisher auch noch "Beginndatum" und "Enddatum" als Präfix. Hier bitte zu "von" und "bis" vereinheitlichen.

**Comment by christian-fr** [comment]
Instruction geändert bei:
- emaa01, emba01, emca01, emda01, emea01, emfa01, em0004


"von", "bis", "beginn vor..." und "dauert noch an" geändert bei:
- emaa01, emba01, emca01, emda01, emea01, emfa01, em0004

**Comment by SilinaKowalewski** [comment]
@vdick: 

Ist es umsetzbar jeweils "von", "bis",  "beginn vor..." und "dauert noch an" zwei Schriftarten größer zu formatieren?

**Comment by christian-fr** [comment]
Die page vzz01 gibt es nicht, es gibt nur vza01 - dort wurde es geändert.

**Comment by jocarstensen** [comment]
@christian-fr vza01 ist natürlich korrekt, danke.

**Comment by christian-fr** [comment]
Alle oben genannten pages wurden entsprechend angepasst.

Ab nächstem Rollout verfügbar.

**Comment by se-lang** [comment]
Danke, passt alles! Ich mach ich dann zu

**Comment by woisch** [comment]
@se-lang: Viktor arbeitet hier scheinbar gerade an etwas und rief mich eben an. Nimm mal Kontakt zu ihm auf, um das zu klären am besten (Viktor ist telefonisch am Platz erreichbar grad)

**Comment by jocarstensen** [comment]
@se-lang @woisch mache ich

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
Stichprobenartig scheint alle gut zu sein. Danke!

Bei nsET fehlten noch Doppelpunkte, die habe ich hinzugefügt. Ab nächstem Rollout verfügbar.
