### ISSUE TITLE
HLs nur im Epimodul

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#195]
Headlines sollten nur im Epimodul verwendet werden. Falls Euch irgendwoanders noch HLs auffallen, bitte rausnehmen.

(Das müsst Ihr nicht systematisch durchgehen, aber falls Ihr irgendwo noch eine HL seht, die da nicht hingehört, könnt Ihr sie einfach rausnehmen.)

**Comment by andreaschu** [comment]
Wir suchen sie und werfen sie raus.

**Comment by jocarstensen** [comment]
Das betrachte ich jetzt mal als geklärt.
