### ISSUE TITLE
Update Modul SozDem: msg_03

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#197]
auf msg_03 den fragetyp ändern auf "Einfachauswahl (vertikal) + offene Angaben", sodass immer nur eine Angabe möglich ist (entweder PLZ oder Land). Außerdem eine Infield Einblendung bei ao2 ("Land")

also von der Funktionalität des Fragetyps so wie zB seaa17:
![grafik](https://user-images.githubusercontent.com/53002476/70602521-ea97ab80-1bf4-11ea-9b26-682f1d68d47e.png)

https://github.com/dzhw/SLC-IntEr/commit/e807e1af1dccdd2c40bc4d9f1639165fae8dfe74

**Comment by woisch** [comment]
Folgende weitere Änderungen hierzu noch (am besten alles zusammen bearbeiten mit der Änderung oben!)

- [ ] Transitions geändert auf msg_02, msg_2a, msg_03

- [ ] Variablennamen angepasst auf msg_03

- [ ] neue Seite eingefügt: msg_03a. Die Gestaltung der Seite msg_3a sollte sich an den Ortsabfragen im Episodenmodul orientieren (z.B. seaa16, siehe Screenshot oben). Wie im Epimodul hier auch die Infield-Einblendungen machen. Steht alles auch nochmal unter "hi".

https://github.com/dzhw/SLC-IntEr/commit/f71b6ac4ce2c2c8bd6a7945d5cd852ea237d1128

Bei Fragen einfach melden!

**Comment by SilinaKowalewski** [comment]
für msg_03 fehlt leider noch eine Variable..quasi für die SingleChoice

**Comment by woisch** [comment]
ups, ja das macht Sinn. Danke !
habe ich ergänzt für msg_03 (wohn_154) und für msg_3a (wohn_183).

https://github.com/dzhw/SLC-IntEr/commit/85e0892cdfdc6ec35522c679a35c464f515ce9d1

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt und ausgerollt. Bitte prüfen.

**Comment by woisch** [comment]
msg_02: Hier stimmt was mit den Transitions für cohort 1 nicht. Wenn ich mit cohort=1 auf msg_02 ein Missing habe oder wenn wohnelt==1, sollte ich zu msg_03 kommen, momentan komme aber ich zu msg_03a.
Bei cohort2 klappt alles wie es soll.

msg_03: 
- [ ] Bei der PLZ soll diese Prüfung des Wertebereichs für die variable plz_154 rein: maxLength="5" maxValue="99999" minValue="1000". (Kann sein dass der drin ist und sich auf den alten Varname bezieht? Momentan kann ich jedenfalls zwar nur 5 stellen eingeben, aber auch Buchstaben und kriege keine Fehlermeldung)

msg_03a: Auch hier ist die Prüfung des Wertebereichs bei der PLZ nicht umgesetzt

**Comment by jocarstensen** [comment]
- [ ] Auf msg_03a brauchen wir noch die Infields der Präfixe

**Comment by SilinaKowalewski** [comment]
@vdick: Kannst du bitte für msg_03 und msg_03a  die Textfelder noch mal zusammen rücken?

**Comment by woisch** [comment]
Die Transitions funktionieren jetzt für beide cohorten korrekt!

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue dann zu? Sebastian hat ja #211 erstellt
