### ISSUE TITLE
stu_20: Einblendung Studiengänge

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#198]
Wenn ich keinen Studiengang und kein Fach angebe, sieht es bei mir so aus:

![grafik](https://user-images.githubusercontent.com/35771616/70602835-94773800-1bf5-11ea-9260-486ee5f08ba5.png)

Haben wir keine Condition für alles Missing?

**Comment by jocarstensen** [comment]
Ok, jetzt verstehe ich. Man soll den Studiengang und auf stu_21 das Fach eintragen, wenn man vorher nichts angegeben hat. Das ist aber nicht besonders leicht ersichtlich. Zumal stu_20 sehr voll mit Instructions ist. Auf stu_21 hingegen gibt es gar keine Instructions mehr.
Aus meiner Sicht sollte man:
- Die Anweisungen auf stu_20 vereinfachen (evtl. visible conditions für Missing und Einblendungen aus dem Studienmodul)
- Eine kurze Wiederholung der Anweisungen (mindestens "Bitte geben Sie das Studienfach an, auf das Sie Ihre Angaben beziehen wollen") auf stu_21.

@woisch @heikQ  Was meint Ihr?

**Comment by woisch** [comment]
-  stu_20: hier vielleicht mit vc arbeiten, ja. Stelle mir das grade so vor, dass man den ganzen letzten Teil des Hinweistextes (Aus diesem Grund bitten wir Sie, den Studiengang und das Haupt- bzw. Unterrichtsfach auszuwählen, auf das Sie Ihre Angaben bei den nächsten Fragen beziehen möchten. Falls Sie aktuell nur einen Studiengang und ein Haupt- bzw. Unterrichtsfach studieren, wählen Sie diese bitte aus der Liste aus bzw. tragen Sie sie in die offenen Antwortfelder ein. ) nur für Personen einblendet, die Angaben beim Studiengang haben. Alle Missing Leute kriegen dann nur einen Alternativtext ("Bitte geben Sie den Studiengang bzw. das Haupt- bzw. Unterrichtsfach an, auf das Sie Ihre Angaben bei den nächsten Fragen beziehen möchten")

- stu_21: Auf jeden Fall einen Text ergänzen, dein Vorschlag wäre OK als Minimallösung!

**Comment by heikQ** [comment]
Müssen das eigentlich zwei Seiten sein? Bekommt man das nicht zunächst hin, dass er nur eine ist, auf der:
- Studiengang und wenn angegeben auch Fächer angezeigt werden
- Wenn nur Studieigang angewgeben wurde, nur dieser angezeigt wird
- Bei Missing für Studiengang und Fächern nochmal gefragt wird, auf welchen Studiengang es sich bezieht, dann hätten wir auch einen mehrwert für Missings.
Wahrscheinlich recht schwer zu basteln auch mit den einblendungen oder?

**Comment by jocarstensen** [comment]
Wenn ich mich nicht komplett irre, dürfte es nicht so schwer sein, das auf eine Seite zu bauen. Könnte aber sehr voll werden, wenn die Leute viele Studiengänge/-fächer angegeben haben. Vielleicht ist das auch der Grund, dass es aktuell auf zwei Seiten ist.

**Comment by woisch** [comment]
@jocarstensen @heikQ Kann jetzt zu, oder? Die Fragen sind ja jetzt raus..

**Comment by jocarstensen** [comment]
Japp, ist raus, kann zu.

**Comment by heikQ** [comment]
?ja zu

________________________________
Von: woisch <notifications@github.com>
Gesendet: Mittwoch, 11. Dezember 2019 18:27
An: dzhw/SLC-IntEr
Cc: Quast, Heiko; Mention
Betreff: Re: [dzhw/SLC-IntEr] stu_20: Einblendung Studiengänge (#198)


@jocarstensen<https://github.com/jocarstensen> @heikQ<https://github.com/heikQ> Kann jetzt zu, oder? Die Fragen sind ja jetzt raus..

-
