### ISSUE TITLE
stu_91: evtl. "weiß nicht" hinzufügen?

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#199]
![grafik](https://user-images.githubusercontent.com/35771616/70603392-c2a94780-1bf6-11ea-9c7c-c02cca478f36.png)

**Comment by woisch** [comment]
ist hier bewusst nicht drin das "weiß nicht", bieten wir bisher in den Papierbefragungen auch nicht an, um die Leute nicht dazu zu verleiten und wenigstens eine ungefähre Richtung zu bekommen, wann das Studium ansteht.

**Comment by jocarstensen** [comment]
Ok. Ich war nur irritiert, dass ich bei "eventuell" dann eine monatsgenaue Angabe machen soll. Aber wenn das Absicht ist, mache ich hier wieder zu.
