### ISSUE TITLE
beg_12: layout 

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#2]
css needs to be adjusted a bit. 

![image](https://user-images.githubusercontent.com/48087320/65749015-8725d380-e105-11e9-8e23-5f49c04caab0.png)

**Comment by vdick** [comment]
fixed, nach nächstem Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Hat geklappt! Danke 🥇
