### ISSUE TITLE
Preloads vs. errechnete Variablen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#20]
@all
Wir haben im [Wiki ](https://github.com/dzhw/SLC-IntEr/wiki#steuerungs--und-hilfsvariablen )die Steuerungs- und Hilfsvariablen dokumentiert. 
Werden alle Variablen während der Befragung erzeugt, oder gibt es darunter auch Preloads, wie _cohort_? Da sie anders eingebaut werden müssen, sollten wir Preloads von erzeugten Hilfsvariablen unterscheiden.

**Comment by jocarstensen** [comment]
Cohort ist der einzige Preload, alle anderen HV werden im Projekt gebildet.

**Comment by jocarstensen** [comment]
Gegenfrage: Wann werden aktuell die Zufallszahlen neu gebildet? Meine SHK hatte beim Testen ein merkwürdiges Verhalten, wenn sie hin und her ging. Da waren Fragen nicht mehr erreichbar, die sie vorher bereits beantwortet hatte. Auf den Seiten, auf denen sie hängengeblieben ist, waren nur Transitions mit Cohort. Tester war 105.

**Comment by andreaschu** [comment]
okay, danke. Könnte jemand diese Tabelle mit Werten füllen, damit wir zum gegebenen Zeitpunkt die Preloads zum Testen einbauen können?
[tester_preloads.xlsx](https://github.com/dzhw/SLC-IntEr/files/3756630/tester_preloads.xlsx)

@jocarstensen im Moment werden sie jedes mal neu gesetzt, wenn man die Index-Seite verlässt. Sie werden auf Seite _msg_01_ angezeigt.

**Comment by jocarstensen** [comment]
[tester_preloads.xlsx](https://github.com/dzhw/SLC-IntEr/files/3756938/tester_preloads.xlsx)
So?

**Comment by jocarstensen** [comment]
Ich habe gerade im Gespräch mit Silina noch einmal konkretisiert: Cohort ist der einzige Preload. Alle im Wiki gelisteten HV sind allerdings modulübergreifend. Wir brauchen sie also trotzdem noch so lange zum Testen, bis die gesamte Befragung zusammenhängend programmiert ist.
