### ISSUE TITLE
SF-Text ändern: se**06

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#200]
Bitte auf seaa06/seab06/seac06/sead06/seae06/seba06/sebb06/sebc06/sebd06/seca06/secb06/secc06/seda06/sedb06/seea06 den SF-Text ändern in:

Für den weiteren Fragebogenverlauf und die Auswertung der Daten ist es wichtig, dass Sie die Frage**n** beantworten.

**Comment by christian-fr** [comment]
Geändert auf den folgenden Pages:

- seaa06, seab06, seac06, sead06, seae06, seba06, sebb06, sebc06, sebd06, seca06, secb06, secc06, seda06, sedb06, seea06

Nicht in der Liste oben aufgeführt, aber auch geändert: 

- sezz06


Ab nächstem Rollout verfügbar.

**Comment by jocarstensen** [comment]
Danke, sezz06 war natürlich auch richtig.

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und ausgerollt.

**Comment by SilinaKowalewski** [comment]
Muss hier noch was geändert werden oder passt alles?

**Comment by jocarstensen** [comment]
Auf sezz06 bitte die SF unter die zweite Frage setzen.

**Comment by SilinaKowalewski** [comment]
SF wurde verschoben.

**Comment by woisch** [comment]
auf sezz06 ist der SF jetzt unter der 2. Frage

**Comment by woisch** [comment]
mache hier mal zu
