### ISSUE TITLE
se**06: ao überschneiden sich

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#201]
Bei sehr kleinen Seitenbreiten überschneiden sich die ao von se**07

EDIT: Gilt für die Seiten: seaa06/seab06/seac06/sead06/seae06/seba06/sebb06/sebc06/sebd06/seca06/secb06/secc06/seda06/sedb06/seea06/sezz06

![grafik](https://user-images.githubusercontent.com/35771616/70615210-4a4d8100-1c0c-11ea-8cc8-3eb6b869c60e.png)

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
Habe alle o.g. Seiten getestet und es sieht jetzt überall gut aus (ohne Überschneidungen)
