### ISSUE TITLE
nsET: Sackgasse emab13

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#202]
mit neuem Tester (tester458), auf internem Testserver: wenn ich nur erwerbstätig bin und einmal meine berufliche Stellung ändere, und dann bei der Nachfrage, ob sich meine berufliche Stellung nochmals geändert hat (Daten: zwischen Sep 19 und Dez 19) "nein" antworte, dann komme ich nicht weiter!
Mit "ja" geht es weiter.

**Comment by woisch** [comment]
Bei mir das selbe Problem

**Comment by bafranke** [comment]
bei der nächsten Runde (emac13) komme ich aber mit "nein" weiter

**Comment by SilinaKowalewski** [comment]
@bafranke @woisch: Bitte testet noch mal ob das Problem weiterhin auftritt.

**Comment by woisch** [comment]
hänge in dem Szenario jetzt nicht mehr fest auf emab13, sondern komme zu emaa42, die wiederum noch nen Break im Text hat aussieht (das ist vermutlich wiederum das Problem mit der Leerzeile?):
![grafik](https://user-images.githubusercontent.com/53002476/70637964-6109cd00-1c38-11ea-908b-f91a66fefb7d.png)

**Comment by se-lang** [comment]
Top
@SilinaKowalewski vor den `{layout.BREAK}` hab ich ein # eingefügt
Da es dafür eigentlich noch einen anderen Issue gibt und dieser gelöst ist, mach ich hier zu.
