### ISSUE TITLE
end: Feld für Kommentare/Anregungen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#203]
Wir hätten auf der Endseite gern noch ein Kommentarfeld. Bitte mit folgendem Text: "Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:"

Das Textfeld sollte ein offener String sein und möglichst viele Zeichen fasst. Von der Optik her gern die Größe der Pretester-Kommentarfelder.

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Kannst du mir hierfür bitte noch einen Variablennamen nennen?

**Comment by jocarstensen** [comment]
@woisch @heikQ Wie hieß die Variable in früheren Erhebungen?

**Comment by woisch** [comment]
in 15.3: "anmerk"

würde ich auch wieder so machen.

**Comment by jocarstensen** [comment]
@SilinaKowalewski Also bitte "anmerk"

**Comment by woisch** [comment]
Ist drin und ok aus meiner Sicht!

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue zu? Haben ja #209
