### ISSUE TITLE
Zwischenseiten: Anleitung Kalendarium und GIFs

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#204]
Für die Anleitung für das Kalendarium habt ihr ja bereits 4 Zwischenseiten (cal0001-cal0004) angelegt, momentan noch mit einem Platzhalter-Text. Jede Kohorte hat 2 verschiedene Zwischenseiten (eine Desktop-Version und eine für mobile Endgeräte).

Auf diesen 4 Seiten soll jeweils ein Text sowie ein GIF erscheinen. Die Texte für die 4 Seiten könnt ihr schon einbauen, die GIFs erstellen wir gerade und liefern die nach.

Hier die Texte:

Cohort=1, mobile Endgeräte (cal0001)
Um Ihren Werdegang besser verstehen zu können, geben Sie uns bitte im Kalender auf der folgenden Seite an, welche Aktivitäten Sie zwischen Januar 2018 und Dezember 2019 ausgeübt haben. Machen Sie nach Möglichkeit in jedem Monat mindestens eine Angabe. Sie können auch mehrere Aktivitäten parallel angeben. Für eine optimale Darstellung dieser Frage sollten Sie das Display drehen.
Und so funktioniert das Ausfüllen:

Cohort=2, mobile Endgeräte (cal0003)
Um Ihren Werdegang besser verstehen zu können, geben Sie uns bitte im Kalender auf der folgenden Seite an, welche Aktivitäten Sie zwischen Juli 2018 und Dezember 2019 ausgeübt haben. Machen Sie nach Möglichkeit in jedem Monat mindestens eine Angabe. Sie können auch mehrere Aktivitäten parallel angeben. Für eine optimale Darstellung dieser Frage sollten Sie das Display drehen.
Und so funktioniert das Ausfüllen:

Cohort=1, Desktop-Version (cal0002)
Um Ihren Werdegang besser verstehen zu können, geben Sie uns bitte im Kalender auf der folgenden Seite an, welche Aktivitäten Sie zwischen Januar 2018 und Dezember 2019 ausgeübt haben. Machen Sie nach Möglichkeit in jedem Monat mindestens eine Angabe. Sie können auch mehrere Aktivitäten parallel angeben.
Und so funktioniert das Ausfüllen:

Cohort=2, Desktop-Version (cal0004)
Um Ihren Werdegang besser verstehen zu können, geben Sie uns bitte im Kalender auf der folgenden Seite an, welche Aktivitäten Sie zwischen Juli 2018 und Dezember 2019 ausgeübt haben. Machen Sie nach Möglichkeit in jedem Monat mindestens eine Angabe. Sie können auch mehrere Aktivitäten parallel angeben.
Und so funktioniert das Ausfüllen:

**Comment by woisch** [comment]
@SilinaKowalewski 
Kannst du auf der Anleitungsseite cal0001 testweise mal dieses GIF umsetzen?

![c1d_new](https://user-images.githubusercontent.com/53002476/70695284-a9210200-1cc1-11ea-8e43-5b349fd083c1.gif)


Das GIF sollte nicht über die ganze Bildschirmbreite angezeigt werden (ist sehr pixelig). Kannst du das so machen wie auf der Endseite, dass es sich mitskaliert und zB höchstens über 60% der Bildschirmbreite geht?

**Comment by woisch** [comment]
Kannst du dann dieses GIF auch mal auf cal0004 umsetzen? (zum 
![c1d_new2_720](https://user-images.githubusercontent.com/53002476/70695907-ef2a9580-1cc2-11ea-89eb-3c4087cd2013.gif)
Vergleich)

**Comment by woisch** [comment]
Bitte die folgenden GIFS umsetzen für die Desktopversion jeweils:

cal0002: 
![c1_desktop_720](https://user-images.githubusercontent.com/53002476/70702472-6dd90000-1cce-11ea-91a4-965fa365dfa9.gif)

cal0004:
![c2_desktop_720-2](https://user-images.githubusercontent.com/53002476/70702480-73364a80-1cce-11ea-924f-467b3583cd14.gif)

**Comment by SilinaKowalewski** [comment]
> * Bitte für den Text eine größere Schrift bei den Anleitungsseiten für die Kalendarien (alle Versionen). Gleiche Schrift wie bei den übrigen Fragen (größer und fett?). Den Passus "Und so funktioniert das Ausfüllen" ebenfalls die Frageschrift und eventuell grau und etwas vom Fragetext absetzen nach unten.

**Comment by SilinaKowalewski** [comment]
> Das GIF sollte nicht über die ganze Bildschirmbreite angezeigt werden (ist sehr pixelig). Kannst du das so machen wie auf der Endseite, dass es sich mitskaliert und zB höchstens über 60% der Bildschirmbreite geht?

@woisch: Habe nun die maximale Breite auf 60% des Bildschirms eingestellt. Schau bitte mal nach, ob das so für dich/euch passt.

**Comment by woisch** [comment]
> 
> 
> > Das GIF sollte nicht über die ganze Bildschirmbreite angezeigt werden (ist sehr pixelig). Kannst du das so machen wie auf der Endseite, dass es sich mitskaliert und zB höchstens über 60% der Bildschirmbreite geht?
> 
> @woisch: Habe nun die maximale Breite auf 60% des Bildschirms eingestellt. Schau bitte mal nach, ob das so für dich/euch passt.

kannst du gerne noch etwas kleiner machen auf 50%

**Comment by woisch** [comment]
folgendes GIF kommt auf cal0001 (hier bitte nicht auf 50% des Bildschirmsanpassen. in der mobilen Ansicht erstmal so normal reinsetzen und wir schauen ob es passt):
![c1-mobil_ob_480](https://user-images.githubusercontent.com/53002476/70721197-72fd7580-1cf5-11ea-8c03-d4aa46ee9f5c.gif)

**Comment by woisch** [comment]
Und hier noch das GIF für cal0003:
![c2- mobil_480](https://user-images.githubusercontent.com/53002476/70726583-9a0c7500-1cfe-11ea-82a1-e81e796efda2.gif)

**Comment by SilinaKowalewski** [comment]
Alle Gifs sind eingebaut.

**Comment by woisch** [comment]
Die GIFs müssen nochmal ausgetauscht werden auf allen 4 Seiten. Bei den beiden Desktop Versionen wollen wir die Begrenzung auf 60% Seitenbreite.
Bei den Mobilen bitte die GIFS möglichst groß machen. Da ist das GIF bisher zu klein (siehe unten). Optimalerweise sollte es in im Portraitmodus die ganze Seitenbreite ausfüllen (wie der Text):

![grafik](https://user-images.githubusercontent.com/53002476/70795255-af85ab80-1d9f-11ea-84b2-ef82a43d3b8b.png)



**Cohort=1, mobile Endgeräte (cal0001)**
![c1_mobil](https://user-images.githubusercontent.com/53002476/70795309-cd531080-1d9f-11ea-9e49-0256c717f8e9.gif)

**Cohort=1, Desktop-Version (cal0002)**
**_Auf 60% der Seitenbreite begrenzen_**
![c1_desktop_hq](https://user-images.githubusercontent.com/53002476/70795342-e5c32b00-1d9f-11ea-9d8f-d59f28e6ec56.gif)

**Cohort=2, mobile Endgeräte (cal0003)**
![c2_mobil](https://user-images.githubusercontent.com/53002476/70795354-ec51a280-1d9f-11ea-8b62-62717b39451e.gif)

**Cohort=2, Desktop-Version (cal0004)**
**_Auf 60% der Seitenbreite begrenzen_**
![c2-dekstop_hq](https://user-images.githubusercontent.com/53002476/70795369-f4114700-1d9f-11ea-8f74-dbd26aa747b9.gif)

**Comment by heikQ** [comment]
Außerdem bitte folegenden Notfall-Text hinterlegen, wenn ein gif nicht angezeigt/geladen werden, der aber nur angezeigt wird, wenn das Bild nicht geladen werden kann:
**Cohort=1, mobile Endgeräte (cal0001):**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch klicken oder Zeiträume durch klicken & ziehen markieren
4. Weitere (parallele) Aktivitäten Aktivitäten auswählen und eintragen
5. Blättern zwischen den Kalenderjahren über Buttons unten links und rechts

**Cohort=1, Desktop-Version (cal0002)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch klicken oder Zeiträume durch klicken & ziehen markieren
4. Weitere (parallele) Aktivitäten Aktivitäten auswählen und eintragen

**Cohort=2, mobile Endgeräte (cal0003)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch klicken oder Zeiträume durch klicken & ziehen markieren
4. Weitere (parallele) Aktivitäten Aktivitäten auswählen und eintragen
5. Blättern zwischen den Kalenderjahren über Buttons unten links und rechts

**Cohort=2, Desktop-Version (cal0004)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch klicken oder Zeiträume durch klicken & ziehen markieren
4. Weitere (parallele) Aktivitäten Aktivitäten auswählen und eintragen

**Comment by andreaschu** [comment]
Bilder sind eingebaut und können beim nächsten Rollout getestet werden.
Texte sind hinzugefügt und können beim übernächsten Rollout getestet werden.

**Comment by heikQ** [comment]
@SilinaKowalewski @andreaschu 
Sind zwar kurze Texte, habs trotdem geschafft, Fehler einzubauen, bitte nochmal austauschen mit folgenden und auch die hinterlegten Texte nochmal wie folgt ändern (kommt jeweils erst der Text, dann das entsprechende gif im Folgenden):

- [ ] **Cohort=1, mobile Endgeräte (cal0001):**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Zeiträume durch Antippen von Start- und Endmonat oder einzelne Monate durch 2x Antippen markieren
4. Weitere (parallele) Aktivitäten auswählen und eintragen
5. Blättern zwischen den Kalenderjahren über Buttons unten links und rechts

![c1-mobil](https://user-images.githubusercontent.com/52539440/70863891-4479d780-1f4d-11ea-81c1-97a97d3a146d.gif)

- [ ] **Cohort=1, Desktop-Version (cal0002)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch Klicken oder Zeiträume durch Klicken & Ziehen markieren
4. Weitere (parallele) Aktivitäten auswählen und eintragen

![c1-desktop_hq](https://user-images.githubusercontent.com/52539440/70863929-81de6500-1f4d-11ea-9eed-ea2247480d96.gif)

- [ ] **Cohort=2, mobile Endgeräte (cal0003)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Zeiträume durch Antippen von Start- und Endmonat oder einzelne Monate durch 2x Antippen markieren
4. Weitere (parallele) Aktivitäten auswählen und eintragen
5. Blättern zwischen den Kalenderjahren über Buttons unten links und rechts

![c2-mobil](https://user-images.githubusercontent.com/52539440/70863948-c4a03d00-1f4d-11ea-85d8-59ccf5028fee.gif)

- [ ] **Cohort=2, Desktop-Version (cal0004)**
1. "Aktivität" per Button über dem Kalender auswählen
2. Ausgeübte Aktivität anklicken
3. Einzelne Monate durch Klicken oder Zeiträume durch Klicken & Ziehen markieren
4. Weitere (parallele) Aktivitäten auswählen und eintragen

![c2-desktop_hq](https://user-images.githubusercontent.com/52539440/70863969-f0bbbe00-1f4d-11ea-8ac2-612d531fc548.gif)
