### ISSUE TITLE
Layout mobile Ansicht

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#205]
Leider gibt es bei einigen früheren Layout-Punkten auf den Seiten der loops und splits noch Probleme, die auf der ersten Seite bereits gelöst sind. Bitte hier nochmal für alle Unterseiten umsetzen:

- [x] em**12: Zeilen überlappen sich in der mobilen Ansicht/ auf schmalen Bildschirmen. gelöst bei emaa12, bitte noch ändern auf:

em0012 emab12 emac12 emad12 emae12 emaf12
emba12 embb12 embc12 embd12 embe12 
emca12 emcb12 emcc12 emcd12 
emda12 emdb12 emdc12 
emea12 emeb12 
emfa12
![grafik](https://user-images.githubusercontent.com/56022369/70691502-7f63dd00-1cb9-11ea-95a7-324ed8a41707.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
ist jetzt auf allen Seiten umgesetzt
