### ISSUE TITLE
Update Kalendarium 

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#206]
- [x] Bitte auf den beiden Kalendariumsseiten (cohort1Cal und cohort2Cal) eine Headline einfügen: Kalender der Aktivitäten

- [x] Auf beiden Kalendariumsseiten unter dem Kalendarium ein offenes Textfeld umsetzen (wie auf der Endseite) mit der Beschriftung: "weitere Kommentare/Anmerkungen:" Als offener String und möglichst viele Zeichen umfassend.

**Comment by heikQ** [comment]
- Bitte für den Text eine größere Schrift bei den Anleitungsseiten für die Kalendarien (alle Versionen). Gleiche Schrift wie bei den übrigen Fragen (größer und fett?). Den Passus "Und so funktioniert das Ausfüllen" ebenfalls die Frageschrift und eventuell grau und etwas vom Fragetext absetzen nach unten.

**Comment by SilinaKowalewski** [comment]
> * Bitte für den Text eine größere Schrift bei den Anleitungsseiten für die Kalendarien (alle Versionen). Gleiche Schrift wie bei den übrigen Fragen (größer und fett?). Den Passus "Und so funktioniert das Ausfüllen" ebenfalls die Frageschrift und eventuell grau und etwas vom Fragetext absetzen nach unten.

Kopiere dies mal in #204

**Comment by SilinaKowalewski** [comment]
> * Auf beiden Kalendariumsseiten unter dem Kalendarium ein offenes Textfeld umsetzen (wie auf der Endseite) mit der Beschriftung: "weitere Kommentare/Anmerkungen:" Als offener String und möglichst viele Zeichen umfassend.

Auch hier bräuchte ich Variablennamen ;) 
Nehme erstmal anmerkcal1 und anmerkcal2

**Comment by woisch** [comment]
anmerkcal1 und anmerkcal2 ist ok!

**Comment by woisch** [comment]
Könntet ihr zwischen der headline (Kalender der Aktivitäten) und dem Aktivitätsbutton noch etwas Abstand einbauen?

**Comment by bafranke** [comment]
@heikQ @woisch @se-lang @jocarstensen 
Aufgrund des Fortschrittsbalken, der Überschrift und den Abständen muss man mobil jetzt scrollen, um das Kalendarium überhaupt zu sehen:
![grafik](https://user-images.githubusercontent.com/56022369/70780452-324d3d00-1d85-11ea-975f-126920cf83aa.png)
Ich persönlich finde das sehr ungünstig und würde daher eher auf die Überschrift verzichten, damit wenigstens ein Teil des Kalendarium zu sehen ist. Was meint ihr?

**Comment by jocarstensen** [comment]
Sehe ich auch so

**Comment by woisch** [comment]
Dito. Überschrift raus. Dann auch für die Desktop Version, damit es einheitlich ist, oder?

**Comment by jocarstensen** [comment]
@woisch Ja

**Comment by woisch** [comment]
@SilinaKowalewski:
Bitte auf den beiden Kalendariumsseiten (cohort1Cal und cohort2Cal) die Headline wieder löschen!

**Comment by woisch** [comment]
Die Headlines sind immer noch drin.

**Comment by andreaschu** [comment]
Headlines gelöscht. Ich werfe gleich wieder einen Rollout an.

**Comment by woisch** [comment]
Headlines sind raus, danke! Aufm Mobile ist das Kalendarium bei mir jetzt auch ohne Scrollen zu sehen.

**Comment by woisch** [comment]
zwischen  "weitere Kommentare/Anmerkungen:" und dem Textfeld ist eine Leerzeile. Kriegt man die noch weg?
![grafik](https://user-images.githubusercontent.com/53002476/70855019-1f8d5200-1ec4-11ea-810e-c722f3c0c646.png)

**Comment by jocarstensen** [comment]
Momentan steht "weitere Kommentare/Anregungen" als instruction. Könnte man nicht einfach qt draus machen?

**Comment by woisch** [comment]
> 
> 
> Momentan steht "weitere Kommentare/Anregungen" als instruction. Könnte man nicht einfach qt draus machen?

Ist als q umgesetzt (besser so). Aber immer noch mit Leerzeile.

**Comment by SilinaKowalewski** [comment]
Die Formatierung als Questiontext hat auch keinerlei Einfluss auf den Abstand zum nächsten Objekt. Der Abstand müsste im css manuell entfernt werden und ist innerhalb der nächsten Stunde nicht umsetzbar.

**Comment by jocarstensen** [comment]
Ok, dann passt das jetzt so.
@woisch Sonst alles gut?

**Comment by woisch** [comment]
ja, dann lassen wir das so mit dem Abstand..
Der Rest hier ist umgesetzt.

**Comment by jocarstensen** [comment]
Dann mache ich mal zu
