### ISSUE TITLE
Layout Episodenmodul

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#207]
![grafik](https://user-images.githubusercontent.com/35341060/70699014-c4dbd680-1cc8-11ea-9c5b-e25154e5b3ff.png)
- [x] Können wir auf diesen Seiten jeweils den Umbruch bereits nach "deutlich" und "genau" haben? Dann wäre in der zweiten Zeile immer ein Wort und die jeweilige Zahl. Das sähe dann einheitlicher aus. Betrifft die Seiten emaa43, emba43, emca43, emda43, emea43, emfa43 und em0043

![grafik](https://user-images.githubusercontent.com/35341060/70699602-afb37780-1cc9-11ea-80a5-d545fee59b4f.png)
- [x] Hier bitte die Antwortkategorien noch etwas entzerren. Das ist leider nur schwer lesbar. Betrifft die Seiten staa24, stab24, stac24, stad24, stae24, stba24, stbb24, stbc24, stbd, stca24, stcb24, stcc24, stda24, stdb24, stea24, st0025

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by se-lang** [comment]
Viele besser, sieht super aus. Danke!
