### ISSUE TITLE
Aufblitzen riesiges DZHW bei Seitenwechsel

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#208]
Machmal blitzt bei einem Seitenwechsel für weniger als eine Sekunde ein riesiges DZHW Logo auf (wie bei so einem psychologischen/neurowissenschaftlichen Experimenten). Hab das schon sowohl auf Desktop als auch auf Mobile gehabt. Bei @bafranke tritt das auch auf.
Ist das bekannt und kann man das verhindern? Wirkt entweder buggy oder eben als hätten wir ein Experiment eingebaut.

**Comment by andreaschu** [comment]
ich habe mal die Bildgröße stark verkleinert. 
@SilinaKowalewski jetzt müsste die Skalierung wahrscheinlich angepasst werden. Falls es nicht geht, ist das Originalbild als Kopie im images-Ordner gespeichert.

**Comment by SilinaKowalewski** [comment]
Also bei mir sieht es jetzt okay aus. Aktuell blitzt bei mir nichts auf. 

@se-lang kannst du auch nochmal kurz testen?

**Comment by se-lang** [comment]
@SilinaKowalewski Kommt bei mir immernoch, allerdings hab ich gerade ein Muster erkannt: Auf (vermutlich) eher kleinen Seiten passiert es nicht oder ich nehm es zumindest nicht wahr. Auf Seiten wo noch andere Elemente geladen werden müssen, also die Zwischenseiten mit den Grafiken oder das Kalendarium, passiert es nach wie vor. Vielleicht hängt das damit zusammen?

**Comment by andreaschu** [comment]
@se-lang ich habe jetzt die Bildgröße verändert. Bitte noch mal beobachten.

**Comment by se-lang** [comment]
Das scheint auf jeden Fall der richtige Weg zu sein, das DZHW Logo sehe ich nicht mehr, jetzt blitzt das Symbol vom Logout-Button auf, aber der soll ja eh noch raus ;-)

**Comment by jocarstensen** [comment]
Vermutlich wird dann etwas anders aufbiltzen. Aber damit können wir glaube ich leben. Sobald der Logout-Button raus ist, möchte ich daran nicht mehr rumexperimentieren. Darum mache ich hier mal zu.
