### ISSUE TITLE
Endseiten umbauen

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#209]
Wir hätten gerne noch weitere Endseiten, und die Endseite bitte einmal umbauen:

**end**.html:
![grafik](https://user-images.githubusercontent.com/56022369/70701969-914f7b00-1ccd-11ea-8d49-bc51758c63db.png)
Bitte hier alles rausnehmen ab: "Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:" (inklusive Kommentarfeld)
Wenn möglich platziert den Weiter-Button auf dieser Seite bitte mittig.

Danach soll eine weitere end-Seite (**end2**) folgen, auf der der rausgenommene Teil von der vorherigen Seite steht:
![grafik](https://user-images.githubusercontent.com/56022369/70702373-3ec28e80-1cce-11ea-9fcb-8bb531f94f7e.png)
Anstatt des Weiter-Buttons soll hier "Absenden" stehen. Ein Zurück-Feld benötigen wir aber ebenfalls.

Als letztes folgt **end3**: 
Vielen Dank! Wir haben Ihre Anmerkungen erhalten. Hier bitte nur ein Zurück-Button.

Optional: Gäbe es die Möglichkeit, den Befragten auf end3 noch einmal den Link zum AddOn zu präsentieren? Was würde passieren, wenn ein Befragter zwei Mal eine Adressaktualisierung angibt?

**Comment by andreaschu** [comment]
- Die _end.html_ ist technisch die letzte Seite, daran ändern wir nichts. Die Seiten vorher müssen also entsprechend umbenannt werden
- auf der End-Seite gibt es keinen Button mit 'Absenden', da es von hier nicht weiter gehen kann.
- es gibt natürlich die Möglichkeit den Link zur AddOn noch mal anzuzeigen. Ein Befragter kann dennoch nur einmal seine Daten angeben. Die Szenarien wären: 
     - Der/die Befragte sieht dieselbe Seite noch mal, ohne Angaben gemacht zu haben: das ist sehr wahrscheinlich, da ein innerhalb von wenigen Minuten die Seite zweimal aufgerufen wird
     - Der/die Befragte hat bereits beim ersten Mal die Daten angegeben und die Seite verlassen. Dann sieht er seine eigenen Angaben und kann diese ändern, sofern der **Session Time Out auf der End-Seite noch nicht abgelaufen** ist.
     - Der/die Befragte hat bereits beim ersten Mal die Daten angegeben und die Seite verlassen. Dann sieht er die Dankesseite, sofern der **Session Time Out auf der End-Seite bereits abgelaufen** ist.

Wir setzen den Session Time Out bei der Add On aus Datenschutzgründen auf wenige Minuten. Danach kann der/die Befragte die Daten nicht mehr ansehen oder ändern.

**Comment by bafranke** [comment]
Dann bitte folgendermaßen:

- end0:

bisherige end-Seite, ohne Kommentarfeld und ohne Satz "Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:"
Ist es hier möglich, den Weiter-Button mittig zu platzieren?

- end1:
"Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:"
und Kommentarfeld 
mit einem Zurück und einem Absenden-Button

- end:
Vielen Dank! Wir haben Ihre Anmerkungen erhalten. Hier bitte nur ein Zurück-Button.

**Comment by SilinaKowalewski** [comment]
> Ist es hier möglich, den Weiter-Button mittig zu platzieren?

Das ist leider nicht möglich.

**Comment by SilinaKowalewski** [comment]
@bafranke: Ich kann das gerne in der Form umsetzen. Allerdings wird das Auswirkungen auf die Rücklaufstatistik sowie Auswertungen aus der Datenbank haben. Hierbei gilt ein Fragebogen erst dann als "beendet" wenn die End-Seite (end) erreicht wurde. In eurem Fall wären also Probanden, die die Befraung auf end0 verlassen quasi "Abbrecher". 

Wenn das für euch kein Problem ist, mache ich mich an die Umsetzung der Änderungen.

**Comment by bafranke** [comment]
@jocarstensen @woisch @se-lang @heikQ Was meint ihr? Könnt ihr das heute noch entscheiden und weitergeben? Ich muss leider weg...

**Comment by heikQ** [comment]
Ohne richtige Rücklauf Statistik während der Feldphase ist ein ein wenig blöd, aber auch nicht ganz so wild, da wir seitenweise schauen können, bis wohin die Leute gekommen sind richtig? Dann wäre es okay

**Comment by woisch** [comment]
der Dropout nach Seiten wird in der Rücklaufstatistik per Mail nicht drin sein, zumindest nicht getrennt nach cohort. Dafür muss jedesmal ein Datenexport gemacht werden. Siehe Issue #95 

@SilinaKowalewski @andreaschu: Kann man in der Rücklaufstatistik, die ihr uns täglich per Mail zustellt, nicht eine alternative Endseite definieren statt "end"? Will sagen: Das die Rücklaufstatistik alle als beendet ausweist, die zB end0 erreicht haben in Barbaras Szenario?

**Comment by SilinaKowalewski** [comment]
Das kann euch am besten @dzhwmeisner beantworten: 

@dzhwmeisner: Ist es möglich das Cockpit so umzuschreiben, dass drei end-Seiten oder nur die end0 als offizielle End-Seite gilt?

**Comment by dzhwmeisner** [comment]
Da es sich um eine befragungsspezifische Anpassung handelt, würdet ihr eine modifizierte Version des Cockpits benötigen. Das hätte zur Folge, dass der tägliche Bericht von Viktor oder mir erstellt werden müsste. Die einzige Alternative wäre aus meiner Sicht ein Export der Daten.

**Comment by andreaschu** [comment]
Dann lassen wir es bei der verabredeten allgemeinen Rücklaufstatistik täglich und einem Bericht über die abgeschlossenen Fragebögen je Cohorte einmal die Woche.

**Comment by bafranke** [comment]
Wir haben mit Andrea besprochen, dass wir über die wöchentlichen Berichte und den Datensatz unseren täglichen Rücklauf nachträglich konstruieren können. Daher bitte die End-Seiten umbauen:

> 
> 
> Dann bitte folgendermaßen:
> 
>     * end0:
> 
> 
> bisherige end-Seite, ohne Kommentarfeld und ohne Satz "Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:"

Hier bitte noch einen Punkt am Ende des Satzes setzen: Klicken Sie hier, um Ihre aktuelle Adresse anzugeben.

> 
>     * end1:
>       "Wenn Sie noch Kommentare oder Anregungen haben, können Sie uns diese gerne hier mitteilen:"
>       und Kommentarfeld
>       mit einem Zurück und einem Absenden-Button
> 
>     * end:
>       Vielen Dank! Wir haben Ihre Anmerkungen erhalten. Hier bitte nur ein Zurück-Button.

Danke!

**Comment by woisch** [comment]
Habe gesehen, dass der Umbau schon gemacht/begonnen wurde bei den Endseiten.
Wichtiger Hinweis noch: @SilinaKowalewski hatte die Bilddatei so eingestellt, dass sie beim kleinerziehen des Bildschirms kleiner wird (meine auf 80% der Bildschirmbreite). Das ist momentan noch nicht der Fall.

Sonst passiert das hier;
![grafik](https://user-images.githubusercontent.com/53002476/70822002-cbf40900-1ddc-11ea-91d9-b0443d9903b7.png)

**Comment by SilinaKowalewski** [comment]
Ist hier noch etwas offen, außer der Bildgröße?

**Comment by woisch** [comment]
Ja.

Hier bitte noch einen Punkt am Ende des Satzes setzen: Klicken Sie hier, um Ihre aktuelle Adresse anzugeben.






:-)

**Comment by bafranke** [comment]
Bildgröße passt bei mir jetzt auch! Der Punkt fehlt noch

**Comment by jocarstensen** [comment]
Sollte jetzt alles passen
