### ISSUE TITLE
Modul msg: Transitions

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#21]
fehlerhafte Transition auf msg_04: Hängenbleiben nach Zurückgehen.

tester105

**Comment by andreaschu** [comment]
transition fehlt noch. Bisher gibt es nur:
`GOTO msg_10 IF cohort=2`

**Comment by jocarstensen** [comment]
Das Problem ist, dass ich als cohort==1 gar nicht auf der Seite landen dürfte. Der Fehler ist also, dass die Transition auf msg_03 noch nicht da ist.

ABER: die Bedingung in der Transition auf msg_04 ist trotzdem überflüssig. Soll ich sie aus dem Code löschen und ein Issue für Update machen?

**Comment by bafranke** [comment]
@jocarstensen: Ich habe noch ein paar weitere Korrekturen für das Modul msg, soll ich die angesprochene transition in dem Zuge einfach mit rausnehmen oder hast du noch weitere Korrekturen und möchtest ein separates Update machen?

**Comment by jocarstensen** [comment]
@bafranke: Die unnötigen Cohort-Bedingungen sind zwar ein allgemeines Problem, das noch an anderen Stellen auftritt, aber Du kannst sie meinetwegen gern schon rausnehmen. Die korrekte Transition wäre an dieser Stelle "GOTO msg_10" statt "GOTO msg_10 IF cohort=2"

@andreaschu: Bleibt noch die fehlende Transition auf msg_03.

**Comment by bafranke** [comment]
@jocarstensen: transitionänderung ist in update2_sozdem aufgenommen

@andreaschu: Könnt ihr die (derzeit noch auskommentierten) transition jetzt programmieren? Ihr habt ja (zumindest für die tester-token) die xls-Liste der Preloadvariable cohort! Das würde uns das Testen der transitions ermöglichen! Braucht ihr dafür noch weitere Zuarbeit von uns?

**Comment by SilinaKowalewski** [comment]
@jocarstensen @bafranke 

Alle Transitions sind nun entsprechend der PV umgesetzt. Nach einem neuen Roll-Out (heute mittag) lassen sich dann die "neuen" Transitions prüfen. 

Die Liste der Preloadvariablen werden wir vermutlich erst morgen hochladen können. Bis dahin könnt ihr aber weiter anhand des Zufallswert für cohort testen.

**Comment by woisch** [comment]
Die o.g. Transitions funktionieren jetzt.
@jocarstensen kann zu, oder?

**Comment by jocarstensen** [comment]
Ja
