### ISSUE TITLE
Layout stu_11 angleichen

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#210]
Könnt ihr bitte noch das Layout der Skala auf stu_11 an das Layout der Skala auf stu_10 angleichen? Da wurde stu_10 nachträglich auf zwei Seiten aufgeteilt.

**Comment by SilinaKowalewski** [comment]
@se-lang: Was meinst du hier genau? 
Für mich sieht alles gleich aus. Abgesehen von den Umbrüchen in der Skalenbeschriftung.

**Comment by se-lang** [comment]
Sorry, war unpräzise ausgedrückt. Ich meinte genau das, die Umbrüche in der Skalenbeschriftung sollten gleich sein, das ist sonst komsich auf zwei Seiten die direkt aufeinander folgen.

**Comment by SilinaKowalewski** [comment]
Ist angepasst und ausgerollt.

**Comment by woisch** [comment]
sieht ok aus, kann zu oder? @se-lang
