### ISSUE TITLE
Layout msg_03a angleichen

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#211]
Und hier bitte noch das Layout von msg_03a bzw. offener Felder an das der anderen Seiten mit dieser Frage angleichen (z.B. staa10). Texte und Felder überlagern sich aktuell noch.
![grafik](https://user-images.githubusercontent.com/35341060/70704758-f194eb80-1cd2-11ea-9266-fbcf3c801ece.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
passt jetzt bei mir
