### ISSUE TITLE
syntaktische Fehler: Fehlerbericht

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#212]
Hier eine Übersicht syntaktischer Fehler, mit Korrekturhinweisen.
[Fehlerbericht_syntaktischeFehler.xlsx](https://github.com/dzhw/SLC-IntEr/files/3955334/Fehlerbericht_syntaktischeFehler.xlsx)

**Comment by se-lang** [comment]
Da kann irgendwas bei den ganzen Fehlern im Episodenmodul Studium nicht stimmen. Da steht überall die gleiche condition mit dem gleichen Fehler und der gleichen Lösung `(navigatorBean.isSame() and zofar.isMissing(st0001)) or sf.st0001.value; java.lang.NullPointerException; sf.st0001.value --> sf_st0001.value`
Den Fehler gibt es zwar (dafür sehr hilfreich, danke!), allerdings nur auf st0001.

**Comment by andreaschu** [comment]
Stimmt. Das gucken wir uns noch mal an.

**Comment by jocarstensen** [comment]
@andreaschu 
Könnt Ihr Euch Zeile 2 und 3 auch noch einmal anschauen? Die Condition betrifft isMobile und width. Ich denke, man kann den Vorschlag (Klammern) einfach übernehmen, möchte aber nicht in Euren Conditions rumpfuschen.

**Comment by jocarstensen** [comment]
@andreaschu Zeile 8 und 9 auch: Da werden die HVs aus dem Kalendarium befüllt. Das muss vermutlich @dzhwmeisner angucken.

**Comment by dzhwmeisner** [comment]
bei 8 und 9 sehe ich keine Auffälligkeiten

**Comment by jocarstensen** [comment]
Ok... Was heißt das? Wie gehen wir damit um? Was ist mit 2 und 3?

**Comment by andreaschu** [comment]
2 und 3 habe ich gerade geändert.

**Comment by andreaschu** [comment]
> Ok... Was heißt das? Wie gehen wir damit um? 

Ich würde sagen, wenn dzhwmeisner es sich angesehen hat und trotz 'Meldung' es als unkritisch bewertet, können wir beruhigt sein.

**Comment by dzhwmeisner** [comment]
Funktionale Überprüfung der Hilfsvariablentrigger h_nohaupt,h_studium,h_ausb,h_erwerb (Fragliche Ausdrücke in 8 und 9) funktionieren aus meiner Sicht für beide Kohorten erwartungsgemäß

**Comment by dzhwmeisner** [comment]
request for closing

**Comment by jocarstensen** [comment]
Ok, danke. Konnte nur nicht einordnen, wie kritisch diese Fehler sind. Aber dann mache ich zu.
