### ISSUE TITLE
Modul Studium: Häkchen stu_45

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#213]
Wenn ich die ersten beiden Items auswähle und beim 2. Item eine ungültige Angabe mache (keine Zahl) verschwindet beim erscheinen der roten Fehlermeldung das gesetzte Häkchen von Item 1! Die Monatsangabe bleibt aber zum glück drin..

![grafik](https://user-images.githubusercontent.com/53002476/70707673-fbb9e880-1cd8-11ea-8fae-af4ba91bdb95.png)

**Comment by SilinaKowalewski** [comment]
@vdick: Lässt dich das Problem eventuell schnell lösen? Bei mir verhält sich die Seite genau so.

**Comment by dzhwmeisner** [comment]
Problem gelöst

**Comment by woisch** [comment]
ok, passt jetzt!
