### ISSUE TITLE
Zeilenumbruch Antwortlabels: stu_17/gsh_02

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#215]
Könnt Ihr in das erste Label noch einen Umbruch einbauen, so dass es umbricht wie das fünfte? (Also Text obere Zeile, Zahl untere)

- [x] stu_17
![grafik](https://user-images.githubusercontent.com/53002476/70721434-d5ef0c80-1cf5-11ea-8db8-150931784eb7.png)

- [x] gsh_02
![grafik](https://user-images.githubusercontent.com/53002476/70721590-27979700-1cf6-11ea-8693-d8538c3a1ec0.png)

**Comment by SilinaKowalewski** [comment]
@vdick: Habe es mal selber ausprobiert.

**Comment by vdick** [comment]
@woisch das ist leider nicht möglich. Das erste und letzte Label werde ab nächsten Rollout 2 zeilig dargestellt werden

**Comment by woisch** [comment]
okay
