### ISSUE TITLE
Layout mobile Ansicht st**09

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#216]
Nach dem Umbau der Frage ist hier die Darstellung im Portrait noch problematisch:

![grafik](https://user-images.githubusercontent.com/56022369/70777664-a6391680-1d80-11ea-8b92-91b91f82d8c1.png)

bitte anpassen für:
staa09 stab09 stac09 stad09 stae09  
stba09 stbb09 stbc09 stbd09  
stca09 stcb09 stcc09
stda09 stdb09
stea09

und

stu_95

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
ist überall umgesetzt
