### ISSUE TITLE
Layout mobile Ansicht taa05 und weitere (Episoden Weiterbildung)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#218]
Antwortkategorien überlappen in der mobilen Ansicht. Betrifft folgende Seiten:
taa05/tba05/tca05/tda05/tea05
![grafik](https://user-images.githubusercontent.com/53002476/70785998-e3ef6c80-1d8b-11ea-82c0-ba668777e5c5.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
passt jetzt so!
