### ISSUE TITLE
Episoden SET: sezz01 Hinweistext doppelt

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#219]
Der Text ist doppelt: Sollten Sie zuletzt mehrere Selbständigkeiten parallel gehabt haben, beziehen Sie sich bitte auf die Tätigkeit mit dem größeren Stundenumfang bzw. (bei gleichen Umfängen) mit der größeren Bedeutung für Sie persönlich.

![grafik](https://user-images.githubusercontent.com/53002476/70786957-05e9ee80-1d8e-11ea-9e11-7f52ec4fa024.png)

**Comment by jocarstensen** [comment]
Geändert, ab nächstem Rollout verfügbar

**Comment by woisch** [comment]
okay, kann zu
