### ISSUE TITLE
Modul beg: Transitions

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#22]
fehlerhafte Transition auf beg_08: Hängenbleiben nach Zurückgehen

tester105

**Comment by andreaschu** [comment]
man bleibt hängen, wenn `cohort=2`. In der PV steht noch `GOTO [NEXT MODUL] if cohort=2`, deswegen gibt es hier noch keine Transition. Was ist [NEXT MODUL]?

**Comment by jocarstensen** [comment]
Stimmt, das machen wir später.
