### ISSUE TITLE
Episoden SET-Not: sezz06: Wording

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#220]
im SET Notmodul sprechen wir davon, dass das "Interview" nicht zu lang wird. Verwenden wir das Wort irgendwo anders  in den Episoddenmodulen auch noch (und es fällt mir erst jetzt auf)? Fände es sonst hier besser, von Befragung zu sprechen.

![grafik](https://user-images.githubusercontent.com/53002476/70789489-6b8ca980-1d93-11ea-8c5c-137279073a4d.png)

**Comment by jocarstensen** [comment]
Geändert, ab nächstem Rollout verfügbar

**Comment by woisch** [comment]
passt.
