### ISSUE TITLE
syntaktischer Fehlerbericht

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#221]
Können wir huete Nachmittag nochmal so einen syntaktischen Fehlerbericht haben oder ist der sehr aufwändig? Ist auf jeden Fall sehr hilfreich.

**Comment by andreaschu** [comment]
Das können wir machen.

**Comment by jocarstensen** [comment]
Können wir Montagvormittag noch einen syntaktischen Fehlerbericht haben? Damit können wir sichergehen, dass wir am Wochenende keine Fehler gemacht haben.

**Comment by jocarstensen** [comment]
Allerdings erst vom Stand gegen Mittag. Wir hoffen gerade noch, eine Änderung erfolgreich bewältigen zu können.

**Comment by jocarstensen** [comment]
@andreaschu ?

**Comment by andreaschu** [comment]
Bei einem neuen Test ist nichts hinzugekommen, zu dem, was [hier](https://github.com/dzhw/SLC-IntEr/issues/185#issuecomment-565495099) schon berichtet wurde.

**Comment by jocarstensen** [comment]
Cool

**Comment by jocarstensen** [comment]
Dann schließen wir mal.
