### ISSUE TITLE
Episoden SET-Not: 0 weitere SET

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#222]
Wenn ich auf se0002 angebe, dass ich 0 weitere Selbständigkeiten habe, meine davor angegebene SET aber im Dez. 2019 noch läuft, bekomme ich auf sezz06 und folgenden Seiten wieder alle Fragen zur bereits angegebenen, aktuellen SET vorgelegt, die ich schon beantwortet habe (Adäquanz usw., alles was für jede aktuelle SET vorgelegt wird). 

Es ist natürlich eh die Frage wie man mit 0 weiteren SET umgeht und ob diese überhaupt noch nachfragen kriegen sollen...

**Comment by jocarstensen** [comment]
Dürfte behoben sein. Bitte nochmal testen.

(Es gibt noch einen bekannten Fehler: Wenn man über die Splits in die Notschleife kommt (über se0002), und nicht über seea60 (über se0004), wird das Synonym für die Episode nicht übernommen. ab den Fehler noch nicht gefunden, bin aber dran. Ansonsten sollte alles passen.)

**Comment by woisch** [comment]
Sieht gut aus. 
Habe nach 5 angegebenen SET die Seite se0004 bekommen. Wenn ich dort 0 angebe, verlasse ich das Modul.
Bin dann nochmal über die Splits gegangen und auf se0002 gelandet. Wenn ich da 0 weitere SET angebe werde ich zur letzten aktuellen befragt. Passt also. Das Problem der Einblendbedingungen des Arbeitgebers ist dir ja bekannt:
![grafik](https://user-images.githubusercontent.com/53002476/70863835-94a46a00-1f4c-11ea-8173-c83252517205.png)

**Comment by jocarstensen** [comment]
Ja, die Einblendung (Klammer in meinem letzten Post) habe ich eben gefixt. Sollte im nächsten Rollout behoben sein.

**Comment by jocarstensen** [comment]
Wenn Du über die se0002, also über unvollendete Splits, in die Notschleife kommst, solltest Du übrigens auch nochmal zu Start und Enddatum befragt werden, wenn Du bei der Frage nach der Anzahl weiterer Episoden ein Missing angibst oder in der letzten Schleife kein Enddatum angegeben hast.

**Comment by jocarstensen** [comment]
Hab bisher keine 500er oder Festhänger gehabt, bin aber noch etwas ängstlich wegen der Conditions:

`            <zofar:transition target="sezz01" condition="	(
															zofar.asNumber(se0002) gt 0	
															or (zofar.isMissing(se0002) and sf_se0002.value)
															)   
															or
															(
															zofar.asNumber(se0002)==0																
															and
															(
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)!=1 
															and zofar.asNumber(flag_seca06)!=1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and (zofar.asNumber(h_seaa06m)==999999 
															or zofar.asNumber(h_seaa06j)==999999))
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)!=1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and (zofar.asNumber(h_seba06m)==999999 
															or zofar.asNumber(h_seba06j)==999999))															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and (zofar.asNumber(h_seca06m)==999999 
															or zofar.asNumber(h_seca06j)==999999))															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)==1 
															and zofar.asNumber(flag_seea06)!=1 
															and (zofar.asNumber(h_seda06m)==999999 
															or zofar.asNumber(h_seda06j)==999999))															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)==1 
															and zofar.asNumber(flag_seea06)==1 
															and (zofar.asNumber(h_seea06m)==999999 
															or zofar.asNumber(h_seea06j)==999999))															
															))
															"/>
            <zofar:transition target="sezz06" condition="	zofar.asNumber(se0002)==0
															and
															(
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)!=1 
															and zofar.asNumber(flag_seca06)!=1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and zofar.asNumber(h_seaa06m)!=999999 
															and zofar.asNumber(h_seaa06j)!=999999)
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)!=1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and zofar.asNumber(h_seba06m)!=999999 
															and zofar.asNumber(h_seba06j)!=999999)															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)!=1 
															and zofar.asNumber(flag_seea06)!=1 
															and zofar.asNumber(h_seca06m)!=999999 
															and zofar.asNumber(h_seca06j)!=999999)															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)==1 
															and zofar.asNumber(flag_seea06)!=1 
															and zofar.asNumber(h_seda06m)!=999999 
															and zofar.asNumber(h_seda06j)!=999999)															
															or
															(	zofar.asNumber(flag_seaa06)==1 
															and zofar.asNumber(flag_seba06)==1 
															and zofar.asNumber(flag_seca06)==1 
															and zofar.asNumber(flag_seda06)==1 
															and zofar.asNumber(flag_seea06)==1 
															and zofar.asNumber(h_seea06m)!=999999 
															and zofar.asNumber(h_seea06j)!=999999)															
															)
															"/>
`

**Comment by woisch** [comment]
> 
> 
> Wenn Du über die se0002, also über unvollendete Splits, in die Notschleife kommst, solltest Du übrigens auch nochmal zu Start und Enddatum befragt werden, wenn Du bei der Frage nach der Anzahl weiterer Episoden ein Missing angibst oder in der letzten Schleife kein Enddatum angegeben hast.

Wurde nochmal nach Start/Ende gefragt, ja. Hatte als Enddatum der letzten Episode "läuft noch" angegeben. Und danach noch ein paar Wechsel von Ort/Vertrag gemacht bis ich ins Notmodul (se0002) gekommen bin. Ist das richtig so? (tester35)

**Comment by woisch** [comment]
klappt jetzt alles, soweit ich das sehe.
Einblendung des Arbeitgebers klappt nun auch, wenn man über se0002 kommt..

**Comment by jocarstensen** [comment]
Neueste Änderungen sehen gut aus. Ich mach mal zu.
