### ISSUE TITLE
Modul Schule: Datum verknüpfen oder Frage umformulieren

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#223]
scab12
![grafik](https://user-images.githubusercontent.com/56022369/70798963-9d5c3b00-1da8-11ea-98e9-6193b80bd13e.png)

**Comment by jocarstensen** [comment]
Kannst Du mir Deinen Tester sagen?

**Comment by bafranke** [comment]
tester150

**Comment by jocarstensen** [comment]
Ich glaube ich habe den Fehler gefunden. Hattest du ein Häkchen bei "dauert noch an" gesetzt?

**Comment by bafranke** [comment]
jap

**Comment by jocarstensen** [comment]
Fehler dürfte gefunden und korrigiert sein. Nach dem nächsten Rollout testbar.

**Comment by woisch** [comment]
Bin mal mit tester 150 rein und sehe die Seite nun so:

![grafik](https://user-images.githubusercontent.com/53002476/70819969-ccd66c00-1dd7-11ea-8e76-d612e6184169.png)

Aus meiner Sicht, wenn ich das Problem richtig verstanden habe, passt jetzt alles.
@bafranke: Wenn du das auch so siehst, kannst du hier zu machen...

**Comment by jocarstensen** [comment]
@woisch: Hast Dich aber nur durchgeklickt und nichts geändert, oder?

**Comment by woisch** [comment]
genau.

**Comment by jocarstensen** [comment]
Dann sieht das für mich gut aus. Barbara wird es bestätigen.

**Comment by woisch** [comment]
Ich möchte Barbara auch einen Preis für dieses Kunstwerk verleihen:

![grafik](https://user-images.githubusercontent.com/53002476/70820153-3f474c00-1dd8-11ea-8ab9-7f46fd01b1ea.png)

**Comment by jocarstensen** [comment]
Den nimmt sie sicher gern.

**Comment by bafranke** [comment]
funktioniert, ich schließe hier!
