### ISSUE TITLE
Modul Schule: keine Abschlussseite?

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#224]
Ich habe gerade nach dem Abschluss des Episodenmoduls Schule keine Abschlussseite bzw. Zwischenseite wie bei den anderen Modulen bekommen - ist das so geplant oder funktioniert einfach irgendetwas nicht?

**Comment by jocarstensen** [comment]
Wohin bist Du danach gekommen?

**Comment by jocarstensen** [comment]
Alle Transitions, die im Schuulmodul nicht innerhalb des Moduls verlaufen, gehen nach zwischen_sc ... Kann mir das nicht erklären.

**Comment by bafranke** [comment]
auf staa01, ich teste es noch einmal systematisch

**Comment by jocarstensen** [comment]
Das kann eigentlich nur über zwischen_sc gegangen sein. Da sollte eine Einblendung "Im Folgenden bitten wir Sie nun um Informationen zu Ihrem Studienverlauf." gekommen sein. Wenn die nicht funktioniert hat, eine leere Seite.
staa01 findet sich im QML des Schulmoduls gar nicht. @SilinaKowalewski Könnte da noch irgendwo eine Debugging-Seite ihre Finger im Spiel haben?

**Comment by bafranke** [comment]
Ich kann den Fehler nicht mehr reproduzieren, keine Ahnung was das war! Läuft so wie du sagst, ich komme auf die Zwischenseite mit richtigem Text. Sorry fürs Aufscheuchen, ich mach hier mal zu...
