### ISSUE TITLE
Infield einblendungen und Layout mobil: iza06

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#225]
- [x] Auf iza06 sehe ich keine Infield Einblendungen.

![grafik](https://user-images.githubusercontent.com/53002476/70806132-eae1a380-1dba-11ea-9f7f-9567ded42623.png)

- [x] das Layout für die mobile Ansicht so anpassen wie auf den anderen Ortsseiten (zB. iaa06):
![grafik](https://user-images.githubusercontent.com/53002476/70806292-4318a580-1dbb-11ea-8f91-ffbce53d3199.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
alles umgesetzt
