### ISSUE TITLE
GSH_02 Fragetext Schriftgröße

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#226]
- [ ] gsh_02: Schriftgröße des Fragetextes ist zu klein und weicht von den übrigen ab

**Comment by woisch** [comment]
hast du mal nen Screensshot? War das auch Safari?

**Comment by heikQ** [comment]
ja war auch safari. Wenns sonst normal ist, ist das dann zu vernächlässigen aufgrund wichtigerer Sachen, ist ja dennoch lesbar, und ich mach hier die Tür zu.
