### ISSUE TITLE
Safari Test

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#227]
Layout Bugs mit Safari Browser (desktop) für Skalen, bin allerdings unsicher, was passiert bei den anderen browsern, wenn es für safari optimiert wird. Daher nur ändern, was das keine Auswirkungen auf häufiger verwendete browser hat, notfalls ist es sonst verschmerzbar, wenn auch nicht schön:

- [ ] Bei allen horizontalen Skalen sitzen die Beschriftungen nicht richtig über den jeweiligen Punkten, sondern sind verschoben. Das betrifft Cohort 1 und 2. Die Verschiebung ist umso größer, je mehr Abstufungen eine Skala hat.

- [ ] Bei allen horizontalen Skalen ragt die Berschriftung der Skalenpunkte in die overlay Hinterlgeung des ersten items, wenn man auf dieses geht

**Comment by heikQ** [comment]
Nach dem Wiedereinstieg in die Befragung mit Safari sieht das zuvor (bei frischem token normale Kalendarium, das adann usgefühlt wurde) vollkommen verzogen und falsch aus, die Darstellung ist vollkommen falsch und monate lassen sich zum Teil nicht mehr anwählen bzw. werden gar nicht richtig dargestellt. Das Kalendarium wäre so unbrauchbar
<img width="1280" alt="Bildschirmfoto 2019-12-13 um 17 07 09" src="https://user-images.githubusercontent.com/52539440/70814441-c8a45180-1dcb-11ea-8b17-38c1cb73c265.png">

**Comment by jocarstensen** [comment]
Safari ist ja leider immer ein Problem. Bevor wir das Kalendarium kurz vor der Feldphase für alle anderen Browser zerschießen, sollten wir darüber nachdenken, für Safari auch drüber hinweg zu filtern. Vorausgesetzt natürlich, der UAS ist zuverlässig.
Da bräuchten wir den professionellen Input von @dzhwmeisner

**Comment by heikQ** [comment]
@jocarstensen Ich würde noch nichtmal filtern, dass problem trat nur einmalig und nur nach unterbrechung und wiederlogin auf. Kommt vermutlich selten vor und beim ersten ausfüllen geht es ja mit leerem token und ich konnte es nicht replizieren mit anderem token und anderen Tätigkeiten. Von daher würde ich auch nicht drüber filtern mit safari, sondern laufen lassen, auch wenn es sich nicht beheben lässt.

**Comment by jocarstensen** [comment]
Ach so, ich dachte das wäre ein generelles Safari-Problem.

**Comment by bafranke** [comment]
Ich habe mehrfach Ausloggen und nochmaliges Aufrufen des Kalendariums getestet und hatte keine Probleme. Würde daher auch dafür plädieren, es so zu lassen, wie es ist.

**Comment by woisch** [comment]
Konnte das Problem von Heiko auf meinem Macbook Pro mit Safari auch zwischendurch beobachten. Erkenne aber nicht wirklich ein System dabei. Mal passierte es, meistens eher nicht. Meist nach erneutem LogIn wie von Heiko beschrieben. Einmal hat sich das Problem von selbst behoben als ich den Browser klein und wieder groß gezogen hab (plötzlich wieder das ganze Kalendarium zu sehen), manchmal wurde das Kalendarium nach einmal "Seite neu laden" korrekt angezeigt. SEHR MYSTERIÖS auf jedemn Fall.
Würde hier auch nichts mehr ändern. Mir ist nicht klar ob es an Safari liegt (aufm iPhone geht Safari ja einwandfrei) oder irgendeine Macbook-Sache ist.

**Comment by jocarstensen** [comment]
Nach Absprache wird hier nichts mehr gemacht.
