### ISSUE TITLE
cohorte 2: Start-/Willkommensseite, Befragungsdauer anpassen

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#228]
Bitte auf der Startseite nur für cohorte 2 im 2ten absatz die angegebene Befragungsdauer ändern in: (...) variiert zwischen 20 und 40 Minuten.

**Comment by SilinaKowalewski** [comment]
umgesetzt. ist im übernächsten Roll-Out verfügbar.

**Comment by woisch** [comment]
Ist jetzt umgesetzt (auf dem internen)

**Comment by woisch** [comment]
jetzt auch auf dem externen. mache hier zu.
