### ISSUE TITLE
Modul_Einstieg: Programmierfehler beg_09

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#23]
beg_09: value label doppelt in ao: (1) trifft voll und ganz zu (1), (2) (2), usw. 
Bitte nur Wert ans Ende der ao

**Comment by andreaschu** [comment]
umgesetzt.

**Comment by SilinaKowalewski** [comment]
@bafranke: 

Auch hier sieht nun alles richtig aus :) Kann dieses Item geschlossen werden?

**Comment by bafranke** [comment]
jap
