### ISSUE TITLE
Episoden SET: seaa06 

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#230]
Kleiner Rechtschreibfehler in der unteren Frage ist in der Klammer ein „s“ zu viel (Werksvertrag)
Gilt auch für die weiteren Seiten in den schleifen

![536483AE-C117-4C3C-9A5E-D642EBE42579](https://user-images.githubusercontent.com/53002476/70851263-2fd90900-1e93-11ea-862d-341ec4eb74ea.jpeg)

**Comment by jocarstensen** [comment]
Ist korrigiert

**Comment by woisch** [comment]
getestet auf seaa06 bis seea06, passt.
