### ISSUE TITLE
staa24: Leerzeichen einfügen

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#231]
Bitte Leerzeichen vor (Bitte geben Sie ...) einfügen
![grafik](https://user-images.githubusercontent.com/56022369/70888813-7472ba80-1fe1-11ea-9fb2-0f562887bb24.png)

**Comment by jocarstensen** [comment]
Merkwürdig. Eigentlich war da eins, und da war auch ein Zeilenumbruch, der scheinbar nicht funktioniert. @SilinaKowalewski Kannst Du Dir das mal angucken? Ich habe jetzt noch ein Leerzeichen zwischen "." und `#{layout.BREAK}` eingefügt.

**Comment by bafranke** [comment]
Der Umbruch klappte bei mit nur in der Desktop-Version, mobil aber nicht.

**Comment by woisch** [comment]
@bafranke bei mir sieht es jetzt gut aus. teste allerdings auf dem internen. der Externe rollt gerade aus scheinbar

**Comment by bafranke** [comment]
extern ist das Leerzeichen nicht da - habs auch mit dem Internet Explorer getestet...
![grafik](https://user-images.githubusercontent.com/56022369/70906089-de9d5680-2005-11ea-9851-f5c40648a8e9.png)
find ich aber auch nicht so tragisch, wenn das so bleibt.

**Comment by SilinaKowalewski** [comment]
Sieht nun so aus: 
![image](https://user-images.githubusercontent.com/48087320/70906659-2ec8e880-2007-11ea-959f-8860d7a68179.png)

**Comment by bafranke** [comment]
super, danke! Auf dem externen Server aber derzeit nicht umgesetzt, richtig? Dann prüfe ich es später im Live modus...

**Comment by woisch** [comment]
Ist jetzt umgesetzt.
Desktop und mobil mit Leerzeichen.
