### ISSUE TITLE
Epimodul Studium: staa24

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#232]
Komische Doppeleinblendung auf staa42:
Habe beim Beginndatum meiner ersten Studienepisode Missing. und dann eine Unterbrechung auf staa24 angegeben.

![grafik](https://user-images.githubusercontent.com/53002476/70895899-0a154680-1ff0-11ea-9259-3454541125a3.png)

(tester25)

passiert auch in den Folgeschleifen auf stba42 usw...Scheint aber nur ein problem bei Angabe einer Unterbrechung auf staa24 zu sein. Wenn ich etwas anderes auswähle stimmen die Einblendungen.

**Comment by se-lang** [comment]
Hoffe ich hab den Fehler gefunden.
@SilinaKowalewski bitte nach dem laufenden Build direkt noch einen neuen anstoßen
@woisch danach bitte nochmal testen

**Comment by woisch** [comment]
auf dem internen nochmal mit dem selben tester getestet. Jetzt sieht es wieder ok aus.

**Comment by woisch** [comment]
auch mit frischem Tester auf dem internen kein Problem mehr. Mach hier zu
