### ISSUE TITLE
Epimodul Ausbildung

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#233]
Wenn ich den Endmonat auf Missing lasse, ist auf vba07 "Monat Jahr" eingeblendet:

![grafik](https://user-images.githubusercontent.com/53002476/70897006-17cbcb80-1ff2-11ea-8d53-169cb383a959.png)

Auf vba20 steht zB:
Hat sich der Ausbildungsort bis zum Ende der Ausbildung oder Umschulung geändert?

PS: In den folgenden Schleifen passt es scheinbar im selben Szenario (vca07, vda07), da steht dann immer "Ende der Ausbildung"
![grafik](https://user-images.githubusercontent.com/53002476/70897222-80b34380-1ff2-11ea-8cdd-446587071891.png)

**Comment by jocarstensen** [comment]
Da bezog sich die VC auf die falsche Variable. Ist korrigiert.

**Comment by woisch** [comment]
stimmt jetzt!
