### ISSUE TITLE
Add-On: zwei kleine Änderungen

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#235]
wenn möglich bitte im Add-On (beide Versionen) noch korrigieren:

- [x] Straße Hausnummer: -> Straße, Hausnummer: (Komma einfügen)

- [x] Land (*wenn Ausland): -> Land (wenn Ausland): (Sternchen streichen)

**Comment by SilinaKowalewski** [comment]
@vdick: Ist umgesetzt. Kann neu ausgerollt werden.

**Comment by woisch** [comment]
ist umgesetzt
