### ISSUE TITLE
aus_03a: Label aktualisieren

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#236]
auf aus_03a ist die untere halbe Skala noch nicht mit + gelabelt
könnt ihr für 1-5 bitte noch fix +1 bis +5 umsetzen? oder ist es zu spät?
![grafik](https://user-images.githubusercontent.com/56022369/70903041-523b6580-1ffe-11ea-803c-9365c33e1d5f.png)

**Comment by jocarstensen** [comment]
Ich mach das.

**Comment by woisch** [comment]
cool, danke!

**Comment by bafranke** [comment]
Vielen Dank!

**Comment by jocarstensen** [comment]
Umgesetzt. Vermutlich vor Livegang nicht mehr testbar.

**Comment by bafranke** [comment]
Danke! Ist auch nicht schlimm, wenn nicht getestet, wird schon passen! Habs in der PV angepasst.

**Comment by jocarstensen** [comment]
doch noch getestet. passt.
