### ISSUE TITLE
Zusätzlicher Token-Export benötigt

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#238]
Wir benötigen am 20. Januar noch eine zusätzliche Lieferung der verbrauchten Tokens, um den Versand der ersten **postalischen** Erinnerung in cohort1 (Panel 2015.4) vorzubereiten. 
Ist das für euch möglich an dem Tag? Wenn ja: Könntet ihr die Info dann bitte noch ins Wiki aufnehmen?

Die Lieferung am 27.01. bleibt davon unberührt, das ist ein eigener Versandschritt (2. Erinnerung online am 29.01.).

Vielen Dank!

**Comment by andreaschu** [comment]
Machen wir. Ich trage es ins Wiki ein.

**Comment by SilinaKowalewski** [comment]
Lieber @woisch, 

wir haben dir einen kompletten Export der Token inkl. Lastpage und Status unter p:/koop/woisch/ abgelegt. Das Trennen von cohort1 und cohort2 müsstet ihr noch selber vornehmen.

**Comment by woisch** [comment]
Vielen Dank!
Das Trennen nach cohort kriegen wir (@nna M.) selber hin.

**Comment by woisch** [comment]
Liebes ZOFAR-Team,

Wir würden die 2. Erinnerung gerne einen Tag später als angekündigt (am 30.1.) von euch versenden lassen. Dementsprechend benötigen wir den Tokenexport auch etwas später. Optimalerweise liefert ihr uns den Export am Mittwoch morgen (29.01.).
Ist das möglich? Wenn ja, tragt ihr das noch im Wiki um?

**Comment by woisch** [comment]
neues Issue erstellt, das hier hat sich erledigt.
