### ISSUE TITLE
Token-Export 2. Erinnerung

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#239]
Liebes ZOFAR-Team,

Wir würden die 2. Erinnerung gerne einen Tag später als angekündigt (am 30.1.) von euch versenden lassen. Dementsprechend benötigen wir den Tokenexport auch etwas später. Optimalerweise liefert ihr uns den Export am Mittwoch morgen (29.01.).
Ist das möglich? Wenn ja, tragt ihr das noch im Wiki um?

_Originally posted by @woisch in https://github.com/dzhw/SLC-IntEr/issues/238#issuecomment-576751306_

**Comment by SilinaKowalewski** [comment]
Lieber Andreas, 

wir haben uns heute morgen kurz besprochen und es ist kein Problem die Erinnerung zu verschieben. Die Änderungen werde ich im Wiki eintragen. 

Wir werden euch am 29.01. wieder eine Tokenliste mit Lastpage und Status der Befragten erstellen. 
Soll diese dann wieder zunächst in deinen koop-Ordner gestellt werden?

**Comment by woisch** [comment]
Danke!

**Comment by woisch** [comment]
Ohne Stress machen zu wollen: Könnten wir den Export der Tokens bis heute Mittag bekommen? Wir brauchen noch etwas Zeit, um die Tokens aufzubereiten.
DANKE!
