### ISSUE TITLE
Update 3 Modul_Ausbildung

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#24]
Frage zugefügt (aus_03b), Items korrigiert (aus_04)
f89b04a

**Comment by woisch** [comment]
Zusätzlich noch geändert:
Transition auf aus_00
Variablenname auf aus_3a
e49ca6e36265a2f49e6c13370197565ccadac03c

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Können getestet werden.

**Comment by SilinaKowalewski** [comment]
Kann das Issue geschlossen werden?
