### ISSUE TITLE
neuer vorläufiger Datenexport

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#242]
Wir brauchen bei nächster Gelegenheit noch einen neuen Zwischenexport. Falls es das einfacher macht, würde ein Export der Stringvariablen reichen.

**Comment by jocarstensen** [comment]
Könnt Ihr uns sagen, wann wir mit dem Export rechnen können?

**Comment by woisch** [comment]
Da wir mit Textangaben aus dem Export arbeiten möchten: Ist es möglich, dass im neuen Export die Umlaute korrekt dargestellt werden? Bisher werden diese immer durch Sonderzeichen ersetzt (auch schon in der csv-Datei).

**Comment by woisch** [comment]
kann zu, da wir jetzt den finalen Export haben
