### ISSUE TITLE
Ende Feldzeit und Datenexport

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#243]
Für den 22.03. haben wir unseren Befragten das Ende der Feldzeit angekündigt. Wir würden euch daher bitten, das Feld kommende Woche, frühestens am Montag den 23.03., spätestens am Freitag, den 27.03. zu schließen und uns einen Datenexport im geschützten Bereich abzulegen. Wichtig wäre uns, dass Feldende und Export möglichst am selben Tag erfolgen (wenn ihr den Export also erst Ende der Woche machen könnt, dann das Feld bitte möglichst lang geöffnet lassen).

Bitte gebt uns Bescheid, sobald das Feld zu ist und der Datenexport erfolgt ist. Bitte Info möglichst ans gesamte Team (Carstensen, Lang, Quast, Franke, Woisch).

Folgendes bitte beim Datenexport beachten:
- Bei den stringvariablen wurden im bisherigen Export die Umlaute nicht korrekt dargestellt, bitte darauf achten, da wir sonst beim codieren Probleme kriegen
- Die Reihenfolge der Variablen darf sich ggü dem ersten Export nicht ändern, da sonst dofiles nicht mehr laufen
-wir haben 2 Variablen mit Postleitzahlen (woplz_183 und plz_154) als Variablentyp "number" mit 5 stellen erhoben. Momentan wird die führende Null, wenn angegeben, nicht mit exportiert im Datensatz. Laut eurer Auskunft im Dezember, müssten die führenden Nullen, wenn angegeben, aber in eurer Datenbank gespeichert und damit exportierbar sein. Könnt ihr die beiden Variablen so exportieren, dass wir die führenden Nullen im Datensatz haben?

Anmerkung: Beim letzten (dem zweiten) vorläufigen Datenexport ist etwas schief gelaufen, da haben wir alle Variablen nur als strings bekommen.

Bitte bestätigen bzw. Rückmeldung, ob das so klappt.
Bei Rückfragen meldet euch einfach!

**Comment by jocarstensen** [comment]
Push: Könnt Ihr uns die Termine für Feldende und Datenexport bestätigen?

**Comment by andreaschu** [comment]
Wir haben die Befragung offline gestellt und werden euch Morgen den Export liefern.

**Comment by jocarstensen** [comment]
Im letzten Export fehlt die Variable se0004. Könnt Ihr beim aktuellen Export mal darauf achten, ob sie drin ist?

**Comment by andreaschu** [comment]
Wir mussten das noch mal machen, deswegen habe ich erst jetzt den Transfer veranlasst.

- Ich habe im docs-Ordner Graphiken zum Rücklauf gelegt.
- Die .csv-Datei und die .dta-Datei unterscheiden sich in der Teilnehmeranzahl, weil ich in der .dta die Tester bereits gelöscht habe.

**Comment by jocarstensen** [comment]
Danke schön.

Zu meiner Anfrag zwei Posts weiter oben: Die Variable se0004 fehlt auch im neuen Export. Könnt Ihr bitte checken, was mit der passiert ist? Im QML ist sie vorhanden.

**Comment by andreaschu** [comment]
Der Exporter greift auf den Gesamtfragebogen im SVN zu (questionnaire_generated). Wegen der vielen Module musste diese lokal erstellt werden bevor sie ausgerollt wurde. Die letzte Version davon wurde nicht ins SVN commited, weswegen es eine Abweichung zu der Online-Version gab: In der Version online gab es die Variable, in der Version im SVN nicht.
Das gilt auch für weitere Variablen (z.B. flag_seaa06, flag_seba06, flag_seca06…).

**Comment by andreaschu** [comment]
ich hoffe das war verständlich. Wenn nicht, lass uns telefonieren.

**Comment by jocarstensen** [comment]
Eigentlich interessiert mich nur, was die Konsequenz daraus ist. Ich brauche die Variablen für die Aufbereitung.

**Comment by andreaschu** [comment]
Für die weitere Bearbeitung gibt es keine Konsequenzen.

**Comment by jocarstensen** [comment]
Ok, ich stelle die Frage nochmal anders: Können wir einen Export mit den fehlenden Variablen bekommen?

**Comment by andreaschu** [comment]
Sie sollte eigentlich drin sein, auch wenn sie nicht gefüllt ist, weil niemand auf der Seite war. Das heißt sie ist da, enthält aber nur den Wert -9991

**Comment by jocarstensen** [comment]
Scheint korrekt zu sein. Im Export vom 27. ist alles gut. Ich schließe dann mal.

**Comment by woisch** [comment]
Im Datenexport sind noch ein paar Sachen nicht umgesetzt. Könntet ihr uns nochmal Rückmeldung geben bitte, wie sich das Lösen lässt?

- Bei den stringvariablen wurden im bisherigen Export die Umlaute nicht korrekt dargestellt, bitte darauf achten, da wir sonst beim codieren Probleme kriegen. Das ist scheinbar nicht nur in dem Stata-Datensatz so sondern auch schon in der csv

- wir haben mehrere Variablen mit Postleitzahlen (u. a. woplz_183 und plz_154) mit 5 Stellen erhoben. Momentan wird die führende Null, wenn angegeben, nicht mit exportiert im Datensatz. Laut eurer Auskunft im Dezember, müssten die führenden Nullen, wenn angegeben, aber in eurer Datenbank gespeichert und damit exportierbar sein. Könnt ihr die Variablen so exportieren, dass wir die führenden Nullen im Datensatz haben? (ggf. auch noch einmal als separate Variablen, falls das weniger Aufwand macht als ein kompletter Export). Eine Liste der betreffenden Variablen reichen wir noch nach.

**Comment by andreaschu** [comment]
> Bei den stringvariablen wurden im bisherigen Export die Umlaute nicht korrekt dargestellt, bitte darauf achten, da wir sonst beim codieren Probleme kriegen. Das ist scheinbar nicht nur in dem Stata-Datensatz so sondern auch schon in der csv

Das liegt an Stata. Bitte beim importieren als Option "encoding(utf8)" verwenden.


> wir haben mehrere Variablen mit Postleitzahlen (u. a. woplz_183 und plz_154) mit 5 Stellen erhoben. Momentan wird die führende Null, wenn angegeben, nicht mit exportiert im Datensatz. Laut eurer Auskunft im Dezember, müssten die führenden Nullen, wenn angegeben, aber in eurer Datenbank gespeichert und damit exportierbar sein. Könnt ihr die Variablen so exportieren, dass wir die führenden Nullen im Datensatz haben? (ggf. auch noch einmal als separate Variablen, falls das weniger Aufwand macht als ein kompletter Export). Eine Liste der betreffenden Variablen reichen wir noch nach.

Das ist Stata, das die Variablen automatisch als Nummern erkennt. Die Spalten können beim Einlesen als strings definiert werden, indem man sich zuerst die Spaltennummer ausgeben lässt über:

`describe afin04a afin04b afin04c afin04d afin04e afin04f afin04g afin04h afin04i afin04j afin04k, num`
//  Stata gibt dann den Typ, und ganz links auch die Spaltennummer der Variablen aus, die dann als stringcols angegeben werden müssen.

import delimited [filename].csv, ///
delimiter(comma) ///
bindquote(strict) ///
encoding(utf8) ///
stringcol(387 388 389 390 391 392 393 394 395 396 397)

**Comment by andreaschu** [comment]
Ich habe gerade noch mal geschaut, bei dem Stata-Datensatz, der im Paket war, sind die Umlaute richtig dargestellt. Zumindest bei mir.

**Comment by woisch** [comment]
Das Problem mit den Umlauten konnten wir nun beheben! Danke für den Hinweis! Wegen der führenden Nullen sind wir noch dran. Ich lasse das Issue aber so lange offen..

**Comment by bafranke** [comment]
Umlaute und führende Nullen funktionieren mit deinen Lösungen, Andrea! Herzlichen Dank, ich habe wieder was gelernt ;) Hab ein schönes Wochenende, ich mach hier mal zu!
