### ISSUE TITLE
Export AddOn-Befragung

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#244]
Wir benötigen noch die Exporte der AddOn-Befragungen (Adressaktualisierung). Es waren ja 2 getrennte Add Ons für die beiden Befragungen: einmal für cohort1 (panel2015) und für cohort2 (panel 2018).
Die Daten müssen im gwinter abelegt werden. Ich sende euch gleich noch eine Mail, in der die genauen Pfade benannt sind.

**Comment by andreaschu** [comment]
Die sind in Arbeit. Könnte sein, dass es erst am Montag was wird.

**Comment by woisch** [comment]
Okay, danke für die Info! Wenn das bis Montag klappt, wäre es super!

**Comment by woisch** [comment]
Könnt ihr schon sagen, wann wir mit den AddOn-Daten rechnen können?

**Comment by woisch** [comment]
Daten sind angekommen! Danke! Ich mach zu.
