### ISSUE TITLE
Screenshots IntEr

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#245]
Wir hätten gerne noch für unsere Projektdoku eine Screenshot-Version des kompletten Fragebogens. Ihr hattet uns sowas mal im Dezember erstellt, das ist aber nicht mehr ganz der letzte Stand.
Vielen Dank schonmal für eure Mühe!

**Comment by woisch** [comment]
(Push)
Könnt ihr uns schon sagen, wann wir mit den Screenshots rechnen können? Die wären für ein paar anstehende Aufgaben in der Datenaufbereitung/Doku sehr hilfreich ...

**Comment by andreaschu** [comment]
da es sehr viele Seiten sind, wird der Screenshot sehr groß, wenn es in ein pdf soll. Sollen wir es irgendwie anders aufteilen oder Euch einfach ein Verzeichnis mit den Bildern als Einzeldokumente geben?

**Comment by woisch** [comment]
Im Dezember hattet ihr uns einen Ordner mit den Einzelbildern abgelegt. Das wäre für uns auch wieder ok, sofern aus den Dateinamen die Seitenbezeichnung hervorgeht und die Reihenfolge der Bilder möglichst der Chronologie im Fragebogen entspricht.
Dann müsste es nicht zwingend eine zusammenhängende PDF sein.

Ablegen könntet ihr es unter \\FAUST\Austausch dann kopiere ich es da raus.

**Comment by christian-fr** [comment]
Ich habe zwei ZIP-Dateien im Ordner:
`\\faust\Austausch\SLC`
abgelegt.

Beide haben den dentischen Inhalt, nur die Dateinamen unterscheiden sich jeweils:

a) mit vorangestelltem Index, der der Reihenfolge im QML entsprechen sollte + pagename
b) nur mit pagename, um ggf. schnell eine bestimmte page zu finden.

**Comment by woisch** [comment]
Danke!
Habe mir die Dateien da rausgeholt und in unseren Projektordner geschoben!
Mache dann hier zu.

**Comment by woisch** [comment]
Ich arbeite gerade mit den Screenshots und habe festgestellt, dass die offenbar alle für die responsive Ansicht erzeugt worden sind. Damit kann ich erstmal arbeiten, ich bräuchte aber auf jeden Fall auch nochmal die Screenshots für die Desktop-Ansicht. 
Könntet ihr uns das noch nachreichen bitte?

**Comment by christian-fr** [comment]
>
> [...] ich bräuchte aber auf jeden Fall auch nochmal die Screenshots für die Desktop-Ansicht. [...]

Was genau meinst Du damit? Also kannst Du mir kurz erklären, was genau Du brauchst?

**Comment by woisch** [comment]
> 
> 
> > [...] ich bräuchte aber auf jeden Fall auch nochmal die Screenshots für die Desktop-Ansicht. [...]
> 
> Was genau meinst Du damit? Also kannst Du mir kurz erklären, was genau Du brauchst?

Habe mich vielleicht etwas verwirrend ausgedrückt. Die Befragung wurde je nach Endgerät bzw. Bildschirmgröße (Smartphone vs. zB Laptop) ja unterschiedlich dargestellt. Insbesondere sind größere Fragebatterien in der responsiven Ansicht auf dem Smartphone als Karussell umgesetzt (diese Darstellung findet sich auch in den von euch gelieferten Screenshots). Am Laptop oder Desktop-PC sah die selbe Seite anders aus, da wir aufgrund des größeren Bildschirms alle Fragen auf einer Seite unterbringen konnten. Somit wird die selbe Seite je nach Endgerät sehr unterschiedlich dargestellt.

Bei der Screenshot-Version vom Dezember hattet ihr uns von jeder Seite mehrere Screenshots (ich meine sogar 3 Versionen: Desktop-PC/Tablet/Mobile) erzeugt, um eben die unterschiedlichen Ansichten darzustellen.

**Comment by christian-fr** [comment]
Könntest Du mir diese alten Screenshots aus dem Dezember irgendwie zugänglich machen? 
Denn dann kann ich wahrscheinlich am besten das liefern, was ihr braucht.

**Comment by woisch** [comment]
Habe die Screenshots vom Dezember nochmal hier nochmal abgelegt für dich auf Faust: "\\FAUST\Austausch\SLC" 
Ist ne recht große ZIP-Datei..

Habe gesehen, dass wir pro Seite offenbar sogar 4 verschiedene Ansichten bekommen haben (mit jeweils unterschiedlicher Bildschirmbreite. Das wäre natürlich die Premium-Variante, da man dann auch Zwischengrößen (zB Tablets) in etwa darstellt.

**Comment by christian-fr** [comment]
Hallo Andreas,

ich habe die neuen Screenshots fertig, sie liegen auf dem Faust im Austausch-Ordner:
`\\faust\Austausch\SLC\2020-05-12_Screenshots_SLC_IntEr.zip`

Bei den Screenshots wurden alle Einblendbedingungen aktiviert, d.h. sämtliche darstellbare Texte sollten parallel angezeigt werden – in der Reihenfolge, in der sie im QML-Code aufgeführt sind. Diese orientiert sich allein an der Reihenfolge der pages in den QML-Dateien, die natürlich nicht zwangsläufig der tatsächlichen Reihenfolge, in der Befragte durch die Befragung geführt wurden, entsprechen wird.

Noch ein Hinweis zu den Fortschritts-Icons direkt unter dem Header jeder Seite: welches Icon auf der jeweiligen page als aktiv (blau) oder inaktiv (grau) angezeigt wurde, ist nicht etwa im Code der Seite vorgegeben, sondern wird - quasi live - vom Webserver anhand der Preloads und der zuletzt besuchten Seiten errechnet und dann entsprechend angezeigt. Dies funktionierte zwar in der echten Befragung, die Screenshot-Erstellung findet jedoch auf einem anderen Rechner statt und dort ließ sich dieses Verhalten leider nicht exakt gleich emulieren. So sind nun auf den allermeisten Screenshots sehr ähnliche Fortschrittsicons zu sehen.

**Comment by woisch** [comment]
Vielen Dank, das sieht gut aus!
@alle: Habe die Screenshots in unseren Projektordner (zu den anderen Screenshots) verschoben!
