### ISSUE TITLE
Kalendarien

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#26]
Wir benötigen zwei Kalendarien, jeweils eine pro Kohorte:

-	Cohort 1: Zeitraum Januar 2018 bis Dezember 2019 mit Episodentypen:
o	Studium
o	Berufsausbildung
o	Fort-, Weiterbildung (längerfristig, insgesamt mind. 70 h)
o	Jobben
o	Erwerbstätigkeit (auch Selbständigkeit)
o	Praktikum
o	Elternzeit/Mutterschutz, Hausmann/-frau, Familientätigkeit
o	Arbeitslosigkeit
o	Sonstiges (z. B. Urlaub/Reisen, Krankheit, Studienvorbereitung, Freiwilligendienst)

-	Cohort 2: Zeitraum Juli 2018 bis Dezember 2019 mit Episodentypen:
o	Schule zum Erwerb d. allgemeinen Hochschulreife
o	Studium
o	Berufsausbildung
o	Fort-, Weiterbildung (längerfristig, insgesamt mind. 70 h)
o	Jobben
o	Erwerbstätigkeit (auch Selbständigkeit)
o	Praktikum (mind. 1 Monat, auch z.B. während Studium)
o	Elternzeit/Mutterschutz, Hausmann/-frau, Familientätigkeit
o	Arbeitslosigkeit
o	Sonstiges (z.B. Freiwilligendienst, Work & Travel, Au Pair, Studienvorbereitung, Familientätigkeit, mehrmonatige Urlaube, Krankheit)

Aus beiden Kalendarien brauchen wir als Hilfsvariablen Dummies, die pro Episodentyp angeben, ob mindestens ein Monat dieses Typs genannt wurde. Die Hilfsvariablen sollen folgende Bezeichnungen haben (überwiegend wie im Pretest):
o	Schule: h_schule
o	Studium: h_studium
o	Berufsausbildung: h_ausb
o	Fort-, Weiterbildung: h_fortb
o	Jobben: h_jobben
o	Erwerbstätigkeit: h_erwerb
o	Praktikum: h_praktikum
o	Elternzeit etc.: h_elternz
o	Arbeitslosigkeit: h_alo
o	Sonstiges (z. B. Urlaub/Reisen, Krankheit, Studienvorbereitung, Freiwilligendienst): h_sonstiges

**Comment by dzhwmeisner** [comment]
Die Kalendarien sind in cohort1Cal (Kalendarium1) cohort1CalPost (Berechnung der zugehörigen Hilfsvariablen) und cohort2Cal/cohort1CalPost in questionnaire7.xml eingebaut

**Comment by andreaschu** [comment]
das war etwas missverständlich formuliert, fürchte ich. Die Seiten sollen heißen:
_cal1_ und _cal2_
Die Weiterleitung läuft durch Preload-Variable _cohort_ (1;2)
Die Variablen-Prefixes heißen: _studium_, _ausb_, _fortb_, _jobben_, _erwerb_, _praktikum_ …

@jocarstensen: Oder habe ich das falsch verstanden? Könntest Du sonst noch mal auflisten, wie die Seiten heißen sollen und die Variablen?

**Comment by se-lang** [comment]
Wir brauchen zusätzlich noch eine HV aus den Kalendarien:
h_studakt=1 if Studium im Dezember 2019 ausgewählt
h_studakt=0 if Studium im Dezember 2019 _nicht_ ausgewählt

**Comment by se-lang** [comment]
@dzhwmeisner Wir bräuchten noch weitere Hilfsvariablen basierend auf den Kalendarien:
- h_calmis=1 wenn weniger als 50% der Monate mit irgendeiner Episode gefüllt sind
- h_nohaupt=1 wenn h_studium!=1 and h_ausb!=1 and h_erwerb!=1
- h_alofam=1 wenn (cohort==1 and (22 Monate Arbeitslosigkeit or 22 Monate Familientätigeit)) or (cohort==2 and (16 Monate Arbeitslosigkeit or 16 Monate Familientätigkeit))

**Comment by jocarstensen** [comment]
@dzhwmeisner @se-lang zu h_calmis: wenn weniger als 50% der Monate **in einem Jahr** mit irgendeiner Episode gefüllt sind. Oder andersrum: Soll null sein wenn pro Jahr mindestens 50 % der Monate mit irgendeinem Episodentyp gefüllt sind.

@andreaschu Ich glaube das müsste so passen. Die Namen der Cal-Seiten sind eigentlich egal, die brauchen wir ja nur an wenigen Punkten und solange die Namen der Hilfsvariablen sind wie im ersten Post, sollte alles klappen. Die Transitions in die Kalendarien können ja entsprechend angepasst werden.

**Comment by jocarstensen** [comment]
1. Die Monatslabels überschneiden sich bei kleinen Bildschirmen wieder schrecklich. Können wir es wieder so machen wie im letzten Jahr, dass die labels auf vertikale Ausrichtung springen, sobald sie nicht mehr überschneidungsfrei dargestellt werden können?

2. Bitte einen horizontalen Trennstrich zwischen die Jahre.

**Comment by jocarstensen** [comment]
4. In der Horizontalen haben die Monatslabels auf meinem Smartphone eine viel zu kleine Schriftgröße (Android 8.1.0, Browser: Firefox Klar 8.0.23).

Anbei: Screenshots zu Issues 1 und 4
![Screenshot_20191113-135201](https://user-images.githubusercontent.com/35771616/68765611-7847a180-061d-11ea-83f0-8b62960624bf.png)
![Screenshot_20191113-135217](https://user-images.githubusercontent.com/35771616/68765612-7847a180-061d-11ea-9845-d0f6946d6acb.png)
![Screenshot_20191113-135310](https://user-images.githubusercontent.com/35771616/68765614-7847a180-061d-11ea-88ef-de14453340de.png)

**Comment by se-lang** [comment]
@dzhwmeisner ich habe leider noch eine Hilfsvariable aus den Kalendarien übersehen:
h_ausbakt=1 if Ausbildung im Dezember 2019 ausgewählt
h_ausbakt=0 if Ausbildung im Dezember 2019 _nicht_ ausgewählt

**Comment by dzhwmeisner** [comment]
cohort1h_calmis2018
cohort1h_calmis2019
cohort1h_nohaupt
cohort1h_alofam
cohort1h_studium
cohort1h_ausb
cohort1h_erwerb
cohort1h_ausbakt
cohort2h_calmis2018
cohort2h_calmis2019
cohort2h_nohaupt
cohort2h_alofam
cohort2h_studium
cohort2h_ausb
cohort2h_erwerb
cohort2h_ausbakt

sind eingebaut

**Comment by jocarstensen** [comment]
@dzhwmeisner Hat es technisch zwingende Gründe, dass wir die HVs jetzt jeweils doppelt, also einmal pro Kohorte haben? Wir brauchen sie einmal, ohne Präfix "cohortX". Außerdem wäre es uns lieber, wenn sie auf der Seite zwischen_k getriggert werden könnten, damit wir nicht jeweils eine zusätzliche Zwischenseite pro Kohorte hätten (s. #62 ).

**Comment by jocarstensen** [comment]
Die offenen Punkte sind auf die Issues #62 und #100 verteilt. Ich lasse dieses Issue trotzdem offen für die Screenshots.

**Comment by jocarstensen** [comment]
Brauchen wir mittlerweile nicht mehr

**Comment by jocarstensen** [comment]
Bitte für beide Kohorten in der Tätigkeitsliste "Berufsausbildung" durch "Berufausbildung, Umschulung, Volontariat" ersetzten.

**Comment by jocarstensen** [comment]
sieht gut aus, vielen dank
