### ISSUE TITLE
Zeitplan

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#27]
Der im Sommer abgestimmte Zeitplan der Studie sieht einen Feldstart am 16.12. vor. Dieser Termin ist nicht verschiebbar. Wir rechnen mit einem Bedarf von mindestens vier Wochen für Testung und Korrektur. Darum die folgenden Fragen:

- Bis wann können wir mit der Umsetzung der noch offenen PVs rechnen?
- Wann werden die bereits als QML gelieferten Module auf den Testserver geladen?
- Wann werden die noch offenen Issues umgesetzt?

**Comment by andreaschu** [comment]
> Heißt das, wir können Anfang nächster Woche mit den noch ausstehenden Modulen zum Testen rechnen?

Ich hoffe es.

**Comment by jocarstensen** [comment]
Ich will nicht nerven, aber wir brauchen wirklich langsam sehr dringend genauere Rückmeldung zum Zeitplan. Können wir ein Update zu folgenden Punkten haben (wann können wir womit rechnen):

- Modul Selbständige
- Modul Studium
- Modul Praktikum - Epsioden
- Modul Studium - Episoden
- Modul Weiterbildung

- Rückmeldung zu offenen Punkten (s. Issue 28)

- Laufende Überarbeitungen und Programmierfehler

**Comment by jocarstensen** [comment]
Push!

**Comment by woisch** [comment]
Wir bitten um Rückmeldung zu den Fragen von Johann.

**Comment by jocarstensen** [comment]
Hier gibt es nichts mehr zu tun.
