### ISSUE TITLE
Rückmeldung offene Punkte

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#28]
Wir brauchen noch Rückmeldung zu den folgenden Punkten:

- Eingabe Kalendarium mobile Devices (Start und Ende antippen)
- Fortschrittsbalken: Klappt das so wie vorgeschlagen, wenn wir die Artwork liefern? Geht es als Overlay für mobile devices?
- Reduzierung des Whitespace auf mobiler Darstellung (unnötiges Scrollen reduzieren)
- Implementierung eines Split-Half-Verfahrens für lange Item-Batterien: Was geht und was sind die Voraussetzungen?

**Comment by jocarstensen** [comment]
Push!

**Comment by dzhwmeisner** [comment]
> Eingabe Kalendarium mobile Devices (Start und Ende antippen)

Bis dato funktioniert nur DragNDrop

**Comment by jocarstensen** [comment]
Heißt "bis dato", dass es bis zu unserem Feldstart nicht mehr möglich ist, das umzusetzen?

Was ist mit Punkt drei der Auflistung (Whitespace)?

**Comment by dzhwmeisner** [comment]
Bis dato heisst, dass dieses Verhalten noch nicht implementiert ist. Wird implementiert, sobald Zeit dafür zur Verfügung steht.

Für Punkt drei bräuchten wir mal ein paar beispielhafte Screenshots, um zu verstehen was ihr meint.

**Comment by jocarstensen** [comment]
@heikQ Kannst Du Screenshots als Beispiel bringen?

**Comment by dzhwmeisner** [comment]
> Eingabe Kalendarium mobile Devices (Start und Ende antippen)
ist implementiert und wird im nächsten Rollout verfügbar sein.

**Comment by woisch** [comment]
> 
> 
> > Eingabe Kalendarium mobile Devices (Start und Ende antippen)
> 
> ist implementiert und wird im nächsten Rollout verfügbar sein.
@dzhwmeisner 
Habe es eben auf meinem mobilen Endgerät getestet. Funktioniert noch nicht, ich muss jeden Monat einzeln antippen bisher...

**Comment by heikQ** [comment]
Hier die Screenshots zu Problem white space
![grafik](https://user-images.githubusercontent.com/52539440/69554813-9f4d8e00-0fa2-11ea-9ba8-4a4407fa0edb.png)

**Comment by jocarstensen** [comment]
Spandau ist vielleicht hip genug?

Von: heikQ [mailto:notifications@github.com]
Gesendet: Montag, 25. November 2019 16:47
An: dzhw/SLC-IntEr
Cc: Carstensen, Johann; Author
Betreff: Re: [dzhw/SLC-IntEr] Rückmeldung offene Punkte (#28)


Hier die Screenshots zu Problem white space
[grafik]<https://user-images.githubusercontent.com/52539440/69554813-9f4d8e00-0fa2-11ea-9ba8-4a4407fa0edb.png>

**Comment by jocarstensen** [comment]
Hoppla, falsches Fenster.

Von: heikQ [mailto:notifications@github.com]
Gesendet: Montag, 25. November 2019 16:47
An: dzhw/SLC-IntEr
Cc: Carstensen, Johann; Author
Betreff: Re: [dzhw/SLC-IntEr] Rückmeldung offene Punkte (#28)


Hier die Screenshots zu Problem white space
[grafik]<https://user-images.githubusercontent.com/52539440/69554813-9f4d8e00-0fa2-11ea-9ba8-4a4407fa0edb.png>

**Comment by dzhwmeisner** [comment]
@woisch Ich habe zum Besseren Verständnis einen anderen Cursor zur Auswahl des Episodenendes eingebaut. Ansonsten bräuchte ich mehr Details wie Gerät, Betriebssystem, Browser, Auflösung,...

**Comment by woisch** [comment]
Ich teste mit nem Iphone 7 (iOs 13.2.3), Safari Browser.
Das mit dem Cursor versteh ich nicht ganz...Hab keinen aufm Smartphone :)

**Comment by se-lang** [comment]
@dzhwmeisner  @woisch Hab es gerade Desktop (Win, Firefox 70.0) und Smartphone (Samsung Galaxy S7, Firefox 68.2.1) getestet und bei mir funktioniert es. Man muss es erstmal kapieren was da passiert und wie es funktioniert, weil man nicht sieht, dass man beim ersten Tippen das Beginndatum ausgewählt hat (dafür haben wir aber ja auch die Erklärungsseiten geplant, wenn wir die gut hinbekommen sollte das kein Problem mehr sein). Dann ist das finde ich aber schon eine riesige Verbesserung was die Usability angeht! Der Kalender lässt sich damit viel schneller ausfüllen als vorher.

**Comment by woisch** [comment]
Jetzt geht es bei mir auch mit dem Start und Ende antippen! Finde das auch eine deutliche Verbesserung!
Vielen Dank!

**Comment by jocarstensen** [comment]
Für Fortschrittsbalken und Split-Half gibt es eigene Issues. Damit bleibt hier nur noch der Whitespace übrig. Gibt es dazu noch Neuigkeiten?

**Comment by dzhwmeisner** [comment]
Ist das Whitespace Problem noch aktuell?

**Comment by jocarstensen** [comment]
@heikQ Ist das Whitespace Problem noch aktuell? Ich hab da gerade keinen Überblick.

**Comment by heikQ** [comment]
@jocarstensen whitespace ist erledigt, wenn das hier das einzige noch offene ist, kann zu

**Comment by jocarstensen** [comment]
ok
