### ISSUE TITLE
beg_11. Units doesn't work for responsive design

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#3]
![image](https://user-images.githubusercontent.com/48087320/65749253-14692800-e106-11e9-9158-82c33a552c30.png)

**Comment by SilinaKowalewski** [comment]
Set as two questions?

**Comment by jocarstensen** [comment]
@se-lang auch für Dich relevant
@SilinaKowalewski gibt es hierzu schon was neues?

**Comment by woisch** [comment]
Liebe alle,

das Issue ist ja schon etwas älter. Inzwischen haben wir das Modul Einstieg überarbeitet und die oben dargestellte Frage (Panel 2015.4) ist gar nicht mehr Bestandteil der  PV/wurde schon gelöscht: 
https://github.com/dzhw/SLC-IntEr/issues/13#issue-500975087

**Comment by se-lang** [comment]
@jocarstensen: Bei mir ist es ja eine einfache Single Choice und keine Matrix, das dürfte dann eigentlich kein Problem machen.

**Comment by jocarstensen** [comment]
Ok, das trifft auf mich genauso zu.
@SilinaKowalewski Sofern das Problem nicht irgendwoanders noch auftaucht, kann das Issue geschlossen werden.

**Comment by SilinaKowalewski** [comment]
Dieses Problem betrifft tatsächlich nur Matrix-Fragen inkl. Units. Solltet ihr sonst keine Matrix-Fragen in diesem Format haben hat sich das Problem erledigt und das Issue kann geschlossen werden :)

**Comment by jocarstensen** [comment]
Was ich hiermit tue
