### ISSUE TITLE
Modul Studium, Skalen, Transition in stu_19 und anderes

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#30]
- [x] Neue (differenziertere) Transition auf Seite stu_19
 https://github.com/dzhw/SLC-IntEr/commit/7af971436597c4277c3ac3f40244ea77f7c3c955

- [x] stu_01: Antwortoptionen in vertikal geändert

- [x] stu_17: AO geändert
- [x] stu_18: AO bitte wie in PV umsetzen

**Comment by SilinaKowalewski** [comment]
Änderungen wurden umgesetzt und können nach einem neuen Roll-Out (heute mittag) getestet werden.

**Comment by heikQ** [comment]
@SilinaKowalewski Das ganze Modul ist jetzt (teilweise schon mit den überarbeitungen da? weil vorher ging es nur zu einem teil

**Comment by woisch** [comment]
wir brauchen wirklich dringend das Modul Studium zum Testen. Momentan ist alles ab Seite stu_90 noch nicht erreichbar.
Wann können wir damit rechnen?

**Comment by andreaschu** [comment]
wir sind noch immer auf Fehlersuche, gehen aber davon aus, den Testlink heute noch aktualisieren zu können.

**Comment by SilinaKowalewski** [comment]
Das Modul ist nun komplett fertig und ausgerollt. 

Kann das Issue somit geschlossen werden?
