### ISSUE TITLE
Implementierung eines Split-Half-Verfahrens - Brainstorming

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#31]
**_Problem:_** 
Pro Proband soll nur die Hälfte der Items angezeigt werden. Welche Items angezeigt werden soll zufällig sein.

**_Anlegen von Hilfsvariablen in entsprechender Anzahl (Anzahl aller Items ingesamt)_**

`variable="hv_it1" value="zofar.randomOf(zofar.list('0','1'))"`
`variable="hv_it2" value="zofar.randomOf(zofar.list('0','1'))"`
`variable="hv_it3" value="zofar.randomOf(zofar.list('0','1'))"`
`variable="hv_it4" value="zofar.randomOf(zofar.list('0','1'))"`
`variable="hv_it5" value="zofar.randomOf(zofar.list('0','1'))"`
`variable="hv_it6" value="zofar.randomOf(zofar.list('0','1'))"`

...

**_Verwenden der Hilfsvariablen_**
`<zofar:item uid="i1" visible="zofar.asNumber(hv_it1)==1">`
`<zofar:item uid="i2" visible="zofar.asNumber(hv_it2)==1">`
`<zofar:item uid="i3" visible="zofar.asNumber(hv_it3)==1">`
`<zofar:item uid="i4" visible="zofar.asNumber(hv_it4)==1">`
`<zofar:item uid="i5" visible="zofar.asNumber(hv_it5)==1">`
`<zofar:item uid="i6" visible="zofar.asNumber(hv_it6)==1">`

**Comment by dzhwmeisner** [comment]
wir bauen eine Zofar-Funktion die zufällig n aus m Elementen wählt. Die Ergebnisliste wird anhand eines variable-Trigger in eine Hilfsvariable geschrieben. Jedes Item bekommt eine visible, in der geprüft wird, ob die Item-Id in der Ergebnisliste vorhanden ist

**Comment by jocarstensen** [comment]
Das heißt für unser Vorhaben?

**Comment by SilinaKowalewski** [comment]
Das wir eine Lösung finden werden :) 

Aktuell sitzen Christian und Viktor allerdings noch an der Navigationsleiste.

**Comment by andreaschu** [comment]
Wir könnten das auch über Preloads machen
pid PRELOADit1 PRELOADit2 PRELOADit3 […] PRELOADit12 

| pid | PRELOADit1 | PRELOADit2 | PRELOADit3 |  […] | PRELOADit12 |
|---|---|---|---|---|---|
| 1 | 0 | 1 | 1 | […] | 0 |
| 1 | 1 | 1 | 0 | […] | 0 |
| 0 | 0 | 1 | 1 | […] | 0 |

Dann könnten wir die Zuordnung im Vorfeld machen und darauf achten, dass die Anzahl der angezeigten Items immer gleich ist. Das ginge alles sogar mit Excel und die Einblendbedingung wäre für jedes Item: `visible="PRELOADit*=1"`

**Comment by jocarstensen** [comment]
Im Vergleich zu allen anderen Issues hat dieses 3,5 Wochen vor Feldstart geringe Priorität. Falls wir am Ende noch Zeit dafür haben, können wir uns drum kümmern. Jetzt muss erstmal die Befragung lauffertig werden.

**Comment by andreaschu** [comment]
okay. Danke für die Rückmeldung.

**Comment by woisch** [comment]
@jocarstensen kann zu? betraf glaube ich die Lehr-Lernumwelt?

Grüße
Aufräum-Woisch ;-)

**Comment by jocarstensen** [comment]
Allerdings
