### ISSUE TITLE
Direktzugriff auf QML per SVN

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#32]
Beim Pretest des Episodenmoduls hatten wir Direktzugriff auf die QMLs. Könnt Ihr den für Sebastian und mich wieder einrichten?

Danke!

**Comment by se-lang** [comment]
Zugangsdaten hab ich noch und SVN ist auch installiert.

**Comment by jocarstensen** [comment]
dito

**Comment by SilinaKowalewski** [comment]
Kann das Issue geschlossen werden?

**Comment by jocarstensen** [comment]
ja
