### ISSUE TITLE
Studium: mas_07

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#33]
https://github.com/dzhw/SLC-IntEr/blob/master/Modul_Studium.md#mas_07

hier ist nicht ganz klar, was programmiert werden soll. Es sieht aus wie eine Einfachauswahl mit offenen Feldern. In der Instruction steht, "Bitte tragen Sie die Angebote/Quellen ein **und bewerten Sie** deren Nützlichkeit." --> fehlt hier noch eine Bewertungs-Skala?

**Comment by woisch** [comment]
Ja, hier fehlt noch die Skala in der PV:
ao1: (1) sehr nützlich
ao2: (2)
ao3: (3)
ao4: (4)
ao5: (5) überhaupt nicht nützlich

Passt ihr die PV entsprechend an oder soll ich das tun?

Silina hatte Ende September einen solchen Fragetyp schon einmal für mich testweise umgesetzt und mir einen Screentshot als Beispiel geschickt.

**Comment by woisch** [comment]
![Unbenannt](https://user-images.githubusercontent.com/53002476/68376230-8f335300-0148-11ea-820e-320aebc05363.PNG)

**Comment by andreaschu** [comment]
Danke.
