### ISSUE TITLE
Updates SozDem

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#34]
Modul Sozdem updaten:
https://github.com/dzhw/SLC-IntEr/commit/1d32dd15535d05657be00ac8f63c215ff79b5ab8

- [x] msg06 Transition geändert und Softforce entfernt
- [x] msg_08 Komma im Hinweistext ergänzt. der Soft-Rangecheck (wenn Zahl kleiner 0 oder größer) funktioniert hier nicht bzw wird nicht eingeblendet. Wenn auf die nächste Seite und dann  wieder zurückgehe, sehe ich den Text aber.
- [x] msg_09 Hinweistext (is: "Geben Sie bitte...") soll unter dem Fragetext erscheinen (q1: Wann wurde dieses Kind geboren?)

**Comment by woisch** [comment]
Bitte außerdem noch prüfen:
Momentan gibt es scheinbar die Seite msg_00 nicht, wie in der PV vorgesehen. Ich bekomme immer die Meldung "Seite existiert nicht"

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Um den Soft-Rangecheck werde ich mich nochmal kümmern. Ich meine, der hätte schon mal funktioniert.

**Comment by woisch** [comment]
msg_08: is hinzugefügt
msg_09: is geändert. Ein Teil des Hinweistextes erscheint zur Zeit immer noch über dem Fragetext, bitte nochmal prüfen und an die richtige Stelle (unter der Frage) setzen.
https://github.com/dzhw/SLC-IntEr/commit/54a2aae6eb0e78c87c5b6cbb43a540ba6710b5b1

**Comment by woisch** [comment]
Die Änderungen oben sind umgesetzt, alles ok.

Bitte noch auf msg_08 die Instruction und die Transition ändern:
https://github.com/dzhw/SLC-IntEr/commit/fdb0cf112a80375f340b330ee3d915b8762a6d87

**Comment by woisch** [comment]
@SilinaKowalewski 
Auch hier muss noch eine Änderung gemacht werden auf msg_08

**Comment by SilinaKowalewski** [comment]
```
GOTO msg_09 IF **kinder_154=1**

GOTO msg_10 IF kinder_154=2 OR kinderanz_154=MISSING OR **kinderanz_154=0**
```

Diese beiden Bedingungen "widersprechen" sich. Dadurch, dass bei jeder Angabe im offenen Textfeld automatisch der Button ausgewählt wird, gilt für kinderanz_154=0 direkt auch kinder_154=1.

**Comment by SilinaKowalewski** [comment]
Würde die Bedingungen nun so einbauen. Das ist ja das, was du möchtest @woisch, oder?

```
GOTO msg_09 IF (kinder_154=1 and kinderanz_154 != 0)

GOTO msg_10 IF kinder_154=2 OR kinderanz_154=MISSING OR (kinder_154=1 and kinderanz_154 == 0)
```

**Comment by woisch** [comment]
sorry für die Verwirrung. Ich will die Missing Gruppe nun aber doch auf msg_09 schicken! Müsste dann also so sein:

GOTO msg_09 IF (kinder_154=1 and kinderanz_154 != 0) OR (kinder_154=1 AND kinderanz_154==MISSING)

GOTO msg_10 IF kinder_154=2  OR (kinder_154=1 and kinderanz_154 == 0)

**Comment by SilinaKowalewski** [comment]
Nun fehlt aber noch eine Transition für kinder_154=MISSING

**Comment by woisch** [comment]
so müsste es aber gehen:

GOTO msg_09 IF (kinder_154=1 and kinderanz_154 != 0) OR (kinder_154=1 AND kinderanz_154==MISSING)

GOTO msg_10 IF kinder_154=2 OR kinder_154==MISSING OR (kinder_154=1 and kinderanz_154 == 0)

**Comment by SilinaKowalewski** [comment]
Oder soll dann GOTO msg_09 IF kinder_154=MISSING AND kinderanz_154<>MISSING greifen?

**Comment by SilinaKowalewski** [comment]
Alles klar, habe das nun erstmal so umgesetzt. Wird aber im nächsten Roll-Out noch nicht mit aktualisiert sein.

**Comment by SilinaKowalewski** [comment]
Die Änderungen kann nun geprüft werden. Es sieht aber auf den ersten Blick so aus, als würde nun alles gut funktionieren.

**Comment by woisch** [comment]
Transition ist ok so!

**Comment by woisch** [comment]
nun geht auf msg_08 wieder gar nix mehr. Bleibe immer hängen...
