### ISSUE TITLE
User Agent String: wiederholter Trigger?

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#35]
Ich habe gerade in altem Code aus unserem Pretest mitten im Arbeitslosigkeitsmodul folgende Zeilen, und zwar in jeder Schleife:

>         <zofar:triggers>
>             <zofar:variable variable="uas" value="zofar.userAgent()"/>
>         </zofar:triggers>

WIrd der uas im Verlauf der Befragung üblicherweise (mehrfach) überschrieben? Wie wird festgelegt, auf welchen Seiten das passiert? In meinen Augen wäre es ratsam, das auf Seiten zu tun, die von allen besucht werden.

**Comment by andreaschu** [comment]
es wird genauso festgelegt, auf welchen Seiten das passiert und ja, sinnvoll wäre es, das auf den Seiten zu tun, die von allen besucht werden oder kurz bevor es relevant wird für Einblendungen oder Weiterleitungen, dann müssten es auch nicht alle Befragten sein, sondern nur die target group.

**Comment by jocarstensen** [comment]
Wir haben den UAS meines Wissens nicht zum Filtern oder Einblenden benutzt. Darum bin ich ja so verwirrt, dass das dort im Code steht. Gibt es noch andere mögliche Gründe dafür?

**Comment by andreaschu** [comment]
> Wir haben den UAS meines Wissens nicht zum Filtern oder Einblenden benutzt.
Kann ich mir auch nicht vorstellen. 
Es scheint im Template gelandet zu sein und damit auch in jeder Schleife. Warum, weiß ich nicht.

**Comment by jocarstensen** [comment]
Das Modul wurde nicht mit Templates gebildet sondern damals komplett von Kim programmiert. Aber es ging mir auch eigentlich nur um die Frage, ob die Zeilen rauskönnen. So wie ich es verstehe müssen sie sogar, damit die UAS von Personen mit und ohne AL-Episoden vergleichbar sind.

**Comment by andreaschu** [comment]
Es ist nur sinnvoll, wenn die Variable die letzte Version anzeigen soll (auch für die Abbrecher). Aber dann müsste es auf jeder Seite rein. Ansonsten raus.

**Comment by jocarstensen** [comment]
Vielleicht war das mal die Idee, aber dann war sie nur in dem Modul umgesetzt. Dann fliegt es jetzt raus.
