### ISSUE TITLE
Episoden: selbständige ET - QML

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#36]
Laut Wiki ist das sET-Modul fertig programmiert. Ist das richtig? Nochmal: Ich muss das noch generieren, also brauche ich die QML.

**Comment by andreaschu** [comment]
ja, aber noch nicht getestet. Wir müssen noch mal drüber schauen und ggf. Seiten anpassen, bevor Du es duplizierst.

**Comment by jocarstensen** [comment]
Wie ist der Stand jetzt? Kann ich davon ausgehen, dass Ihr Bescheid sagt, wenn ich das Modul duplizieren kann?

**Comment by andreaschu** [comment]
Variablen werden mehrmals definiert:
h_embe12
h_emcd12
h_emaf12
h_emdc12
h_emeb12

Ob es dupliziert werden kann, hängt vom Testen ab.

**Comment by jocarstensen** [comment]
Nein, ist noch nicht dupliziert und nicht veraltet. Aber die Variablen, die Du auflistest, kommen in der PV und in dem QML nicht vor. Meinst Du nsET (questionnaire17)?

**Comment by andreaschu** [comment]
Oh, Module verwechselt. Ja, es ging um nsET

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden? Haben ja mittlerweile einzelne Issues für dieses Modul.

**Comment by jocarstensen** [comment]
ja
