### ISSUE TITLE
Tokenliste erstellen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#38]
Wir benötigen für die Adressaufbereitung möglichst schnell eine Tokenliste von euch für 11.400 Tokens zur Befragung. Die Tokens müssen teilweise auf Fragebögen gedruckt werden, daher eilt es. 
Wenn wir die Liste von euch erhalten haben, bekommt ihr von uns die Zuordnung der Tokens zu der Preloadvariable "cohort" zurückgemeldet.

Bitte bei der Tokenerstellung unbedingt darauf achten, dass Verwechslungen von Buchstaben ausgeschlossen sind ("Null" und großes "O"; "I" und kleines "L").

Bitte die Tokens per Mail senden (an Johann und mich) und nicht in Github einstellen (da offenes Repository)

**Comment by andreaschu** [comment]
Werden erst mal nur die Token benötigt? Ansonsten bräuchte ich schon den Namen der Befagung im Link.

**Comment by woisch** [comment]
Wie eben besprochen: 
Erstelle uns gleich 12.000 Token, das ist dann auch die Gesamtzahl der benötigten Token.
Wir nehmen erstmal nur die Token. Den Namen für die Befragung reichen wir nach.

Bitte 7-stellige Tokens mit einem großen "P" als Prefix.

Tokenliste bitte per Mail zusenden an Johann und mich.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?
