### ISSUE TITLE
aus_05: Fragetyp

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#40]
It3 sollte statt ja/nein/weiß nicht eine offene Angabe haben. Muss vermutlich als eigene Frage statt als it3 programmiert werden?

![grafik](https://user-images.githubusercontent.com/35771616/68406297-ddb11380-0181-11ea-8533-79635c7ffd66.png)

**Comment by woisch** [comment]
@SilinaKowalewski: sollte am Ende etwa so aussehen

![Unbenannt](https://user-images.githubusercontent.com/53002476/68408457-b0fefb00-0185-11ea-8861-19f7940c1f23.PNG)

**Comment by SilinaKowalewski** [comment]
Sieht nun so aus. Passt das vom Aufbau der Frage?

![image](https://user-images.githubusercontent.com/48087320/68753119-bd130e80-0604-11ea-9070-c4835de97fd5.png)

Am Layout können wir natürlich noch ein bisschen was anpassen.

**Comment by bafranke** [comment]
Der Aufbau ist ok. Kannst du noch folgende Layoutänderungen vornehmen:
- ao's näher zusammenrücken (idealerweise stehen "ja" und "nein" eng zusammen, "weiß noch nicht" ist etwas abgerückt)
- Linie zwischen ja und nein entfernen
- Höhe der Zeilen verringern
- items mittig ausrichten

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by bafranke** [comment]
@vdick: die items sind immer noch oben ausgerichtet und ist es möglich, die ao's näher zusammen zu rücken?

**Comment by andreaschu** [comment]
@bafranke bitte noch mal testen.
![grafik](https://user-images.githubusercontent.com/30111489/69419258-669c8300-0d1c-11ea-859a-3cef29933d70.png)

**Comment by bafranke** [comment]
besser, danke! Kannst du das Freitextfeld noch über die Länge des längsten Items ziehen, so wie bspw. bei stu44? 
![grafik](https://user-images.githubusercontent.com/56022369/69421488-7074b500-0d21-11ea-809f-7df1a7410bbc.png)


Und noch eine grundsätzliche Frage: Ist es möglich, die Kategorie "weiß nicht" mit größerem Abstand abzusetzen? Oder gibt es aus eurer Sicht Punkte, die dagegen sprechen? Wenn möglich, würden wir die betreffenden Fragen sammeln und noch einmal in einem gesonderten issue melden.

**Comment by SilinaKowalewski** [comment]
@bafranke: Die "weiß nicht"-Kategorie mit größerem Abstand zu setzen ist leider nicht möglich.

**Comment by woisch** [comment]
Das ist schade, dass das nicht geht. Ist dann aber scheinbar nicht zu ändern.

In eurer Anleitung (Konventionen für die Erstellung einer Programmieranleitung) steht diese Möglichkeit drin  (unter "Formatierung"). Solltet ihr dann ggf. anpassen.

**Comment by bafranke** [comment]
bitte noch anpassen:

- [ ] Freitextfeld noch über die Länge des längsten Items bzw. die Breite der ersten Spalte ziehen, so wie bspw. bei stu44

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
@bafranke 
kann zu oder?

**Comment by bafranke** [comment]
Sieht es bei dir vernünftig aus? Das Freitextfeld hängt bei mir immernoch irgendwo in der Luft und ist in einer komischen Länge?!

Von: woisch [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. November 2019 18:29
An: dzhw/SLC-IntEr
Cc: Franke, Barbara; Mention
Betreff: Re: [dzhw/SLC-IntEr] aus_05: Fragetyp (#40)


@bafranke<https://github.com/bafranke>
kann zu oder?
