### ISSUE TITLE
Msg: Eingabe in msg_02 und msg_03

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#41]
1.: Bei Datumsvariablen haben wir normalerweise DropDowns mit gelabelten Monaten. Ansonsten ist unklar ob man Buchstaben oder eine Zahl eingeben muss und wie viele Stellen die Zahl haben soll.

2.: Ich würde für die PLZ einen Rangecheck einfügen (10000-99999). Aktuell kann ich auch "1" als PLZ eingeben.

**Comment by se-lang** [comment]
Rangecheck von PLZ darf nur 1000-99999 sein (oben eine 0 zu viel), im Episodenmodul haben wir folgende Angaben:
```
type="number" validationMessage="Bitte geben Sie eine gültige Postleitzahl ein." 
maxLength="5" maxValue="99999" minValue="1000"
```

**Comment by woisch** [comment]
- [ ] Bitte den Rangecheck bei der Postleitzahl einfügen (msg_03).
- [ ] Bitte noch einen kleinen Fehler auf msg_08 korrigieren

https://github.com/dzhw/SLC-IntEr/commit/45870947fb73de004121918052c682f0f47e63c2

**Comment by woisch** [comment]
Rangecheck funktioniert jetzt.
