### ISSUE TITLE
beg_06: Instruction inkonsistent

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#42]
„Bitte jeweils den zutreffenden Skalenwert ankreuzen.“
Das steht bei den anderen Matrixabfragen nicht. Wie soll das angepasst werden?

**Comment by SilinaKowalewski** [comment]
Gibt es hierzu schon news?

**Comment by woisch** [comment]
@jocarstensen In 2015.4 ist das so im Papierfragebogen vorgesehen und würde ich auch gerne drin lassen. In 2018.1 und 2018.2 gab es den Zusatz nicht mehr.
Wir können das über eine visible condition für cohort2 ausblenden, wenn ihr das nicht haben wollt?

**Comment by jocarstensen** [comment]
Es ging mir auch eher um die Inkonsistenz über den gesamten Fragebogen hinweg. Eigentlich müsste man es entweder überall oder nirgendwo schreiben. Für 18.3a würde ich ihn also gern ausblenden, wenn Du ihn weiter behalten möchtest.

**Comment by woisch** [comment]
Gerade gesehen, dass es sowieso getrennte Seiten sind für die Kohorten. Habe die Instruction für cohort 2 rausgenommen.

@SilinaKowalewski : Bitte beg_07 anpassen:
https://github.com/dzhw/SLC-IntEr/commit/d2f5da22d2f0925c127e33688425991834144164

**Comment by woisch** [comment]
ist umgesetzt, kann geschlossen werden.
