### ISSUE TITLE
Matrixfragen: vertikale Ausrichtung der Items

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#43]
Bei den Matrixfragen ist die vertikale Ausrichtung der Itemtexte uneinheitlich. Sie sollten in meinen Augen an den Buttons/Checkboxes mittig ausgerichtet sein.

![grafik](https://user-images.githubusercontent.com/35771616/68407467-e99dd500-0183-11ea-9903-42871649f2c6.png)

**Comment by SilinaKowalewski** [comment]
@vdick: 

Kannst du hier die Items mittig zur Skala setzen?

**Comment by bafranke** [comment]
Dieses Layoutproblem besteht, soweit ich es überblicke, noch in den Modulen Ausbildung, Studium und Gesundheit. Im Einstiegs-Modul sind die Items passend ausgerichtet. Könnt ihr das übergreifend für die Module umsetzen oder braucht ihr eine Liste der betroffenen Seiten?

**Comment by vdick** [comment]
Bitte noch einmal testen, sollte bereits umgesetzt sein. Falls es noch Problemfälle gibt, bitte die Pages hier auflisten

**Comment by bafranke** [comment]
Weiterhin scheint es in den Modulen Ausbildung, Studium und Gesundheit nicht zu funktionieren. z. B. auf folgenden Seiten (betrifft aber soweit ich es überblicke alle entsprechenden Seiten in den genannten Modullen):
stu_17, stu_18, stu_41, stu_42
gsh_02
aus_04
![grafik](https://user-images.githubusercontent.com/56022369/69850526-cdbbb980-127f-11ea-9ffe-08d473ec6160.png)
