### ISSUE TITLE
beg_10: horizontale Ausrichtung der AOs

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#44]
Bitte die AOs horizontal mittig über den Checkboxen ausrichten.

![grafik](https://user-images.githubusercontent.com/35771616/68407525-03d7b300-0184-11ea-9209-623427bf646c.png)

**Comment by SilinaKowalewski** [comment]
@vdick: 

Auch hier müssen die Items ausgerichtet werden.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
Ausrichtung der ao's ist OK.

Allerdings ist die vertikale Ausrichtung des ersten Items noch komisch (der Ihnen bei einem Umzug helfen würde? ). Bitte auch dieses wie die anderen Items auf Höhe der Checkboxen ausrichten!

**Comment by woisch** [comment]
Das erste Item ist jetzt genauso ausgerichtet wie der Rest, ok!
Dennoch sind die Items immer noch nicht ganz auf Höhe der Kästchen ausgerichtet, sondern noch etwas zu tief..

![grafik](https://user-images.githubusercontent.com/53002476/69724106-78669780-111b-11ea-8cd5-e0875422597c.png)

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
danke!
