### ISSUE TITLE
Update Modul Einstieg

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#45]
ee7caaf
außerdem Programmierfehler (bitte ändern):

- [x] in beg_06 und beg_07: ao "weiß nicht" - wurde programmiert als "weiß ich nicht" - bitte "ich" streichen!
- [x] tr von beg_08 in nächstes Modul (cohort=2) funktioniert noch nicht, hier bleibt man stecken

Update-Doku:
überflüssige IF-Bedingungen in tr gelöscht
ao in beg_10 aktualisiert
beg_06 und beg_07 gegendert
Löschung item in beg_10 (wurde bereits aufgrund eines anderen issues umgesetzt, Änderung in Code dient nur der Übersichtlichkeit und kann ignoriert werden)
Rechtschreibfehler in beg_04

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können geprüft werden.

**Comment by bafranke** [comment]
Danke, ich prüfe es noch heute!

**Comment by bafranke** [comment]
Änderungen sind geprüft und passen soweit (Danke!), folgende (weitere) Punkte sind noch aufgefallen:

- [ ] Beg_01: Anfang und Ende der Skalenbeschriftung verschwinden, wenn das Fenster zu klein ist

- [ ] Beg_01: springt nicht in gedrehte Ansicht um ->responsives Design

- [ ] Beg_06: Beschriftung ao 5 und 6 überlappen sich bei schmalem Bildschirm 

- [ ] bei Itembatterien: vertikale Anordnung Items und Antwortkästchen – nicht in einer Linie, bitte mittig zentrieren
- [ ] 859b5cb (beg_02: is: Rechtschreibung)

**Comment by SilinaKowalewski** [comment]
@vdick: Kannst du dir die Layout-Probleme mal anschauen?

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by bafranke** [comment]
getestet, funktioniert, Danke!
