### ISSUE TITLE
Update Modul_Ausbildung.md

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#46]
872bca5

außerdem Programmierfehler (bitte korrigieren):

- [x] aus_01: tr GOTO aus_02 IF beau_154=1  funktioniert nicht (auch mit bisheriger cohort-Bedingung)

- [x] aus_03a: ao10:4: (4) (wird derzeit ohne 4 als () angezeigt)

- [x] Aus_05: tr: GOTO [NEXT MODUL] funktioniert nicht, es wird zu aus_06 weitergeleitet. Nächstes Modul wäre Studium

Update-Doku:
überflüssige If-Bedingungen in tr gelöscht
tr in aus_02 aktualisiert (war korrekt programmiert, dient nur der Übersichtlichkeit, kann ignoriert werden)
it in aus_03 gelöscht
Rechtschreibfehler korrigiert

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können geprüft werden.

**Comment by bafranke** [comment]
Danke, ich prüfe es heute!

**Comment by bafranke** [comment]
9bfcb88

doku update:
tr angepasst
aus_01: in

**Comment by heikQ** [comment]
außerdem transition auf ausb_06 gefixed, bitte anpassen
https://github.com/dzhw/SLC-IntEr/commit/3019885e3af0b59900b79d224c737e48f0805137

**Comment by woisch** [comment]
aus_04: visible condition angepasst im Hinweistext
https://github.com/dzhw/SLC-IntEr/commit/3605b99e6458f353788991653d20cee64f80d8a9

**Comment by woisch** [comment]
aus_04: visible condition funktioniert, bitte aber den Hinweistext noch mal austauschen, der stimmt nocht nicht!

**Comment by bafranke** [comment]
funktioniert alles!
