### ISSUE TITLE
Anzeige der Antwortkategorien bei kleineren Bildschirmen

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#47]
Es gibt noch ein generelles Darstellungsproblem bei langen Antwortitems wenn der Bildschrim verkleinert wird: Bei einer bestimmten Breite überlappen sich bei einigen Fragen die ao’s (z. B. beg_07: „sehr schlecht“ und „weiß nicht“, aus_03a) bzw. werden die Anfänge und Enden der ao's verdeckt, sodass man sie nicht mehr lesen kann. Habt ihr einen Vorschlag, wie man das Problem lösen kann? 

![grafik](https://user-images.githubusercontent.com/56022369/68478047-35598880-022f-11ea-99df-c8aff28d9824.png)

![grafik](https://user-images.githubusercontent.com/56022369/68478056-3db1c380-022f-11ea-86d7-def3c1fcf716.png)

**Comment by SilinaKowalewski** [comment]
@vdick: Kannst du dir das Problem mal anschauen?

**Comment by andreaschu** [comment]
@bafranke es gibt fixe Umbruchpunkte, bei denen technisch etwas passiert. Dazwischen kann es, je nach Labellänge, zu Überlappungen kommen. Wir können nicht ausschließen, dass bei graduellen Verkleinerung des Browserfensters es zu Überlappungen kommt und ausschließlich Anpassungen für bestimmte Fenstergrößen/ Gerätetypen vornehmen.

**Comment by bafranke** [comment]
Ok. Danke für die Rückmeldung.
