### ISSUE TITLE
Update Modul Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#48]
Update in Modul Studium:
https://github.com/dzhw/SLC-IntEr/commit/966cce31cb4ccf9434b9f096d7ec1ad68448d176

- [x] Stu_04: ao5 ist falsch umgesetzt, bitte korrigieren: „sehr schwer (5)“ (wie in PV)

- [x] Stu_06: TRansitions angepasst

- [x] Stu_08: Transition angepasst

- [x] Stu_17: bei 3 Items fehlt ein Punkt am Ende

- [x] Stu_18: bei ao4 fehlt ein Punkt am Ende

- [x] Stu_19: bei ao7 bis ao10 sind die Klammern an den Labels nicht umgesetzt

- [x] Stu_41: Fragetext falsch. Müsste lauten: Wie stark ist Ihr Studiengang an Ihrer Hochschule charakterisiert durch ... (siehe PV)

- [x] Stu_41, stu_42, stu_43: bei ao2 bis ao4 sind die Klammern an den Labels nicht umgesetzt

- [x] Stu_44: ao6 ist nicht umgesetzt. Bitte wie in PV umsetzen (nur den Text „betrifft mich nicht“, ohne die „(6)“). Item 3 und 4 korrigiert.

- [x] Stu_45: Ausfüllanweisung (is) ergänzt. Gültigen Wertebereich angepasst für av1 und av2. Layout: Bitte Breite des Textfelds verringern, hier können nur 2-stellige Monatszahlen angegeben werden!
@vdick: Kannst du bitte die Textfelder verkürzen?

- [x] Stu_46: Zahlen vor dem Label entfernt für ao1-ao5

- [x] Stu_48: Einblendbedingung ergänzt. Fragetext angepasst. Überschrift entfernt

- [x] Stu_96: Klammern am Label der ao6 entfernt

- [x] Mas_05: Transition angepasst

- [ ] Mas_07: die Zahlen sollten links neben dem Textfeld für die offene Angabe stehen
@vdick: Kannst du mal schauen ob sich hier im CSS was anpassen lässt?

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können geprüft werden. 

Die Labels aller Fragen prüfen wir gerade nochmal systematisch anhand der PV und werde sie entsprechend umsetzen.

**Comment by woisch** [comment]
Bitte noch korrigieren (in der PV korrekt, aber falsch umgesetzt):
stu_44: Labels von ao2 bis ao5 sind falsch
stu_45: Wertebereich wurde nicht angepasst (sollte 1 bis 99 sein, statt 1 bis 12)
stu_96: Der Wert 6 (weiß ich nicht) soll optisch nicht mit den Skalenwerten 1 bis 5 durch die Linie verbunden sein. 
mas_11: Layout prüfen: Die beiden Überschriften brechen so um, dass der Text sich überlappt.

**Comment by SilinaKowalewski** [comment]
@woisch: 
Damit wir in der PV erkennen, dass ein Skalenpunkt nicht mit den anderen verbunden sein soll, muss er als Missing (mv:) definiert sein. In der Programmierung der stu_96 habe ich das nun angepasst :)

**Comment by woisch** [comment]
Ok, danke!

**Comment by woisch** [comment]
Hier ist noch ein Punkt zum Layout offen (mas_07)

**Comment by woisch** [comment]
Hier ist auch noch ein weiterer Layout-Punkt offen:
mas_11: Layout prüfen: Die beiden Überschriften brechen so um, dass der Text sich überlappt.

**Comment by woisch** [comment]
@SilinaKowalewski @vdick 
Bitte die 2 offenen Layoutpunkte bearbeiten, damit dass Issue geschlossen werden kann:
mas_11: Layout prüfen: Die beiden Überschriften brechen so um, dass der Text sich überlappt.
Mas_07: die Zahlen sollten links neben dem Textfeld für die offene Angabe stehen

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
@vdick: Lassen sich die Zahlen **vor** die Textfelder setzen oder gibt es dann wieder das Problem mit dem Umbrechen?

**Comment by woisch** [comment]
im Rollout vom 22.11.2019 13:53 sind die Layout-Probleme immer noch nicht behoben.

**Comment by woisch** [comment]
mas_11 ist behoben.
mas_07 hat sich erledigt durch Issue #130   

Ich schließe jetzt hier.
