### ISSUE TITLE
Update & bugs Modul Gesundheit

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#49]
- Seite gsh_01 ist nicht repsonsiv, Skala bricht entsprechend nicht in vertikal um bei kleinem Screen, bitte responsive bzw. Karussell.

- Seite 2, gsh_02: Text der Items und zugehörige Skala sind innerhalb der jeweiligen Zeile irgendwie nicht in einer Reihe, besonders extram ist dies bei einzeiligen Texten. Text & zugehörige Skala bitte horizontal immer auf gleicher höhe innerhalb der einzelnen Zeilen. Außerdem, wenn man die Fensterbreite auf eine Größe noch vor dem Karussell verkleinert, dreht sich bzw. kippt die Beschriftung der Skala von horizonatal in vertikal, dadurch liegen die Zahlenbeschriftung dann quasi auf der Seite und sind nicht mehr lesbar. Bitte nur normale Ausrichtung und erst Kippen wenn Karussell angeht. Das Problem tritt bei allen Skalen auf, z.B. auch im Modul ausbildung seite aus_04. Bitte daher bei allen Skalen der Befragung korrigieren.
![grafik](https://user-images.githubusercontent.com/52539440/68581307-742e4f00-0478-11ea-9115-70a122391eb4.png)

- Seite 4, gsh_04: Im Fragetext scheint ein Umbruch zwischen den beiden Sätzen zu sein. Bitte ohne Umbruch

**Comment by heikQ** [comment]
Das Problem mit der kippenden Skala scheint nicht auf jedem Rechner vozuliegen, bei Andreas W. passiert das nicht, bei mir aber in allen Browsern (firefox, explorer und chrome). Etwas schräg der Effekt.

**Comment by andreaschu** [comment]
@vdick bitte kippende Labels ausschalten und break nach "sehr" und nach "(un)zufrieden" einbauen

**Comment by SilinaKowalewski** [comment]
@heikQ: 
Kannst du bitte einmal schauen ob hier noch was offen ist? 

Der Stand ist: 
- [x] gsh_01 -> komplett vertikal programmiert
- [x] ghs_02 -> Items mittig ausgerichtet
- [x] Kippende Label -> die kippenden Label hat Viktor komplett ausgeschaltet. Dadurch ergeben sich aber evtl. an einigen Stellen weitere Layout-Probleme die wir nun händisch durchgehen müssen.

**Comment by vdick** [comment]
beg_06, beg_07, iaa18 bis iea18 optimiert, ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
@heikQ: 
Lalalalalalalalala (wo sind die Äste?)
Lalalalalalalalala (ich will eure Äste sehen)
Lalalalalalalalala (put your Äste in the air)
Lalalalalalalalala
Lalalalalalalalala (astrein)

**Comment by woisch** [comment]
@heikQ 
Bitte mal prüfen, ob hier noch was offen ist oder das zu kann
