### ISSUE TITLE
Preload h_enterdatum

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#50]
Wir bräuchten noch einen Preload für h_enterdatum, der für cohort 1 "Januar 2018" und für cohort 2 "Juli 2018" ist.

Außerdem noch einen Preload h_exitlabel mit dem Inhalt "Dezember 2019" für alle Befragten.

(Zum Hintergrund, warum wir das nicht in den Code schreiben: So können wir in Zukunft ohne Änderungen am Code das Modul in anderen Wellen einfacher anpassen.)

**Comment by SilinaKowalewski** [comment]
Beide Hilfsvariablen sind eingebaut und werden auf der Seite msg_00 eingeblendet.

**Comment by jocarstensen** [comment]
Danke!

**Comment by jocarstensen** [comment]
Wir brauchen zusätzlich einen Preload für h_exitdatum mit dem Wert 201912 für alle Beobachtungen.

**Comment by SilinaKowalewski** [comment]
Die Preload-Variable ist eingebaut und wird auf der Seite msg_00 eingeblendet.

**Comment by jocarstensen** [comment]
Danke
