### ISSUE TITLE
Update Modul Studium: vc und tr und weiteres

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#51]
- [x] Seiten stu_02, stu_03: Bitte responsive bzw. Karussell für das Item.
- [ ] Seite stu_91: Angabe von Moinat und Jahr bitte in eine Zeile
@woisch @heikQ: Das ist leider nicht möglich.
- [x] stu_92: Eingabefeld etwas länger ziehen (etwa um die hälfte dazu) 
- [x] stu_93: Eingabefeld länger ziehen (etwa doppelt so lang lang) 
- [x] stu94: Eingabefeld bei der angabe sonstiges länger ziehen (etwa dopplet so lang)

Außerdem Anpassungen in der PV:
https://github.com/dzhw/SLC-IntEr/commit/ce240af2ca3d64d9687c0a3fb5455e7518ee3c20 

- [x] stu_90: vc geändert
- [x] mas_05: Transition geändert
- [x] stu_07: Transition geändert

**Comment by SilinaKowalewski** [comment]
@heikQ: 

In der PV steht für die Frage stu_02  `tr: GOTO stu_03` und exakt so ist die Transition aktuell umgesetzt. Meinst du wirklich stu_02?

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Können jetzt geprüft werden.
