### ISSUE TITLE
sET Hilfsvariablen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#52]
In sET fehlen **alle** Hilfsvariablen sowohl in den **Triggers** als auch in den **Transitions**. Es geht hier um Hilfsvariablen, die innerhalb des Moduls gebildet werden und die in den Conditions für die Transitions benötigt werden. 

Bitte **wie in der PV** umsetzen.

**Comment by jocarstensen** [comment]
Das Issue hat übrigens eine hohe Priorität, weil ich an dem Modul mindestens zwei Tage arbeiten muss, nachdem in dieser aktuellen vorläufigen Form alle Fehler korrigiert sind, bevor es in das Gesamtinstrument aufgenommen werden kann.

**Comment by andreaschu** [comment]
ist geupdated, es gibt klammerfehler

**Comment by andreaschu** [comment]
z.B.  auf Seite seab06

transition zu seab15

```
			<zofar:transition target="seab15"
				condition="(
							zofar.asNumber(seab08)==2 or 
								(
								zofar.isMissing(seab08) and sf_seab06.value)
								) 
							and 
							(
							zofar.isMissing(seab07) or 
							(
							(
							zofar.asNumber(seab07)==1 or zofar.asNumber(seab07)==2
							)
							and
							zofar.asNumber(h_seaa04)==1
							)
							or
							(
							zofar.asNumber(seab07)==3 or zofar.asNumber(h_seaa05)==1
							)
							and sf_seab06.value 
							and 
							(
							!zofar.isMissing(seab06) or (zofar.isMissing(seab06) and sf_seab06.value)
							)" />
```

**Comment by jocarstensen** [comment]
Ok, ich kümmere mich drum. Aber die Checks sind jetzt durch, das heißt ich kann dran arbeiten?

**Comment by andreaschu** [comment]
wir suchen noch zwei fehlenden geschlossene Klammern, ansonsten ja. Ist ausgerollt.

**Comment by andreaschu** [comment]
sezz01, visible condition des softforce (erste doppelte Klammer zu viel)

> 
visible="((navigatorBean.isSame() and (zofar.asNumber(sezz01)==999999 or zofar.asNumber(sezz02)==999999 or zofar.asNumber(sezz03)==999999 or zofar.asNumber(sezz04)==999999)) or sf_sezz01.value">

**Comment by jocarstensen** [comment]
Da ist auch noch ein Fehler gegenüber der Programmiervorlage drin. In 
`zofar.asNumber(seab07)==3 or zofar.asNumber(h_seaa05)==1` müsste AND stehen, nicht OR.

**Comment by andreaschu** [comment]
3. sezz06, transition to sezz11

> 			<zofar:transition target="sezz11"
> 				condition="(zofar.asNumber(sezz07)==1 or zofar.asNumber(sezz07)==2 and (zofar.isMissing(sezz06) or (zofar.isMissing(sezz06) and sf_seaa06.value)) and zofar.asNumber(h_sezz04)!=1" />

**Comment by andreaschu** [comment]
sollen wir das korrigieren und gleich commiten?

**Comment by jocarstensen** [comment]
Ja, bitte. Das falsche OR bitte auch (s. mein letzter Post).

**Comment by jocarstensen** [comment]
Wisst, Ihr, wo jeweils die geschlossenen Klammern hingehören? In sezz06 zumindest ist es in der PV korrekt.

**Comment by andreaschu** [comment]
wir vergleichen es mit der PV und korrigieren es entsprechend. Also, ja.

**Comment by jocarstensen** [comment]
Ok, danke

**Comment by andreaschu** [comment]
ist commited, aber noch nicht ausgerollt.

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Wenn in den Hilfsvariablen keine Fehler mehr sind, können wir dieses Issue dann schließen? #70 besteht ja weiterhin.

**Comment by jocarstensen** [comment]
Ich teste noch.

**Comment by jocarstensen** [comment]
Ich mache hier erstmal zu. Als nächstes kommt das Modul dann vollständig.
