### ISSUE TITLE
Flussdiagramm Gesamtinstrument

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#53]
Hier nochmal die aktuelle Version vom Flussdiagramm für das Gesamtdokument.
[FD_IntEr_20191111.pdf](https://github.com/dzhw/SLC-IntEr/files/3832411/FD_IntEr_20191111.pdf)

**Comment by SilinaKowalewski** [comment]
Danke!

Habe das Dokument unter "Code" eingebaut und schließe hier das Issue.
