### ISSUE TITLE
Update Episodenmodule Arbeitslosigkeit und Praktikum

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#54]
Hier sind die Updates für die Module Arbeitslosigkeit (u) und Praktikum (i). Bitte auf dem Server ausrollen und Bescheid geben, falls etwas crasht.

Weil Github keine xml akzeptiert habe ich noch ein .txt rangehängt.
[arbeitslosigkeit_20191112.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3835558/arbeitslosigkeit_20191112.xml.txt)
[generated__Praktikum_20191112.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3835560/generated__Praktikum_20191112.xml.txt)

**Comment by jocarstensen** [comment]
Sind die Updates im neusten Rollout berücksichtigt?

**Comment by SilinaKowalewski** [comment]
Nein, bisher noch nicht. 

Da bin ich aber gerade dran.

**Comment by SilinaKowalewski** [comment]
Die Module sind aktualisiert und ausgerollt.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?

**Comment by jocarstensen** [comment]
Ja, danke
