### ISSUE TITLE
Neue Episodenmodule: Ausbildung, Schule, andere Taetigkeiten

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#55]
Hier drei neue Epsiodenmodule. Die Zwischenseiten werden dann noch von Sebastian geliefert. Für sET gibt es dann erstmal einen Platzhalter, damit wir in der Zwischenzeit das Episodenmodul komplettieren und testen können.

[ausbildung_20191112.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3835574/ausbildung_20191112.xml.txt)
[Schule_20191112_2.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3835577/Schule_20191112_2.xml.txt)
[andereT_20191112.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3835579/andereT_20191112.xml.txt)

**Comment by SilinaKowalewski** [comment]
Die drei Module sind eingebaut, ausgerollt und können geprüft werden.

**Comment by jocarstensen** [comment]
Danke. Bleibt noch #66 , das trifft mindestens auch auf oaa01 und scaa01 zu. Dort wird ebenfalls die getMonth-Funktion verwendet.

**Comment by SilinaKowalewski** [comment]
Können wir dieses Issue dann schließen?

**Comment by jocarstensen** [comment]
Ja, danke
