### ISSUE TITLE
Modulübergreifend: Drehen der AO von einzelnen Skalaitems

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#58]
Aufgrund von Darstellungsproblem bei verkleinerten Fenstern etc. , sollen bei folgenden Fragen, die lediglich ein Item mit Antwortskala auf einer Seite haben die AOs von horizontal in vertikal geändert werden. In den PVs haben wir dies an den entsprechenden Stellen auch geändert:

- [x] Modul Einstieg: Seite beg_01
- [x] Modul Ausbildung: Seite aus:03a
- [x] Modul Studium: Seiten stu_19, stu_24, stu_96, mas_04
- [x] Modul SozDem: Seite msg_01, msg_10

**Comment by SilinaKowalewski** [comment]
Alle Änderungen sind umgesetzt und können geprüft werden.

**Comment by bafranke** [comment]
geprüft, läuft<!
