### ISSUE TITLE
Modul Studium: Update, Korrekturen

### ISSUE THREAD

**Issue by heikQ** [dzhw/SLC-IntEr#59]
- [x] stu_09: Antwortoptionen näher zusammenrücken, keine Verbindungslinie zwischen den Antwortoptionen 

- [x] stu_10: In der ersten Zeile das "Erwerbstätigkeit" streichen, ist auch nicht in der PV

- [x] stu_19:  Die Transition GOTO stu_20 IF cohort=2 AND h_studakt=1 (siehe PV) funktioniert nicht und führt zu Fehlermeldung "HTTP Status 500 - Encountered "<EOF>" at line 1, column 28." für stu_20, obwohl Hilfsvariablen cohort 2 und h_studakt=1 für Test gesetzt. Gleiches gilt für stu_21.

- [x] stu_26: bitte keine horizontale Verbingunslinie zwischen den AO

- [x] stu_27: bitte keine horizontale Verbingunslinie zwischen den AO

- [x] stu_29: Transition stimmt nicht, für cohort 2 muss es mit stu_44 weitergehen (siehe PV), derzeit gehts mit stu_41 weiter

- [ ] stu_44: Für die AO "andere Umstände, und zwar:"  bitte andere Darstellung. Das "andere Umstände, und zwar: " in das offene Angabefeld als inlay, so dass es verschwindet, wenn Angabe gemacht. @SilinaKowalewski Weißt was ich (frau) meine? @heikQ: Ich verstehe was du meinst, aber das geht an dieser Stelle leider nicht, sondern nur bei "reinen Offenen Fragen".

**Comment by SilinaKowalewski** [comment]
@heikQ 
> stu_26: bitte keine horizontale Verbingunslinie zwischen den AO
> 
>  stu_26: bitte keine horizontale Verbingunslinie zwischen den AO

Ist dieser Punkt doppelt oder meinst du eine andere Seite?

**Comment by heikQ** [comment]
@SilinaKowalewski sorry, meine 26 und stu_27

**Comment by SilinaKowalewski** [comment]
@heikQ: Kann dieses Issue geschlossen werden?
