### ISSUE TITLE
Modul Einstieg (first draft)

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#6]

**Comment by SilinaKowalewski** [comment]
done. please check. 

http://vmzofar-pres.his.de:8080/SCL_IntEr/beg_00.html

**Comment by SilinaKowalewski** [comment]
@woisch

**Comment by woisch** [comment]
Kann geschlossen werden. Wir machen noch eine weitere Korrekturrunde für das Modul einstieg und eröffnen dafür ein neues Issue
