### ISSUE TITLE
Update2 Modul Studium

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#60]
Diverse Updates:
f01d5341730951b9b572620fcfe78a92b2aefa1e

- [x] Stu_01: Text unter „in“ ergänzt
- [x] Stu_46: Transition geändert
- [x] Stu_47: Hinweistext eingefügt
- [x] Stu_49, 57, 65, 73, 82: ao1 (ganzes Studium im Ausland) streichen. Die neue ao1 wurde umformuliert (Studium statt „Auslandsstudium (zeitweise)“). 
- [x] Stu_49, 57, 65, 73, 82: Frage jeweils nicht als Dropdown sondern Einfachauswahl mit vertikalen AO umsetzen
- [x] Stu_49, 57, 65, 73, 82: transitions geändert!
- [x] Stu_55, 63, 71, 79, 89 :ao4 ergänzt
- [x] Stu_56, 64, 72, 80: transitions geändert!
- [x] Stu_48: Instruction gelöscht, stattdessen geänderten Fragetext unter „q“ eingefügt 
- [ ] Stu_80: Transition geändert
- [x] Neue Seite stu_89a eingefügt
- [x] Stu_90 Transition geändert
- [x] Mas_02: „für“ unterstrichen
- [x] Mas_03: „gegen“ unterstrichen
- [x] Mas_07: Punkt nach „Ich habe mich (noch) nicht informiert“ ergänzt
- [x] Mas_09: Fragetext geändert „…für Ihr Masterstudium…“ eingefügt.
- [x] Mas_09: Layout: Bitte die beiden Zeilen „Anzahl Fachhochschulen…“ und „Anzahl Universitäten“ ein paar Zentimeter nach rechts einrücken
@vdick: Kannst du dir dieses Problem mal anschauen?
- [x] Mas_10: Doppelpunkt in ao2 entfernt (direkt vor dem offenen Textfeld)
- [x] Mas_10: ao3 geändert (Bachelorstudium statt Bachelor)
- [x] Mas_12: ao7 "Kann ich noch nicht sagen" soll exklusiv sein. Transition geändert

**Comment by woisch** [comment]
Zusätzlich bitte noch umsetzen:
Stu_41: drei Punkte am Anfang der ao’s entfernt

https://github.com/dzhw/SLC-IntEr/commit/df239651c94230980bc5059a1f00cee07f397319

**Comment by woisch** [comment]
und hier noch weitere Änderungen:
Stu_94: Transitions geändert
Stu_94a als neue Seite eingefügt
Stu_95: Transition geändert

https://github.com/dzhw/SLC-IntEr/commit/d873576b09df73b5ca9932f388fd58228ffbc164

**Comment by SilinaKowalewski** [comment]
@woisch:
> - [ ] Stu_94: Transitions geändert

Aus meiner Sicht fehlen hier noch Bedingungen. 
z. B.:

```
GOTO stu_94a if cohort=1 AND (examplan=4 OR examplan=5 OR examplan=6)
GOTO stu_95 if cohort=2
```
-> GOTO ??? if cohort=1 **AND (examplan=1 OR examplan=2 OR examplan=3)**

**Comment by woisch** [comment]
Stimmt. Habe es angepasst:

https://github.com/dzhw/SLC-IntEr/commit/711d8f3b7f49fa2e0fbc05d63259b3fceace846d

**Comment by SilinaKowalewski** [comment]
Super, setzte ich gleich um :) 

Ein  ähnliches Problem ist mir allerdings auch bei stu_90 aufgefallen. Hier gibt es keine Bedingungen falls die Softforce-Variable (sf_bestwuw) ausgewählt wurde.

**Comment by woisch** [comment]
Transitions auf stu_90 angepasst und auch sf berücksichtigt
https://github.com/dzhw/SLC-IntEr/commit/6784c1783f6fd535d7cabc23d55aae7b156cae74

**Comment by woisch** [comment]
oben fehlt noch eine Änderung:
 Stu_80: Transition geändert

Absicht? Bist du da noch dran?

**Comment by SilinaKowalewski** [comment]
@woisch: 
Ja, das ist Absicht. Im qml sieht alles richtig aus, aber die Transition funktioniert leider nicht wie sie sollte. Muss da den Fehler noch finden.

**Comment by woisch** [comment]
Die Änderungen oben (bis auf das nicht abgehakte) habe ich geprüft, alles ok.

Folgende Änderungen noch:
stu_48: Rechtschreibfehler (Auslandserfahrungen) korrigiert
stu_89a: Text als "is" nicht als "q" formatiert und Text überarbeitet.
https://github.com/dzhw/SLC-IntEr/commit/2ecd01093a690196c711b8fdd78987c20288fd0c

**Comment by vdick** [comment]
mas_09 fixed, ab nächsten Rollout verfügbar

**Comment by woisch** [comment]
@SilinaKowalewski 
**Bitte** hier die noch offenen Änderungen umsetzen, damit das Issue geschlossen werden **kann:**
Folgende Änderungen noch:
stu_48: Rechtschreibfehler (Auslandserfahrungen) korrigiert ->  _Momentan_ ist die Seite stu_48 ganz _leer!_
stu_89a: Text als "is" nicht als "q" formatiert und Text überarbeitet.
2ecd010

Transitions auf stu_90 angepasst und auch sf berücksichtigt -> fubktioniert noch nicht
6784c17

 Stu_80: Transition geändert (siehe ganz oben: f01d534) -> hier bleibt man immer noch hängen, dass wolltest du noch anpassen.

**Comment by andreaschu** [comment]
- [x] 2ecd010 (beim nächsten erfolgreichen rollout testbar)

> Stu_80: Transition geändert (siehe ganz oben: f01d534) -> hier bleibt man immer noch hängen, dass wolltest du noch anpassen.

Transition ist nicht erschöpfend. Man bleibt hängen, wenn man angibt, dass man Kinder hat und keine Kinderzahl angibt. Das entspricht der Condition.

**Comment by woisch** [comment]
Ok, danke für den Hinweis!
Habe die Transition angepasst, jetzt dürften die Fälle nicht mehr hängenbleiben:
https://github.com/dzhw/SLC-IntEr/commit/2733fa7c5ac4d86597aab4383ec037759387fbb7

**Comment by woisch** [comment]
> 
> 
> mas_09 fixed, ab nächsten Rollout verfügbar

-> Danke!

**Comment by woisch** [comment]
> 
> 
> Ok, danke für den Hinweis!
> Habe die Transition angepasst, jetzt dürften die Fälle nicht mehr hängenbleiben:
> [2733fa7](https://github.com/dzhw/SLC-IntEr/commit/2733fa7c5ac4d86597aab4383ec037759387fbb7)

@SilinaKowalewski

**Comment by woisch** [comment]
Transition auf stu_80 läuft jetzt, danke!

letzte Änderung:
stu_48 ist der Rechtschreibfehler immer noch drin: Es muss heißen Auslandserfahrungen (nicht Auslands_auf_erfahrungen)

**Comment by SilinaKowalewski** [comment]
stu_48 ist angepasst und die Änderung bereits ausgerollt.
