### ISSUE TITLE
Update Episodenmodul nsET und Studium

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#61]
Hier die aktuellsten Versionen der Episodenmodule nsET und Studium:
[generated__em_20191113.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3841651/generated__em_20191113.xml.txt)
[generated__st_20191113.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3841652/generated__st_20191113.xml.txt)

Hier sollten alle Fehler behoben sein, außerdem verweisen diese Versionen bereits auf die korrekte Zwischenseite und nicht mehr auf `end`.

**Comment by SilinaKowalewski** [comment]
Die beiden Module sind aktualisiert und ausgerollt.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?

**Comment by jocarstensen** [comment]
Ja, danke
