### ISSUE TITLE
Update Zwischenseiten Episodenmodul

### ISSUE THREAD

**Issue by se-lang** [dzhw/SLC-IntEr#62]
Anbei die QML mit den neuen Zwischenseiten für die Teilmodule des Episodenmodul:
[zwischenseiten_episoden_neu20191113.xml.txt](https://github.com/dzhw/SLC-IntEr/files/3841690/zwischenseiten_episoden_neu20191113.xml.txt)

@SilinaKowalewski kleine Abweichung zu dem was ich mit dir heute Morgen besprochen habe: Wir würden die Zwischenseiten gerne als eigene QML lassen, weil dann alles zusammen, falls wir noch Fehler finden, und man nicht in jedes Modul einzeln rein muss. Passt das für euch auch?

Es müsste dann lediglich `zwischen_k` noch angepasst werden, siehe #26.

**Comment by SilinaKowalewski** [comment]
@se-lang:
> Es müsste dann lediglich zwischen_k noch angepasst werden, siehe #26.

Das verstehe ich tatsächlich nicht so richtig. Betrifft das die Hilfsvariablen des Kalendariums?

**Comment by jocarstensen** [comment]
Entweder meint Sebastian, dass die transitions aus dem Kalendarium auf zwischen_k angepasst werden müssen (das muss auf jeden Fall passieren), oder dass zwischen_k die Seiten cohort1CalPost und cohort2CalPost ersetzen kann, wenn die Trigger aus den Seiten auf zwischen_k geschrieben werden. Das wäre in meinen Augen auch wünschenswert, da wir ja sonst keine sichtbaren Inhalte für die Post-Seiten haben. Ich bin mir aber spontan nicht sicher, inwiefern die Trigger daraus auf einer Seite integriert werden können.

**Comment by se-lang** [comment]
Im Prinzip ist aus meiner Sicht beides möglich, sorry für die Unklarheit. 
Variante 1:
Entweder es ist möglich die Trigger von cohort1CalPost und cohort2CalPost zusammen auf zwischen_k zu integrieren. Dann müsste man nur noch die transitions von cohort1Cal und cohort2Cal auf zwischen_k ändern.

Variante 2:
Man kann die Trigger nicht einfach integrieren. Dann müsste man die Texte und Transitions, die ich auf zwischen_k geschrieben habe auf cohot1CalPost und cohort2CalPost integrieren.

Ausgehend von unserem Pretest würde ich sagen, dass Variante 1 auch gehen müsste und vermutlich etwas weniger Aufwand bedeutet.

**Comment by jocarstensen** [comment]
@dzhwmeisner Kann man die Trigger von cohort1CalPost und cohort2CalPost gemeinsam auf zwischen_k integrieren und die zwei Seiten stattdessen löschen?

**Comment by SilinaKowalewski** [comment]
Die Zwischenseiten (Stand vom 13.11) sind eingebaut und funktionieren soweit ich das beurteilen kann.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?

**Comment by jocarstensen** [comment]
Sind die Trigger auf zwischen_k? Gibt es cohort1CalPost und cohort2CalPost noch? Wurde Variante 1 oder 2 umgesetzt? Die Fragen sind noch nicht beantwortet.

**Comment by SilinaKowalewski** [comment]
Ich habe die Triffer auf zwischen_k eingebaut und dafür die cohort1CalPost und cohort2CalPost raus genommen. 

Ob das so funktioniert wie es sollte müsste allerdings noch mal geprüft werden.

**Comment by jocarstensen** [comment]
@se-lang @woisch @bafranke Könnt Ihr testen, ob die HV aus dem Kalendarium richtig gebildet werden bzw. ob die Filterung danach funktioniert wie sie soll?

**Comment by SilinaKowalewski** [comment]
Habe mal in der Datenbank geschaut und hier sieht es so aus als würde alles richtig funktionieren 👍 
Können aber auch gerne noch mal gemeinsam schauen (oder mit einem Kalendariums-Experten deiner Wahl).

**Comment by se-lang** [comment]
@SilinaKowalewski: Vielleicht können wir da heute einmal kurz telefonieren, das ist vermutlich am einfachsten und wir können auch gleich noch checken ob die HVs nach einer Korrektur entsprechend geupdated werden.

**Comment by jocarstensen** [comment]
@se-lang Funktioniert hier alles? Kann das Issue geschlossen werden?

**Comment by SilinaKowalewski** [comment]
Sebastian und ich wollten uns noch mal anschauen wie die h_ausbakt gebaut wird und ob es hier einen Fehler gibt. Habe ich bei diesem Issue immer im Hinterkopf und würde es daher noch kurz auf lassen.

**Comment by SilinaKowalewski** [comment]
Sebastian und ich haben die HV nochmal geprüft und sie funktioniert nun sauber. Schließe dann hier das Issue.
