### ISSUE TITLE
Autoforward und Navigation in Karussells

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#63]
Wir hätten gern Autoforward für alle Karussells.

Außerdem hätten wir die Navigationsleiste gern zwischen AOs und den Navigationsbuttons.

![grafik](https://user-images.githubusercontent.com/35771616/68782798-4133b900-063a-11ea-8221-e934a7ac8af0.png)

**Comment by SilinaKowalewski** [comment]
Könnt ihr uns bitte eine Liste mit Seiten zusammenstellen auf denen Karussells vorkommen? 

Dann könnte ich das einbauen. 👍

**Comment by jocarstensen** [comment]
@woisch Hast Du hier einen Überblick? In den Episoden haben wir keine Batterien.

**Comment by woisch** [comment]
Barbara erstellt eine Liste mit den Karussels (Karussellen?)

**Comment by SilinaKowalewski** [comment]
Danke!

**Comment by bafranke** [comment]
Folgende Seiten brechen in ein Karussell um:

- [ ] Ausbildung: aus_: 04, 05

- [ ] Einstieg: beg_: 05, 06, 07, 09, 10

- [ ] Gesundheit: gsh_02

- [ ] Studium: stu_: 04, 05, 09, 10, 17, 18, 22, 23, 25, 26, 27, 28, 29, 41, 42, 43, 44; mas_:01, 02, 03, 07

(kommt nicht vor in SozDem, Selbständige, Weiterbildung)

**Comment by bafranke** [comment]
! stu_04 und stu_05 haben bei cohort=1 nur ein item, da das 2. Item nur für cohort2 eingeblendet wird
@SilinaKowalewski -> wie funktioniert da dann der autoforward? Passiert in der cohort dann einfach nichts nach dem Klicken?

**Comment by SilinaKowalewski** [comment]
@bafranke: 
Genau das würde ich auch vermuten. Aber probieren wir es mal aus :) 
Ich werde das einbauen und Bescheid geben, wenn der autoforward überall eingebaut ist. Dann können wir schauen wie es sich auf den beiden Seiten verhält.

**Comment by SilinaKowalewski** [comment]
Das autoforwarding ist eingebaut und funktioniert auf den Seiten stu_04 und stu_05 so wie erwartet. Für cohort==1 passiert nach dem Auswahlen einer ao nichts und für cohort==2 greift das autoforwarding.

Lediglich bei der Seite beg_10 kann diese Option nicht genutzt werden, da es sich um eine Mehrfachauswahl-Matrix handelt.

**Comment by bafranke** [comment]
Guten Morgen! Ich habe alles mit cohort1 getestet (aber auch die cohort2-Seiten damit aufgerufen), bis auf aus_05 klappt alles - hast du eine Idee, warum es da nicht funktioniert?

**Comment by SilinaKowalewski** [comment]
@bafranke: Habe gerade den Fehler gefunden. Hatte das Autoforward für aus_04 zweimal eingebaut und dafür nicht auf aus_05. 

Nach dem nächsten Roll-Out sollte aber auch aus_05 passen.

**Comment by bafranke** [comment]
Leider läuft aus_05 im autoforward weiterhin nicht...

**Comment by andreaschu** [comment]
bei mir läuft es. welchen browser und welches gerät verwendest du denn?

**Comment by bafranke** [comment]
jetzt geht es bei mir auch (firefox, PC), heute morgen lief es aber nicht, mit dem gleichen tester den ich gerade verwendet habe...aber hauptsache es läuft jetzt! Danke!

**Comment by SilinaKowalewski** [comment]
zur Doku: 

auf diesen Seiten wird nun zusätzlich Autoforwarding verwendet: 
 seaa61
seaa66
 seba61
seba66
 seca61
seca66
 seda61
seda66
 seea61
seea66
 sezz61
sezz66
 emaa43
 emba43
 emca43
 emda43
 emea43
 emfa43
 em0043
