### ISSUE TITLE
vaa01 crasht beim Verlassen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#66]
Der Fehler auf vaa01 besteht immer noch. Habt Ihr die getMonth-Problematik berücksichtigt? Ich finde auf der Indexseite kein startPoint

Zur Erinnerung: In fast allen Episodenmodulen gibt es noch Bedingungen mit zofar.getMonth(startPoint). startPoint wird aber aktuell nirgendwo definiert. Darum hatte ich per Mail den Code aus unserem Pretest geschickt:

Variablenblock:
        <zofar:variable name="startPoint" type="string"/>

Indexseite:
            <zofar:variable variable="startPoint" value="zofar.getTimeStamp()"/>

**Comment by SilinaKowalewski** [comment]
crasht leider immer noch.

**Comment by jocarstensen** [comment]
Ok, danke. Ich setze mich nachher mal ran und gucke, welche Gemeinsamkeit alle crashenden Seiten haben. Falls @dzhwmeisner noch irgendwelche Fehler findet (insbesondere Klammerfehler) **BITTE BESCHEID SAGEN!** Klammerfehler haben inhaltliche Bedeutungen und alles andere könnte systematisch im gesamten Episodendokument vorliegen bzw. Auswirkungen haben!

(Ich weiß, dass Ihr das selber wisst, aber manchmal könnten wir ein bisschen mehr Feedback gebrauchen um den Überblick zu behalten.)

**Comment by andreaschu** [comment]
Fehler gefunden. Wird beim nächsten roll out aktualisiert.

**Comment by jocarstensen** [comment]
Kannst Du mir sagen, was es war? Ich vermute den Fehler noch auf ein paar anderen Seiten (die auch crashen).

**Comment by andreaschu** [comment]
es war die Preload-Variable cohort. Wir bauen die gerade ein. Dabei gehe ich noch mal alle Fragebögen durch und suche nach der Kohorten-Zuordnung.
Diese Bedingung:
`condition="cohort==1 …`
habe ich korrigiert zu: 
`condition="zofar.asNumber(PRELOADcohort)==1 …`

**Comment by andreaschu** [comment]
wurde korrigiert und funktioniert hoffentlich

**Comment by SilinaKowalewski** [comment]
kann dieses Issue geschlossen werden?

**Comment by jocarstensen** [comment]
ja
