### ISSUE TITLE
Update Modul_Studium (3)

### ISSUE THREAD

**Issue by bafranke** [dzhw/SLC-IntEr#67]
Update:
f4249ca

außerdem:

- [x] bug: stu_90: bei Angabe 4 oder 5, stürzt die nächste Seite ab, Tr scheinen aber korrekt zu sein

- unschöne Formulierung bei Wertebereichsüberschreitung - bei vielen Fragen erscheint bei Überschreitung des Wertebereichs: "Bitte geben Sie Nummer ein" - ist das eine Standardformlierung? Im Code steht davon nichts! Wenn wir das ändern wollen, können wir einen Standardtext definieren oder müssen wir das für jede Seite gesondert angeben?

Doku Update:

- stu_90: q2 und q3 Komma

**Comment by andreaschu** [comment]
> unschöne Formulierung bei Wertebereichsüberschreitung - bei vielen Fragen erscheint bei Überschreitung des Wertebereichs: "Bitte geben Sie Nummer ein" - ist das eine Standardformlierung? Im Code steht davon nichts! Wenn wir das ändern wollen, können wir einen Standardtext definieren oder müssen wir das für jede Seite gesondert angeben?

Für Zahlenfelder wird eine Formulierung benötigt. Das ist unsere Standardformulierun.

**Comment by andreaschu** [comment]
update und bug sind geändert.

**Comment by bafranke** [comment]
Könntet ihr die Standardformulierung ändern in: "Bitte geben Sie eine gültige Zahl ein!"?
Wir prüfen dann noch einmal auf allen Seiten, ob wir ggf eine andere seitenspezifische Formulierung festlegen.

**Comment by SilinaKowalewski** [comment]
Die Formulierungen sind angepasst worden und sich nach dem nächsten Roll-Out verfügbar.

**Comment by woisch** [comment]
@bafranke kann zu oder?
