### ISSUE TITLE
seaa55: Seite nicht programmiert

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#68]
Seite wurde noch nicht programmiert (ist leer).
[seaa55](https://github.com/dzhw/SLC-IntEr/blob/master/Modul_Selbstst%C3%A4ndige.md#seaa55)

**Comment by andreaschu** [comment]
@jocarstensen kannst Du bitte doch noch mal in die PV gucken? Die Frage macht keinen Sinn: Wie viele Stunden arbeiten Sie … -> ja / nein
Ich habe jetzt die sezz70 als Vorlage genommen. Bitte ansehen. Die Transitions und Hilfsvariablen sind noch nicht drin. @SilinaKowalewski bitte ansehen und einbauen.

**Comment by jocarstensen** [comment]
Stimmt, da ist die PV falsch. Ich gucke es mir an und kümmere mich um Transitions und HV.

**Comment by SilinaKowalewski** [comment]
@jocarstensen: Hattest du diese Seite bereits selber gebaut bzw. hat sich dieses Problem erledigt?

**Comment by andreaschu** [comment]
@SilinaKowalewski ich hatte sie gebaut, war aber unsicher, ob 1. ich es richtig verstanden hatte und 2. ich es richtig gebaut habe.

**Comment by jocarstensen** [comment]
Ja, ich hab es jetzt noch entsprechend angepasst und Trigger und Transitions geschrieben.
