### ISSUE TITLE
Episoden - Weiterbildung: SF funktioniert nicht

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#69]
auf den Seiten taa01, tba01, tca01, tda01 und tea01

**Comment by jocarstensen** [comment]
Die Einblendungen und visible conditions auf tba01, tca01, tda01 und tea01 funktionieren auch nicht. Vielleicht ist das derselbe Fehler.

**Comment by SilinaKowalewski** [comment]
`GOTO taa01 IF (taa01==MISSING OR taa02==MISSING OR taa03==MISSING OR taa04==MISSING) AND sf_taa01==MISSING`

Diese Bedingungen beinhaltet aktuell die Checkboxen noch nicht. Also würde der SF auch erscheinen, falls eine der Checkboxen ausgewählt ist.
Wann soll der SF genau erscheinen. Wenn alle angaben leer sind? Oder reichen beispielweise Angaben zum Jahr?

**Comment by jocarstensen** [comment]
Angaben zum Jahr reichen nicht. Der SF soll erscheinen, sobald irgendein Teil des Datums nicht vorliegt. 

ABER: Ich war davon ausgegangen, dass die Trigger, die bei gesetzten Checkboxen die taa01/taa02 bzw. taa03/taa04 überschreiben, bereits beim Seitenwechsel berücksichtigt werden. In dem Fall müsste die Transition auch bei Missings und gesetzten Checkboxen funktionieren bzw. die Missings müssten überschrieben worden sein. Ich dachte auch, dass ich dieses Verhalten in anderen Modulen bereits beobachten konnte. Liege ich da falsch?

**Comment by SilinaKowalewski** [comment]
Ach ja, darüber hatten wir schon einmal gesprochen! Sorry für die Verwirrung. Das mit den Triggern sollte nach wie vor passen. 

Das Problem liegt hier übrigens darin, dass die AntwortOptionen "Jahr" bzw. "Monat" keine Missings sind sondern den Wert "99999" haben.

**Comment by jocarstensen** [comment]
Ah, das macht Sinn. Das könnte auch noch an anderen Stellen falsch programmiert sein. Ich schreibe mir das auf die To-Do-Liste.

**Comment by jocarstensen** [comment]
Wenn das auf den oben genannten Seiten korrigiert ist, kann das Issue meinetwegen geschlossen werden.

**Comment by SilinaKowalewski** [comment]
Das wird leider ziemlich sicher an anderen Stellen auch falsch programmiert sein. Würde das gerne einmal für die taa01 testen bevor wir das überall anders ändern.

**Comment by jocarstensen** [comment]
Ok, gern. Danke.

**Comment by SilinaKowalewski** [comment]
Die SF auf den oben genannten Seiten funktionieren nun aus meiner Sicht 👍

**Comment by jocarstensen** [comment]
Funktioniert, danke. Es gibt noch falsch angesteuerte Variablen, dafür habe ich das Issue #83 aufgemacht. Außerdem funktionieren die Trigger immer noch nicht. Soll ich dafür ein neues Issue aufmachen oder reicht #70 ?

**Comment by SilinaKowalewski** [comment]
An #83 sitzen wir gerade dran und Issue #70 sollte reichen. Die Lösung des Problems haben wir aber leider noch nicht gefunden.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?

**Comment by jocarstensen** [comment]
Ja
