### ISSUE TITLE
Modul Ausbildung (first draft)

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#7]

**Comment by SilinaKowalewski** [comment]
done. please check. 

http://vmzofar-pres.his.de:8080/SCL_IntEr/aus_00.html

**Comment by SilinaKowalewski** [comment]
@woisch

**Comment by heikQ** [comment]
can we get some pretty nice token for testing?

**Comment by SilinaKowalewski** [comment]
have a pretty nice look at the [wiki](https://github.com/dzhw/SLC-IntEr/wiki#links-und-token)
