### ISSUE TITLE
Episoden - SF-Messages werden nicht angezeigt; Trigger für seaa01, seaa02, seaa03 und seaa04 machen Probleme

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#70]
Soweit ich das sehe, werden im ganzen Modul SF-Messages nicht angezeigt. Wenn ich also ein Missing habe, bleibe ich nur hängen, ohne Erläuterung und Möglichkeit zu überspringen.

Die Trigger für die Variablen seaa01, seaa02, seaa03 und seaa04 scheinen auch nicht zu funktionieren, da trotz gesetzter Haken bei seaa01a und seaa03a offenbar die Werte nicht überschrieben wurden. In diesem Fall werden auf späteren Seiten auch keine Labels eingeblendet.

**Comment by andreaschu** [comment]
Das sind die nicht deklarierten Variablen. Das werde ich heute zur Korrektur an unsere SHK geben.

**Comment by jocarstensen** [comment]
Beziehst Du Dich auf die ausbleibenden SF-Messages oder auf den zweiten Punkt?

**Comment by jocarstensen** [comment]
Zu der Sache mit den Triggern: Im Ausbildungsmodul funktioniert das auch nicht. Kann mal jemand von Euch rausfinden, was da der Fehler ist, damit wir es in allen Modulen korrigieren können?

**Comment by jocarstensen** [comment]
@andreaschu PUSH

**Comment by andreaschu** [comment]
@SilinaKowalewski kann es sein, dass es bei der letzten Bedingung im Trigger (seaa01) es eigentlich heißen muss? `or !sf_seaa01.value">`
Ansonsten kann ich keinen Fehler entdecken
```
<zofar:multipleChoice uid="mcsf" 
		visible="( navigatorBean.isSame()              
				 and (              
				 (
				 (zofar.asNumber(seaa01dropDown)==999999 or zofar.asNumber(seaa02dropDown)==999999) and !seaa01a.value
				 )              
				 or  (
				 (zofar.asNumber(seaa03dropDown)==999999 or zofar.asNumber(seaa04dropDown)==999999) and !seaa03a.value
				 )              
				 )
				 )              
				 or	sf_seaa01.value">
```

**Comment by SilinaKowalewski** [comment]
@andreaschu: Ne, die letzte Bedingung ist schon richtig so.

**Comment by jocarstensen** [comment]
Das Problem mit den Triggern besteht auch in anderen Modulen (z.B. vaa01 --> Labels für gesetzte Häkchen werden später nicht eingeblendet)

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden? Haben ja #101

**Comment by jocarstensen** [comment]
Ja, kann zu
