### ISSUE TITLE
Episoden Selbständigkeit - Labels in seaa17 etc. fehlen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#71]
Die Labels bei den Ortsabfragen werden weder im Feld noch als Präfix eingblendet. Das betrifft die Seiten:
- seaa17
- seaa25
- seaa33
- seaa41
- seaa49
- seab17
- seab25
- seab33
- seab41
- seab49
- sezz17

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner: 
Kannst du bitte mal schauen ob sich hier Infield-Texte einblenden lassen? Habe mich schon am CSS versucht aber scheinbar mit wenig Erfolg.

**Comment by vdick** [comment]
Die Logik ist bereits implementiert, die einzelnen Fälle/Pages können von @SilinaKowalewski  gesetzt werden

**Comment by SilinaKowalewski** [comment]
Hier sollte nun auch alles behoben sein.

**Comment by jocarstensen** [comment]
Bisher waren sie überall da, wo ich geguckt habe. Falls irgendwo welche fehlen, werden uns das hoffentlich die Tester sagen. Ich mach mal wieder zu.
