### ISSUE TITLE
Update Modul Sozdem: Dropdown-Menü bei Auswahl Monat/Jahr

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#72]
Bitte die Abfrage von Monat und Jahr auf Seite msg_02 jeweils als DropDown-Menü umsetzen, siehe PV:
https://github.com/dzhw/SLC-IntEr/commit/56ecf756272f4675c01c993ccb0cb56011233883

**Comment by SilinaKowalewski** [comment]
@woisch: Eine Dropdown kann leider nicht in eine SingleChoice Frage eingebaut werden...bzw. in keine andere Frage, da ein Dropdown-Menü eine eigenständige Frage ist. 

Eine Alternative zu offenen Textfeldern gibt es hier leider nicht, falls es weiterhin eine SingleChoice Frage sein soll.

**Comment by woisch** [comment]
Dann setzen wir die Abfrage Monat/Jahr als Drop Down auf einer neuen Seite um (msg_2a), siehe PV:

https://github.com/dzhw/SLC-IntEr/commit/3be4a53fa5cfa462e1bb3423ecc55808aba57ad0

**Comment by SilinaKowalewski** [comment]
Ich bräuchte hierfür noch eine Liste für "Jahr"

**Comment by SilinaKowalewski** [comment]
Oh, ups...Habe sie gefunden. Sorry!

**Comment by SilinaKowalewski** [comment]
Die Änderungen sind umgesetzt und können nun geprüft werden.

**Comment by woisch** [comment]
Könnt ihr das Layout da noch anpassen und die beiden Dropdowns links ausrichten, neben dem "seit:"
Finde die Mittige Ausrichtung hier unschön.

Im responsiven ist das besser gelöst:
![grafik](https://user-images.githubusercontent.com/53002476/69331156-93856300-0c54-11ea-9c45-2761874acd5f.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?
