### ISSUE TITLE
Update4 Modul Studium: Monat/Jahr als Dropdown umsetzen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#73]
Bitte auf stu_91 die Abfrage für Monat und Jahr jeweils als Dropdown umsetzen. Siehe PV:
https://github.com/dzhw/SLC-IntEr/commit/7c828373415bf398b907214f67ceb7ced0ba2a9c

**Comment by heikQ** [comment]
@woisch  https://www.youtube.com/watch?v=wGexgNKPl0k

**Comment by andreaschu** [comment]
geändert, beim nächsten rollout testbar.

**Comment by woisch** [comment]
Danke!
