### ISSUE TITLE
AddOn zur Adressaktualisierung

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#74]
Wir brauchen pro Kohorte eine AddOn-Befragung zur Adressaktualisierung

Dazu noch folgende Fragen:
- Werden dafür neue Token vergeben?
- Wie funktioniert die Verknüpfung zwischen den Token?
- Kann das AddOn von SBer 18.2 als Vorlage verwendet werden?

**Comment by andreaschu** [comment]
1. Ja, dafür gibt es neue Token
2. Das Matching erfolgt in der Befragung - dort gibt es beide Token als Preloads
3. Ja, kann es. Ändern sich die Variablennamen? Für Beide Add Ons?

**Comment by jocarstensen** [comment]
@andreaschu zu 3.: Wie lauten denn die Variablennamen? Mir liegt das AddOn nicht vor.
@heikQ @woisch zu 3.: Was sagt Ihr?

**Comment by andreaschu** [comment]
Variablen(namen)

- sample
- name
- ggfco
- street
- plzort
- land
- mail

**Comment by woisch** [comment]
Ich würde die Variablennamen (name bis mail) so beibehalten. Bei sample weiß ich nicht, was das war bei 18.2

**Comment by heikQ** [comment]
find ich gut so

**Comment by andreaschu** [comment]
zwei Add On's sind aber zwei völlig voneinander getrennte Befragungen. Eine spezielle Bennenung ist - zumindest für uns - aus technischer Sicht nicht notwendig. Stört aber auch nicht.

**Comment by woisch** [comment]
Falls noch nicht zu spät:
Wenn es keine technische Notwendigkeit für eine unterschiedliche Benennung gibt, brauchen wir diese auch nicht vorzunehmen. Wir bekommen dann ja die Exporte der Daten sowieso nur getrennt für die einzelnen Kohorten. Dann sollten wir der Einfachheit halber bei der alten Version bleiben:

- name
- ggfco
- street
- plzort
- land
- mail

**Comment by andreaschu** [comment]
okay. 
@vdick kannst Du noch eine weitere AddOn generieren mit dem Zusatz 183?

**Comment by vdick** [comment]
@andreaschu beide addon's wurde soeben angelegt

**Comment by woisch** [comment]
Danke!
Wie ist die Befragung zur Zeit erreichbar, um es sich anzuschauen? Die Weiterleitung in die AddOn per Link auf der Endseite müssen wir noch bauen..

**Comment by SilinaKowalewski** [comment]
Aktuell ist die Befragung noch nicht auf dem Presentation-Server ausgerollt. Werde ich aber im Laufe des Tages machen und euch die Links nennen.

**Comment by andreaschu** [comment]
@vdick ich habe die Preloads für die Add-On-Befragungen in der preloads.xlsx im docs-Ordner aktualisiert. Kannst Du die der Datenbank hinzufügen?

**Comment by SilinaKowalewski** [comment]
https://presentation.dzhw.eu/SCL_IntEr-Addon-154

https://presentation.dzhw.eu/SCL_IntEr-Addon-183

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden?

**Comment by woisch** [comment]
ja
