### ISSUE TITLE
sET: Counter

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#75]
Verstehe ich das richtig, dass h_se0001 immer value+1 bekommen soll, wenn h_seaa01==0?

`h_se0001=[COUNTER], COUNT IF h_seaa01==0`

**Comment by jocarstensen** [comment]
Ja. Das ist eine Art Flag-Variable, die sichergehen soll, dass nur einmal gezählt wird, falls vor- und zurückgegangen wird.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by jocarstensen** [comment]
Kann erst nach Duplikation getestet werden. Ich behalte das auf dem Schirm.
