### ISSUE TITLE
sET: transition auf seab06

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#76]
wir haben hier eine Bedingung verändert von: 

h_seaa05=0 IF seaa07<>3 AND seab07<>3 AND **secb07**<>3 AND sead07<>3 AND seae07<>3

zu:
h_seaa05=0 IF seaa07<>3 AND seab07<>3 AND **seac07**<>3 AND sead07<>3 AND seae07<>3

Wenn das richtig ist, bitte issue wieder schließen (und PV anpassen).

**Comment by jocarstensen** [comment]
Ja, ist korrekt.
