### ISSUE TITLE
sET: transition auf seaa33

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SLC-IntEr#77]
wir haben hier eine Bedingung verändert von: 

GOTO seaa33 IF **seaa28**==MISSING AND sf_seaa38==MISSING
zu:
GOTO seaa33 IF **seaa38**==MISSING AND sf_seaa38==MISSING

Wenn das richtig ist, bitte issue wieder schließen ([und PV anpassen](https://github.com/dzhw/SLC-IntEr/blob/master/Modul_Selbstst%C3%A4ndige.md#seaa33-1)).

**Comment by jocarstensen** [comment]
Ja, ist korrekt
