### ISSUE TITLE
Layout: AddOn

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#78]
Bei beiden AddOn-Befragungen müssen die Textfelder größer und die Item-Texte mittig gezogen werden.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Die beiden AddOns sind neu ausgerollt und sehen jetzt hübsch aus! :)

**Comment by woisch** [comment]
Mir gefällts so.

**Comment by SilinaKowalewski** [comment]
Dann schließe ich dieses Issue.
