### ISSUE TITLE
Zwischenseiten nicht erreichbar

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#79]
Momentan sind fast alle Zwischenseiten nicht abrufbar (Seite existiert nicht). 
Betrifft stu_00, aus_00, msg_00

Arbeitet ihr gerade an den Seiten und das ist nur vorübergehend?

**Comment by jocarstensen** [comment]
Die heißen jetzt zwischen_stu etc.

**Comment by woisch** [comment]
Okay, danke!
Dann hat sich das erledigt!
