### ISSUE TITLE
Modul SozDem: msg_06 gelöscht

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SLC-IntEr#8]
Bitte updated: 773fe8003ccaf35f97a38956b25ec3cc137f3e35

**Comment by SilinaKowalewski** [comment]
Änderungen umgesetzt. Bitte prüfen.

**Comment by SilinaKowalewski** [comment]
@woisch:

Müssen hier noch Änderungen vorgenommen werden oder kann das Issue geschlossen werden?

**Comment by woisch** [comment]
Kann geschlossen werden
