### ISSUE TITLE
Update 5 Modul Studium 

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#80]
Auf stu_08 Hinweistext eingefügt. Bitte Wertebereich begrenzen, entsprechend PV

https://github.com/dzhw/SLC-IntEr/commit/e464053e11f20c129aeb4898fc06541f4b368f1f

**Comment by woisch** [comment]
Weitere Korrekturen im Modul Studium:

- [ ] Stu_09: Anführungszeichen geändert
- [ ] Stu_10: hl entfernt
- [ ] Stu_23: hl entfernt
- [ ] Stu_24: hl entfernt
- [ ] Stu_25: Labels der ao korrigieren: es fehlen die Zahlen 1-5 (siehe PV)
- [ ] Stu_26: mv nicht umgesetzt
- [ ] Stu_28: hl entfernt

https://github.com/dzhw/SLC-IntEr/commit/d52e403d0f4cd2f0bbd007e43e1a5f4256dd6b5f

**Comment by SilinaKowalewski** [comment]
@woisch: 
Laut PV sollen für die Fragen Stu_25-Stu29 keine Zahlen in den Labels angezeigt werden. Damit Zahlen in die Labels programmiert werden müsste die Pv so aussehen: 

> ao1:1:**1** trifft gar nicht zu
> ao2:2:**2**  trifft eher nicht zu
> ao3:3:**3**  teils/teils
> ao4:4:**4**  trifft eher zu
> ao5:5:**5**  trifft völlig zu

Ich werde für diese Fragen aber trotzdem Zahlen mit aufnehmen, richtig?

**Comment by woisch** [comment]
Sorry, das war mein Fehler.
Bitte bei stu_25-stu_29 keine Zahlen an die Labels!

**Comment by SilinaKowalewski** [comment]
Änderungen sind umgesetzt und können getestet werden.

**Comment by woisch** [comment]
geprüft, ok!
