### ISSUE TITLE
Episodenmodul Studium 

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#81]
Das Episodenmodul Studium crasht direkt auf Seite st0001.
Kann momentan nicht getestet werden.

**Comment by SilinaKowalewski** [comment]
Ich glaube, ich habe den Fehler gefunden. Kann ich allerdings erst morgen Vormittag bei einem neuen Roll-Out testen.

**Comment by SilinaKowalewski** [comment]
Der Seitenübergang klappt nun wieder.

**Comment by bafranke** [comment]
bei mir stürzt die Seite immernoch ab, wenn ich ja antworte... (cohort1)

**Comment by SilinaKowalewski** [comment]
@bafranke: Du hast Recht! Es gibt weiterhin einen Fehler. Allerdings liegt bzw. lag auf staa01. Denke aber, den Fehler gefunden und behoben zu haben.

**Comment by bafranke** [comment]
super, funktioniert! Danke! Wir arbeiten uns vorwärts: nächster Crash auf Seite https://presentation.dzhw.eu/SCL_IntEr/staa24.html wenn Antwortoption 1, 4 oder 5 angegeben werden!

**Comment by jocarstensen** [comment]
Bitte erstmal nichts dran machen. Sebastian arbeitet gerade offline. Ich gebe Bescheid, wenn das Modul wieder frei ist.

**Comment by SilinaKowalewski** [comment]
@se-lang: 

Auf der Seite gibt es folgende Fehler: 

Hilfsvariablen die kein Value enthalten. In diesem Fall würden bisherige Wert der HV mit "null" (also leer) überschrieben werden. Ist das so gewollt? 
```
            <zofar:variable variable="h_staktsga" value="" direction="forward" onExit="true" ...
            <zofar:variable variable="h_staktsfa01" value="" direction="forward" onExit="true" ... 
            <zofar:variable variable="h_staktsfa02" value="" direction="forward" onExit="true" ... 
```

Zudem verwendest du im gesamten Modul: 
`!zofar.value(sf_staa4) und zofar.value(sf_staa4)`

Richtig wäre dieser Ausdruck aber als: 
`!sf_staa4.value und sf_staa4.value`

Da du ja gerade daran arbeitest habe ich bisher keine Änderungen vorgenommen.

**Comment by se-lang** [comment]
@SilinaKowalewski:
> Hilfsvariablen die kein Value enthalten. In diesem Fall würden bisherige Wert der HV mit "null" (also leer) überschrieben werden. Ist das so gewollt?
> 
> ```
> <zofar:variable variable="h_staktsga" value="" direction="forward" onExit="true" ...
> <zofar:variable variable="h_staktsfa01" value="" direction="forward" onExit="true" ... 
> <zofar:variable variable="h_staktsfa02" value="" direction="forward" onExit="true" ... 
> ```
> 
Das ist so gewollt, hatte euch dazu auch eine Mail geschrieben, weil ich die Vermutung hatte, dass vielleicht hier ein Fehler liegt. Kann ich das grundsätzlich so schrieben, wenn ich damit tatsächlich eine Hilfvariable mit "null" überschreiben will?

> Zudem verwendest du im gesamten Modul:
> `!zofar.value(sf_staa4) und zofar.value(sf_staa4)`
> 
> Richtig wäre dieser Ausdruck aber als:
> `!sf_staa4.value und sf_staa4.value`
> 
Ok, ändere ich. Würde aber noch die Entscheidung zu den Häkchen abwarten, weil damit ja auch auch noch Überarbeitungen dazu kommen.

**Comment by se-lang** [comment]
@SilinaKowalewski, noch eine Nachfrage:
Kann man in folgendem Fragetyp dieses Kästchen für die Überschrift ausblenden, wenn es leer ist? Ich habe hier mehrere Gruppen für die es einfach keine sinnvolle Überschrift gibt, würde diese Gruppierung aber trotzdem gerne nutzen, um die zelativ lange Liste etwas übersichtlicher zu machen.
![grafik](https://user-images.githubusercontent.com/35341060/69526417-6d203a00-0f6a-11ea-8102-8a84525547bb.png)

**Comment by SilinaKowalewski** [comment]
@se-lang: Habe nochmal mit @vdick Rücksprache gehalten und wir denken, dass sollte funktionieren. Würden wir uns dann bei Gelegenheit mal im CSS anschauen.

**Comment by woisch** [comment]
Vielleicht seid ihr noch am Problem dran, aber momentan ist es nun wieder so, dass beim Verlassen der Seite st0001 alles crasht (egal was ich angebe).

**Comment by SilinaKowalewski** [comment]
Dadurch das Sebastian dieses Modul komplett ersetzt hat tritt dieser Fehler nun wieder auf. 

Zur Dokumentation: 
Das Problem liegt in dieser Bedingung
`<zofar:transition target="st0001" condition="zofar.isMissing(st0001 and !sf_st0001.value)"/>`

hier fehlt eine Klammer. Richtig wäre: 
`<zofar:transition target="st0001" condition="zofar.isMissing(st0001) and !sf_st0001.value)"/>`

**Comment by jocarstensen** [comment]
@se-lang War das beabsichtigt, dass Du alles ersetzt hast?
@SilinaKowalewski Könnte er damit noch andere sinnvolle Änderungen revertiert haben? Könnt Ihr zusammen und mit dem Log-File den Zeitraum eingrenzen und rekonstruieren, welche Änderungen Sebastian überschrieben hat?

**Comment by SilinaKowalewski** [comment]
Das war so beabsichtigt und abgesprochen. Aus meiner Sicht haben wir alle Änderungen die wir an dem Modul vorgenommen haben hier in Issues "dokumentiert". 

Wollte aber morgen tatsächlich noch mal schauen ob sich das über die History der Dokumente doppelt prüfen lässt.

**Comment by jocarstensen** [comment]
Ok, Ihr macht das schon. Sorry für die Einmischung.

**Comment by se-lang** [comment]
> Zur Dokumentation:
> Das Problem liegt in dieser Bedingung
> `<zofar:transition target="st0001" condition="zofar.isMissing(st0001 and !sf_st0001.value)"/>`
> 
> hier fehlt eine Klammer. Richtig wäre:
> `<zofar:transition target="st0001" condition="zofar.isMissing(st0001) and !sf_st0001.value)"/>`

@SilinaKowalewski Danke dir, hab das in den Templates auch korrigiert.

**Comment by SilinaKowalewski** [comment]
Kann dieses übergeordnete Issue dann geschlossen werden?

**Comment by se-lang** [comment]
Ja, ich würde sagen wir machen hier mal zu, falls einer der hier genannten Fehler nochmal auftritt neuer Issue (Seitencrash an den Stellen bekommen wir mit).
