### ISSUE TITLE
Kalendarium - Seiten zur Erklärung

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#82]
Wir brauchen vor den Kalendarium zwei Seiten für Ausfüllhinweise pro Kohorte, jeweils eine für mobile und eine für nicht-mobile. 

Da wir die alte ismobile nicht überschreiben wollen, müsste hier mit einer neuen Variable (ismobile2) gefiltert werden, die auf der Seite gebildet wird, von der aus auf die Seiten mit Ausfüllhinweisen gefiltert wird (cohort1: beg_10; cohort2: beg_08), damit die Info Endgerät auch sicher aktuell ist.

Weitere Frage dazu: Können wir auf diesen Seiten ggfs. animierte GIFs einblenden, damit wir die Infos alle ohne Scrollen auf eine Seite bekommen?

**Comment by jocarstensen** [comment]
@andreaschu Kannst Du hierfür jemanden assignen?

**Comment by andreaschu** [comment]
> Weitere Frage dazu: Können wir auf diesen Seiten ggfs. animierte GIFs einblenden, damit wir die Infos alle ohne Scrollen auf eine Seite bekommen?

Ich denke, das geht, oder @dzhwmeisner ?

**Comment by andreaschu** [comment]
> Wir brauchen vor den Kalendarium zwei Seiten für Ausfüllhinweise pro Kohorte, jeweils eine für mobile und eine für nicht-mobile.

Ich nehme an, das heißt vier Seiten.

Ich habe jetzt im Einstiegsmodul (questionnaire2) je eine zweite Variable angelegt für jsCheck, width, heigth und isMobile und sowohl auf beg_08 als auch auf beg_10 getriggert. Aber die cohort=1 sehen beide, Seiten. Da werden die Variablen dann überschrieben.
Ich habe im Kalendarium-Modul (questionnaire7) vier Seiten angelegt (cal0001 bis cal0004).

Texte und ggf. neue Seiten-Namen müssten nachgeliefert werden.

**Comment by jocarstensen** [comment]
@andreaschu @dzhwmeisner Können wir nochmal eine Bestätigung haben, ob GIFs gehen, bevor wir jetzt aufwändig welche basteln?

**Comment by se-lang** [comment]
Die Übergänge von beg_08 und beg_10 nach zwischen_epi passen.
Von zwischen_epi auf die entsprechenden Erklärungsseiten der Kalendarien und von da weiter zu den Kalendarien habe ich gerade Transitions eingefügt. Nach dem nächsten Rollout müsste man also durch kommen.
Die gifs kommen wie im JF besprochen dann erst nächste Woche.

**Comment by SilinaKowalewski** [comment]
> @andreaschu @dzhwmeisner Können wir nochmal eine Bestätigung haben, ob GIFs gehen, bevor wir jetzt aufwändig welche basteln?

Gifs funktionieren und können auf cal0001-cal0004 getestet werden.

**Comment by jocarstensen** [comment]
@woisch @heikQ @bafranke Könnte das bitte jemand von Euch mobil testen?

Ansonsten warten wir für die Erklärseiten noch auf das fertige Layout des Kalendariums. Vorher wollen wir da keine Screenshots machen.

**Comment by woisch** [comment]
Habs getestet aufm iPhone, kriege auf allen Seiten bis auf cal0004 das GIF angezeigt!

**Comment by jocarstensen** [comment]
Bei mir nichtmobil auch so.

**Comment by SilinaKowalewski** [comment]
War tatsächlich nicht eingebaut bzw. an der falschen Stelle. Habe es mal korrigiert. Da wir ja aber sowieso später andere Gifs einfügen sollte uns das jetzt erstmal nicht weiter stören.

**Comment by jocarstensen** [comment]
Ok, danke. Dann gibt es keine Probleme und sobald das Kalendarium aussieht wie es soll, können wir Screenshots machen.

**Comment by woisch** [comment]
Können wir die Test-Gifs dann wieder rausnehmen (und von mir aus einen Platzhalter-Text: Hier kommt eine Anleitung fürs Kalendarium o.ä.)?
Die irritieren den/die eine(n) oder andere(n) Tester(in) eventuell ... ;-)

**Comment by jocarstensen** [comment]
Meinetwegen schon

**Comment by woisch** [comment]
@SilinaKowalewski: Bitte die Test-GIFs wieder rausnehmen vorerst.

**Comment by SilinaKowalewski** [comment]
Ist schon längst passiert :) Hatte nur noch keine Zeit das zu testen aber sieht gut aus.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue geschlossen werden? Haben ja nun #204

**Comment by jocarstensen** [comment]
Kann zu
