### ISSUE TITLE
Episoden - Weiterbildung: zofar.isMissing statt !=999999

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#83]
Im Modul Episoden Weiterbildung werden Variablen mit
`!zofar.isMissing(taa01)`
angesprochen anstatt mit
zofar.asNumber(taa01dropDown)==999999

Das betrifft offenbar von den Episodenmodulen nur das Modul Weiterbildung.
Dort betrifft es die Variablen
taa01/taa02/taa03/taa04
tba01/tba02/tba03/tba04
tca01/tca02/tca03/tca04
tda01/tda02/tda03/tda04
tea01/tea02/tea03/tea04

**Comment by andreaschu** [comment]
korrigiert, kann nach dem nächsten roll out getestet werden

**Comment by SilinaKowalewski** [comment]
@jocarstensen: 
Müssen hier noch Änderungen vorgenommen werden oder passt nun alles?

**Comment by jocarstensen** [comment]
Das lässt sich mit einem Blick auf den Code leichter sagen als durch Testen. Ich muss gerade dringend sET fertig machen. Kann das jemand von Euch überprüfen?

**Comment by SilinaKowalewski** [comment]
Habe den Code noch mal durchsucht und keine Fälle mehr gefunden.

**Comment by jocarstensen** [comment]
Ok, danke
