### ISSUE TITLE
Episoden - Selbständige: SF-Messages werden nicht angezeigt

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#84]
Auf den Seiten:

    seaa17
    seaa25
    seaa33
    seaa41
    seaa49
    seab17
    seab25
    seab33
    seab41
    seab49
    sezz17

**Comment by jocarstensen** [comment]
Gilt auch für seaa09, seab09

**Comment by SilinaKowalewski** [comment]
Habe nun alle Sections dieses Moduls mit Bodys versehen. Hoffe, ich habe damit auch alle SF gefixed.

**Comment by jocarstensen** [comment]
Funktioniert leider nicht bei seab17, seab25 und seab41 crasht

**Comment by jocarstensen** [comment]
seab09 crasht auch

**Comment by SilinaKowalewski** [comment]
Der SF auf seab17 und seab25 funktionieren, meiner Meinung nach entsprechend der PV. Oder übersehe ich da etwas?

`GOTO seab17 IF seab22==MISSING AND sf_seab22==MISSING`
` GOTO seab25 IF seab30==MISSING AND sf_seab30==MISSING`

Auf seab41 habe ich einen Klammerfehler gefunden und behoben.

**Comment by jocarstensen** [comment]
Das Problem ist nicht die Transition, sondern die visible condition für die SF-Message (s. oben: werden nicht angezeigt). Habe den Fehler gefunden: 

seaa statt seab
`visible="(navigatorBean.isSame() and zofar.isMissing(se**aa**22)) or sf_seab22.value">` (Zeile 2645)
`visible="(navigatorBean.isSame() and zofar.isMissing(se**aa**22)) or sf_seab30.value">` (Zeile 2876)

Kannst Du das korrigiere? Aktuell ist irgendjemand in dem Dokument unterwegs.

**Comment by jocarstensen** [comment]
Außerdem: Teilweise noch fehlende Leerzeichen zwischen Monat und Jahr. Gefunden habe ich es auf seab17, habe aber nicht gecheckt, wo das noch auftritt. Könnt Ihr das bitte checken und korrigieren?

**Comment by SilinaKowalewski** [comment]
> Das Problem ist nicht die Transition, sondern die visible condition für die SF-Message (s. oben: werden nicht angezeigt). Habe den Fehler gefunden:
> 
> seaa statt seab
> `visible="(navigatorBean.isSame() and zofar.isMissing(se**aa**22)) or sf_seab22.value">` (Zeile 2645)
> `visible="(navigatorBean.isSame() and zofar.isMissing(se**aa**22)) or sf_seab30.value">` (Zeile 2876)
> 
> Kannst Du das korrigieren? Aktuell ist irgendjemand in dem Dokument unterwegs.

Ah, das erklärt, warum bei mir alles funktioniert. Habe mich nicht durchgeklickt. Daher stimmt zofar.isMissing(seaa22) bei mir in allen Bedigungen.

**Comment by SilinaKowalewski** [comment]
`visible="(navigatorBean.isSame() and zofar.isMissing(se**aa**22)) or sf_seab30.value">`

Hier ist die Variable komplett falsch, oder? Müsste 'seab30' sein, oder?

**Comment by SilinaKowalewski** [comment]
> Außerdem: Teilweise noch fehlende Leerzeichen zwischen Monat und Jahr. Gefunden habe ich es auf seab17, habe aber nicht gecheckt, wo das noch auftritt. Könnt Ihr das bitte checken und korrigieren?

Habe hoffentlich alle fehlenden Leerzeichen gefunden und ersetzt. 
@andreaschu: Wir könnten bei Gelegenheit Parmida noch mal drüber schauen lassen.

**Comment by jocarstensen** [comment]
Richtig, die war komplett falsch.

**Comment by SilinaKowalewski** [comment]
Die SF scheinen nun zu funktionieren.

**Comment by jocarstensen** [comment]
Gut, ich mache hier zu
