### ISSUE TITLE
Zeitplanung Mailversand

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#85]
1. Wir benötigen zeitnah nach dem Versand der Einladungsmails am 16.12. (Feldstart) von euch die Rückmeldung, welche E-Mails nicht zustellbar waren (getrennt nach cohort 1 und 2), damit wir die Mailadressen für einen Nachversand prüfen können. Wir brauchen die unzustellbaren Mailadressen von euch spätestens am 17.12., wenn möglich gerne auch schon direkt am 16.12. Könnt ihr uns zusichern, dass wir diese Informationen spätestens am 17.12. vorliegen haben?

2. ) Ebenso haben wir im Sommer besprochen, dass die erste Erinnerung am 06.01.2020 versendet wird. Um diese vorzubereiten benötigen wir von euch am 02.01. einen Export der verbrauchten Tokens. Ist sichergestellt, dass am 02. Januar jemand da ist, um uns diesen Export zu erstellen?

3.) Die zweite Erinnerung soll Ende Januar per Mail versendet werden, voraussichtlich am 29. Januar. Auch hier bräuchten wir dann ca. 2 Tage vorher einen Export der verbrauchten Tokens von euch.

Soll ich diese Termine noch mal ins Wiki schreiben?

**Comment by andreaschu** [comment]
1. Wir können Euch zeigen, wie ihr das selbst machen könnt. Zusichern können wir nicht, dass wir das in so kurzer Zeit schaffen, da in dieser Woche Schulungen geplant sind.
2. ja, das können wir. Termine sind eingetragen 
3. Termine sind eingetragen.

> Soll ich diese Termine noch mal ins Wiki schreiben?
Ja, bitte. Bitte auch eine Angabe, nach welchen Kriterien die Token exportiert werden sollen. Nur die, die nicht fertig geworden sind, nur die, die fertig geworden sind  oder nur die die bis zu einer bestimmten Seite gekommen sind.
Die Kriterien, kannst Du auch per E-Mail schicken, wenn Dir Github zu öffentlich ist.

**Comment by woisch** [comment]
Danke fürs Aufnehmen ins Wiki!
Die Kriterien für die Tokens teilen wir euch natürlich noch einmal mit, wenn wir den Export anfordern.

**Comment by woisch** [comment]
alles wichtige steht im Wiki, schließe hier jetzt.
