### ISSUE TITLE
Update SozDem: Layout/Rangecheck 

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#86]
auf msg_08 ist ein Rangecheck von 0 bis 9 implementiert. folgende Probleme treten noch auf:

1) Bei EIngabe von Werten größer als 9 (sollten laut Rangecheck nicht erlaubt sein) kommt keine Fehlermeldung, man kommt auf die nächste Seite. Erst bei Zurückgehen auf msg_08 wird die Fehlermeldung sichtbar ("Bitte überprüfen Sie Ihre Eingabe. Sie haben einen Wert kleiner 0 oder größer 9 eingegeben. Wenn Ihre Angabe korrekt ist, können Sie diesen Hinweis ignorieren.")

2) Layout-Bug: Bei Eingabe ungültiger Werte kleiner 0 oder bei Buchstaben erscheint die Fehlermeldung. Allerdings rutscht das Eingabefenster durch den Umbruch des Fehlertextes nach oben. 

![grafik](https://user-images.githubusercontent.com/53002476/69330647-9d5a9680-0c53-11ea-8e23-341f4b8441e0.png)

**Comment by SilinaKowalewski** [comment]
@woisch: Bin gerade dabei mich endlich mal dem Range-Check zu widmen. Wenn der funktioniert würde als Korrekturhinweis und als Range-Check der gleiche Text eingeblendet. Denke, dass ich dann überflüssig, oder? 

Wir könnten also das Layout-Problem direkt mit lösen wenn du dir für den Korrekturhinweis einen neuen Text einfallen lässt.

**Comment by woisch** [comment]
Wenn Range-Check und kh den gleichen Text haben, ist der der kh überflüssig, ja.
Für welche Fälle (außer Angabe von Werten außerhalb der definierten Range) bräuchte ich denn überhaupt noch einen kh?! (vielleicht versteh ich da auch etwas falsch..)

**Comment by SilinaKowalewski** [comment]
Auch hier wurde der RangeCheck komplett gelöscht und dafür das Textfeld auf **zweistellige Zahlen** beschränkt. 

@woisch: Kannst du bitte später noch mal die Transitions prüfen? Diese weichen etwas von der PV ab und ich kann mich nicht erinnern diese Transitions geschrieben oder angepasst zu haben.

**Comment by woisch** [comment]
@SilinaKowalewski 
checke ich nach dem nächsten Rollout, lasse solange hier offen..

**Comment by woisch** [comment]
Ok so, mache zu.
