### ISSUE TITLE
Update3 Modul SozDem

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#87]
- [x] msg_05: Punkte ans Satzende

- [x] msg_05: Unterstreichung statt fett

https://github.com/dzhw/SLC-IntEr/commit/dc33d9f5fb7eaf40bfb3f956f24de4283c8611a9

**Comment by andreaschu** [comment]
geändert. beim nächsten roll out testbar.

**Comment by woisch** [comment]
Bitte noch korrigieren:
auch bei "aus der Familie der Mutter":
Das Wort "kein" unterstreichen statt kursiv! (wie bei "aus der Familie des Vaters schon umgesetzt")

**Comment by woisch** [comment]
jetzt ist "kein" wieder beides mal kursiv... unterstrichen sollte es sein...

**Comment by SilinaKowalewski** [comment]
oh sorry! Ändere ich für den nächsten Roll-Out!

**Comment by woisch** [comment]
danke, ist geändert und passt so!
