### ISSUE TITLE
Fortschrittsbalken

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#89]
Hier nun die Vorlagen für die Fortschrittsbalken.

Einblendungen Kohorte 1:
Teil 1: Modul Einstieg (beg_00 bis einschl. beg_10)
Teil 2: Episoden (zwischen_epi bis einschl. zwischen_o)
Teil 3: Modul Ausbildung (zwischen_aus bis einschl. aus_07)
Teil 4: Modul Studium (zwischen_stu bis einschl. mas_12)
Teil 5: Modul SozDem (zwischen_msg bis end)

Einblendungen Kohorte 2:
Teil 1: Modul Einstieg (beg_00 bis einschl. beg_10)
Teil 2: Episoden und Ausbildung (zwischen_epi bis einschl. aus_07)
Teil 3: Modul Studium (zwischen_stu bis einschl. mas_12)
Teil 4: Modul Gesundheit (zwischen_gsh bis gsh_05)
Teil 5: Modul SozDem (zwischen_msg bis end)

[fortschrittsbalken.zip](https://github.com/dzhw/SLC-IntEr/files/3878624/fortschrittsbalken.zip)

**Comment by woisch** [comment]
@SilinaKowalewski 
Hier die Dateien, die Verena in Absprache mit dir erstellt hat. getrennt für beide Kohorten: Jeweils als einzelne Bilder und blau und grau und einmal als Gesamtbild für den ganzen Balken. Ist das jetzt alles so wie ihr es braucht?

[Verlaufsgrafiken_Kohorte_1.zip](https://github.com/dzhw/SLC-IntEr/files/3916425/Verlaufsgrafiken_Kohorte_1.zip)
[Verlaufsgrafiken_Kohorte_2.zip](https://github.com/dzhw/SLC-IntEr/files/3916427/Verlaufsgrafiken_Kohorte_2.zip)

**Comment by woisch** [comment]
habe den Fortschrittsbalken für cohort1 getestet. Er baut sich über die Befragunb korrekt auf. 
Beim Zurücknavigieren passiert allerdings noch folgendes (in diesem Beispiel bin ich von Icon 5 auf Icon 2 gesprungen):

![grafik](https://user-images.githubusercontent.com/53002476/70215123-0d314c80-173d-11ea-9a94-d037837b3c04.png)
****

**Comment by dzhwmeisner** [comment]
Die Navigationslogik ist korrigiert und wird im nächsten Rollout enthalten sein

**Comment by woisch** [comment]
Das Problem ist nun behoben.

Unschön ist der Header im ersten Teil (bis zur Seite "zwischen_epi")
![grafik](https://user-images.githubusercontent.com/53002476/70229472-9903a280-1756-11ea-995f-d228c8fd2210.png)

![grafik](https://user-images.githubusercontent.com/53002476/70229514-a9b41880-1756-11ea-843d-fabab2f9501e.png)

**Comment by dzhwmeisner** [comment]
Fehler gefixed. Beim nächsten angestossenen Rollout wird's mit ausgerollt

**Comment by woisch** [comment]
Bei längeren Fragebatterien (Scrollen notwendig) verdeckt der Header in die Fragen/antworten, da er mit runtergeht.
Gäbe es aus eurer Sicht eine Möglichkeit, dieses "mitwandern" zu unterbinden?

**Comment by woisch** [comment]
> 
> 
> Bei längeren Fragebatterien (Scrollen notwendig) verdeckt der Header in die Fragen/antworten, da er mit runtergeht.
> Gäbe es aus eurer Sicht eine Möglichkeit, dieses "mitwandern" zu unterbinden?
> 
> ![grafik](https://user-images.githubusercontent.com/53002476/70257335-5fe52580-178a-11ea-8bd8-349a6dbe99ce.png)

Naiv gefragt: Könnte man den Fortschrittsbalken nicht in den Header machen und das Problem des "Mitwanderns" damit lösen?

**Comment by dzhwmeisner** [comment]
Das "Mitwandern" ist deaktiviert. Verfügbar im nächsten Rollout.

**Comment by woisch** [comment]
Im Rollout von 11:58 noch nicht implementiert.

**Comment by woisch** [comment]
> 
> 
> Das "Mitwandern" ist deaktiviert. Verfügbar im nächsten Rollout.

jetzt funktioniert es, danke!

**Comment by woisch** [comment]
Wie schon in #139 und weiter oben gefragt: Wäre es grundsätzlich möglich, den Fortschrittsbalken auch in den Header zu platzieren?

**Comment by SilinaKowalewski** [comment]
@woisch @heikQ: 
Wir hätten dann von Anfang an den Fortschrittsbalken für den Header programmieren bzw. anpassen müssen. Technisch ist es zwar möglich dass zu tun basiert aber eben nicht auf einer exakt gleichen Programmierung. 

Wenn ihr die Notwendigkeit hierfür seht, können wir das auch nachträglich noch umsetzen. Dies würde bedeuten, dass Christian nochmal einige Tage mit der Programmierung beschäftigt wäre und wir zudem anschließend sehr gründlich testen müssten.

**Comment by jocarstensen** [comment]
m.E. muss er nicht unbedingt in den Header, solange er nicht mitwandert.

Ich frage mich aber mittlerweile beim Testen, ob wir das gleiche Verständnis vom gewünschten Verhaltens des Fortschrittsbalkens haben:
Wir wollten, dass immer alle Icons sichtbar sind und die bereits absolvierten bis zum gerade bearbeiteten blau, der Rest ausgegraut. Habt Ihr das auch so verstanden und arbeitet noch an der Umsetzung oder gab es da ein Missverständnis?

**Comment by andreaschu** [comment]
Ich glaube, das haben wir tatsächlich anders verstanden. 
Im Moment ist es so, dass die Sichtbarkeit davon abhängt, in welche Module eine Person wandert, oder? Soll das wirklich so sein, dass Bilder sichtbar sind, die von der Person gar nicht angesteuert werden sollen? 
Wenn also eine Person keine Ausbildung hatte, soll das Symbol dafür dennoch sichtbar sein?

**Comment by jocarstensen** [comment]
Die Icons sind nur für ganze inhaltliche Module. Das Epi-Modul hat nur ein Icon. Alle weiteren Module werden von allen besucht. Da das Ausbildungsmodul für Cohort 2 beispielsweise nur ein Item hat, hat es dort auch kein Icon.

In den Bildern, die wir Euch geliefert haben, sind die Icons schon so, wie sie eingeblendet werden sollten.

**Comment by jocarstensen** [comment]
- Bitte die Navigationsfunktion deaktivieren (nur Bilder wie im vorigen Post beschrieben)
- Bitte mobil entweder, wenn möglich, den Balken wie im nichtmobilen einblenden. Wenn nicht möglich, bitte ganz raus. (Auf jeden Fall nicht mit Menübutton)
- Wenn es egal ist, können die Bilder auch probeweise in den Header. Das ist aber nicht so wichtig.

**Comment by dzhwmeisner** [comment]
> Bitte die Navigationsfunktion deaktivieren (nur Bilder wie im vorigen Post beschrieben)

Die Navigationsfunktion ist deaktiviert. Die Anpassung der Darstellung gemäß der letzten Posts wird morgen gemacht

**Comment by woisch** [comment]
Auf der Endseite überlappt der Fortschrittsbalken mit dem Header:

![grafik](https://user-images.githubusercontent.com/53002476/70619202-c8ae2100-1c14-11ea-8bf4-2c112d81a9df.png)

**Comment by dzhwmeisner** [comment]
Navigationsblaken überarbeitet. Verfügbar im nächsten Rollout.

**Comment by jocarstensen** [comment]
sieht sehr gut aus so, danke. ich mache dann mal zu.
