### ISSUE TITLE
Modul Ausbildung: aus_05 answer options

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#9]
Please check answer options on page "aus_05" in Modul Ausbildung. Item order should be: ja, nein, weiß nicht, PV is correct.

 048151cf87e4c561abbcd8d494932c805b7b03a2

**Comment by SilinaKowalewski** [comment]
In der PV zu diese [Frage](https://github.com/dzhw/SLC-IntEr/blob/master/Modul_Ausbildung.md#aus_05) steht: 

ao1:1: ja
ao2:2: nein
ao3:3: weiß noch nicht

Wie soll die ao3 heißen?

**Comment by woisch** [comment]
die ao3 bitte "weiß noch nicht" nennen!

**Comment by SilinaKowalewski** [comment]
Changed 👍

**Comment by SilinaKowalewski** [comment]
@woisch: 

Müssen hier noch Änderungen vorgenommen werden oder kann das Issue geschlossen werden?

**Comment by woisch** [comment]
Kann geschlossen werden.
