### ISSUE TITLE
Tester-Token zurücksetzen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#92]
Da wir inzwischen fast alle Tester durchgetestet haben:
Könnt ihr bitte die Tester-Tokens zurücksetzen?
Bei der Gelegenheit gerne noch ein paar mehr Tester-Tokens erzeugen, sodass wir 500 Tester Tokens haben und diese wieder im Wiki ablegen .

Danke!

**Comment by woisch** [comment]
@SilinaKowalewski: Hattest du das Zurücksetzen und Hinzufügen der Tokens gestern noch erledigt?

**Comment by SilinaKowalewski** [comment]
@woisch: 

Zurückgesetzt sind die Token noch nicht. Dafür habe ich 300 neue Token eingefügt.

**Comment by woisch** [comment]
Ok, dann arbeiten wir erstmal mit den Tokens ab 201 weiter.
@vdick: könntest du dann bei Gelegenheit auch noch die ersten 200 Tokens zurücksetzen? (falls das  geht)

**Comment by woisch** [comment]
Gerade erst gesehen: In der Liste im Wiki fehlen die Tester 201-500 ja noch. Wir brauchen die Info, welcher cohorte, die Tester zugewiesen sind!

**Comment by andreaschu** [comment]
@vdick oder @dzhwmeisner ich habe die zusätzlichen Token im docs-Ordner hinzugefügt mit Preloads sowie die Token in den add on - Befragungen hinzugefügt (siehe ebenfalls docs-Ordner). Könnte einer von Euch:
- [ ] die Datenbank leeren
- [ ] die Token mit den Preloads hinzufügen
- [ ] in der add on für 18-3 die Token hinzufügen
- [ ] in der add on für 15-4 die Token hinzufügen

**Comment by SilinaKowalewski** [comment]
@woisch: 
Die Datenbank lässt sich leider nur komplett leeren. Nur die ersten 200 Token können wir nicht zurücksetzen. 

Sag einfach Bescheid, ob du die komplette Datenbank leeren lassen möchtest oder wir sie so lassen wie sie ist.

**Comment by woisch** [comment]
Dann macht doch einfach nochmal komplett leer und setzt alle Token zurück!
________________________________
Von: SilinaKowalewski <notifications@github.com>
Gesendet: Dienstag, 26. November 2019 12:05:20
An: dzhw/SLC-IntEr
Cc: Woisch, Andreas; Mention
Betreff: Re: [dzhw/SLC-IntEr] Tester-Token zurücksetzen (#92)


@woisch<https://github.com/woisch>:
Die Datenbank lässt sich leider nur komplett leeren. Nur die ersten 200 Token können wir nicht zurücksetzen.

Sag einfach Bescheid, ob du die komplette Datenbank leeren lassen möchtest oder wir sie so lassen wie sie ist.

-

**Comment by SilinaKowalewski** [comment]
Habe gerade die gesamte Datenbank geleert.

**Comment by vdick** [comment]
@andreaschu Token incl. Preloads wurden in die Datenbank importiert

**Comment by woisch** [comment]
Danke fürs Zurücksetzen. Kann aus meiner Sicht dann zu!
