### ISSUE TITLE
Zwischenseiten

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#93]
Hier die Zwischenseiten.

Einblendungen Kohorte 1:
ZS1: zwischen_epi
ZS2: zwischen_aus
ZS3: zwischen_stu
ZS4: zwischen_msg
ZS5: end

Einblendungen Kohorte 2:
ZS1: zwischen_epi
ZS2: zwischen_stu
ZS3: zwischen_gsh
ZS4: zwischen_msg
ZS5: end

[SLC-IntEr_Zwischenseiten.zip](https://github.com/dzhw/SLC-IntEr/files/3887382/SLC-IntEr_Zwischenseiten.zip)

**Comment by SilinaKowalewski** [comment]
Wo sollen die Bilder denn auf der Seite eingeblendet werden? Über oder unter den bisherigen Texten?

**Comment by jocarstensen** [comment]
Stattdessen, seitenfüllend.

Ihr wisst vermutlich am besten selbst, wie man mit der Responsivität umgeht. Im Portrait Mode würde ich mir vorstellen, dass das Bild bis zu einem gewissen Maße beschnitten wird und erst danach skaliert. Wäre sowas möglich?

**Comment by SilinaKowalewski** [comment]
Die Bilder sind nun überall auf den Seiten eingefügt...bzw. überall bis außer auf der End-Seite. Wollt ihr dort wirklich ein Bild haben. Dort wird ja vermutlich auch der Link zur Addon erscheinen. 

Generell sind die Bilder, die ihr geliefert habt, sehr sehr groß. Wir haben sie daher noch mal kleiner gespeichert. Beim nächsten Roll-Out sollte also die Ladezeit der jeweiligen Seiten geringer sein.

**Comment by se-lang** [comment]
Bzgl. Größe der Bilder: Hast du das mit Photoshop o.Ä. runterskaliert oder nur die Komprimierung erhöht? Das sind ja über 20000x10000 pixel.
Wenn man das auf ne realisitsche Pixelzahl runterskaliert und dann noch bischen komprimiert dann kommt man da locker auf weniger als 0,5MB pro Bild.
@jocarstensen & @SilinaKowalewski: Könnte ich im Zweifelsfall innerhalb von 5min machen.

**Comment by jocarstensen** [comment]
@se-lang @woisch @heikQ Was sagt Ihr zu der Endseite? Silina hat da nen berechtigten Punkt. Das Add-On sollte auf keinen Fall zu übersehen sein.

**Comment by woisch** [comment]
Sehe ich auch so, AddOn ist hier wichtiger. Im Zweifel können wir auf das Bild verzichten und stattdessen nur den Text in normaler Schriftgröße verwenden? (Vielen Dank für Ihre Teilnahme! Ihre Angaben sind sicher bei uns angekommen.) Dann sollten die meisten auch den AddOn-Text darunter sehen können...

**Comment by jocarstensen** [comment]
Vielleicht einfach nur den hier plus Text und Link? Oder lenkt das schon zu sehr ab?

![OK](https://user-images.githubusercontent.com/35771616/69739499-1cf6d280-1138-11ea-9083-ab2f3f5e0d57.png)

**Comment by SilinaKowalewski** [comment]
Würde auf jeden Fall vorschlagen, dass Thema End-Seite in einem neuen Issue zu klären ;) 

Hier geht das im Zweifel unter und ein Text fehlt uns für diese Seite ja auch noch. 
Genau so wie die Start-Seite und der ganze Datenschutz-Kram.

**Comment by woisch** [comment]
Startseite und Datenschutzkram kommt als eigenes Issue auf jeden Fall.
Für die Endseite können wir meinetwegen auch ein eigenes Issue erstellen, hier gehört es nicht wirklich hin.

@jocarstensen: Ich würde das Bild spontan eher ganz weglassen und nur mit Text arbeiten, wie oben geschrieben. Können das aber nochmal per Mail klären

**Comment by se-lang** [comment]
@SilinaKowalewski Ich hab die Bilder jetzt einfach mal runtergerechnet, die Ladezeiten sind einfach viel zu lang. Auflösung reicht so trotzdem noch locker. Ich hab sie einmal als png (wie bisher) und einmal als jpg gespeichert (Komprimierung ist bei letzerem minimal besser),  und jetzt sind die Bilder noch gut 100kb groß, das sollte wesentlich schneller laden 😉 
[SLC-IntEr_Zwischenseiten.zip](https://github.com/dzhw/SLC-IntEr/files/3902239/SLC-IntEr_Zwischenseiten.zip)

**Comment by SilinaKowalewski** [comment]
@se-lang: Hatte sie ja gestern selber schon komprimiert. Aktuell sind sie 300kb groß. Ein riesiger Unterschied ist also nicht mehr zu erwarten.

**Comment by woisch** [comment]
Wurden die Bilder jetzt eigentlich noch mal ausgetauscht?
Die Ladezeiten sind immer noch sehr lang.

**Comment by SilinaKowalewski** [comment]
@woisch: Sie sind schon einmal ausgetauscht worden und jetzt nur so zwischen 300kb und 400kb groß. Werde es aber noch mal mit denen von Sebastian probieren.

**Comment by woisch** [comment]
Also bei mir laden die Zwischenseiten jetzt deutlich schneller, es gibt keine sichtbare Verzögerung mehr!

**Comment by woisch** [comment]
@SilinaKowalewski: 
Allerdings stimmt die Zuordnung der Bilder zu den Seiten nicht, das war aber unser Fehler, wir haben die erste Zwischenseite (beg_00) vergessen:

Einblendungen Kohorte 1:
ZS1: beg_00
ZS2: zwischen_epi
ZS3: zwischen_aus
ZS4: zwischen_stu
ZS5: zwischen_msg

Einblendungen Kohorte 2:
ZS1: beg_00
ZS2: zwischen_epi
ZS3: zwischen_stu
ZS4: zwischen_gsh
ZS5: zwischen_msg


Endseite: Für die Endseite möchten wir nicht das Bild haben (ZS6), da sonst die Gefahr besteht, dass der Link zur AddOn übersehen wird. Stattdessen bitte folgendermaßen umsetzen:

Als Text umsetzen (fett)
Vielen Dank für Ihre Teilnahme! Ihre Angaben sind sicher bei uns angekommen.

Links neben den Text folgendes Bild (habe ich aus ZS6 ausgeschnitten):
![Kohorte_1_ZS_6_haken](https://user-images.githubusercontent.com/53002476/69976104-b9e6b080-1528-11ea-88a0-d9f04661699e.png)

**Comment by SilinaKowalewski** [comment]
@woisch: Ein Bild links neben einem Text einzublenden ist für mich nicht so einfach umsetzbar. Mit CSS bestimmt machbar aber kostet eben Zeit. 

Wäre es eine Option den Text einfach in dem Bild daneben zu schreiben? Theoretisch sieht es dann identisch aus und dürfte keine Auswirkungen auf die Sichtbarkeit des Links haben.

**Comment by woisch** [comment]
Vielleicht können wir dann aber auch einfach wieder das Original nehmen. Habe es mal kleiner gemacht (und das weiß oben und unten abgeschnitten). Denke so passt der Link noch auf die Seite?

![Kohorte_1_ZS_6_textundhaken](https://user-images.githubusercontent.com/53002476/70028110-11763200-15a4-11ea-9ea3-c7d5f2315615.png)

**Comment by woisch** [comment]
Die neu eingefügten Bilder auf beg_00 sind größer als die übrigen. Hast du da evtl die alten Dateien (größer) genutzt?

**Comment by SilinaKowalewski** [comment]
Ich habe alle Bilder komplett aus dem Ordner von Sebastian genommen. Aber habe den Fehler gefunden. 

Wir haben die Größer der Bilder zusätzlich im css verankert. Dort muss ich die Seite beg_00 dann noch aufnehmen. 

Die Reihenfolge passt leider aber auch noch nicht, oder? Muss gleich mal checken was ich da genau für die einzelnen Seiten eingebaut habe.

**Comment by SilinaKowalewski** [comment]
Das Bild auf der Endseite ist eingefügt und auch die anderen Bilder sollten nun zu den Seiten passen.

**Comment by woisch** [comment]
Reihenfolge der Bilder passt. 

Die Seite zwischen_aus muss noch angepasst werden. cohort 2 hat da kein Bild, daher soll der Text (Im Folgenden geht es um das Thema Berufsausbildung). nur für cohort 2 sichtbar sein. cohort 1 hat ein Bild an der stelle.

**Comment by se-lang** [comment]
> Die Seite zwischen_aus muss noch angepasst werden. cohort 2 hat da kein Bild, daher soll der Text (Im Folgenden geht es um das Thema Berufsausbildung). nur für cohort 2 sichtbar sein. cohort 1 hat ein Bild an der stelle.

@jocarstensen Das hat zur Folge, dass Befragte auf ihrer letzten Zwischenseite im Episodenmodul und zwischen_aus exakt den gleichen Text bekommen. Ich hatte das in irgendeinem Issue schonmal erwähnt und war davon ausgegangen, dass das wegen dem Bild auf zwischen_aus nicht so wild ist. Dabei hatte ich aber nicht bedacht, dass es das für cohort 2 nicht gibt.
Möglicher Lösungen:
    - Doch ein Bild auf zwischen_aus für cohort 2 (wirkt entweder inkonsistent wenn wir irgendwas eigenes nehmen oder es müssten alle Bilder nochmal angepasst werden und die meisten Befragten aus cohort 2 würden sehen, dass sie ein Modul überspringen)
    - Eigene Transition für cohort 2 auf allen Zwischenseiten, die nicht auf zwischen_aus führt, sondern direkt auf aus_06 führt.

Vermutlich wird es auf die 2. Lösung hinauslaufen, wollte das aber gerne noch kurzfristig absprechen.

**Comment by SilinaKowalewski** [comment]
@se-lang: Wenn ich Viktor heute vormittag richtig verstanden habe, würde die 2. Lösung ein Problem in der Navigation bedeuten.

**Comment by se-lang** [comment]
> 
> 
> @se-lang: Wenn ich Viktor heute vormittag richtig verstanden habe, würde die 2. Lösung ein Problem in der Navigation bedeuten.

Ok... hab die 2, Lösung jetzt schon umgesetzt. 
Warum sollte das für die Navigation ein Problem sein? Wir lassen einfach auf zwischen_aus die Transition für cohort 2 drin. Dann kann die Seite für den Fortschrittsbalken genutzt werden. Oder ist es wichtig, dass die Befragten auf die Seite kommen?

**Comment by SilinaKowalewski** [comment]
@se-lang: Über die Navigation kann nur auf Seiten gesprungen werden die schon mal angezeigt wurden. Cohorte 2 soll aber sowieso nicht zum Modul Ausbildung springen können, richtig? Dann wäre es auch kein Problem für die Navigation.

**Comment by jocarstensen** [comment]
Ich bin einigermaßen verwirrt.
Für mich ist die Situation wie folgt:
- cohort2 hat im Ausbildungsmodul nur ein Item. Darum soll ihnen das Modul im Header und den Zwischenseiten nicht angezeigt werden.
- Mit Lösung 2 werden sie über die Seite zwischen_aus hinweggefiltert, sodass sie keine zwei gleichen Seiten hintereinander sehen (weil sie keine Zwischenseite dafür bekommen).
- Für Befragte aus Cohort 2 sieht es dann so aus, als gehöre die eine Frage aus dem Ausbildungsmodul zum Episodenmodul.
- Eine Notwendigkeit, zum Ausbildungsmodul zu navigieren, ergibt sich für Cohort 2 nicht.

**Comment by se-lang** [comment]
@jocarstensen @SilinaKowalewski: Absolut korrekt, wir haben also kein Problem.

**Comment by jocarstensen** [comment]
@se-lang Können wir dann schließen oder muss noch getestet werden?

**Comment by woisch** [comment]
Aus Sicht von cohort1 passt hier alles (cohort2 hab ich nicht geprüft bisher)
Würde jetzt hier schließen. Brauche noch ein neues Issue für die Endseite, da fehlt noch der Übergang zur AddOn. Hab ich auf meinem toDo stehen.

**Comment by jocarstensen** [comment]
@woisch Es geht ja explizit um cohort 2. Darum würde ich gern noch Sebastians Rückmeldung abwarten.

**Comment by se-lang** [comment]
Ist getestet und funktioniert. Ich mach hier zu.
