### ISSUE TITLE
Episoden - WB: taa01 crasht beim Verlassen

### ISSUE THREAD

**Issue by jocarstensen** [dzhw/SLC-IntEr#94]

**Comment by SilinaKowalewski** [comment]
Der Fehler liegt hier auf taa05. Denke aber ihn gefunden zu haben. 

Rolle nun neu aus und hoffe, dass die taa05 dann funktioniert.

**Comment by SilinaKowalewski** [comment]
Ups. Habe wohl einen zusätzlichen Fehler eingebaut. Kümmer mich aber weiterhin drum den eigentlichen Fehler zu finden!

**Comment by SilinaKowalewski** [comment]
taa05 funktioniert nun wieder, oder sieht das jemand anders?

**Comment by jocarstensen** [comment]
Funktioniert.

Mir ist gerade zusätzlich aufgefallen, dass auf taa05 und taa08 noch "Test" und Ähnliches in der HL steht. Ist das Absicht?

**Comment by SilinaKowalewski** [comment]
Joar, also das ist der "Test" ob die Label bzw. Trigger funktionieren. Sollten wir aber auf jeden Fall vor Feldstart ausblenden. Das habe ich aber auf dem Schirm :)

**Comment by jocarstensen** [comment]
Ok, dann ist das erledigt
