### ISSUE TITLE
Zwischenseite vorm Kalendarium (cohort1)

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#96]
Momentan bleibe ich als cohort=1 auf der Seite cal0001.html hängen...

![grafik](https://user-images.githubusercontent.com/53002476/69610001-234b5880-102b-11ea-8c87-1db565a487bb.png)

**Comment by SilinaKowalewski** [comment]
Soweit ich weiß, fehlen uns hier noch die Transitions. In #82 hatte @andreaschu schon geschrieben, dass sie die Übergange noch nicht angefasst hat.

**Comment by se-lang** [comment]
@woisch: Nach dem nächsten Rollout müsste man jetzt eigentlich durchkommen. Hab gerade die Transitions in dem Zusammenhang gemacht.

**Comment by woisch** [comment]
Jetzt läuft es durch, zumindest bis zum Epimodul Studium komme ich weiter!
