### ISSUE TITLE
Episoden nsET: Bleibt bei emaa40 hängen

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#97]

**Comment by se-lang** [comment]
Schau ich mir gerade an (@SilinaKowalewski, damit du Bescheid weißt)

**Comment by SilinaKowalewski** [comment]
@se-lang: 
Du verwendest immer sf_emaa39.value. Es wird aber auf der Seite kein SF angelegt.

**Comment by se-lang** [comment]
Jep, gerade gesehen, copy-paste-Fehler... 😒 
Korrigiere ich gleich

**Comment by se-lang** [comment]
Erledigt, sollte nach dem nächsten Rollout funktionieren

**Comment by SilinaKowalewski** [comment]
Scheint nun zu funktionieren.

**Comment by woisch** [comment]
ok, nun komme ich auf der Seite jedenfalls weiter!
