### ISSUE TITLE
Episoden Studium: crasht beim Verlassen der Seite staa34

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#98]
Wenn auf staa24 die Option "Einer oder mehrere der oben genannten Punkte haben sich geändert." angegeben wird (crasht auch unabhängig davon, welche Auswahl auf Seite staa33 getroffen wird).

**Comment by se-lang** [comment]
Liegt vermutlich am Counter, der wurde nicht korrekt initialisiert.
@woisch: Du bist vermutlich über staa01 eingestiegen und nicht über st0001, oder?
@SilinaKowalewski: Ich hab entsprechende trigger auf staa01 eingefügt, wenn du keinen anderen Fehler findest müsste es das gewesen sein.

**Comment by woisch** [comment]
@se-lang: Habe mal beides probiert als Einstiegsseite, das Problem besteht scheinbar in beiden Fällen.

**Comment by SilinaKowalewski** [comment]
Das Problem scheint behoben zu sein.

**Comment by woisch** [comment]
Bin wieder über staa01 eingestiegen und fliege nach wie vor beim Verlassen der staa34 raus.

Ein Einstieg über st0001 klappt  gerade nicht, da es dann direkt beim Verlassen der st0001 crasht

**Comment by SilinaKowalewski** [comment]
Habe den Fehler nicht auf Anhieb gefunden. 

In dem Modul scheint es aber einige Klammer-Fehler zu geben. Habe gerade die Anzahl der Klammern gezählt: 

- Klammer auf = 23.496
- Klammer zu = 23.537

**Comment by se-lang** [comment]
ich schau auch nochmal rein, vielleicht fällt mir was auf...

**Comment by se-lang** [comment]
eine "Klammer zu" zu viel hab ich direkt gefunden, auf st0001

**Comment by se-lang** [comment]
@woisch Auf welche Seite müsstest du denn von staa34 kommen? Bzw. was gibtst du denn ein?

**Comment by se-lang** [comment]
@SilinaKowalewski : Hab die überflüssigen Klammern gefunden, bin gerade dabei sie zu löschen

**Comment by woisch** [comment]
Zum Beispiel wenn ich einen Wechsel von Umfang und von Art des Abschlusses angebe:

![grafik](https://user-images.githubusercontent.com/53002476/69728259-7523d980-1124-11ea-80fa-665b1d43bc59.png)

**Comment by se-lang** [comment]
Ok, ich hoffe mal die Klammern waren das Problem, sonst kann ich keinen Fehler finden.

**Comment by SilinaKowalewski** [comment]
Der Seitenübergang von staa34 klappt nun. Kann somit dieses Issue geschlossen werden?

**Comment by se-lang** [comment]
Jep, kann zu.
