### ISSUE TITLE
 Episoden Studium: crasht beim Verlassen der Seite staa24

### ISSUE THREAD

**Issue by woisch** [dzhw/SLC-IntEr#99]
...jeweils bei Auswahl der ao 1, 4 oder 5

**Comment by se-lang** [comment]
@SilinaKowalewski: Hier hab ich leider keine Ahnung woran das liegen könnte...

**Comment by SilinaKowalewski** [comment]
@se-lang:

Scheinbar lag der Fehler hier: 
`value=""`

Habe zum Testen den Ausdruck so angegeben: 
`value="''"`

Nun scheint es zu funktionieren. Habe den Ausdruck auch in allen anderen Triggern ersetzt.

**Comment by se-lang** [comment]
Super, danke dir!
@jocarstensen: Sollten wir im Hinterkopf behalten. Wenn sich rausstellt, dass das wirklich das Problem war sollten wir vorsorglich die anderen Module nochmal checken. Ist aber zum Glück ja leicht zu korrigieren.

**Comment by jocarstensen** [comment]
Kann man das nicht vorsorglich überall mit Suchen/Ersetzen durchgehen? Im Hinterkopf behalten erscheint mir aktuell riskant.

**Comment by SilinaKowalewski** [comment]
Ich kann das gerne überall ändern. Dann kann für die (kurze) Zeit aber niemand anders in den qmls arbeiten. Soll ich das jetzt direkt machen?

**Comment by woisch** [comment]
Wir sind in Besprechung, daher kannst du das gerne jetzt direkt machen!

Von: SilinaKowalewski [mailto:notifications@github.com]
Gesendet: Dienstag, 26. November 2019 14:41
An: dzhw/SLC-IntEr
Cc: Woisch, Andreas; Author
Betreff: Re: [dzhw/SLC-IntEr] Episoden Studium: crasht beim Verlassen der Seite staa24 (#99)


Ich kann das gerne überall ändern. Dann kann für die (kurze) Zeit aber niemand anders in den qmls arbeiten. Soll ich das jetzt direkt machen?

**Comment by SilinaKowalewski** [comment]
Habe alle qmls durchsucht und den Fehler nirgendwo anders gefunden.

**Comment by SilinaKowalewski** [comment]
Kann dieses Issue dann geschlossen werden?

**Comment by jocarstensen** [comment]
Ja, danke
